### ISSUE TITLE
【 あったら嬉しい 】プロフィールページが欲しい

### ISSUE THREAD

**Issue by sushi-udon** [zenn-dev/zenn-community#112]
## 機能説明
プロフィール欄だけではなく、もう少しプロフィール関連を書きたいときに、
詳細プロフィール用のページ（マークダウン 形式？）があるといいなと思いました。

**Comment by spiegel-im-spiegel** [comment]
便乗させて貰うと， GitHub 連携している場合は連携しているリポジトリの README.md を表示するようにしてほしいです。
GitHub Profile Readme みたいな感じ。

**Comment by catnose99** [comment]
> GitHub 連携している場合は連携しているリポジトリの README.md を表示する
実はこれリリース前から構想にありました…。README.mdだと使用用途間違えられる可能性があるので
`PROFILE.md`とか`ABOUTME.md`とかになるんですかね。

**Comment by spiegel-im-spiegel** [comment]
それならば PROFILE.md に1票です！

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ニーズが限定的であり実装コストに見合わないため対応しないこととなりました。

個人のWebサイトやSNSを活用いただければと思います。
