### ISSUE TITLE
Stripe決済のJCBカード対応

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-community#14]

**Comment by catnose99** [comment]
- クラスメソッドへの譲渡契約の締結が完了するのが6月1日
- JCB決済を申請するうえで運営会社が変更すると再手続きが必要になる => 譲渡完了後に申請を行う

**Comment by tfukumori** [comment]
こちらのJCBへの対応はまだ検討中の状態でしょうか？

**Comment by youcune** [comment]
:+1:

**Comment by catnose99** [comment]
ようやくJCBカード利用が承認されました。すでにzenn.devでJCBを利用できるようになっています。
