### ISSUE TITLE
本の著者との連絡手段が欲しい (誤植の連絡やフィードバックなど)

### ISSUE THREAD

**Issue by tatane616** [zenn-dev/zenn-community#141]
Zenn で販売された本の内容で読者が誤植を発見した場合、著者に連絡する手段に困ることがあるなと思いました。
記事であれば Discussion 内で報告することも可能ですが本ではそのような導線が無いようです。
(私が見落としているだけでしたらすみません)

Twitter などで気軽に連絡できれば良いのですが、著者が SNS をやっていない場合もあるので、本を公開する際に連絡手段を表示できる項目があっても良いのではないかと思います。

もちろんデメリットもあるかと思うので任意のフィールドでも良さそうですが、ご検討お願いいたします。

**Comment by catnose99** [comment]
あー、なるほどですね…。
レビュー機能は検討していますが、それとは別に誤植などを報告できるような導線があった方が良いですね。
検討させていただきます。

**Comment by blueplanet** [comment]
同じくフィードバック機能がほしいですね。

実際本を読んでいて、明らかな誤字脱字などがありましたが、どうやって著者に連絡できるかは分からず困ってますね。
特に、「どのページ、どの文言」など、その場でマークをつけてフィードバックを送れるとありがたいです。

**Comment by cm-igarashi-ryosuke** [comment]
お問い合わせにて類似の要望がありましたのでメモしておきます。

> 購入者から本に関する要望やフィードバックを集める時に使いたいと考えていました。

（本を購入した後もコミュニティとして活用できればいいなと思いました。）

**Comment by cm-igarashi-ryosuke** [comment]
こちらで対応しましたのでクローズします。
https://info.zenn.dev/2023-04-13-book-author-require-contact
