### ISSUE TITLE
独自ドメインを設定できるように

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-community#147]

**Comment by ress997** [comment]
Qrunch さんが終了しましたしぜひとも対応お願いします！

**Comment by catnose99** [comment]
@ress997 
え、qrunchって独自ドメインに対応してましたっけ？

**Comment by ress997** [comment]
@catnose99 `Qrunch Pro β` として実装されていましたよ〜
なので一部個人技術ブログが見れない状態でGoogleにキャッシュされてます…

**Comment by catnose99** [comment]
おぉーそうなんですね！
もはやQrunchのソースコードを買わせていただいて参考にしたいくらいです。
（Qrunchの作者さんとは過去にTwitterで交流していたことがあったので聞いてみようかな…）

情報ありがとうございました。

**Comment by ress997** [comment]
これからも応援していますので頑張ってください！

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、Zennとしてはコミュニティ作りが重要と考えており、独自ドメインの設定は相反するという結論になり対応しないこととなりました。
