### ISSUE TITLE
Scraps）画像のコピペでアップロード

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-community#167]
画像をコピーした状態で、エディターにフォーカス => Ctrl + Vで貼り付け

**Comment by SnowCait** [comment]
スクラップはさっと書けるのが魅力なので対応していただけると嬉しいですー（気軽に書けるのでよく使ってます）

**Comment by catnose99** [comment]
気軽に投稿できる場所のぶん、著作権周りを気にしています。
引用の要件を満たさずに拾ってきた画像を貼られるのがこわいなと…

**Comment by SnowCait** [comment]
確かに。ペースト時に警告を出すくらいしか思いつかないですが難しい問題ですね。。

**Comment by catnose99** [comment]
こちらさきほどのリリースで対応しました。

**Comment by tktcorporation** [comment]
待望の機能だったのでとても嬉しいです！ありがとうございます！
