### ISSUE TITLE
Eメール + パスワードログイン

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-community#17]

**Comment by kun432** [comment]
👍

**Comment by hws-nishimaki-masaya** [comment]
Eメール + パスワードログインの検討、とてもありがたいです！！
Publication Pro にして、会社のみんなで記事を書き始めたのですが、
Googleアカウント使っておらず、、、別途Googleアカウントを有料で発行する必要があり・・・
助かります！

Microsoft365アカウントログインも、今後検討頂けると嬉しいですmm
（Publication Proの料金の価格体系が少し変わったとしても、M365連携は嬉しいですmm）

**Comment by cm-wada-yusuke** [comment]
@hws-nishimaki-masaya フィードバックありがとうございます！
> 別途Googleアカウントを有料で発行する必要があり

これって個人の無料Gmail・Googleアカウントは使えない、という会社としてのレギュレーションがあるということでしょうか？

**Comment by KokiTakeishi** [comment]
@hws-nishimaki-masaya に代わって返信させてください。

そうなんです、もともとは個人のgmailアカウントで認証していたのですが、
業務として利用するなら個人のメアドで認証するのもNGでは・・という話になりまして。。

何も文句の言われない方に倒したという状態です。

逆に、ISMS取得していて、かつPublication Pro使っているけど、gmailの個人アカウントでの認証で全く問題ないよ
ということであれば、個人のgmailアカウントでの利用にするという手もなくはないですが、
気になる人は気になるようなので、できれば独自ドメインのメアドでの認証か、Microsoftアカウントでの認証などがあると助かります。

**Comment by cm-wada-yusuke** [comment]
@KokiTakeishi 詳細にありがとうございます。チームで検討しています。Googleアカウントが使えない・使いにくい事情がある点は理解しました。

ご認識いただいているように、Google アカウント（もしくはMicrosoftアカウント）は、それ自体が一定のセキュリティレベルを担保しており、たとえばYouTubeのコメントが理由でBANされた場合などはGoogleアカウント自体が利用できなくなります。

ログイン手段を増やすにあたり、こうした仕組みから漏れる部分があるのか、あるとしたらそこはどうサービスとしての秩序を担保するか、ということを考慮する必要があります。時間がかかっておりますが、場所が場所だけにさまざまな可能性を考慮しているという点、ご理解いただけると幸いです。もうしばらくおまちいだけるとありがたいです。

**Comment by lamrongol** [comment]
Google自体の問題と言うより、ログイン方法が「一つ」しかないのがリスクだと思います(「卵は一つのカゴに盛るな」的な意味で)。
Twitter(現X)によるログインを多くのサービスが廃止したことがありましたが、Googleがすぐに不安定になる事は考えにくいにせよ「ログイン方法が一つしかない」のはリスクがあると思います。

**Comment by cm-dyoshikawa** [comment]
コメント頂きありがとうございます。

ユーザのみなさんの声を受けてチームで検討を重ねた結果、（Googleアカウントではなく）メールアドレスを使用したログインについて実装含めて進行中の状況です。
時期は明言できないのですが、今後本Issueについて良い報告ができるかと思います。

**Comment by cm-dyoshikawa** [comment]
本日より、Zennでメールアドレスを使ったログインができるようになりました！

[Zennでメールアドレスを使ったログインができるようになりました \| What's New in Zenn](https://info.zenn.dev/2024-09-10-email-login)

メールアドレス+パスワードではなく、確認コードを使ったログインとさせていただきました。
いただいたご要望のすべてを解決する機能にはまだ至っていないかと思います。引き続き本CommunityによるIssue起票や問い合わせフォームからのフィードバックをお待ちしております 🙇 

ユーザーのみなさまのお声により実現いたしました。いつもお声をいただきありがとうございます。
引き続きZennをよろしくお願いいたします。

本Issueは、ひとまずクローズいたします。
