### ISSUE TITLE
GitHub連携されている場合、Editボタン（またはページのリンクとして）GitHubのリポジトリのページを開いてくれるとありがたい

### ISSUE THREAD

**Issue by terrierscript** [zenn-dev/zenn-community#176]
現状、GitHub連携されている場合もEditで編集が出来る状態ですが、GitHubのページに遷移・または動線があると嬉しいと感じました。

`https://github.com/{ユーザー名}/{連携リポジトリ名}/edit/master/articles/{slug}.md`などでリンク可能なので、リンク先の導出自体は比較的容易かなと感じています。

**Comment by catnose99** [comment]
ありがとうございます。これについては考えていて（確かにロードマップにはまだあげてなかったかな・・・）、複数リポジトリ連携の対応後にやろうと思っています。

プライベートリポジトリを使いたいケースも多いと思うので、連携したリポジトリごとに「GitHubへのリンクを載せる」のON/OFFの設定をできるようにしようかなと。もうしばらくお待ちください。

**Comment by catnose99** [comment]
対応しました
