### ISSUE TITLE
インライン画像 (テキスト内画像) を使えるように

### ISSUE THREAD

**Issue by ixkaito** [zenn-dev/zenn-community#189]
ちょっとしたアイコンやロゴなど、テキスト内に画像を入れたいときがあります。

**Comment by catnose99** [comment]
なるほど・・・
```
![alt](url)改行せずに文章
```
みたいな書き方をされたときに改行してほしくないということですね。
確認します。

**Comment by ixkaito** [comment]
@catnose99 はい、そのとおりです！

**Comment by catnose99** [comment]
これやろうと思ったのですが、画像の中央寄せとの両立の絡みで実現できないかもしれません。

HTMLとしては以下のようになるとして

```
<p><img src="~" alt="foo"></p>
```

CSSでimgのdisplayをinline系にしつつ中央寄せしたいのですが、色々試行錯誤してみたものの実現不可能な気がしています。
（画像を含む段落だけ`text-align:center`にすることはできず）

**Comment by ixkaito** [comment]
なるほど…確かに、

```html
<p>Lorem ipsum dolor sit <img src="…"> amet consectetur adipiscing.</p>
```

これをインライン画像にしつつ、

```html
<p><img src="…"><p>
```

この場合は画像中央寄せ、を CSS のみで実現するのは不可能ですね…🤔

あとは HTML を変えるしかないですね。

```html
<p>Lorem ipsum dolor sit <img src="…"> amet consectetur adipiscing.</p>
```

```html
<figure><img src="…"><figure>
```

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ニーズが限定的であるため実装は見送ることとなりました。

**Comment by hyrodium** [comment]
https://shields.io/ などバッジの一覧を箇条書きで書きたくて本issueを見つけました！
見送りを再検討してもらえると嬉しいです:bow:

また、https://github.com/zenn-dev/zenn-community/projects/1 でShippedに入っていると実装済みのように見えてしまうので、NotPlannedのようなカラムを追加してもらえると嬉しいです。

**Comment by cm-igarashi-ryosuke** [comment]
@hyrodium ご意見ありがとうございます。

CommonMarkなど一般的な記法でサポートされていないものをサポートするのは様々な面からハードルが高いです。

ワークアラウンドですが、テーブルレイアウトを使用されるのはいかがでしょうか？

```
| Image | text |
|:-------:|:-------:|
| ![](https://img.shields.io/badge/build-passing-brightgreen) | build-passing-brightgreen |
```

GitHub Projectの方は管理されていなかったのでクローズしました 🙏

**Comment by hyrodium** [comment]
早速のご回答 & GitHub Projectの対応ありがとうございます！

テーブルレイアウトは検討していなかったので試してみます！:pray:
