### ISSUE TITLE
アコーディオン付きの警告またはメッセージ

### ISSUE THREAD

**Issue by kawadumax** [zenn-dev/zenn-community#203]
多くの人にとっては必要のない警告は赤い表示でかつ折りたためるようにしたいと思いました。
独自記法なのであまりここを拡張すべきではないのかもと思いましたが、似た要望の人が多くいらっしゃれば考えていただけると幸いです。
```
# アコーディオン記法
:::details タイトル
表示したい内容
:::
# 警告記法
:::message alert
警告メッセージをここに
:::
# メッセージ記法
:::message
メッセージをここに
:::

# アコーディオンつき警告（のイメージ）
:::details alert タイトル
メッセージをここに
:::

# アコーディオン付きメッセージ(のイメージ)
:::details message タイトル
メッセージをここに
:::

```

**Comment by cm-igarashi-ryosuke** [comment]
@kawadumax ご提案ありがとうございます。（すごく時間が経ってしまいすみません）

メッセージの中にアコーディオンを配置して折りたたむことはできます。ただ、このようにすると多くの人は気になって開いてしまうと思います。

```
::::message alert
::: details 折りたたみ
メッセージをここに
:::
::::
```

![image](https://user-images.githubusercontent.com/13619209/168013344-7b9591f4-0166-4ce9-802f-9e921296a23b.png)

![image](https://user-images.githubusercontent.com/13619209/168012942-e490446d-9cbd-43d4-b983-1963de835b0a.png)

必要な人だけに届けたいメッセージであれば、情報をアコーディオンでくるんだ中にメッセージを配置するのが良いかと思いました。

```
:::: details 折りたたみ
:::message alert
メッセージをここに
:::
::::
```
![image](https://user-images.githubusercontent.com/13619209/168013292-f8766b93-eb7d-4c90-b3b5-8fbeda6747d7.png)

![image](https://user-images.githubusercontent.com/13619209/168013238-e1183602-4ede-4625-9b6e-ed85a1ba0113.png)

ご参考になれば幸いです。
もし意図と違うようでしたら再オープンしてください。
