### ISSUE TITLE
ideasの一覧

### ISSUE THREAD

**Issue by takundao71** [zenn-dev/zenn-community#204]
記事やbooks、scrapsの一覧はあるのにideasの一覧はない模様
https://zenn.dev/ideas

作成してほしいです〜

**Comment by catnose99** [comment]
今のところtechとidea両方がまとまった一覧を下記のURLで見ることができます。
https://zenn.dev/articles

**Comment by catnose99** [comment]
フィルターをかけられるようにするのは良いかも

**Comment by umi-tyaahan** [comment]
(デザインの変更前に固執するユーザーっぽくて言いにくい感じですが…)
以前の、techとideaに分けた上で、画面遷移無しでそれぞれの新着が見れる仕様は結構良かったです。

**Comment by catnose99** [comment]
@umi-tyaahan なるほど、もうすこし考えてみます！
