### ISSUE TITLE
RSSフィードにLike数を付与して欲しい

### ISSUE THREAD

**Issue by yuki-yano** [zenn-dev/zenn-community#205]
ZennのRSSフィードを使って（色んな条件でフィルタリングして）興味がある記事を抽出するサービスを作ってみたいなーと思ったんですが、現状記事にアクセスしてスクレイピングしないとLike数が取れないんじゃないかと思っています。
なので、RSSフィードを使ってLIKE数が取れるとありがたいです。

複数記事のLIKE数をまとめて取得するためのAPIなどがあると最もありがたいのですが現実的でない気がするので、もしよければ上記を対応していただけるとありがたいです。

**Comment by catnose99** [comment]
ありがとうございます。
RSSにメタデータを含めて良いものか / どのようにして含めるかがいまいち分かっていないのですが、何かイメージはありますか？

Like数であれば`article`のレコードに含まれているため表示自体はそこまで難しくありません。ただ、基本的に新着の投稿を購読するためにRSSフィードを用意しているため、表示される記事の数には限りがあります。すべての投稿を取得したうえでフィルタリング…みたいなことは難しいと思います。

**Comment by yuki-ycino** [comment]
最低限の情報しか取れなさそうだというのは気になっていて、ただカテゴリ毎に数日分のLikeまで取得できれば最悪それ以降はあまり増えない前提でもいいのかな、と思っていました。

ただ、
https://github.com/zenn-dev/zenn-roadmap/issues/207#issuecomment-751702779
の通りAPIで対応するのが適切かと思うので、そちらの対応を待たせていただこうかと思います。

**Comment by cm-igarashi-ryosuke** [comment]
APIの目処は立っていないですが、クローズさせていただきます。
