### ISSUE TITLE
サポートした記事の一覧が欲しい

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [zenn-dev/zenn-community#206]
購入した本や Like した記事の一覧は見れますが，サポート（投げ銭）した記事や本の一覧を見ることは可能でしょうか。もし可能ならユーザごとの Library ページで一覧として見れると嬉しいです。

**Comment by catnose99** [comment]
@spiegel-im-spiegel 

[購入履歴](https://zenn.dev/settings/payments_history) から見ることができるのですが、少し見づらいですよね…。改善しようと思います。

**Comment by spiegel-im-spiegel** [comment]
あっ，アカウント設定にあったのですね。

**Comment by cm-wada-yusuke** [comment]
@spiegel-im-spiegel 

こちら一度クローズさせていただきます。もしサポート記事一覧についてさらに改善してほしいポイントがありましたら、別途issueを発行いただけると嬉しいです。
