### ISSUE TITLE
APIについて

### ISSUE THREAD

**Issue by skanehira** [zenn-dev/zenn-community#209]
@catnose99 
zenn.devのフロントで使っているいくつかのpublicなAPI？を開発者ツールで見つけましたが、これらを使ってvimプラグインを作っても問題ないでしょうか？

```
https://api.zenn.dev/articles/recent?count=48&min_liked_count=0&require_next_page=true&page=1
https://api.zenn.dev/topics/vim/articles
https://api.zenn.dev/skanehira/articles
https://api.zenn.dev/search?q=vim
```

**Comment by catnose99** [comment]
@skanehira 問題ないのですが、現時点のAPIはあくまでもzenn.dev向けのものなので、告知なく仕様が変更されることがあります。

ちょうど年末年始でAPIのリファクタ + 検索（`/search`）周りの改善を行おうとしていたので、少し待っていただいた方が良いと思います…！

**Comment by skanehira** [comment]
@catnose99 了解しました
ありがとう御座います
