### ISSUE TITLE
はてなブックマークの「コメント一覧非表示」サポート

### ISSUE THREAD

**Issue by dmikurube** [zenn-dev/zenn-community#210]
はてなブックマークは有用に使われているサービスですが、強く否定的なコメントを一方的に残しがちなユーザーも一部にいて、それをあまり好んでいないユーザーもいくらかいるようです。 (私自身を含め)

あくまでブックマークなので、それは禁止できることでも禁止されるべきことでもないとは思いますが、コメントの一覧表示によってその種のコメントが加速する面もあって、はてなではページに下記 `<meta>` タグを入れることでコメントの一覧表示だけはしないようにできるようです。

```
<meta name="Hatena::Bookmark" content="nocomment" />
```
https://b.hatena.ne.jp/help/entry/nocomment

著者が、なにかしらの方法 (例: Markdown 上部の属性や、特定の特殊トピックや、この `<meta>` タグを直に Markdown に埋め込む、ユーザー設定など) で、これを記事・本に設定できるようになっていたらいいなと思っています。 (これがアクセス数等に影響する面もあると思うので、その上での判断はしかたがないと思いますが)

**Comment by catnose99** [comment]
ありがとうございます。はてブのnocommentはじめて知りました。
検討します。

**Comment by tenntenn** [comment]
私も過去にZennの記事をブックマークされ、不快な思いをしてZennを使うのをやめた経緯があります。Zenn自体は非常に良いサービスですが、安心して使えるまで気長に待ってます。

なお、こちらの機能でもコメントを非表示することができるようです。
https://b.hatena.ne.jp/help/entry/pageowner
はてなのIDと連携という形で機能を提供していただいても非表示にできそうです。

**Comment by uttk-dev** [comment]
@dmikurube @tenntenn 

提案ありがとうございます。
先ほど、[はてなIDと連携できる機能](https://b.hatena.ne.jp/help/entry/pageowner)を実装しましたので、そちらで対応して頂ければと思います。

※ ブラウザキャッシュが残っている場合、古いページが表示されることがありますので、その際はキャッシュを削除してから再度表示して頂くと直ると思います。

Zennでの設定方法につきましては、以下の記事まとめてありますので、そちらをご参照下さい。

https://zenn.dev/zenn/articles/connect-with-hatena

また、コメント一覧非表示の設定方法につきましては、以下のサイトをご参照下さい。

https://b.hatena.ne.jp/help/entry/nocomment

よろしくお願いします。
