### ISSUE TITLE
IEで開こうとするとEdgeやChromeにリダイレクトされるように

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-community#213]
下記のリンク先から申請する

https://docs.microsoft.com/en-us/microsoft-edge/web-platform/ie-to-microsoft-edge-redirection#request-an-update-to-the-ie-compatibility-list

**Comment by cm-wada-yusuke** [comment]
サポート打ち切られたので対応しないでもいいかもしれません
