### ISSUE TITLE
Zenn CLI でファイルを編集しているときのプレビュー自動更新とスクロール位置

### ISSUE THREAD

**Issue by dmikurube** [zenn-dev/zenn-community#223]
Zenn CLI の (ローカル) プレビューをブラウザで開いているときに、対象のファイルを外部エディタ等で編集・保存すると、プレビューが変更を検知してブラウザからリロードするようになっていると思います。

とても長い記事の下の方を編集していると、セーブするたびにブラウザの現在位置が上の方に戻ってしまい、プレビュー結果を確認するたびに手でスクロールダウンしないとならず、少ししんどいなあと感じています。

* 自動更新をオフにする Zenn CLI のオプション設定
* 自動更新してもスクロール位置を維持できるように
* セクションごとの目次リンクをプレビュー画面でも有効に

のいずれかができたら、これはかなり緩和されるかなあと思っているのですが、いかがでしょうか? (または別の緩和策でも)

**Comment by catnose99** [comment]
@dmikurube ちょうど昨日のリリースでこの部分の問題を解消したと思われるのですが、`npm install zenn-cli@latest`でアップデートしてみていただけますか？

**Comment by dmikurube** [comment]
ありがとうございます。既に `0.1.72` で、念のため `npm install zenn-cli@latest` してみましたが、まだ起こりますね…。常に起こるわけではなく、起きたり起きなかったりなので、なにか timing issue があるかもしれません。

環境は
* Ubuntu 20.04
* Google Chrome 87
です。

リロードの際に `😿エラーが発生しました / コンソールのエラーメッセージをご確認ください` になることもありますね。 DevTools を見ると `Failed to load resource: the server responded with a status of 500 (Internal Server Error)` でした。

**Comment by catnose99** [comment]
@dmikurube 
ありがとうございます。なるほど、もう少し確認してみます。
ご不便をおかけしてすみません。
なお`zenn preview --no-watch`という形でプレビューを立ち上げると自動リロードをオフにできます。

**Comment by dmikurube** [comment]
おお `--no-watch` があったんですね! ありがとうございます。目先このオプションで事足りると思いますので、特に急ぐことはありません。サービス運営、ありがとうございます :)

**Comment by catnose99** [comment]
こちらおそらく解消済みだと思われますのでクローズさせていただきます。
