### ISSUE TITLE
Fromt Matter で設定した特定の絵文字が表示できないかも？

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [zenn-dev/zenn-community#224]
前提：GitHub に Zenn 用のリポジトリを作って，そこから Zenn 側にデプロイさせる形で運用しています

原稿の markdown ファイルの fromt matter に設定する "emoji" 項目にキーボートの絵文字「⌨ U+2328」をよく使うのですが，これを設定すると何故か他の絵文字に差し替えられるようです。他の絵文字（🤔 U+1F914 など）は大丈夫ぽいです。

以前はこういったことはなく，割と最近になって起きている現象です。

個人的に絵文字の内容自体に拘りがあるわけではないので，さほど気にしてないのですが，もしかしたら何らかのバグが紛れ込んでるかもしれないので，一応報告しておきます。

**Comment by catnose99** [comment]
@spiegel-im-spiegel 
ありがとうございます。
実はこちら最近仕様を変えました。
以前の仕様だと、Windowsでは対応しているが、Macでは対応していないZWJ絵文字を通してしまい、Macで2つの絵文字となってしまう問題が発生していたためです。これが結構致命的で、レイアウトが崩れてしまうことがあり…

現在は使用可能なZWJ絵文字をunicode.orgの[Recommended Emoji ZWJ Sequences](https://www.unicode.org/emoji/charts/emoji-zwj-sequences.html)に制限しています。

最近「よくある質問」にもこの問題を記載しました。
https://zenn.dev/faq#emoji-not-shown

なんとかCSS側でできないか模索はしていますが、解決策は見つけられていない状況です。すみません。

**Comment by spiegel-im-spiegel** [comment]
なるほど。仕様変更の余波って感じですかねぇ。やっぱ絵文字は闇が深い...


当面解決できそうにないのであれば，この issue はいったん閉じていただいても構いません。

**Comment by catnose99** [comment]
闇が深いです…w

CSSを使って対処できないか今度もう少し試そうと思っているのでopenのままにしておきます。
ご不便をおかけしてすみません…！

**Comment by catnose99** [comment]
すっかり書き忘れてたんですが、こちら対応済みです！
ご指摘ありがとうございました！
