### ISSUE TITLE
Categorize topics

### ISSUE THREAD

**Issue by kkiyama117** [zenn-dev/zenn-community#227]
# About

topics(tag)の大分類の要望

## What/Why

現在、Zennの記事にはその記事が何に関連したものであるかを表す`topics`の機能があります.
現状topicsは言語そのもの、ソフトウェア、フレームワーク、OS、サービス、概念(競技プログラミングなど)等様々なものが存在しています.
これは現在すべて1種類の`tag`として存在していますが、導線が [topics](https://zenn.dev/topics)および検索欄で検索する、のみであるので
「具体的に特定の事象について調べたい訳ではないが、トピックの話題を攫いたい」といった際に気になったトピックの記事を検索したい際に記事がひっかからなかったり(e.x. `Android`の記事を検索したら`flutter`のみの記事がひっかからない)、逆に関係の薄い記事がひっかかったり、
記事を書く際にどういったタグがあるか分からずタグの極端な過不足が出たり、表記揺れのタグを付けてしまったり、ということがあると思います.

これに対し、topics自体を分類することで解決できるのではないか、と思い、issueを立てた次第です.
合わせて、副次的に以下のような効果も期待できるかと思います.

- (User) topics一覧において分類毎に導線が作れてわかりやすく目的のトピックにたどりつくことができる.
- (User) 条件つき検索を用意してあげた場合検索がしやすくなる(検索エンジンのように大分類ごとに条件をつけるetc.)
- (Maintainer) どういった記事が多いかの統計がとりやすくなる(タグそのものだけでなく分類ごとに簡単に集計できる).

## example

要望のイメージを共有しやすくするために簡単に考えた例を記しておきます.

- Languages
  - Java
  - Python
  - Typescript
  - ......
- Frameworks
  - React
  - Vue
  - ......
- Environments
  - Web
  - Windows
  - Mac
  - Mobile
    - Android
    - iOS
  - ......
- Concepts
  - 競技プログラミング
    - Atcoder
  - 機械学習
  - Security
  - ......
- Services/Software
  - AWS
  - Slack
  - Azure
  - ......
- Others(ideas?)
  - ポエム
  - 初心者
  - 個人開発
  - ......

# Cons

一方で幾つか問題もあると思いましたので合わせてあげておきます

- 分類が難しいものがある
- 分類のネストが深くなりすぎる可能性
- 実装/保守コスト

**Comment by catnose99** [comment]
これは僕もリリース前から考えていて、（手動でやるには大変すぎるので）共起関係を利用して分類するのが良いかなと思っています。機械学習を用いることになるので、そのあたりに強い人の力を借りたいと思っています。

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、万人が納得するカテゴライズは難しいとの結論になり、実装は見送ることとなりました。
