### ISSUE TITLE
トップページの Ideasにあるリンクを Ideaのトレンドに変えてはどうでしょうか？

### ISSUE THREAD

**Issue by Samemura** [zenn-dev/zenn-community#233]
現状だと、トップページを開いて、Ideasをみてもっとみようと思うと、記事ページのトップにいってしまうので、Ideaのトレンドかidea一覧にリンクがあると見やすいと思いました。

![image](https://user-images.githubusercontent.com/7892834/106866532-ea6b4100-670f-11eb-8e82-9391cbfe7027.png)

**Comment by catnose99** [comment]
たしかにそうですね。ありがとうございます。

**Comment by Samemura** [comment]
ありがとうございます。 #204 とか見ると、ideaのページとか仕様変わってたんですねー

**Comment by cm-igarashi-ryosuke** [comment]
だいぶお時間があいてしまいましたが、リンク先を適切な位置に修正しました。
ご提案ありがとうございました。
