### ISSUE TITLE
Github 連携後にもオンラインエディタが使いたい

### ISSUE THREAD

**Issue by tktcorporation** [zenn-dev/zenn-community#238]
## 種別

- 機能リクエスト

## 目的

- Github 連携後にもオンラインエディタが使いたい(zenn.dev から投稿したい)

## なぜ

- 手元のエディタで記事を書くのと、同じかそれ以上の頻度でオンラインエディタを使って記事を書きたくなる
- 記事の投稿までの手数はオンラインからのほうが圧倒的に少なく、手軽である
- 画像連携の体験はオンラインエディタのほうが良い
- Github 連携してから記事の投稿頻度が下がってしまった(上記の手軽さが下がった理由で)

### オンラインエディタから記事の作成を行い、その内容で、連携リポジトリに対して PullRequest が送れる

(記事の公開は merge 後)

#### 利点

- リポジトリ側が正になる構造を保ちつつ、オンラインエディタの利便性を享受できる

#### 欠点

- Github との連携が面倒そう

### オンラインエディタから記事の作成を行い、その内容を md で export する
(or plain text でコピーできる)

#### 利点

- オンラインエディタの手軽さを活かせる
- 実装コストがあまり高くならない（ならなさそう）

#### 欠点

- Github を開き、記事を作成する手間がある
  - Github 側もブラウザ操作できるので、作業はブラウザのみで完結する
  - Zenn 側でリンクを表示するなどの導線があればそんなに面倒ではなさそう

**Comment by tktcorporation** [comment]
https://github.com/zenn-dev/zenn-roadmap/issues/18
これと意図がかぶっていたら close でお願いします
見落としていました:bow:

**Comment by tktcorporation** [comment]
commit でも良いんですが、連携が面倒かなと思ったので PullRequest の形での提案としました。

**Comment by catnose99** [comment]
今のところは「オンラインエディタから記事の作成を行い、その内容で、連携リポジトリに対して PullRequest が送れる」のイメージをしています。プルリクかコミットかはまずは実装しやすい方でやりたいと考えています。

しばらくお待ちください。

**Comment by kiyoka** [comment]
オフラインエディタ「Mark Text」を使うワークフローを紹介します。
オンラインエディタではないですが、要望に近い運用ができるのではないかと思います。
https://zenn.dev/kiyoka/articles/write-zenn-article-with-marktext

**Comment by cm-igarashi-ryosuke** [comment]
検討したのですが、GitHubとの同期の問題があり、Zennとしては [github.dev と VSCode Web拡張](https://info.zenn.dev/release-vscode-extension) をご利用いただく方向でお願いしたいです。
