### ISSUE TITLE
スクラップの詳細画面の上部にも投稿欄を表示してほしい

### ISSUE THREAD

**Issue by yktakaha4** [zenn-dev/zenn-community#241]
いつもサービスを楽しく使わせて頂いています。ありがとうございます。

スクラップ機能を個人的な備忘録として利用しているのですが、内容が長くなってくるとEndキーで画面末尾に移動してから投稿という動きになるため、
スレッドの上部側にも投稿欄があるとより使いよくなるような気がしています。
（これは要望というより所感ですが、Twitterのように最上部に投稿欄&投稿日時の降順で内容が並ぶ...というような表示を選択できると、より柔軟な使い方ができるようにも感じました。ただ議論が目的の場合は現状の表示の方が適切に感じています）

ご検討頂けますと幸いです。

**Comment by catnose99** [comment]
ありがとうございます。

> 内容が長くなってくるとEndキーで画面末尾に移動してから投稿という動きになる

ご指摘の通りですね。ひとまずこの部分の体験をなんとかする方向で考えます。しばらくお待ちください。

**Comment by catnose99** [comment]
> スレッドの上部側にも投稿欄があるとより使いよくなるような気がしています。（これは要望というより所感ですが、Twitterのように最上部に投稿欄&投稿日時の降順で内容が並ぶ...というような表示を選択できると、より柔軟な使い方ができるようにも感じました。ただ議論が目的の場合は現状の表示の方が適切に感じています）


こちら検討しましたが、スクラップの並び順の変更（ #181 ）への対応することになった場合、投稿日時の降順ソート機能があると非常にややこしいことになりそうです。そのため、現状ではソート機能は対応しないことにしました。


ただ、投稿数が増えても入力欄へアクセスしやすいように、ジャンプボタンを表示するようにしました。


![スクリーンショット 2021-04-20 13 29 14](https://user-images.githubusercontent.com/34590683/115337698-6be55200-a1dc-11eb-9c11-42eeea734ced.png)
