### ISSUE TITLE
記事一覧でのいいねに関する表示について

### ISSUE THREAD

**Issue by kai0310** [zenn-dev/zenn-community#248]
現状，記事にいいねをしても記事一覧のページでは以下のようにハートの色が変わらない。
ハートの色が変わらないので自分がいいねを押していなかったという認識をしてしまう。

自分がいいねしたものに関しては色をつけるなどで分かりやすくするなどの方法でご検討して頂けると幸いです。

<img width="200" alt="スクリーンショット 2021-02-23 15 05 44" src="https://user-images.githubusercontent.com/52205108/108807826-a1106200-75e8-11eb-94c6-fadddc9a2e15.png">

**Comment by cm-wada-yusuke** [comment]
すごく実装寄りの話で申し訳ないのですが、記事一覧ガッツリ取得で済むところを自分がいいねした履歴とJOINしなければならなくなり、パフォーマンス低下を招くため、見送りとさせていただきます。
