### ISSUE TITLE
diffのシンタックスハイライトを行った際に、diffの前の行がタグだとプレビュー時に一行空いて表示されてしまう

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-community#255]
> コードブロックでdiff + tsxのシンタックスハイライトを行った際に、diffの前の行がタグ（`<div>`など）だとプレビュー時に一行空いて表示されてしまう

**Comment by catnose99** [comment]
done

**Comment by dqn** [comment]
@catnose99 いつもお世話になっております。こちらのバグ、再発しておりますでしょうか？zenn-cli v0.1.103 と [zenn.dev](https://zenn.dev) で確認しました。他の行も巻き込んでいるので、別のバグの可能性もありますが…

![スクリーンショット 2022-01-23 2 50 42](https://user-images.githubusercontent.com/30195678/150649856-bfe79b4a-8df9-4a14-8f02-7757a8a43534.png)
![スクリーンショット 2022-01-23 2 43 47](https://user-images.githubusercontent.com/30195678/150649860-3fb2a489-9ea5-45ab-8ccc-ff0a75331da8.png)

**Comment by catnose99** [comment]
ご報告ありがとうございます。確認します。

**Comment by uttk-dev** [comment]
@dqn 

ご報告ありがとうございました。
こちらのバグは既に修正しましたが、反映されるまでに時間がかかるため、リリースまでしばらくお待ち頂ければ幸いです。

**Comment by dqn** [comment]
@uttk-dev

お忙しい中ご対応いただきありがとうございます！
