### ISSUE TITLE
改正版を出せるように（記事のリファクタリングのサポート）

### ISSUE THREAD

**Issue by shogowada** [zenn-dev/zenn-community#259]
一度出した記事に手を入れたいとき、どうしても躊躇してしまいます。かといって、同じような内容の記事を少しだけ変えてもう一度出すのも気が引けるし、何も言わずに勝手に編集するのも読者を裏切っているような気持ちになってしまう。

物理的な記事なら、一度出版したものを改正するのが大変なので「仕方ない」で諦められるのですが、デジタルなものはもっといい方法があると思うんです。

コードのようにもっと気軽にリファクタリング出来るようにするにはどうしたらいいかと考えたのですが、以下のような機能はどうでしょうか。

- 今まで通り一度出した記事を編集できるのはそのまま
- それに加えて、一度出した記事を改正版（ver 2, ver 3）として何度でも出版し直せるようにする
- 自分がスキをした記事の改正版が出た場合、通知で教えてくれる
- 記事はデフォルトで最後の改正版を表示することになるが、過去の版も見れるようにする
    - どこが変わったのかdiffを表示できるのも便利かもしれません

もちろん上記の機能全てが必要という訳ではないと思いますし、他にもあると便利な機能があるかもしれませんが、とりあえず頭の中にあるアイデアを書いてみました。

この機能によって、今までのオンライン記事のあり方を変えること・Zennを他のサービスと差別化することもできると思います。スキを押すインセンティブにもなると思います。どうでしょうか。

**Comment by shogowada** [comment]
ただ一つ問題があるのが、UXにそうとう気をつけないとシンプルさにかけてしまうかもしれないことです。データ上は他の記事として扱ってリンクした方がいいかもしれません。その辺をクリアすれば素晴らしい機能になると思います。

**Comment by catnose99** [comment]
アイデアありがとうございます。バージョン番号をつけて変更を通知できるというのはとても面白いと思います。落ち着いたタイミングで時間を取って検討してみようと思います。
