### ISSUE TITLE
本の購入者限定のスクラップ

### ISSUE THREAD

**Issue by dijzpeb** [zenn-dev/zenn-community#264]
本を購入した人のみが閲覧&コメントできるスクラップを作成したいです

**Comment by cm-wada-yusuke** [comment]
organizations 機能と合わせて、プライベートコンテンツについてはあり方を含め検討中です。しばしお待ちください。

関連： https://github.com/zenn-dev/zenn-community/issues/258

**Comment by cm-wada-yusuke** [comment]
@dijzpeb お待たせいたしました。チーム内でも熟考を重ねたのですが、やはりプライベートなコミュニティを形成した場合、悪用やトラブルに対して対応が必要になり、人手とコストが追加で必要になります。Zennは現在少数で運営しており、このたぐいの治安維持が現状難しいです。申し訳ないのですが、一度クローズさせていただきたく存じます。
