### ISSUE TITLE
insertモードの状態がわからない

### ISSUE THREAD

**Issue by YTJVDCM** [zenn-dev/zenn-community#266]
記事編集モードでinsertモードが有効になっていてることが分かりづらいので、Kateのような、insertモードの状態に応じてテキストカーソルの見た目が変わる機能が欲しいです。

**Comment by catnose99** [comment]
@YTJVDCM 

なるほど。
Kateというものを参考にしたいのですが、URLなどを教えていただけますか？（検索してもヒットせず…）

**Comment by YTJVDCM** [comment]
こちらです
https://kate-editor.org/

**Comment by catnose99** [comment]
@YTJVDCM ありがとうございます！参考にさせていただきます。

**Comment by cm-wada-yusuke** [comment]
@YTJVDCM ご提案ありがとうございます。 文字入力の insert/override モードがカーソルでわかると嬉しいという意図でしょうか？ catnoseさんがアプリを実際に試した上で、CSSも検討しましたが、ブラウザ上では IME の入力モードを検出することができなく、このとおりの機能を実現することは難しそうです。

* GitHub 連携いただいた上で、手元でkate-editorなどお好みのエディタで編集する
* 別の手段で insert/overrideを検出する

GitHub 連携は、もし実施頂く場合、移行が大変かと思いますので、エクスポート機能をお待ちいただくのもご一考いただければと思います。

* https://github.com/zenn-dev/zenn-community/issues/18
