### ISSUE TITLE
ダークモードが欲しい

### ISSUE THREAD

**Issue by Khsmty** [zenn-dev/zenn-community#267]
普段はダークモードを主に使っているため、Zennを見ると、少し眩しいと感じます。
ダークモードが欲しいです。

**Comment by catnose99** [comment]
こちらは以前より検討しています。今しばらくお待ちください。

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ニーズの割に実装コストに見合わないため対応しないこととなりました。

**Comment by sakumei** [comment]
chromeブラウザをお使いなら機能拡張で[Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh/related?hl=ja)を検討してください。
