### ISSUE TITLE
左右キーで本の前・次のページへ遷移できるように

### ISSUE THREAD

**Issue by ixkaito** [zenn-dev/zenn-community#270]
アクセシビリティ向上にもなると思いますので、キーボードの左右キーで本の前・次のページへ遷移できるといいな。

**Comment by cm-wada-yusuke** [comment]
コメントありがとうございます。たしかにキーボードで操作できると嬉しいですね。一方でもともとの左右キーの動作を期待している方々にとってはそれを上書きすることにもなるので、検討させていただきたいです。

Chromeであれば、キーボードの操作に慣れている場合、 Vimium でリンク移動も含めてキーボードで完結できます。こちらもご覧ください。
[Vimium \- Chrome ウェブストア](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=ja)

**Comment by catnose99** [comment]
@ixkaito 
こちらさきほどのリリースで対応しました。
ご要望ありがとうございました。

**Comment by ixkaito** [comment]
@catnose99 すばらしい！ありがとうございます！
