### ISSUE TITLE
[追加機能の要望]記事の形態（ex.まとめ/コラム/ポエム/ハウツー）が分かる機能もほしいです

### ISSUE THREAD

**Issue by kurocraft0312** [zenn-dev/zenn-community#271]
いつもお世話になっております。

## 要望
記事の形態（ex.まとめ/コラム/ポエム）が分かるタグのような機能もほしいです（今のトピックスみたいな機能をイメージしています）

![memo](https://user-images.githubusercontent.com/33552681/113466015-81841900-9473-11eb-8713-ac9feedc61d0.png)

## 背景
 - Zennは「朝の出勤時にざっと良さそうなツールや技術がないか、まとめをざっくり見たいとき」「自分で開発しながら参考で記事を読む＆コードを試して動かすとき」利用することが個人的に多いため。
 - 「ハウツー」「まとめ」のように、指定する記事形態で絞り込みできる機能があると、見たい情報にだけ絞って記事を探すことができるため。

## 関連
とくにございません。

何卒よろしくお願いいたします。

**Comment by cm-wada-yusuke** [comment]
@kurocraft0312 
コメントありがとうございます。Zennのお手伝いをしている者です。

* 少し詳しく聞きたいのですが、[Tech or Idea](https://zenn.dev/tech-or-idea) 以外にも種類がほしい、ということでしょうか？
* ユースケースも添えていただいて大変ありがたいです。ごもっともだと考える一方、出稿側の手間を最小限に抑えたいという思いもあります。検討させてください。いまいまは、「Tech かつ、5min read 以内のものを読む」といった感じでご判断いただけると幸いです

**Comment by kurocraft0312** [comment]
@cm-wada-yusuke
ご返信が遅くなってしまい大変申し訳ございません。お世話になっております。

> 少し詳しく聞きたいのですが、Tech or Idea 以外にも種類がほしい、ということでしょうか？

→左様でございます。正確に言うと、もう少し細分化して頂けると嬉しいなあと思う所存です。

> ユースケースも添えていただいて大変ありがたいです。ごもっともだと考える一方、出稿側の手間を最小限に抑えたいという思いもあります。検討させてください。

→かしこまりました！あくまでこちらもあったら嬉しいと思うレベルですので、もし可能でしたらお願いいたします！

**Comment by cm-wada-yusuke** [comment]
@kurocraft0312 大変お待たせいたしました。チーム内でも時間をかけて話し合ったのですが、やはり **いつだれが分類するか** というUX部分のひと手間に回答が出せませんでした。少し内情をお話すると現状は `tech` と `idea` のみですが、それでも明らかに逆のカテゴリにしてほしいよね、という記事もありますので、現時点での細分化対応は難しいです。ご提案いただいたところ大変申し訳無いのですが、一度クローズさせていただきたく思います。
