### ISSUE TITLE
公開日時なのか更新日時なのかが分かりづらい

### ISSUE THREAD

**Issue by ko1nksm** [zenn-dev/zenn-community#273]
## 提案・要望
公開日時なのか更新日時なのかをわかりやすくして欲しい

## 背景

1. 最初に[こちら](https://zenn.dev/yajamon/articles/eb72c96faa60b0aa569b)のページをGoogleからの検索で見つけました
2. トップの日付に「2021/4/3」と書かれていることから、つい最近公開されたのだろうと思いました
   -  実際にはこれは更新日時であり公開日時は「2020-10-22」ですがポインタを合わせないとそれがわかりません
3. 記事が含まれるトピックスの[latest](https://zenn.dev/topics/bash?order=latest)を開きましたが（古い記事なので当然ですが）最近の一覧に記事が見つかりません
   - 記事一覧には日付が表示されていますが、公開日時なのか更新日時なのか表示されていないため区別できません
4. よって記事と記事一覧の両方に日付が表示されているものの、それが異なる日付であることがわかりづらく、最近の記事が正しく一覧表示できていないと勘違いしました

**Comment by catnose99** [comment]
@ko1nksm 

ご指摘はもっともだと思ったので、以下のように日付を明確に表示するようにしました。

![スクリーンショット 2021-04-07 10 09 51](https://user-images.githubusercontent.com/34590683/113796109-6bcf6600-9789-11eb-9c57-e3aebbeb613f.png)
