### ISSUE TITLE
Publication機能

### ISSUE THREAD

**Issue by Tocyuki** [zenn-dev/zenn-community#275]
## 提案・要望
Qiitaで言うところのOrganizations機能を実装してほしい

## 背景
是非実装してほしいと思っていたが該当issueが無かったため起票しました

## 関連
https://github.com/zenn-dev/zenn-community/issues/258#issuecomment-796333917

**Comment by cm-igarashi-ryosuke** [comment]
@Tocyuki 
Zenn開発チームです。
起票ありがとうございます。
https://github.com/zenn-dev/zenn-community/issues/258#issuecomment-796333917 にもあります通り、実現方法を検討しておりますので、しばらくお待ち頂ければと思います。

**Comment by catnose99** [comment]
企業やコミュニティなどチームで記事を管理・投稿できるような仕組みを準備中です。

**Comment by catnose99** [comment]
クローズドベータでリリースしました。
https://info.zenn.dev
