### ISSUE TITLE
【あったら嬉しい】公開していない状態の記事を、特定の人だけ見ることができるようにする

### ISSUE THREAD

**Issue by sushi-udon** [zenn-dev/zenn-community#279]
## 提案・要望
公開していない状態の記事を、特定の人だけ見ることができるようにしたい。

## 背景（欲しいと思った理由）
例えば、Aさんという方のお話を元に書いた記事があるとします。
その内容をAさんにご確認頂きたいときなどに、現状ですと公開後にしか共有することができないため、この機能があったら便利だと思いました。

## 関連
特になし

**Comment by cm-igarashi-ryosuke** [comment]
@sushi-udon 
Zenn開発チームです。

貴重なご意見をいただきましてありがとうございます。
本件と類似するissue: #97 がありまして、こちらで記事も含めて検討中というステータスになっておりますので、お待ち頂ければと思います。
内容が重複しますので、本Issueはクローズさせて頂きます。

**Comment by sushi-udon** [comment]
@cm-igarashi-ryosuke 
返信遅れてしまい、申し訳ございません。
承知いたしました！ご確認いただき、ありがとうございます✋
