### ISSUE TITLE
Webエディタ上で「option+d」を押すと期待する「∂」ではなく文字の削除が実行される。

### ISSUE THREAD

**Issue by ensan-hcl** [zenn-dev/zenn-community#282]
## 事象

Webエディタで「option+d」を入力すると、カーソルのある行が文末方向に削除される挙動を示し、目的の「∂」が入力できない。

## 発生したページのURL

URLとしては入力できないが、新規記事の作成画面など。

## 再現方法

入力方式を英字とし、エディタ上で「option+d」を入力する。その他のキー、例えば「option+z→Ω」「option+p→π」は問題なく動作する。

## 環境

- Device: Macbook Air 2020
- OS: macOS11.2.3
- Browser: Brave V1.23.71

## 補足

Option周りの挙動でいくつか怪しいものを発見したので、補足として述べる。

* 「option+f」では「ƒ」の入力が期待されるが、文末方向にカーソルが移動する挙動を示す。
* 「option+b」では「∫」の入力が期待されるが、文頭方向にカーソルが移動する挙動を示す。
  * この挙動を示すのはf(forward), b(backward), d(delete)の3文字であったため、何かコマンド関連の処理が絡んでいると思う。
* 「option+e」を入力した後に削除キーを入力すると「´」に加えて制御用文字であるU+001Cが入力される。赤丸で表現される。「option+u」「option+i」「option+n」でも類似の事象が発生。
  ![image](https://user-images.githubusercontent.com/63481257/115149636-efe5ef80-a09f-11eb-886c-2f5bd27c0ad1.png)

**Comment by catnose99** [comment]
ご報告ありがとうございます。
Zennの記事や本のエディターが依存しているパッケージのデフォルトのショートカットのよりご指摘の挙動が発生しているようです。
https://easy-markdown-editor.tk/

これらのショートカットは無効にして通常の挙動となるように修正しようと思います。今しばらくお待ちください。

**Comment by ensan-hcl** [comment]
ありがとうございます。
>「option+e」を入力した後に削除キーを入力すると「´」に加えて制御用文字であるU+001Cが入力される。赤丸で表現される。「option+u」「option+i」「option+n」でも類似の事象が発生。

の部分で言及した事象はmacOS側のデフォルトの挙動のようなので、エディタ側の問題ではありませんでした。失礼しました。

**Comment by catnose99** [comment]
@ensan-hcl 
こちら対応しました。

**Comment by catnose99** [comment]
[memo] ライブラリ側での修正が確認できました。
https://easy-markdown-editor.tk/
