### ISSUE TITLE
編集とプレビューを同時に行いたい

### ISSUE THREAD

**Issue by t4t5u0** [zenn-dev/zenn-community#283]
## 提案・要望
記事や本を書く際に、左側に編集画面、右側にプレビュー画面が開いてほしいです。

## 背景
現在はトグルなので、いったり来たりが少しつらいです

**Comment by cm-wada-yusuke** [comment]
@t4t5u0 ご提案ありがとうございます。そしてごもっともなご指摘です。こちらとしてもやりたいと思っていますが、シンタックスハイライト周りの処理が非常に難しく対応するにしてもしばらく先になりそうです。もしよければ zenn-cli をご利用いただき、手元での編集・プレビューをご活用いだければと思います。…私も iPad Pro で執筆したりするので、Webエディタが充実していると嬉しいというのは同じです。

**Comment by t4t5u0** [comment]
返信ありがとうございます。zenn-cli の使用を検討します

**Comment by uttk-dev** [comment]
web 上での実装が難しく、体験の良いUIを作ることが出来そうにないためクローズしたいと思います。
