### ISSUE TITLE
issueラベルの種類を追加

### ISSUE THREAD

**Issue by skanehira** [zenn-dev/zenn-community#284]
## 提案・要望
issueのラベルの種類を追加してほしい

**凡例**
- スクラップ
- ログイン
- 記事
- リポジトリ連携
- 検索
- カテゴリ

## 背景
提案したいことがすでにissueになっているかどうかを確認するのに、機能単位で絞り込みできたら効率が良いため

## 関連
なし

**Comment by cm-wada-yusuke** [comment]
ご提案ありがとうございます。また、issueを出していただくときに既存のissueも確認していただいているということで、ありがとうございます。ラベルわけはあると確かに便利ですが、現状Zennチームとして問い合わせ対応から開発まで行っています。今の状態からラベルを増やしたとして、適切にメンテナンスできる保証と体制がないため、先送りとさせてください。

現状では、一度キーワードで検索していただいて重複を確認していただく、などご対応いただければと思います。お手数をおかけしますが、よろしくお願い致します。
