### ISSUE TITLE
スクラップに投稿したコメントを折りたたみたい

### ISSUE THREAD

**Issue by skanehira** [zenn-dev/zenn-community#285]
## 提案・要望
スクラップボックスに投稿したコメントを折りたたみたい

## 背景
スクラップにつらつら情報を書いていくと長くなってしまうので、
折り畳めるようになったらスクロールも楽になるため

**Comment by cm-wada-yusuke** [comment]
@skanehira ご提案ありがとうございます。折りたたみを利用したい状況について少し詳しく教えて下さい。

* 下にスクロールして新しいコメントを入力するときに欲しい
* 俯瞰したい
* 他

**Comment by skanehira** [comment]
当初、スクラップに記事のネタを溜め込んでいこうとしていました
そのため、結構な量になっていたので折りたたみたいなと考えていました

しかし、そもそもスクラップって溜めるのでなく一時的にメモする場所として使うべきなので、
用途が異なるなと思ったのでこのissueはcloseとさせてくださいm(_ _)m
