### ISSUE TITLE
スクラップのTwitterカードのタイトルが変更されない

### ISSUE THREAD

**Issue by skanehira** [zenn-dev/zenn-community#286]
## 事象
スクラップの名前を変更したあと、リンクをTwitterに貼る時にカードのタイトルが変更されず古いままになっている

## 発生したページのURL
https://zenn.dev/skanehira/scraps/1455434c808975#comment-d7b89334b7280d

## 発生した画面のスクリーンショット
![](https://i.gyazo.com/b748e7285de03c680dfaf53a55eae0f3.png)

## 再現方法
1. スクラップを作成
2. コメント投稿
3. スクラップ名を変更
4. コメントのパーマリンクを取得してTwitterに貼る

## 環境
- Device: M1 MacBook Pro 13
- OS: MacOS Big Sur
- Browser: Vivaldi 3.6.2165.40 (Stable channel)

**Comment by kato-k** [comment]
カードは一定間隔を開けてTwitterが取得する仕様になっているため、すぐには変更が反映されません。
一度こちらのページにURLを貼り付けて再度Twitterに取得させてみてはいかがでしょうか→https://cards-dev.twitter.com/validator

**Comment by cm-wada-yusuke** [comment]
@kato-k  さんのご指摘どおり、Twitter側のさじ加減によるものが大きいため、サードパーティツールを用いで更新を試みていただければと思います。
