### ISSUE TITLE
スクラップの下へジャンプボタンのキーボードフォーカス考慮

### ISSUE THREAD

**Issue by yamanoku** [zenn-dev/zenn-community#287]
## 提案・要望

[4/20のアップデート](https://zenn.dev/changelog#20210420)により追加されたスクラップでコメントが多い場合に「下へジャンプ」するボタンが追加されたが、
このボタンにキーボードフォーカスが当たるようにしてほしい。

## 背景

タブフォーカス操作をしているときにこのボタンにフォーカスが当たらず利用することができなかった。

[![フォーカスの動き確認](https://i.gyazo.com/32dc1c28094bc449aa64b4afdf9f454a.gif)](https://gyazo.com/32dc1c28094bc449aa64b4afdf9f454a)

提案としてはトピックリストの次に下へジャンプするボタンへフォーカスが当たるようになると
操作ができるようになると思うのでフォーカス順序を考慮してほしい。

**Comment by catnose99** [comment]
分かりやすくご指摘いただき、ありがとうございます。
こちら対応します。

**Comment by catnose99** [comment]
対応しました。
