### ISSUE TITLE
書いた記事を後から本にまとめたい

### ISSUE THREAD

**Issue by daichi-takezawa** [zenn-dev/zenn-community#288]
## 背景
とりあえず記事で作成して後から本にまとめたいと思った場合、現状コピペして新しくチャプターとして作成する事しかできないと思います。URLやいいねも失われてしまうので作成した記事を本にまとめられたら嬉しいのですが... どうでしょうか？

**Comment by cm-wada-yusuke** [comment]
@kurowassan1212 ご提案ありがとうございます。たしかに個別で記事を書いて、あとからまとめられると便利そうです。一方で、以下のことを新しく考慮せねばなりません。

* チャプターリンクの記事が持ち主かどうかの判定。本の作成を便利にすると、その分転売に狙われやすくなってしまいます
* 記事を削除したときの挙動
* 「購入者のみに公開」との折り合い

本を読む側としてはこの本専用のコンテンツとしてまとまっている方が、ありがたい面もあります。直リンクと言う形で実現するのは難しいかもしれませんが、作成した記事を手早く本のチャプターにコピーするといった機能は zenn-cli に投入できるかもしれません。そちらの方面で検討させていただきたく存じます。

**Comment by kurowassan1212** [comment]
丁寧にありがとうございます。私のイメージとしてはリンクをまとめるのではなく、本にまとめると記事は本としてしか見れなくなる、つまり本専用のコンテンツに切り替わるというものでした。技術的に実装できるかどうかわかりませんが...

**Comment by cm-wada-yusuke** [comment]
なるほど！勘違いしていました、すいません。
それまで記事だった見た目が、本のチャプターの見た目になるイメージですね。いただいた案で一度検討してみます、ありがとうございます。もともと記事についていたコメントをどうするか、という部分もあるので持ち帰らせてください。

**Comment by cm-wada-yusuke** [comment]
チームで検討しました。申し訳ないです、見送りとさせていただきます。

- 記事についていたコメントを移すすべがない
- SEO上重複コンテンツとみなされる可能性が高い
- 本にまとめた後に、その本を有料にした場合、サーチエンジンからみるといきなりアクセスできない形となり、サイト全体の質に影響する可能性がある
