### ISSUE TITLE
Scrapsなどの検索結果が古い順に表示されている→新しい順に変えて欲しい

### ISSUE THREAD

**Issue by negitamago** [zenn-dev/zenn-community#289]
## 提案・要望
Scrapsなどの検索結果が古い順に表示されている→新しい順に変えて欲しい

## 背景
新しく追加された記事等をみつけにくいため

**Comment by cm-wada-yusuke** [comment]
@negitamago ご提案ありがとうございます。検索ですが、こちらの検索ページのことで合ってるでしょうか。

* 検索 https://zenn.dev/search

こちらですが現状「いいねの数が多い順」、つまり人気順になっています。他のソート条件を検討しますのでお待ちください。ユースケースにによって、コメントが新しくついているものが見たい、単純に作成された日時が新しいものがいい、などがあると思います。

なお、単純に新しいものから探す場合はスクラップ一覧を、

* https://zenn.dev/scraps

トピックごとに新しくうごきがあったものを知りたい場合はトピックごとのスクラップ一覧を、

*  https://zenn.dev/topics/typescript/scraps?order=daily　←TypeScript の場合

それぞれご活用いただければと思います。

**Comment by cm-wada-yusuke** [comment]
@negitamago 本日リリースし、検索結果をソートできるようにしましたので、お試しください。
