### ISSUE TITLE
見出しへのリンクを作りたい

### ISSUE THREAD

**Issue by sevenc-nanashi** [zenn-dev/zenn-community#290]
## 提案・要望
リンクのURLに`#見出し名`でその見出しへのリンクを作れるようにして欲しいです。
また、#の前に[]か何かでIDを指定し、そのIDでも作れるようにして欲しいです。
```md
# Aをする
もうAをした人は[#Bをする](#Bをする)まで飛ばして下さい。
色々します。

# Bをする
色々なことをします。
```
```md
# Aをする
もうAをした人は[#Bをする](#[do-b])まで飛ばして下さい。
色々します。

[do-b]# Bをする
色々なことをします。
```
## 背景
アカウントを作成するところから始める記事を書いていて、「もう○○している人は#××まで飛ばして下さい。」のように飛ばすリンクが欲しかったので建てました。

**Comment by sevenc-nanashi** [comment]
あ、出来たのですね。知らなかったです。
しかしそれならどこかに見出し名で出来ることを書いておくべきかなと思いました（個人の感想です。見逃してるかも知れません）

**Comment by cm-wada-yusuke** [comment]
空白などの扱いが現状自動になっており、ユーザーへ周知するには若干機能不足感が否めないため自動で生成された目次でのみ利用しています。周知する場合は提案いただいたように 任意のID を付与できる状態もセットで提案できるように検討します。

ご連絡ありがとうございました。
