### ISSUE TITLE
本のタイトルが狭い画面でも記事に出ていてると嬉しい

### ISSUE THREAD

**Issue by terrierscript** [zenn-dev/zenn-community#291]
## 提案・要望

本について、モバイル等の狭い画面で見た時、タイトルが表示されないのがされていると嬉しいと感じました。

## 背景

SEOからジャンプしてきた際など、何の本かわからないのが少々不便に感じました。
書き手からしても、逆に本のタイトルが無い前提で章題を考えることになりそうかなとも感じました

|desktop|mobile|
|-|-|
|![スクリーンショット 2021-05-04 17 30 21](https://user-images.githubusercontent.com/13282103/116979035-7422ae80-acff-11eb-92c5-e1ad8e7a5479.png)|![スクリーンショット 2021-05-04 17 30 01](https://user-images.githubusercontent.com/13282103/116979041-74bb4500-acff-11eb-9fad-15d3274673a6.png)|

## イメージ図

例えばこのような場所にあると良いのではないか？を想像しました

|ヘッダに出す案|チャプター付近に出す案|
|-|-|
|![スクリーンショット 2021-05-04 17 37 00](https://user-images.githubusercontent.com/13282103/116979026-7127be00-acff-11eb-8563-62243ff041f8.png)|![スクリーンショット 2021-05-04 17 33 32](https://user-images.githubusercontent.com/13282103/116979032-72f18180-acff-11eb-9a26-86ba9a742eb9.png)|

**Comment by catnose99** [comment]
> SEOからジャンプしてきた際など、何の本かわからない

たしかに。改善しようと思います

**Comment by catnose99** [comment]
対応しました
