### ISSUE TITLE
チャプター数の上限を50から増やしてほしい

### ISSUE THREAD

**Issue by kazutxt** [zenn-dev/zenn-community#292]
## 提案・要望
1つの本で作成できるチャプターが50に制限されているかと思いますが、これを100まで上限を増やしてほしいです。

誤操作や紙幅が大きくなりすぎるのを防ぐためのガードとして、上限が50で設定されているかと思いますが、
Zennのオンライン書籍の場合は、全体の文量が大きくなっても、適切なチャプターの管理が行われていれば、可読性を失うことは無いかと思います。
むしろ、チャプター数が制限されることで、1つのチャプターのボリュームが大きくなるため、文量が多くなったりテーマが混ざりやすくなると思われます。

上限そのものを撤廃するのは好ましくないと思われますので、せめて100程度まで増やして頂けないでしょうか。

## 背景
作成した書籍のチャプター数が50を超えてしまい、チャプターをマージしながら、チャプターを節約して執筆をしています。
* https://zenn.dev/kazutxt/books/flutter_practice_introduction

**Comment by catnose99** [comment]
こちら対応しようと思います。

**Comment by kazutxt** [comment]
ありがとうございます。
よろしくおねがいします。

**Comment by catnose99** [comment]
@kazutxt 上限を100へと変更しましたのでIssueをクローズさせていただきます。
