### ISSUE TITLE
本の閲覧中、下部のボタンで次のチャプターに移動した際に、頻繁に上部へのスクロールが行われない

### ISSUE THREAD

**Issue by ensan-hcl** [zenn-dev/zenn-community#294]
## 事象
本の閲覧中、下部のボタンで次のチャプターに移動した際に、頻繁に上部へのスクロールが行われない。

## 発生したページのURL
https://zenn.dev/mebiusbox/books/22d4c1ed9b0003/viewer/80f0ee

これに限らず、多くの本の閲覧中に同様の動作を示す。

## 再現方法
1. 本を開く
2. ページ最下部に移動する
3. トラックパッド等の拡大ジェスチャによって「NEXT」部分を拡大してクリック
4. 上部へのスクロールが行われない

すでに次のページを読み込んだ状態だと発生しないことがあるほか、稀に発生しないことがある。
## 環境
Chrome系ブラウザで発生。

- Device: MacBook Air 2020(early)
- OS: macOS11.2
- Browser:  90.0.4430.93 (Official Build) （x86_64）

**Comment by catnose99** [comment]
見直してみます！

**Comment by catnose99** [comment]
@ensan-hcl 
こちら修正を行ったのですが、問題が解消するかご確認いただけますでしょうか？

**Comment by ensan-hcl** [comment]
いえ、解消しておりません。

**Comment by catnose99** [comment]
問題が発生するのは拡大ジェスチャを行ったときのみでしょうか？

**Comment by catnose99** [comment]
こちら色々な方法を試してみたのですが、現状では良い解決方法が見つかっていません。
（ピンチインでの拡大時にブラウザの`window.scrollTo(0, 0)`等がうまく効かない）

すみませんが、現状では拡大ジェスチャを戻す等の形で対応をお願いします。

**Comment by ensan-hcl** [comment]
わかりました。ありがとうございます！

**Comment by cm-wada-yusuke** [comment]
ご連絡ありがとうございました。
