### ISSUE TITLE
リポジトリ連携時、`.DashboardArticles_linkAdd` が `display: none`されるのが期待動作だと思うが、スマートフォン時にはされていない

### ISSUE THREAD

**Issue by ulwlu** [zenn-dev/zenn-community#296]
## 事象
- 【前提条件】リポジトリ連携済
- スマートフォン時に`.DashboardArticles_linkAdd` が `display: none`されていない。
- PC時は`display: none`されている。

## 発生したページのURL
https://zenn.dev/dashboard

## 発生した画面のスクリーンショット
<img src="https://user-images.githubusercontent.com/41639488/117562789-9f7d1300-b0dc-11eb-97ee-17453de97816.jpg" width="320">

## 再現方法
1. リポジトリ連携する
2. スマートフォンで https://zenn.dev/dashboard にアクセスする

## 環境
- Device: iPhone SE 2
- OS: iOS14.4.2
- Browser: chrome 87.0.4280.163

## その他
重箱で隅つつくレベルのバグなので、優先度最低で結構です。

**Comment by catnose99** [comment]
ご指摘ありがとうございます。修正します。

**Comment by catnose99** [comment]
対応しました
