### ISSUE TITLE
Scrapsのコメント投稿用のMarkdown Editorで改行時に消えてしまう文字列がある

### ISSUE THREAD

**Issue by Himenon** [zenn-dev/zenn-community#297]
## 事象

* 特定の文字列を入力した後改行すると、入力した文字列が消える

## 発生したページのURL

* `https://zenn.dev/[username]/scraps/[hash]`

## 発生した画面のスクリーンショット

![zenn-bug mov2](https://user-images.githubusercontent.com/6715229/117817628-bcfbd980-b2a2-11eb-96fe-6f7f7d3c21c2.gif)

## 再現方法

1. Scrapのコメント投稿用のMarkdown Editorで`**`と入力します。
2. Enterキーで改行します。
3. 入力した`**`が消えます。

`--`という文字列でも発生します。

## 環境

- Device: PC
- OS: macOS Catalina 10.15.7
- Browser: Google Chrome 90.0.4430.93（Official Build）（x86_64）

**Comment by cm-igarashi-ryosuke** [comment]
@Himenon ご報告ありがとうございます。問題を認識しました。近日中に修正いたしますね。

**Comment by catnose99** [comment]
こちら対応しました。
