### ISSUE TITLE
画像にリンクを付加するとキャプションが正常に表示されない

### ISSUE THREAD

**Issue by miya789** [zenn-dev/zenn-community#298]
## 事象
画像にリンクを付加すると，キャプションが正常に表示されませんでした

## 発生したページのURL
https://zenn.dev/miya789/articles/github-actions-rubocop
恥ずかしながら，自分の記事の例です

### 正常時 (Webのプレビューのみ)
![image](https://user-images.githubusercontent.com/31382715/118128692-35df6a80-b436-11eb-9fd4-c7817032c692.png)

### 異常時 (一部開発者ツールの画面も)
![Screenshot from 2021-05-13 21-49-35](https://user-images.githubusercontent.com/31382715/118127963-44795200-b435-11eb-8585-f1efd2ef0489.png)

## 再現方法

以下の様に変更すると発生します

```diff markdown
- ![rubocop-linter-actionを使ったPRの表示例](https://storage.googleapis.com/zenn-user-upload/6k87lepan1tw4l3azw3d9ceupift)]
+ [![rubocop-linter-actionを使ったPRの表示例](https://storage.googleapis.com/zenn-user-upload/6k87lepan1tw4l3azw3d9ceupift)](https://github.com/miya789/RubocopReviewTest/pull/5)
_`rubocop-linter-action` を使った PR の表示例． Rubocop で違反箇所があると GitHub Actions が落ちます．_
```

## 環境
- 特に無し

**Comment by catnose99** [comment]
色々試してみましたが「画像を含むaタグ の 直後の emタグ」を検知するのは現在のCSSだけでは難しいと思っています。以下の形で対応をお願いします。

```
[![alt](画像のURL)*キャプション*](リンク先のURL)
```

**Comment by miya789** [comment]
@catnose99 

なるほど，ありがとうございます．
ひとまず正常に表示できました．
失礼いたしました．
