### ISSUE TITLE
ユーザー側が作成したＣＳＳを適用できるようにしてほしい。

### ISSUE THREAD

**Issue by yuki1111117** [zenn-dev/zenn-community#300]
## 提案・要望
ＣＳＳをユーザー側で変更、比較、共有、販売できるようにしてほしい。

## 背景
ＬＩＮＥの有料・無料のテーマ機能が気に入っており、Zennでも似たようなものが欲しいと思いました。

**Comment by cm-wada-yusuke** [comment]
こちら広告と合わせて検討させてください。

https://github.com/zenn-dev/zenn-community/issues/274

**Comment by cm-wada-yusuke** [comment]
@yuki1111117 社内で検討しましたが、セキュリティ上の理由で今の仕組みに載せるのは難しそうです。

* 購入ボタンの文言やUIを変えてユーザーに意図せず購入させる余地ができてしまう
* 特定の領域内（例えば記事のみなど）に適用するように考えることもできるが、結局レンダリング済のHTMLにCSSを適用する以上、やろうと思ったら他のコンポーネントにもCSSを適用できてしまう

とくに決済の仕組みがあるZennではすぐには難しそうです、ご了承ください。
