### ISSUE TITLE
スクラップでも画像をコピペで配置したい

### ISSUE THREAD

**Issue by tktcorporation** [zenn-dev/zenn-community#301]
## 提案・要望
スクラップでも画像をコピペでアップロード、配置できるようにしてほしい

## 背景

記事の方では、コピーした画像をペーストで直接アップロードできると思うのですが、
スクラップではそれができず、コピーした画像を一旦ローカルに保存してそれを選択してアップロードという手順をとっています。
これが面倒なので改善できると嬉しいです。

**Comment by cm-wada-yusuke** [comment]
@tktcorporation リクエストありがとうございます。こちら検討中です。恐れ入りますが重複につきこちらの ISSUE はクローズさせていただきます。

https://github.com/zenn-dev/zenn-community/issues/167

をウォッチいただければと思います。

**Comment by tktcorporation** [comment]
@cm-wada-yusuke 
すみません、見つけられていなかったです。
対応ありがとうございます:bow:
