### ISSUE TITLE
スライド表示機能を追加して欲しい

### ISSUE THREAD

**Issue by KazukiKuriyama** [zenn-dev/zenn-community#302]
## 提案・要望
スライド表示機能を追加して欲しい

## 背景
Qiitaから移行検討中ですが、Qiitaでは勉強会等でスライド表示することがあり、スライド表示がないと完全に移行することが難しいため。

## 関連
https://qiita.com/Qiita/items/4ff5873776992f0511d6

**Comment by cm-wada-yusuke** [comment]
@KazukiKuriyama ご提案ありがとうございます。スライド表示は魅力的な機能ですが、いまのところZennに組み込むことは考えていません。

知見の共有のためには記事または書籍を記述する形式が良いと私たちは考えており、スライド表示のことを考えるとどうしても段落が短くなったり、画像のサイズをかえたりと、本来の作業から追加で考えることになります。「良い記事と良いスライド」の両立は難しいのではないかと。

Markdown で記載したものをスライド表示したい場合は、それ専用のツールを利用することをおすすめします。私は [Marp: Markdown Presentation Ecosystem](https://marp.app/#get-started) を利用しています。

ご理解いただけますと幸いです。よろしくお願い致します。
