### ISSUE TITLE
スクラップの管理画面の初期表示はAllではなくOpenにしてほしい

### ISSUE THREAD

**Issue by nnabeyang** [zenn-dev/zenn-community#303]
## 提案・要望
現状、"スクラップの管理"を押したとき、"All"が選択された全件表示状態で表示されるが、"Open"にして頂きたいと思います。

## 背景
スクラップのクローズされるタイミングはまちまちで、ずっとオープンのままな古いスクラップを開くのに毎回"スクラップの管理"を選択して、"Open"を選択してという操作を繰り返しているので、はじめから"Open"の方が良いと思います。

## 関連

イシューを検索した限り、見当たりませんでした。

**Comment by catnose99** [comment]
ありがとうございます。検討させていただきます。

**Comment by catnose99** [comment]
こちら検討したのですが、以下の理由から見送らせていただきます。

- ユーザーによっては現状の仕様を好むこと
- 検索の手間が増える可能性が高いこと（クローズされたスクラップを検索するときには検索フィールドにテキストを入力したうえでタブを切り替える必要がある）
- SEOへの影響（クローズされたスクラップがクロールされづらくなる = 検索結果にインデックスされづらくなる）

ご不便をおかけして申し訳ないです。

**Comment by nnabeyang** [comment]
検討いただきましてありがとうございました。
理由についても丁寧に説明してくださり、ありがとうございます。
