### ISSUE TITLE
KaTeXの更新と後方互換性について

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-community#304]
ref: https://github.com/zenn-dev/zenn-editor/pull/170

- 現在Zennのマークダウン記法ではKaTex v0.12.0が使用できる（数式が書かれている場合にはクライアントで`https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js`が読み込まれる）
- 2021年4月リリースのKaTex 0.13.xで破壊的変更が行われた
- 旧バージョンと新バージョンの両立はライブラリの性質上困難

## 対応について
- チームで対応方針を決める
- 破壊的変更となる場合は事前に周知する/ユーザーへ適切に通知する方法を検討

**Comment by y-yu** [comment]
どのような問題が生じたのかよく分かっていませんが、もしLaTeX上の何かのコマンドが使えなくなったというような場合でしたら、0.13系の方が基本的に表現力が高いと思っているので、LaTeXによるコマンド定義を記事テンプレートに埋め込んでしまうことで解決できるのではないか？ 🤔 というようなことを思いました。

**Comment by catnose99** [comment]
具体的にはKaTeX記法をLaTeXに近づけるために記述の仕方に一部変更があったようです。
https://github.com/KaTeX/KaTeX/issues/2490

**Comment by y-yu** [comment]
ありがとうございます。リンクされているKaTeXのマイグレーションガイドを見てみました。先に（あくまでも）個人的な結論からもうしあげておくと、たぶんこの変更で記事に問題が生じるユーザーは存在しない可能性さえあると思います。なぜそう思うのか説明すると、こういう感じです。

- KaTeXにしろMathJaxにしろ、この手のものを好んで使うのはLaTeXをある程度使っていて、たとえば同人誌や論文などをLaTeXで作っていて、そこからzenn.devの記事にするために持ってきたというように考えられる
    - KaTeXではじめてこの数式記法に入門した、という人も存在しなくはないと思うが、大多数はLaTeXから入門していると考えられ、LaTeXとは異なるKaTeXの仕様に依存した数式を書いている人がいる可能性は低いと思う
- この中で自分が知っていたLaTeXとKaTeX 0.12.0との違いとして、あきらかに引数のパーズや展開が変（未完成？）であろうとは思ったものの、そこは素直に使うのを諦めて対応した
    - KaTeXとLaTeXの違いに気がついた人がいても、たぶんKaTeXで無理やりがんばる方法を探すよりは使うのをやめる人が多いのではないか……？
- ここで紹介されているコマンドや0.13 vs 0.12の違いは、数式というよりはLaTeXとの差であって、数式関連のコマンドに大きな変更はないように思われる
    - LaTeXはいわばMarkdownのように文書全体の組版能力があり、数式はそのごく一部の能力にすぎない
         - 一方でzenn.devではMarkdownで記事と書いて、KaTeX記法はその一部の数式を記述するのに使うだけな人が多いと思う
    - したがって、そもそもKaTeXの`\def`など組版用のコマンド（not 数式）を利用している人が少ないのではないか 🤔 
        - まあ、そう書いてる自分は`\def`つかったりしてるわけですが……

あくまで主観ですし、自分の記事もなんとか無理やり（？）KaTeX 0.12.0でもそれなりに綺麗さを保てるようにして公開できたので、全然あわてているわけではないですが、特にマイグレーションガイドの`Macro arguments`のあたりはむしろLaTeXユーザーが混乱すると思うので、今の記事でこのあたりの機能が利用されているかを調査することよりも0.13系へアップデートする方がむしろUXが高いような気がします。

**Comment by catnose99** [comment]
とても参考になる情報をありがとうございます。

> この変更で記事に問題が生じるユーザーは存在しない可能性さえあると思います

なるほど、理由も納得感があります。

既存の記事で互換性のない機能が利用されているかというの調査については、以下の理由からやっておきたいと考えています。

- 自動化でき、今後同様の懸念が発生したときに同じ方法を使い回せること
- 仮にZennに投稿するためにわざわざKaTeX v0.12の記法を学習してくれたユーザーさんがいた場合、スムーズに修正ができるように周知したいこと

お待たせして大変申し訳ないのですが、もうしばらくお待ちいただけると幸いです。

**Comment by catnose99** [comment]
@y-yu 
こちら調査を行ったところ、まさに

> この変更で記事に問題が生じるユーザーは存在しない

という状況でした。来週のはじめにアップデートを行おうと思います。貴重なご意見、ありがとうございました。

**Comment by y-yu** [comment]
ご調査おつかれさまでした。素早い対応に感謝します。KaTeX 0.13系のより洗練された数式表現力でよりよい記事を書けるのを楽しみにしています。
