### ISSUE TITLE
コンテンツの埋め込みでasciinemaのプレイヤーを対応してほしい📺

### ISSUE THREAD

**Issue by tantan-tanuki** [zenn-dev/zenn-community#306]
## 提案・要望
コンテンツの埋め込みに
[asciinema.org](https://asciinema.org/)
のプレイヤーを埋め込めるようにしてほしい

↓こういうやつです
```html
<script id="asciicast-3" src="https://asciinema.org/a/3.js" async></script>
````

## 背景
CLIでの実行手順等をコードブロックで記述するとき
簡易な内容だと良いのですが長大な内容だと記事の大半を埋め尽くしてしまい
記事そのものの見通しが悪くなってしまいます

asciinemaのプレイヤーを埋め込めるとプレイヤー分のスペースで済むため見通しも良くなり
実際の画面の挙動確認及び画面で実行しているコマンドのコピペも可能なのでかなり便利なのですが
対応できないでしょうか？

**Comment by cm-wada-yusuke** [comment]
@tantan-tanuki 
要望ありがとうございます！私このツール知りませんで、はじめてつかってみたのですが、ターミナル作業の可視化という点ですごく便利ですね。Qiitaではプレイヤーの埋め込みに対応しているのですね。

こちらのプレイヤーを埋め込む点についてですが、申し訳ないのですが現時点では保留とさせてください。特に `script` タグの埋め込みはセキュリティリスクへの考え方などライブラリ側の姿勢や考え方を確認した上でメンテナンスコストに見合うかを検討させていただきたいです。 asciinema の [Twitter](https://twitter.com/asciinema) や [ブログ](https://blog.asciinema.org/) も更新が止まっている点も気がかりではあります。

（KaTeX や mermiad.js は、記事の表現力向上に寄与し、かつ代替を用意するのが大変（画像など）という理由で精査した上で対応しています。）

一方、 `iframe` であれば安全に埋め込みができるのですが、Asciinema は公式で iframe による埋め込みは謳っていないようにみえます。このあたりも意図が汲めず、Zennへの組み込みは少し躊躇するところです。

### まとめ

長くなってしまい申し訳ないです。いいツールだと思うので、どうにかして対応できないか考えたのですが、やはり以下の点で現時点では難しいという回答です。

* Twitter や ブログ、Issue などに対してここ最近アクションが薄い、またはないこと
* `<script>` タグの許可はリスク評価を行ってから対応したいが、今はその時間がとれなそうであること

すみませんがソースコード表示や、asciinemaへのリンク表示などでご対応いただければと思います。


以下の条件が揃ったら執筆者側で対応できると思いますので、こちらもウォッチいただくとよいかもしれません。

* Zenn が 特定の HTML タグをサポートする（iframeなど）
* asciinema が iframe による埋め込みを公式でアナウンスする（非公式でも iframe なら安全そうです。 現に devto は iframe で埋め込めるかもしれません） => https://github.com/forem/forem/issues/4135

よろしくお願い致します。

**Comment by tantan-tanuki** [comment]
確かにセキュリティリスクがあると対応するのは難しそうですね

asciinema側のiframe対応を願って静観したいと思います

丁寧な返信有り難うございました🙇

> 余談ですが最初はJSFiddlerかCodePen経由で表示させようとしていたのですが
> 横幅が途切れて見えなくて断念しました😢

**Comment by cm-wada-yusuke** [comment]
> 余談ですが最初はJSFiddlerかCodePen経由で表示させようとしていたのですが

これすごいアイデアですね。熱意はうけとりました！私も使ってみたいのでiframe対応待ちましょう。
