### ISSUE TITLE
Zenn Editor の Article 一覧の並び順を変更できるようにしてほしい

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [zenn-dev/zenn-community#307]
## 提案・要望

類似の要望が既にありましたらすみません。

Zenn CLI のプレビューコマンドで Zenn Editor が開きますが，左サイドバーの Article 一覧を更新日（？）だけではなく slug や公開日時でもソートできるようにしてほしいです。

## 背景

いままで Zenn Editor の Article 一覧の並び順は slug でソートされていた筈ですが，いつのバージョンからか更新日の降順（？）でソートされるようになっていました。

個人的な運用の話で恐縮ですが，私は slug に日付文字列を付加して Article 一覧が時系列に並ぶように管理していたのですが，これができなくなりました。おそらく何らかの要望があったためと思いますが，私のような管理・運用をしているユーザもいると思いますので，配慮していただければと思います。

## 関連

（おそらく）なし

**Comment by cumet04** [comment]
> いつのバージョンからか更新日の降順（？）でソートされるようになっていました。

こちら元々自分の出した要望 (https://github.com/zenn-dev/zenn-editor/issues/91) で、現在はファイルのタイムスタンプの降順に並ぶようになっているようです。

この要望がどうなるかは自分ではわかりませんが、現使用での運用ハックとして、ファイルのタイムスタンプを書き換える （ `ls -r articles/*.md | while read LINE; touch $LINE;sleep 1; end` など）があるので、もし参考になれば。

**Comment by catnose99** [comment]
>  slug に日付文字列を付加して Article 一覧が時系列に並ぶように管理していた

なるほどですね。ソート機能を実装できないか確認します。しばらくお待ちください。

**Comment by spiegel-im-spiegel** [comment]
ありがとうございます。期待して待ってます。

あと @cumet04 さんのタイムスタンプ云々で思ったのですが， git の最終コミット時刻でソートすることは可能でしょうか。 git でコード管理しているとファイルのタイムスタンプ情報はほとんど意味をなさなくなるので。でも，実装が面倒そうならこの話は忘れてくださいw

**Comment by catnose99** [comment]
> git の最終コミット時刻でソート

こちら実装の都合上かなり難しいですね……ｽﾐﾏｾﾝ

**Comment by catnose99** [comment]
@spiegel-im-spiegel 

ソート機能に対応しました。

https://user-images.githubusercontent.com/34590683/124539837-2b9b8480-de59-11eb-9c97-aa0c436ea7f1.mov

`npm install zenn-cli@latest`でCLIのアップデートをお願いします。

**Comment by spiegel-im-spiegel** [comment]
確認しました。ありがとうございます！
