### ISSUE TITLE
ブラウザバックした際に遷移前にスクロールしていたところに戻ってほしい

### ISSUE THREAD

**Issue by kathmandu777** [zenn-dev/zenn-community#308]
## 提案・要望

ブラウザバックした際に遷移前にスクロールしていたところに戻ってほしい

## 背景

1. 記事一覧で記事を探している際に、下のほうまでスクロールしてある記事をタップ
2. 記事を読む
3. ブラウザバック
4. 記事一覧の先頭に戻る

この4の挙動を「記事ページに遷移する前にスクロールしていた記事一覧のところへ戻る」ようにしていただきたいです。

**Comment by catnose99** [comment]
ref: https://github.com/vercel/next.js/issues/20951

**Comment by cm-igarashi-ryosuke** [comment]
scrollRestorationフラグ（experimental）を有効化して、スクロール位置が復元されるようになりました。
https://mmazzarolo.com/blog/2021-04-10-nextjs-scroll-restoration/

scrollRestorationが正式な機能として取り込まれたらIssueをクローズします。
