### ISSUE TITLE
ScrapsをTwitterのようなタイムラインで閲覧したい

### ISSUE THREAD

**Issue by yutaro-elk** [zenn-dev/zenn-community#310]
## 提案・要望
Scrapsの一つ一つ記事がサービス全体で一つのタイムラインとして閲覧できる機能があると嬉しいです。
エンジニア用Twitterのイメージです。

## 背景
他の方の Scraps を閲覧するとき、スレッドのタイトルを見てから詳細を見に行きますが、それだと少しハードルが高く感じます。タイムライン上をダラダラ眺めるくらいのハードルで見れると良いなと思いました。

TwitterでちょっとしたTipsや作業記録が流れてくるのが楽しみなのと、自分の作業記録を残すのにTwitterとScrapsどちらに書こうか悩む事があるので、コードハイライトも書きやすいですしScrapsがエンジニア用Twitterも担っていただけると嬉しいです。

## 関連

**Comment by catnose99** [comment]
ご提案ありがとうございます。
タイムラインをTwitterのように一つにまとめることも選択肢の一つとしては考えており、実際に手元で試してみたこともあります。試してみると、コンテキストがない状態でタイムラインにコメントが並ぶと読む方が内容をつかむのに労力が必要 or ページに遷移しないと内容が分からない等、あまり良い体験ではないと感じました。

上記の形とは異なりますが、現在タイムライン（フォローユーザーの投稿一覧フィード）を根本的に変更するリリースを準備中です。近いうちにリリースできると思いますので、しばらくお待ちください。

**Comment by yutaro-elk** [comment]
ご返事ありがとうございます。楽しみにしています！
