### ISSUE TITLE
スクラップにトピックを設定できない

### ISSUE THREAD

**Issue by pocke** [zenn-dev/zenn-community#314]
## 事象

スクラップ(Scraps)にトピックを設定できません。

スクラップにトピックを設定しようとすると、トピック名の入力はできますが、その後の「確定する」ボタンをクリックしても反映がされません。またその隣の「キャンセル」ボタンも反応しないようです。

なおトピックが設定できなくなったのは最近です。5日前(7/5ごろ)に書いたscrapにはトピックが設定できていた(Firefoxを使っています)ので、問題が発生したのはそれ以降だと思われます。 ref: https://zenn.dev/pocke/scraps/f363a880e8f7cc

## 発生したページのURL

https://zenn.dev/pocke/scraps/710517556e9477

また、自分が書いた他のscrapsでも同様の問題が起きています。

## 発生した画面のスクリーンショット

https://user-images.githubusercontent.com/4361134/125044371-dcfb1e00-e0d6-11eb-812d-7b365ac08d61.mp4

動画だと分かりづらいですが、「確定する」「キャンセル」ボタンをクリックしていますが、反応していません。

## 再現方法

1. スクラップを作成
2. 「+トピックを追加しましょう」をクリック
3. 入力欄にトピック名を入力してEnter
4. 「確定する」ボタンをクリック
    * トピックの設定が反映されるのを期待しているが、反映されない

## 環境

- Device: PC
- OS: Arch Linux
- Browser: Chrome 91.0.4472.114, Firefox 89.0.1
  * ChromeはExtensionをすべて無効にした上で動作確認しました。Firefoxの方はExtensionがいくつか有効な状態でしか確認できていません。

なおAndroid (Pixel 3a)のGoogle Chromeで試したところ、問題が再現せずトピックを設定することができました(そのため先にURLを上げたスクラップにはトピックが設定されています)。

**Comment by Qs-F** [comment]
## 事象

私もこちら，同じ問題に遭遇しました．
DevToolsで見たところScrapのThreadのカードが意図せずトピック設定等の上に覆いかぶさってしまっているようで，これらのカードをDevToolsで消してしまうことで一応トピックの設定は可能でしたが修正していただけると助かります．

## 発生したページのURL

https://zenn.dev/qsf/scraps/0e3a6d696aeb8b

## 発生した画面のスクリーンショット

![image](https://user-images.githubusercontent.com/8467289/125202964-2010e900-e2b1-11eb-9967-6b1bdd8e0a99.png)

## 再現方法

上の方に同じです．

## 環境

- Device: PC
- OS: macOS 11.4
- Browser: Chrome 91.0.4472.114)

**Comment by tktcorporation** [comment]
同じくです

## 解消方法
![image](https://user-images.githubusercontent.com/37575408/125207850-e1d3f380-e2c9-11eb-9330-b40076eec090.png)
横幅をせまくするとクリックできるようになるみたいです

## 環境
- Device: PC
- OS: Windows
  - エディション: Windows 10 Home
  - バージョン: 20H2
- Browser: Chrome バージョン: 91.0.4472.124（Official Build） （64 ビット）

**Comment by cm-wada-yusuke** [comment]
@pocke @Qs-F @tktcorporation 
皆様、ご連絡ありがとうございます。
こちらチームで確認・修正しますのでお待ち下さい。

**Comment by cm-wada-yusuke** [comment]
@pocke @Qs-F @tktcorporation
皆様のご報告を参考に、ワークアラウンドを模索したところ、 **Google Chrome の 開発者ツールにてモバイルモードを有効にする** と回避できそうです。まずはこちらでご対応いただけると幸いです。お手数をおかけしますがよろしくおねがいします。


https://user-images.githubusercontent.com/17589989/125233634-f3dd8280-e319-11eb-90b9-5c3ea8a93d86.mov

**Comment by catnose99** [comment]
@pocke @Qs-F @tktcorporation 
ご迷惑をおかけして大変申し訳ありません。また、丁寧にご報告いただきまして、ありがとうございました。
こちらさきほど修正しました。お時間がありましたら念の為ご確認いただけますと幸いです。
