### ISSUE TITLE
自分が投稿した記事についての絞り込み

### ISSUE THREAD

**Issue by mo-ri-regen** [zenn-dev/zenn-community#315]
## 提案・要望
現状では、検索は他の人の記事も検索されますが、たとえばプロフィール画面から検索したときは
自分の投稿した記事だけがでてくるようにしてほしいです。
## 背景
自分が以前投稿したことがある内容かを調べるために使いたいです。
今はまだ少ないので覚えられていますが100件、200件と増えていくと
かぶった内容を投稿していないか調べられると便利だと思います。

**Comment by catnose99** [comment]
なるほど、ユーザーページの記事一覧上に検索フィールドを設置するのが良いかもしれません。色々とやることが溜まっているので対応が遅くなるかもしれませんが、検討させていただきます。

**Comment by mo-ri-regen** [comment]
検討ありがとうございます。
お忙しいとは思いますが、よろしくお願いいたします。

**Comment by tonbijp** [comment]
自分に限らず、作者を指定した検索は欲しいですね。
あるていど質と量とジャンルの方向性がある作者なら、全体を検索するより確実に情報にたどり着けると思います。

**Comment by longbridgeyuk** [comment]
私も自分の記事は自分のための忘備録的なこともあり
自分の記事をトピックで絞り込みできたら便利だと思っています。

特定の作者の関連する他の記事を読みたい時など、作者＆トピックで絞り込みたいことがよくあります。

**Comment by cm-igarashi-ryosuke** [comment]
issueの本題である「自分が投稿した記事についての絞り込み」については、ダッシュボードから検索ができるようになっていますので、本issueはクローズいたします。
リリースノート: https://info.zenn.dev/search-article-dashboard

全体検索における詳細検索については、 #332 で管理します。
