### ISSUE TITLE
特定の画像が投稿時に消える

### ISSUE THREAD

**Issue by inabajunmr** [zenn-dev/zenn-community#316]
## 事象

以下をエディターに入力した場合、プレビューでは画像が両方表示されるが投稿すると片方表示されない

```
# 消える
![](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuKfCBiaiIon9LGXrv0frLD2rKtZSjFvnyyh7JKiUDorwtBpvSNC7N14skQBKajAYFAZU5wjwd_QlVzoqzN7pdiVD4u2a5KoiUHL8SzEAnqqxWTfYyjxlwIXAJSaiIaqkYIyjohJDA2afABRIrq_EoKpDAz5BhKZCBSX9rKlEpts_fnFX0amRe2x0wNg42zQ0xPuB50Ooy7eAKmYNxu1IG1giVZEQ7ubmD8noICrB0SO60000)

# 消えない
![](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuKfCBiaiIon9LNWsPVUpISql6beVDwuBTUH2vIhesYayRbh_k7dbuwObZviMFMxU_BYv0wuPcrnHQabfKPx2YrMzJ_k1agj0IffMF6xQ2PG4cgaG6kG9r3RfQV-qf_kcSpcavgK0dGC0)
```

## 発生したページのURL
https://zenn.dev/inabajunmr/articles/3a4130a672adbe

### プレビュー
<img width="926" alt="スクリーンショット 2021-07-19 10 11 47" src="https://user-images.githubusercontent.com/10000393/126089009-a7ce0a79-9416-4ccb-a113-0fdbdb1206a5.png">

### 投稿時
<img width="827" alt="スクリーンショット 2021-07-19 10 12 18" src="https://user-images.githubusercontent.com/10000393/126089048-a5e1e99e-9d27-442d-b003-d778fb8ebba4.png">

## 再現方法
以下のマークダウンを記事として投稿する

```
# 消える
![](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuKfCBiaiIon9LGXrv0frLD2rKtZSjFvnyyh7JKiUDorwtBpvSNC7N14skQBKajAYFAZU5wjwd_QlVzoqzN7pdiVD4u2a5KoiUHL8SzEAnqqxWTfYyjxlwIXAJSaiIaqkYIyjohJDA2afABRIrq_EoKpDAz5BhKZCBSX9rKlEpts_fnFX0amRe2x0wNg42zQ0xPuB50Ooy7eAKmYNxu1IG1giVZEQ7ubmD8noICrB0SO60000)

# 消えない
![](http://www.plantuml.com/plantuml/png/SoWkIImgAStDuKfCBiaiIon9LNWsPVUpISql6beVDwuBTUH2vIhesYayRbh_k7dbuwObZviMFMxU_BYv0wuPcrnHQabfKPx2YrMzJ_k1agj0IffMF6xQ2PG4cgaG6kG9r3RfQV-qf_kcSpcavgK0dGC0)
```

## 環境

- Device: MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
- OS: Catalina 10.15.7
- Browser: Google Chrome: 91.0.4472.114

**Comment by catnose99** [comment]
Cloudinaryを用いた画像プロキシの際にURLの長さの上限を超えてしまっているようです。
※ レスポンスヘッダの`x-cld-error`に

```
public_id (http://www.plantuml.com/plantuml/png/.....) is too long
```

と表示されています。


参考:
https://support.cloudinary.com/hc/en-us/articles/207746165-Why-do-I-get-a-public-ID-too-long-error-when-trying-to-fetch-from-a-remote-URL-

お手数ですが、PlantUMLからダウンロードした画像をアップロードしていただくようお願いします。
今の仕組みでは根本的な解決は難しそうですが、分かりやすいエラーメッセージを表示する等で対応したいと思います。

**Comment by catnose99** [comment]
PlantUMLの画像はプロキシ対象外にするという選択肢もあるのでそちらも検討してみます。

**Comment by inabajunmr** [comment]
確認ありがとうございます。検証用の記事は閉じておきます:bow:

**Comment by catnose99** [comment]
ありがとうございます！

**Comment by cm-igarashi-ryosuke** [comment]
レスポンスヘッダーを見る限り、サーバキャッシュはなさそうです。
PlantUMLに限らず長さ上限を超えてしまうケースはあるので、長さ上限を超えていたらプロキシしない、というのがいいのかな？

**Comment by kanonji** [comment]
自分もPlantUMLで図を作って画像へのURLをスクラップに含めた所、図が表示されない事象にあいました。
回避策としてbitlyでURLを短くする事で、図を表示させる事が出来ました。

しかし、図を編集可能に保つため、図のテキスト表現がbase64エンコードで含まれる元のURLは、大事な情報です。
そうそう無いとは思いますが、もしbitlyがサービスを終了した場合、元のURLを得られなくなってしまうため、短縮URLを使った回避策には課題があります。
また、図を編集した場合にはPlantUML側のURLも変わってしまうので、短縮URLを発行し直す手間もあります。

短縮URLを介さずとも図が表示される様になるか、欲を言えばPlantUMLのテキストを以下の様に書いたら、図への変換から表示までが出来ると、図の編集を記事やスクラップの編集と同時に、同じ画面で行えるので、とても助かります。

````
```plantuml
//PlantUMLテキスト表現
```
or
@startuml
//PlantUMLテキスト表現
@enduml
````

**Comment by cm-igarashi-ryosuke** [comment]
@kanonji こちらの問題、対応できておらずすみません。

解決になるかわかりませんが、mermaid.js でしたらコードブロックによる埋め込みに対応しています。ご参考までに。

https://zenn.dev/zenn/articles/markdown-guide#%E3%83%80%E3%82%A4%E3%82%A2%E3%82%B0%E3%83%A9%E3%83%A0

**Comment by kanonji** [comment]
@cm-igarashi-ryosuke ありがとうございます。
Mermaidでも十分なケースもあるとは思いますが、今回の図はおそらくMermaidでは表現出来ないかもしれません。
またちょうど最近、NotionでもPlantUMLが使えずMermaidなら使えるという状況があり、Mermaidでの書き直しを試みた事があったのですが、残念ながらMermaidだと表現力が足りず、似ているとはいえやはり違うものだなと思いました。
なので、PlantUMLも使えるととても助かります。

**Comment by cm-wada-yusuke** [comment]
もともとの課題について。これは画像のURLが長すぎるときに、Cloudinary の仕様でエラーになってしまうというものでした。お手数ですがこのようなケースでは、短縮URLサービスなどの利用や、画像をアップし直すなど検討してもらえると助かります。

PlantUMLの埋め込みについては別課題ですので、一度このISSUEはクローズさせていただきます。
