### ISSUE TITLE
スラッシュを含むページ内リンクを、パーセントエンコーディングなしで行いたい

### ISSUE THREAD

**Issue by ver-1000000** [zenn-dev/zenn-community#318]
## 提案・要望
見出しに、半角スラッシュを含む文字列を設定したとき、ページ内リンクを機能させるためには、
パーセントエンコーディングをおこなわなければいけません。

Qiitaではスラッシュは除去されたリンクとして生成されるようで、同じような実装を行えないでしょうか。

```md
[link](#hogefoo)

# hoge/foo
Qiitaはこれでスラッシュのある見出しにページ内リンクが可能。
```

## 再現方法
以下のような記事を書くと、 `link` 文字列を押下しても飛ぶことができません。

```md
[link](#hoge/foo)

# hoge/foo
```

以下のように書き直すと動作します。

```md
[link](#hoge%2Ffoo)

# hoge/foo
```

## 環境

- OS: ArchLinux
- Browser: Google Chrome 92.0.4515.107

**Comment by cm-igarashi-ryosuke** [comment]
@ver-1000000 Zenn開発チームです。ご提案ありがとうございます。

確かにスラッシュを除去するアイディアは一部の利用者にはメリットがあると思いますが、一方で以下のデメリットも伴います。

- スラッシュが除去されることが直感的ではないと感じる利用者もいる
- MarkdownからHTMLへの変換には markdown-it を利用しており、デフォルトの動作を変えることでメンテナンスコストが増える

これらを検討した結果、ご提案は採用できないと判断いたしました。

**Comment by ver-1000000** [comment]
こちらの調査に小一時間要しましたので、「スラッシュを含む文字列へのリンクはパーセントエンコーディングを用いると可能」ということをどこかに記載されてるとよいかもしれませんね。

**Comment by cm-igarashi-ryosuke** [comment]
@ver-1000000 そうだったんですね。見出しへのリンクを埋め込む際は、公開ページの見出しの横にあるクリップアイコンからURLを取得すると確実です。こちらは markdown-it の仕様でパーセントエンコーディングされています。

![image](https://user-images.githubusercontent.com/13619209/128121594-e6f07e7b-7fac-4518-8b6b-6869a10f344d.png)
https://zenn.dev/zenn/articles/markdown-guide#%E8%A6%8B%E5%87%BA%E3%81%97

**Comment by ver-1000000** [comment]
@cm-igarashi-ryosuke この辺の挙動も試したのですが、下書き時点ではリンクが生成されないようなので、編集時には利用できませんでした。

![ss](https://user-images.githubusercontent.com/6778957/128123927-1cd15a98-738a-406d-9c9c-813da7271258.png)

---

とスクショを撮って説明しようとしたところで

> 公開ページの見出しの

という説明に気づきました…… 「公開してからリンク確認して編集してね」、ということですかね……。 なるほど……。

**Comment by cm-igarashi-ryosuke** [comment]
@ver-1000000 公開ページとお伝えしましたが、下書き状態で保存した後のプレビューページでもクリップアイコンが表示されました。確認不足で失礼しました。こちらであれば、公開する前にURLを確認することができます。

- 記事の編集画面から「公開する」のトグルをオフにして、下書きとして保存する
  ![image](https://user-images.githubusercontent.com/13619209/128127323-71cc146d-772c-4e04-b143-e29990bc1bb3.png)
- 記事の一覧に戻り、「表示を確認」ボタンでプレビューを表示する
  ![image](https://user-images.githubusercontent.com/13619209/128127473-8cc250e2-8c50-4dc6-aacc-d34cacc674f3.png)

編集画面のプレビュー表示では、URLが公開URLと異なることからクリップアイコンのリンクを表示していません。

**Comment by ver-1000000** [comment]
@cm-igarashi-ryosuke あーなるほど、こういう手順で確認できるのですね、ありがとうございます。
