### ISSUE TITLE
全記事の編集リクエスト機能がほしい

### ISSUE THREAD

**Issue by donchan922** [zenn-dev/zenn-community#320]
## 提案・要望
GitHub連携している記事であれば編集リクエストできるのは知っているのですが、全記事に対して編集リクエストができるようにしてほしいです。

## 背景
記事のメンテナンス性も高まりZennコミュニティの発展にもつながるのではと思いました。自分はQiitaで他人の記事への編集リクエストをたびたび行うことがあり、それがけっこう楽しかったりするのですが、Zennだとそれが記事によってできたりできなかったりするのがむず痒いです。

## 関連
https://github.com/zenn-dev/zenn-community/issues/226

**Comment by cm-igarashi-ryosuke** [comment]
@donchan922 ご提案ありがとうございます。確かに細かい指摘だとコメントで伝えるのも煩わしいですよね。Qiitaにあるような編集リクエスト機能はとても良いと思うのですが機能的に結構ヘビーなんですよね。優先度は低めになると思いますが、実現方法を含めて検討してみます。

**Comment by cm-igarashi-ryosuke** [comment]
@donchan922 参考までに教えていただきたいのですが、Qiitaで行う編集リクエストの内容はどんな物が多いですか？

**Comment by donchan922** [comment]
@cm-igarashi-ryosuke タイポが多いですね。

**Comment by matobaa** [comment]
+1
GitHubリポジトリがPrivateだと「編集の提案」⇒ 404 になって「うーむ」となりました

**Comment by cm-igarashi-ryosuke** [comment]
@matobaa 
問題のご報告ありがとうございます。

通常、Privateリポジトリで管理されている記事には「編集の提案」リンクは表示しないようになっているのですが、最初にPublicリポジトリとして連携されたあとで、リポジトリをPrivateに変更された場合に、Zennのデータベースで管理しているリポジトリのステータスが変わらないためにリンクが表示されてしまっています。
これはZennのGitHub Appのパーミッションの問題で、現在リポジトリの変更イベントを受け取れない状態になっているためです。この問題は認識しており、対応する予定です。

ちなみに今回「編集の提案」をしたかった内容としては、記事のコメントとしてお伝えするのではやりにくかったでしょうか？
記事の内容と直接関係ないことをコメントするのは気がひけるかと思うのですが、少し前に、記事のコメントを記事の著者が非表示にできる機能をリリースしておりますので、気軽にコメント欄を使っていただけると幸いです。
https://zenn.dev/zenn/articles/hide-comment

**Comment by qsona** [comment]
改めて、カジュアルに編集リクエストできる機能は、あると嬉しいなあとユーザー目線では思いました。

> 記事のコメントとしてお伝えするのではやりにくかったでしょうか？

@donchan922 さんがおっしゃるとおり自分も typo fix のリクエストがほとんどなのですが、該当箇所がココでこう修正すればいいよ、というのをダイレクトに簡単に伝えられるのが編集リクエストの良いところで、コメントで指摘するほどではないか・・・という心理になってしまいました。
