### ISSUE TITLE
スクラップ一覧にもRSSフィードがほしい

### ISSUE THREAD

**Issue by sukedon** [zenn-dev/zenn-community#321]
## 提案・要望
現状 https://zenn.dev/ユーザー名/feed でユーザー投稿のフィードは取得できますが、スクラップ一覧に関してはフィードがないため、ユーザー投稿に含めるか、スクラップ一覧個別のフィードがほしいなと思いました。

## 背景
https://zenn.dev/catnose99/articles/cb72a73368a547756862
こちらを使用して個人の記事を集約するサイトを公開しているのですが、そこにスクラップも含めたいと思ったのが背景です。

## 関連
検索したところ特にありませんでした。

**Comment by catnose99** [comment]
なるほど、ユーザーのフィードにおいて、`?include_scraps=1`などのクエリを足したらスクラップも含めるようにする等が良いかもしれませんね。
検討します。

**Comment by sukedon** [comment]
ご確認ありがとうございます。
何卒ご検討よろしくお願いします。

**Comment by catnose99** [comment]
@sukedon 
`https://zenn.dev/ユーザー名/feed?include_scraps=1`のように`include_scraps=1`というクエリ文字列が指定されている場合はスクラップもフィードに出力されるようにしました。

**Comment by sukedon** [comment]
@catnose99 
ご対応ありがとうございます！
早速活用させていただきます
