### ISSUE TITLE
Logo だけのメディアキットが欲しい

### ISSUE THREAD

**Issue by sadnessOjisan** [zenn-dev/zenn-community#322]
## 提案・要望

https://zenn.dev/mediakit にあるメディアキットですが、ロゴ + サービス名 の画像ではなく、ロゴだけで欲しいのですが可能でしょうか。

## 背景

Twitter, GitHub のロゴと並べるときに、レイアウトの都合で正方形の形で並べたいためです。

**Comment by catnose99** [comment]
@sadnessOjisan 

以下のサイトからZennのロゴだけのSVGファイルをダウンロードできます。
https://simpleicons.org/

近日中にメディアキットにも含めるようにしておきますね。

**Comment by sadnessOjisan** [comment]
@catnose99 おお！こんなところに！ありがとうございますmm

**Comment by catnose99** [comment]
メディアキットにも入れておきました

**Comment by cm-wada-yusuke** [comment]
メディアキットはこちら
https://zenn.dev/mediakit
