### ISSUE TITLE
読者コミュニティの投稿を整理する機能

### ISSUE THREAD

**Issue by dijzpeb** [zenn-dev/zenn-community#323]
## 提案・要望
読者コミュニティへの投稿数が多くなった場合、見づらいので
- githubのissuuesのような形式にする
- YouTubeのコメント欄のように、返信が折り畳めるようにする
- 期間で絞り込んだり、新しい順に並べたりできる

など、使いやすくなるための機能が欲しいです。よろしくお願いいたします。

**Comment by catnose99** [comment]
こちらは近日中に対応できると思います。

- YouTubeのコメント欄のように、返信が折り畳めるようにする

しばらくお待ちください。

**Comment by catnose99** [comment]
https://zenn.dev/zenn/articles/hide-comment
こちら対応しました
