### ISSUE TITLE
スクラップで Markdown/Preview 切替を下にも設置希望

### ISSUE THREAD

**Issue by jay-es** [zenn-dev/zenn-community#326]
## 背景
ひとつのコメントが長くなると、書いている部分をプレビューするためには
- 上までスクロールして Preview に切り替え
- 下に戻って表示を確認
- また上にスクロールして Markdown に切り替え
- 一番下まで戻って執筆続行

という手順が必要になります。

切替ボタンが上だけでなく下にもあると便利かなと思いました。
（スクロールせずに切り替えられるようになればよいので、ヘッダー部分を sticky にする、などでも）

マークダウンとプレビューで高さが変わるので制御が大変かも知れませんが...

**Comment by catnose99** [comment]
なるほどですね。
Markdown/Preview を上部にstickyで固定できないか確認します。

**Comment by catnose99** [comment]
stickyによるMarkdown/Previewの固定を試したのですが、固定される瞬間の体験があまり良いものでは無かった（エディターにフォーカスした瞬間に固定するためガタつく）ので、別のアプローチを取ることにしました。

具体的には、入力欄の最大高を画面からはみ出ないように制限することで、入力開始時点でMarkdown/Previewや送信ボタンが見えていれば、長文を打ってもこれらのボタンが画面からはみ出ることがなくなりました。
この変更はすでにzenn.devに反映済みです。

何か問題があればIssueをreopenしていただければと思います。

**Comment by jay-es** [comment]
ご対応ありがとうございました！:pray:
