### ISSUE TITLE
$ に囲まれる長い一続きの文字列を markdown プレビューすると、文字列が要素からはみ出ます。

### ISSUE THREAD

**Issue by kis9a** [zenn-dev/zenn-community#327]
## 事象

$ に囲まれる長い一続きの文字列を markdown プレビューすると、文字列が要素からはみ出ます。
予期されないMarkdownかもしれませんが、要素に収まるように修正されていれば尚良いと思いました。
対応可能であれば、修正をお願いしたいです。

## 発生したページのURL

https://zenn.dev/kis9a/scraps/6a645ccc80b9cb

## 発生した画面のスクリーンショット
<img width="952" alt="Screen Shot 2021-08-29 at 22 34 23" src="https://user-images.githubusercontent.com/65019715/131252259-39a20024-11d9-4e6f-b930-4aa170bdf02c.png">

## 再現方法

$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$

をプレビューすると。

## 環境

Browser:

- Crhome: Version 92.0.4515.159 (Official Build) (arm64)
- Safari Version 14.1.2 (16611.3.10.1.6)

**Comment by catnose99** [comment]
ご報告ありがとうございます。
こちら認識できていませんでした。
対応します。

**Comment by catnose99** [comment]
なお、`$文字列$`は、KaTeXのインライン記法と認識されるため、KaTeX記法としたくない場合はお手数ですが
```
`$`文字列`$`
```
のように$を`で囲っていただくようお願いします。
