### ISSUE TITLE
ZennのMarkdown記法一覧の数式にKaTeXの記法一覧へのリンク追加

### ISSUE THREAD

**Issue by umi-tyaahan** [zenn-dev/zenn-community#328]
## 提案・要望

ZennのMarkdown記法一覧の数式部分ににKaTeXの記法一覧へのリンク追加してほしい。

数式ガイド
https://zenn.dev/zenn/articles/markdown-guide#%E6%95%B0%E5%BC%8F

KaTeXの記法一覧
https://katex.org/docs/supported.html

## 背景

具体的なKaTeX記法を知りたかったのだが、結局分からず検索してQiitaの記事を見たりしていたので、
Markdownガイドのところにリンクがあったら良いなと思いました。

**Comment by cm-igarashi-ryosuke** [comment]
@umi-tyaahan フィードバックありがとうございます！ガイドにリンクを追加しておきました。
