### ISSUE TITLE
画像の参照が機能していない

### ISSUE THREAD

**Issue by yusuke-aoki-dev-techblue** [zenn-dev/zenn-community#330]
## 事象

記事内で以下のような記事を書いたところ、参照先が異なるのに全く同じ画像を参照してしまっている
```

#### Amazon RDSのアーキテクチャー

![](/images/awscontainerguide-2/RDS-archi.png)
Amazon RDSですが、このアーキテクチャーだとプライマリーとスタンバイの2つが用意されています。それぞれにEBSストレージが紐づいていて、これらがミラーリングしていることによって耐久性を高めています。

#### Amazon Auroraのアーキテクチャー

![](/images/awscontainerguide/AmazonAurora.png)
Amazon AuroraはDBクラスターを作成します。いわゆる大きな箱のようなイメージです。このなかにインスタンスとストレージが入っているのですが、RDSとちがい、インスタンスとストレージが分離しています。
ストレージがさらに1AZに２か所,それが東京リージョンだと3AZ分すべてにコピーされます。これらは同期的に通信をしているため、もし何かデータの消失が起こっても他のインスタンスが修復しあう関係になっています。
また書き込み自体も並列に行うため処理自体のパフォーマンス自体にも大きな影響は与えません。
Amazon Auroraにも独自機能があります。AWSが提供している分かなり高機能なのでアプリ要件を十分に検討したうえで、導入を検討する余地があります。
```
## 発生したページのURL

https://zenn.dev/yuki_tech/articles/awscontainerguide

## 発生した画面のスクリーンショット

<img width="1165" alt="otoiawase-1" src="https://user-images.githubusercontent.com/84622214/132145554-5f3e303e-ac1f-4a11-8efc-422f48dcb7b2.png">
<img width="731" alt="otoiawase-2" src="https://user-images.githubusercontent.com/84622214/132145552-65d7af2e-53f6-4b40-a56b-db73c70906ea.png">
<img width="789" alt="otoiawase-3" src="https://user-images.githubusercontent.com/84622214/132145553-424f26d3-8ac3-4653-b04e-c95f9e391fda.png">

お問い合わせ1が実際のコード、お問い合わせ2,3が画像の内容になります。

## 再現方法

なし

## 環境

Amazon cloud9環境で作成し、zenn CLIを使用して管理しています。

- Device: [e.g. iPhone12]
- OS: [e.g. iOS14.4]
- Browser: [e.g. chrome 89.0.4389.72]

**Comment by catnose99** [comment]
ご迷惑をおかけして申し訳ありません。確認します。

**Comment by yusuke-aoki-dev-techblue** [comment]
よろしくお願いします。
私の理解が間違っていた場合はすいません・・・

* 必要があればcatnose99様を私のリポジトリに招待してご確認いただきたく存じます。よろしくお願いします

**Comment by catnose99** [comment]
@yusuke-aoki-dev-techblue 

丁寧にありがとうございます。
さきほど該当の記事の対応を行いましたので、イメージ通りに表示されているかご確認いただけますと幸いです。
https://zenn.dev/yuki_tech/articles/awscontainerguide

1点確認させていただきたいのですが、問題が発生する際、すでにZennにデプロイ済みの画像のファイル名を変更するようなアクションはされましたでしょうか？

原因調査の結果、すでにアップロード済みの画像と同一のファイル名（リポジトリ上のパス）の画像のデプロイを行うことで問題の再現が出来たため、念のため同じ原因によるものか確認させていただきたく…

なお、こちらで再現できた問題については今週中に修正を完了したいと考えています。また同様の問題が発生した場合は恐れ入りますが再度コメントしていただけますと幸いです。

**Comment by yusuke-aoki-dev-techblue** [comment]
対応いただきありがとうございます。イメージ通りです。
>1点確認させていただきたいのですが、問題が発生する際、すでにZennにデプロイ済みの画像のファイル名を変更するようなアクションはされましたでしょうか？

原因調査の結果、すでにアップロード済みの画像と同一のファイル名（リポジトリ上のパス）の画像のデプロイを行うことで問題の再現が出来たため、念のため同じ原因によるものか確認させていただきたく…

こちらですがお伝えし忘れており申し訳ございません。
がっつりとご指摘の名前変更のアクションをしております。

よろしくお願いします

**Comment by catnose99** [comment]
早速の返信、ありがとうございます。
こちらで確認できた問題と一致しているようで安心しました。
近日中に問題を修正するようにします。

丁寧にIssueを報告していただき、ありがとうございました。

**Comment by cm-igarashi-ryosuke** [comment]
@yusuke-aoki-dev-techblue 
問題の修正が完了しましたのでクローズします。
ご報告いただき感謝いたします。

ところで、ご報告いただいた記事ページを確認したところ画像が消えておりました。
https://zenn.dev/yuki_tech/articles/awscontainerguide

こちらで確認したところ、画像がGitHubリポジトリから削除された形跡がありました。
ご確認いただけますと幸いです。
