### ISSUE TITLE
保存後の記事編集画面のtextareaでCtrl+Zを押すと空になる

### ISSUE THREAD

**Issue by kjirou** [zenn-dev/zenn-community#331]
## 事象
保存した後の記事編集画面の本文の textarea で `Ctrl + Z` の Undo をすると、textare が空欄になります。
この後に保存を行うと、空で保存されてしまうので、少し怖いと感じました。

## 発生したページのURL
- `https://zenn.dev/articles/{記事ID}/edit` の画面全てで発生するように見えます。
  - 「下書き」と「公開」のどちらでも発生します。

## 発生した画面のスクリーンショット
- 再現方法のセクションで提出します。

### 1) 下書きの記事を作成し、画面を閉じる
`https://zenn.dev/articles/{記事ID}/edit` の画面が以下のようになっている状態で、一度画面を閉じます。
![image](https://user-images.githubusercontent.com/648041/132154275-92126bc5-3b3b-4e21-a461-ceb7f35908c0.png)

### 2) 再び同じ画面を開き、本文の textarea を focus する
![image](https://user-images.githubusercontent.com/648041/132154410-908be378-8979-4c57-b5d2-51e0e8ccf94d.png)

### 3) `Ctrl + Z` で Undo すると、textarea が空になる
![image](https://user-images.githubusercontent.com/648041/132154490-fd975fa5-072a-4d42-b3e0-fd156364e984.png)

## 環境

- Device: 関係なさそうなので省略します。
- OS: `macOS 10.15.7`
- Browser: Google Chrome `93.0.4577.63（Official Build） （x86_64）`

----

ちゃんと仕組みを把握しておらず、お問い合わせ側からも送信してしまいました。

**Comment by cm-wada-yusuke** [comment]
@kjirou ご連絡ありがとうございます。たしかに、誤って保存してしまうと怖いですね。以下２点、ご確認いただけるでしょうか。

* 誤って保存してしまった場合でも、再度編集画面で Cmd+Shif+Z で復元できるようです。こちらでは不十分でしょうか？
* オンラインエディタはその特性上、マルチデバイスに対して影響が出たり、予期しない結果になる可能性があるため、デフォルトの動作から変更する場合は少し慎重に進めたいと考えています。厳密なバージョン管理を行いたい場合は、GitHub 連携もご利用いただけます。お手数ですがこちらで検討させていただく間、GitHub連携の利用をご検討いただけると幸いです

**Comment by kjirou** [comment]
返信ありがとうございます。
不具合でないのなら、問題ありませんでした。

**Comment by cm-wada-yusuke** [comment]
そのような現象が発生しうることがわかったので助かりました、ご連絡ありがとうございました。

**Comment by cm-wada-yusuke** [comment]
@kjirou こちらですが、私は修正したくない雰囲気を出してしまっていたのですが、 @catnose99 さんがエディタライブラリの修正点を発見してくれ、Zenn本体にも修正を適用してくれました。現在は、初回で開いたときも Cmd+Zで内容が消えなくなっています。

https://zenn.dev/catnose99/articles/83f5755918500a
