### ISSUE TITLE
mermaid.js ダイアグラム表示の前後の空きについて

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [zenn-dev/zenn-community#333]
## 提案・要望

スマートフォンなどの携帯端末で mermaid.js ダイアグラム表示を見た場合に，図の前後の空きが大きすぎるように思います。
これの調整は可能でしょうか。

## 背景

拙文の記事

- [Krypton で git commit/tag に電子署名できるらしい](https://zenn.dev/spiegel/articles/20210913-openpgp-sign-with-krypton)

で mermaid.js 表記を使ってシーケンス図を描きました。

PC のブラウザで見たときは気にならなかったのですが，スマートフォンなどの携帯端末で見ると図の前後の空きが大きすぎるように感じました。かなりスクロールさせないと図が出てこない（図の下の文章もかなりスクロールしないと出てこない）感じです。

動作環境は

- Android 11 (Galaxy 端末)
- Firefox または Firefox Focus ブラウザ

です。
端末やブラウザ固有の問題であれば諦めます。

## 関連

特になし（多分）

**Comment by cm-wada-yusuke** [comment]
@spiegel-im-spiegel ご連絡ありがとうございます。たしかにスマホでみるときになるスペースですね。こちら解消できるか調査しますのでしばしお待ち下さい。

**Comment by cm-wada-yusuke** [comment]
@spiegel-im-spiegel こちら調査した結果、mermaid.js 側でデグレになってしまっているようです。利用側からはワークアラウンドが難しい問題だったためプルリクエストチャレレンジをしています。いましばらくおまちください。

https://github.com/mermaid-js/mermaid/issues/2160
https://github.com/mermaid-js/mermaid/pull/2312

**Comment by cm-wada-yusuke** [comment]
@spiegel-im-spiegel こちら、mermaid本体で改善する動きがなかなかなさそうだったので、catnose さんのアドバイスのもと、Zenn側のCSSを調整することでワークアラウンド対応としました。リリース済みでして、ご提示いただいた記事も解消していそうです。おまたせしました。ご確認いただければと思います。

**Comment by spiegel-im-spiegel** [comment]
いい感じになってると思います。ありがとうございます。
