### ISSUE TITLE
スクラップの投稿についてmeta robotsタグの設定が知りたいです

### ISSUE THREAD

**Issue by hdmt** [zenn-dev/zenn-community#338]
いつもZennを便利に使わせていただいています。

## 提案・要望

スクラップの投稿についてmeta robotsタグが、投稿により、`noindex,nofollow` がつくもの、つかないものがあるようです。

どのような仕様になっているかお聞きできるでしょうか。
スクラップのopen/close/archiveと連動しているのでしょうか。
（将来的にユーザが設定するようなことは可能でしょうか。）

## 背景

スクラップは気軽に備忘的にメモしていけるのが良いですが、結論や問題解決に至らず中途半端なメモの断片も多いです。
自身や第三者が検索により、問題解決に至らない半端なメモに辿りつくのは望ましくない（noindexしたい）ように思いました。

**Comment by cm-igarashi-ryosuke** [comment]
@hdmt ご意見ありがとうございます。

`noindex,nofollow` にしている条件は以下があります。

- アーカイブ済み
- 情報量が少ない

情報量の基準は随時調整をしますのでこの場で具体的な内容を書くことは控えさせていただきます。

> 将来的にユーザが設定するようなことは可能でしょうか。

こちらは実装したとしても、利用者が一つ一つ判断して設定してくれるかというと難しい気がします。

背景にあるようなことはごもっともなのですが、一方で「問題解決にたどり着いてないスクラップに、たどり着いた誰かがコメントする」というような助け合いが生まれることもzennとしては期待しています。

現状、これらを両立できるようないいアイディアがないので、引き続きやり方を検討します。

なにかアイディアありましたら、どなたでもコメントお願いします！

**Comment by hdmt** [comment]
@cm-igarashi-ryosuke 
さっそくご返信ありがとうございます。
よく理解しました。
もし見せたくないようなスクラップならばアーカイブすればよかったですね。

引き続き楽しく利用させていただきます。
