### ISSUE TITLE
「本の管理」ページを開けない 

### ISSUE THREAD

**Issue by Reputeless** [zenn-dev/zenn-community#339]
## 事象
https://zenn.dev/dashboard/books をクリックしても「本の管理」が開かれず、「記事の管理」が表示される。
数日前までは正常だった。

同様の報告
- https://twitter.com/NoraProgram/status/1444938020348567553

## 発生したページのURL
https://zenn.dev/dashboard/books

## 再現方法
- https://zenn.dev/dashboard で Books を押す
- または、プロフィールアイコンから「本の管理」を選択する

**Comment by catnose99** [comment]
ご迷惑をおかけして申し訳ないです。
昨日の夕方のリリースでページのRewrite周りの設定を誤ってしまっていたようです。
すぐに修正します。

**Comment by cm-wada-yusuke** [comment]
@Reputeless 修正リリースしました。現在、本の管理ページが開けると思いますので、お手数ですがご確認いただけますと幸いです。ご迷惑をおかけしました。

**Comment by Reputeless** [comment]
ありがとうございます。
期待した動作になりました。
