### ISSUE TITLE
「アカウント設定 > お振込先」のラベルのPayPay銀行への対応

### ISSUE THREAD

**Issue by paithiov909** [zenn-dev/zenn-community#340]
## 提案・要望

「アカウント設定 > お振込先」ページのラベルから自動入力できる銀行名のリストのなかに「ジャパンネット」がありますが、ジャパンネット銀行は「ＰａｙＰａｙ銀行」に改称しているため、修正してもらいたいです。

## 背景

2021年7月3日から旧銀行名（ジャパンネット銀行）への振込入金はできなくなっているため、気づかずにそのまま登録してしまうとよくない可能性があるかと思います。

## 関連

- [2021年4月5日、ジャパンネット銀行はPayPay銀行としてスタートしました。 - PayPay銀行](https://www.paypay-bank.co.jp/namechange/index.html)

**Comment by cm-wada-yusuke** [comment]
@paithiov909 ご連絡ありがとうございます！表記を修正しますのでしばしお待ち下さい。
