### ISSUE TITLE
ブロック機能

### ISSUE THREAD

**Issue by umireon** [zenn-dev/zenn-community#342]
## 提案・要望
TwitterやQiitaのような特定のユーザーのブロック機能

## 背景
別の民度の低いSNS（Twitterなど）で口論になって、その後そのSNSで該当ユーザーをブロックすると、Zennのコメント欄で蒸し返そうとしてくる人がいました。
ブロック機能はZennの信念に反しているのかもしれませんが、話の通じない人というのは確かに存在するので、ブロック機能の実装を望みます。

私は私の記事に対する建設的なフィードバックが欲しいのであって、自分の気に入らない記事をこの世から抹消するという目的で揚げ足取りをしてほしくてZennに記事を公開しているのではありません。

Qiitaにはブロック機能は存在します。

https://help.qiita.com/ja/articles/qiita-block

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ニーズが限定的であり実装コストに見合わないため対応しないこととなりました。

理想論かもしれませんが、ブロック機能は必要ないような、建設的でリスペクトを持った文化のコミュニティにしたいです。
