### ISSUE TITLE
IDとパスワードでログインできるようにしてほしい

### ISSUE THREAD

**Issue by huideyeren** [zenn-dev/zenn-community#347]
## 提案・要望

ID とパスワードでもログインできるようになると助かります。

## 背景

会社の Google Chrome のプロファイルが業務用の Google アカウントしか選べないため、
会社で個人用の Google アカウントからログインできない状態です。

## 関連

#68

**Comment by tannerjohn65** [comment]
こちら同様のIssueが存在するため、管理のためにCloseいたします 🙏 
duplicate
https://github.com/zenn-dev/zenn-community/issues/17
