### ISSUE TITLE
Web フォント Inter の `A` のグリフの表示が崩れている

### ISSUE THREAD

**Issue by mashabow** [zenn-dev/zenn-community#348]
## 事象

Zenn で使用されている Web フォント Inter の `A` のグリフが崩れ、交叉部分が白抜きで表示されています。

## 発生したページのURL

例えば https://zenn.dev/catnose99 。

## 発生した画面のスクリーンショット

<img width="1165" alt="CatNoseさんの記事一覧___Zenn" src="https://user-images.githubusercontent.com/6268183/139409090-41c8eeab-7238-4c92-9504-c7bf3e8ca856.png">

## 再現方法

ページを表示。

## 環境

- OS: macOS 10.15.7
- Browser: Firefox 93.0 / Chrome 95.0.4638.69

**Comment by catnose99** [comment]
ご報告ありがとうございます。

以下の環境で検証したのですが、再現せず…

- Chrome(94.0.4606.81)
- Chrome(95.0.4638.69)
- Firefox(72.0.2)
- Firefox(73.0.2)

念の為ローカルフォントとしてInterがインストールされていないかご確認いただけますでしょうか？

**Comment by catnose99** [comment]
再現できないため一旦クローズ
