### ISSUE TITLE
アップロードしたPNGがJPEGに圧縮されてしまう場合があるが、拡張子が合っていない/合わせられない、そもそもJPEG圧縮してほしくない。

### ISSUE THREAD

**Issue by libraplanet** [zenn-dev/zenn-community#349]
## 事象
* アップロードしたPNGがJPEGに圧縮されてしまう場合がある。
* 圧縮されない場合もあるが、条件が不明瞭で、結果もわからないため、適切な拡張子がつけられない。
* アップロード後の拡張子が「.png」のままのため、JPEGに圧縮されていると、不正なファイルとなる。
* そもそもPNGファイルをアップロードしているのに、再圧縮されたくない。(他のフォーマットにも買えたくない)。
* クリップボードからの貼り付けはPNGにしてほしい。 (自然写真をクリップボード経由で貼り付けたり、普通しないので)

## 発生したページのURL
https://zenn.dev/libraplanet/articles/69447cf0cdbca5

## 発生した画面のスクリーンショット
![image](https://user-images.githubusercontent.com/1041858/140555668-5cee2a5d-0012-408a-95f0-332bd384a224.png)
![image](https://user-images.githubusercontent.com/1041858/140556252-2731a30d-d527-45dd-946f-4c0518311e80.png)

## 再現方法
1. クリップ ボードの画像をペーストした場合
2. PNG画像ファイルをアップロードした場合

## 環境
- Device: PC
- OS: Windows 10 v1809
- Browser: Google Chrome 95.0.4638.69

**Comment by catnose99** [comment]
ご報告ありがとうございます。
こちら原因が分かったので対応しようと思います。

**Comment by catnose99** [comment]
pngがjpegに変換されてしまう原因は、クライアント側で使用していた画像圧縮ライブラリによるものでした。
さきほどのリリースで該当の問題を修正しました。

恐縮ながら既にアップロード済みの画像については対応が難しそうです。申し訳ないです。
