### ISSUE TITLE
サポート機能に一言コメントを添える機能

### ISSUE THREAD

**Issue by daichi-takezawa** [zenn-dev/zenn-community#351]
## 提案・要望

Zennでいつもお世話になっております。投げ銭の際に一言コメントでき、投げ銭された方はコメントを返せるような機能があったらと思っています。
## 背景

Zennの投げ銭機能非常にありがたいです。しかし、投げ銭するメリットをあまり感じにくい仕組みになっているかと思います。というのも例えばYouTubeやTwitchなどの生放送などで投げ銭する場合は、すぐに生主の反応を見れたり、感謝の言葉など伝えられるので、投げ銭するメリットを感じやすいと思いますが、現状Zennではただバッジを送るのみで投げ銭するメリットを感じにくいのでは？と個人的には考えております。

そこで投げ銭の際にバッジではなく、名前とともに一言コメント(例えばありがとう！やこれからも記事見たいです！)など出来たらより投げ銭したくなるかなと思います。また投げ銭された側も一言返せる機能があったらいいな～と考えている次第です。

一意見として受け取ってくださると嬉しいです！これからも応援しています！

**Comment by catnose99** [comment]
ご意見ありがとうございます。
サポート機能でメッセージを送れるようにする機能は実はすでに検討中です。

また何か決まったらこちらに追記します。

**Comment by kurowassan1212** [comment]
そうでしたか！良かったです！楽しみにしておきます😀

**Comment by cm-igarashi-ryosuke** [comment]
コメントを添える機能をリリースしました！
https://info.zenn.dev/2024-01-31-badge-message
