### ISSUE TITLE
ID変更機能

### ISSUE THREAD

**Issue by miyomiyo344** [zenn-dev/zenn-community#352]
## 提案・要望
自分のIDを変更できるようにしていただけると嬉しいです

**Comment by cm-wada-yusuke** [comment]
ご要望ありがとうございます。ユーザーIDの変更については過去いくつか希望をいただいていますが、機能追加を優先しておりそのあたりの足回りは後回しにさせていただいているという現状です。

ユーザー名がかかわる機能追加が一段落した後に着手することになりそうです。ご不便をおかけしますが気長にお待ちいただけると幸いです。

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、影響範囲が大きくニーズの割に実装コストが高いので、実装は見送ることとなりました。
