### ISSUE TITLE
MermaidでActorが利用できない

### ISSUE THREAD

**Issue by ayumukob** [zenn-dev/zenn-community#353]
## 事象
mermaidでシーケンス図をmdに組み込もうとしたところactorステートメントを記述しているとシンタックスエラーでレンダリングできないと表示されてします。
こちらはそういう仕様でしょうか？

## 発生した画面のスクリーンショット
<img width="487" alt="スクリーンショット 2021-11-23 1 16 05" src="https://user-images.githubusercontent.com/24975740/142896795-13c02d6b-150c-4fcb-a2a7-a22ebc29b3d4.png">
<img width="539" alt="スクリーンショット 2021-11-23 1 18 14" src="https://user-images.githubusercontent.com/24975740/142896921-e79877ac-0609-4d16-a38f-1dc71a5c5ea4.png">

## 再現方法
公式にあったサンプルでも同様の結果となっています。
```
sequenceDiagram
    actor Alice
    actor Bob
    Alice->>Bob: Hi Bob
    Bob->>Alice: Hi Alice
```

## 環境
- Device: Mac
- OS: macOS Monterey 12.0.1
- Browser: Vivaldi 4.3.2439.65

以上、よろしくお願いいたします。

**Comment by cm-igarashi-ryosuke** [comment]
@ayumukob 詳細なご報告ありがとうございます。

確認したところ、

- Zennが利用しているmermaid.jsのバージョンが `8.12` 
- Actor機能の追加が `8.13.0` 
  https://github.com/mermaid-js/mermaid/releases/tag/8.13.0

となっておりましたので、Zenn側のmermaid.jsのバージョンを上げる必要がありました。
対応いたしますので少々お待ち下さい。
完了しましたらこちらのissueに報告いたします。

**Comment by cm-igarashi-ryosuke** [comment]
@ayumukob こちら対応完了しましたので、 actor ご利用いただけます。

**Comment by ayumukob** [comment]
確認が遅くなり申し訳ありません。
こちら正常に動くことが確認できました。
ご対応ありがとうございました！
