### ISSUE TITLE
mp4動画を埋め込みたい

### ISSUE THREAD

**Issue by knsg16** [zenn-dev/zenn-community#354]
## 提案・要望

mp4動画も埋め込みたい！

## 背景

mp4の動画を埋め込みたかったが、対応されてなかったようなので、gifに変換する必要があったため。

**Comment by cm-igarashi-ryosuke** [comment]
@knsg16 ご提案ありがとうございます。

gifからの変換のひと手間は面倒ですよね。

重複するissueがあるため、本issueはクローズさせていただきます。
https://github.com/zenn-dev/zenn-community/issues/239

引き続き検討いたします。
