### ISSUE TITLE
details内の見出しを目次から除く

### ISSUE THREAD

**Issue by ojklab** [zenn-dev/zenn-community#355]
## 提案・要望

Bookの場合、details内の見出しもチャプター冒頭の目次にリストアップされるのですが、リンクとして機能しません。目次だけでなく、details内の見出しに文中からリンクを張っても機能しません。

details内の見出しは目次に表示しないという対策もあろうかとは思いますが、可能でしたらdetailsを開いた状態にしてリンク先に飛べるようになると文中からのリンクも機能するのでたいへん嬉しいです。

**Comment by catnose99** [comment]
ご報告ありがとうございます。たしかにそうですね。

> detailsを開いた状態にしてリンク先に飛べるようになる

これができればベストなのですが技術的に難しそうです。
details内の見出しは目次から除く方向で検討します。

**Comment by ojklab** [comment]
ありがとうございます。

**Comment by catnose99** [comment]
リリース後にこちらのIssueをクローズさせていただきます！🙏

**Comment by catnose99** [comment]
こちらさきほど対応のリリースを行いました。今後は上記の問題は発生しないはずです。
（すでに投稿済みのデータに関してはキャッシュのクリアが行われるまでしばらく時間がかかります）
