### ISSUE TITLE
スクラップで複数のコメントで脚注を使用した場合のリンクの参照先がおかしい

### ISSUE THREAD

**Issue by dmystk** [zenn-dev/zenn-community#356]
## 事象

スクラップに複数のコメントを入れ、それぞれのコメントで脚注を使用すると、脚注へのリンクおよび脚注から戻るリンクが想定通りに動作しないようです。どのコメントの脚注リンクも、最初に脚注が使用されたコメントへのリンクになってしまいます。

## 発生したページのURL

https://zenn.dev/dmystk/scraps/62cf7ee7fb6bda

一番下のコメントの脚注リンクを押下した際に全く別のコメントの脚注へリンクされます。

## 再現方法

1. スクラップを作成する
2. `^[hoge]` という内容のコメントを追加する
3. `^[fuga]` という内容のコメントを追加する
4. `^[fuga]` で生成された脚注へのリンクおよび脚注から戻るリンクを押下する

4 で押下したリンクの参照先が 2 で生成されたコメントの脚注へのリンクになっています。本来は 3 で生成されたコメントへのリンクになるのが正しいと考えています。
２と 3 のコメントを長めにしておくとリンクの参照先がわかりやすいかもしれません。

## 環境

- Device: PC
- OS: macOS Big Sur Version 11.6
- Browser: Safari Version 15.0 (16612.1.29.41.4, 16612)

**Comment by catnose99** [comment]
丁寧なご報告ありがとうございます。
問題が確認できました。ご迷惑をおかけしますが、対応まで今しばらくお待ちください。

**Comment by catnose99** [comment]
こちら修正をリリースしました。
今後作成されるコメントについては上記の問題は発生しないのですが、すでに作成済みのコメントについては反映まで少しお時間をいただきます（保存されている変換済みのHTMLの再変換が必要になるため）。

一旦Issueはクローズさせていただきます。
