### ISSUE TITLE
コードブロックの言語指定に続けて情報文字列があると意図したシンタックスハイライトが行われない

### ISSUE THREAD

**Issue by lempiji** [zenn-dev/zenn-community#357]
## 事象

ZennCLIのプレビューで、Markdown上のコードブロックに言語名のあとスペース分けで情報文字列が付いていると、スペース以降もハイフン区切りで言語名の一部と認識される。結果、GitHubとは異なる言語指定となってしまい、目的のハイライトにすることができない。

たとえば、

~~~
```d single
```
~~~

という記述で言語が `d-single` として扱われ、意図したハイライトが行われない。

markdown-itの解析やCommonMarkの仕様でこういった扱いはないと思われるが、原因は不明。

これができないと、記事用のMarkdownを他のツールで処理する際に付けたい情報が付与できないことがある。
（これを使って2021年のアドベントカレンダーの記事を書こうと思っています）

なお確認用の記事は投稿しておらず、実際の記事で同様の現象が起きるかどうかは確認していません。

- 情報文字列について
    - https://spec.commonmark.org/0.30/#info-string
- 情報文字列の例
    - https://spec.commonmark.org/0.30/#example-143

## 発生した画面のスクリーンショット

![image](https://user-images.githubusercontent.com/1206221/145830090-45d0eff4-0eaf-401b-aedd-0bf02631fa59.png)

ZennCLIでpreviewしているときのコンソール表示

![image](https://user-images.githubusercontent.com/1206221/145830864-2aa9428d-9250-4e98-a554-50aee401164e.png)

## 再現方法

以下のブロックをそのままMarkdownとして保存すると確認することができます。
GitHubでは両方ともハイライトされることが確認できています。

~~~
# 1

```d
import std;
```

# 2

```d single
import std;
```
~~~

## 環境

- Zenn CLI: 0.1.99

**Comment by catnose99** [comment]
ご報告ありがとうございます。コードブロックにファイル名を表示する仕組みが影響していそうです。確認してみます。

**Comment by catnose99** [comment]
こちら対応しました。今後は上記の問題は発生しないはずです。
（すでに投稿済みのデータに関してはキャッシュのクリアが行われるまでしばらく時間がかかります）

ご報告ありがとうございました。
