### ISSUE TITLE
gistのようにgithubレポジトリ内のファイルを埋め込み可能にしてほしい

### ISSUE THREAD

**Issue by anatawa12** [zenn-dev/zenn-community#359]
## 提案・要望

gistのようにgithubレポジトリ内のファイルを埋め込み可能にしてほしい

## 背景

1ファイル単位の場合はgistで全然問題ないと思いますが、複数のファイルがまとまっていたり、また既存のプロジェクトの一部を参照したいときなどにgithubのソースを埋め込めるようにしていただきたいです。
既存のプロジェクトの一部を参照したい場合には行数を指定したいことが多いと考えられるので、<https://github.com/fixrtm/fixRTM/blob/1c26efee74977c950df80b1800e37c52652b50f1/build.gradle.kts#L168-L206> のように#Lbegin-Lendにも対応してほしいです。(github内のリンクは#Lがないと埋め込まれないので、ないとエラーもいいと思います。)

## 関連

gist対応: #155

**Comment by cm-wada-yusuke** [comment]
@anatawa12 ありがとうございます。こちらの機能、追加候補です。
https://github.com/zenn-dev/zenn-community/issues/208

現在チームのリソースを[Amazonギフト対応](https://github.com/zenn-dev/zenn-community/issues/358)へ優先的に注いでいるところでして、こちら落ち着き次第機能追加を行っていきます。もうしばらくお待ち下さい。

**Comment by anatawa12** [comment]
Duplicateでしたか。検索が甘くすみません。closeしたほうがいいですかね？

**Comment by cm-wada-yusuke** [comment]
具体的な要望ケースとして残しておいていただけるとありがたいです！

**Comment by uttk-dev** [comment]
@anatawa12 

提案ありがとうございます。

こちら対応しましたのでクローズします。
具体的な使用方法については、[ガイド記事](https://zenn.dev/zenn/articles/markdown-guide#github)に解説を載せてありますので、そちらを参照して頂ければと思います。

よろしくお願いします。
