### ISSUE TITLE
機能リクエスト）Elm版のクラウド開発環境であるEllieの埋め込みに対応して欲しいです

### ISSUE THREAD

**Issue by TheSacredLipton** [zenn-dev/zenn-community#36]
elm記事を書くにあたりサンプルにEllieを埋め込みたいです。

https://ellie-app.com/b2nPzKxmTMXa1 の場合

```
<iframe src="https://ellie-app.com/embed/b2nPzKxmTMXa1" style="width:100%; height:400px; border:0; overflow:hidden;" sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"></iframe>
```

のような感じです。

**Comment by catnose99** [comment]
チェックしてみます。

ちなみにCodeSandboxでelmを使うこともできるんですかね。
https://github.com/codesandbox/codesandbox-client/issues/155

**Comment by TheSacredLipton** [comment]
ありがとうございます🙏

私自身CodeSandbox上でElmを使ったことが無いのでなんとも言えないのですが、Elmを使っている方がサンプルの埋め込み用にCodeSandboxかEllieを選ぶとしたらEllieを選ぶことが大多数だと思います。

またEllie自体の有用性につきましてはこちらの記事が参考になります
https://qiita.com/ababup1192/items/f72dc6bbcbe2f075a74b

**Comment by catnose99** [comment]
情報ありがとうございます！

**Comment by cm-wada-yusuke** [comment]
メンテナンスが止まっているように見受けられます。クラウドIDEなので埋め込むリスクは小さいかもしれませんが、一度マイルストーンからははずさせていただきます。

https://github.com/ellie-app/ellie
