### ISSUE TITLE
モバイルでの記事編集時にヘッダーのフローティングに不具合がある

### ISSUE THREAD

**Issue by 0si43** [zenn-dev/zenn-community#360]
## 事象

※ クリティカルではないです

モバイルブラウザからの記事編集時、ヘッダーのフローティングがズレて、保存ボタンがタップ不能になりました。
プレビュー画面に切り替えるなどの操作で復旧できるので、
ユーザーにとってはクリティカルなバグではないですが、一応ご報告します。

## 発生したページのURL

記事編集ページ

## 発生した画面のスクリーンショット

https://user-images.githubusercontent.com/45909001/147398374-93a0a121-e317-411a-a88e-4372809c7d81.MOV

## 再現方法

ある程度の長さの文を書いてからスクロールすると発生

## 環境

- Device: iPhone 12 Pro
- OS: iOS 15.2
- Browser: Google Chrome

**Comment by 0si43** [comment]
ちなみにですが、この不具合がなければモバイルからの執筆も、
(コード出てこない記事なら)普通にできるかなと思いました

**Comment by catnose99** [comment]
ご報告ありがとうございます。
自分の環境（iOS15.1 + Safari or Chrome）では再現できず…
iOS15.2で発生する問題かもしれないので来年確認します。

**Comment by catnose99** [comment]
iOS15.2で長文を書いたものの再現できず…
今度時間を取って該当部分のコードを見直してみます

**Comment by 0si43** [comment]
調査、ありがとうございます:pray:
うーん今手元で再現を試みたんですが、5回中1回成功（動画撮れず）でした

アプリをバックグラウンドにして、戻ってくるとかも関係してる……？
でも確定で再現する手段がないですね

他に優先して対応しなきゃいけないこともたくさんあろうかと思うので、このissueは一旦閉じますね
