### ISSUE TITLE
mermaid のダイアグラムをアコーディオンの中に記述すると正しく表示されない

### ISSUE THREAD

**Issue by hankei6km** [zenn-dev/zenn-community#361]
## 事象

アコーディオンの中に mermaid のダイアグラムがあるときに、アコーディオンを開くとダイアグラム左上の一部分のみが表示される。

Zenn-CLI のプレビューと Scraps で確認しています。

## 発生したページのURL
https://zenn.dev/hankei6km/scraps/a8ad5babeebf65

## 発生した画面のスクリーンショット
通常の記述
![scap-mermaid](https://user-images.githubusercontent.com/1386689/147405959-c1c8f0af-d87f-478f-87b2-7937e218f4e2.png)

発生時
![scrap-mermaid-inside-accordion](https://user-images.githubusercontent.com/1386689/147405966-14d9588b-3264-4704-a22d-f1988d6bb298.png)

## 再現方法
以下のコードを Scrap で入力

    :::details ダイアグラム
    
    ```mermaid
    graph LR
      cms[/"Hedless CMS(RichText)"/] --> local[("local repo")] --> github[("repo on GitHub")] --> zenn[/"Zenn"/]
    ```
    
    :::

Preview を確認する。

## 環境

- Device: PC
- OS: Windows10
- Browser: chrome 96.0.4664.110

Android の Chrome でも確認しています。

**Comment by catnose99** [comment]
ご報告ありがとうございます。

こちらでも問題を確認できました。
来年調査しますのでしばらくお待ちください。

**Comment by hankei6km** [comment]
年末年始のバタバタしている時期にすみません。

今回の件は「アコーディオンの範囲をミスしてたまたま気が付いた」ものなので
とくに困っているという状況ではありません。

落ち着いた時期に調査いただければと思います。よろしくお願いいたします。

**Comment by cm-wada-yusuke** [comment]
Safariのみ2段階の問題があることがわかり、引き続き調査します。
Chrome と Edge では https://github.com/zenn-dev/zenn-editor/pull/233 
により直る見込み。

**Comment by cm-wada-yusuke** [comment]
@hankei6km こちら @catnose99 さんの修正により Chrome と Edge で問題が解消しました。ただ Safari については別の問題が残っており現在対応中です。もうしばらくお待ち下さい。

**Comment by hankei6km** [comment]
ご対応ありがとうございます。

Safari は手元に環境ないので検証のお力になれませんが、
Chrome と Edge では正常に表示されることをこちらでも確認できました。

![Chrome でアコーディオン中のダイアグラムが正常表示されているスクリーンショット](https://user-images.githubusercontent.com/1386689/149746457-0b796988-9653-43b9-8d45-1a920331d122.png)

**Comment by cm-wada-yusuke** [comment]
ご確認・ご連絡ありがとうございます！Safariが残タスクとしてこちらのissueは残させてください。

**Comment by cm-wada-yusuke** [comment]
@catnose99 さんにより mermaid.js を遅延ロードする仕組みが入りまして、Safariでも解消しました。ありがとうございました。何かまた見つけたらご連絡いただければとおもいます。報告ありがとうございました！クローズします。

**Comment by hankei6km** [comment]
ありがとうございました。また何かありましたらよろしくお願いいたします。
