### ISSUE TITLE
トピックの略称を正称になるようにしてほしい

### ISSUE THREAD

**Issue by Neko7sora** [zenn-dev/zenn-community#362]
## 提案・要望

Win10 --> Windows 10 
https://zenn.dev/topics/win10 https://zenn.dev/topics/windows10
Win11 --> Windows 11
https://zenn.dev/topics/win11 https://zenn.dev/topics/windows11

html5 html
https://zenn.dev/topics/html5 https://zenn.dev/topics/html
css3 css
https://zenn.dev/topics/html5 https://zenn.dev/topics/html
## 背景

重複のトピックがあることによって、片方にはあって、もう片方にはないということが起きる。

**Comment by cm-wada-yusuke** [comment]
ご報告ありがとうございます。このあたり少しむずかしいですね。`html5`、`html` は意図して区別している場合もありそうです。一方、ご指摘にもあるように `Win10`、'Windows 10' など明らかな略称はまとめてしまったほうが書き手にとっても読み手にとってもメリットが大きそうです。ただ、運営側で勝手にまとめて良いもの、そうでないものがあると思うのでトピックにおいて何を重視するのかポリシーを定める必要があります。

チームで方針を相談しますのでしばしお待ちいただければと思います。

**Comment by catnose99** [comment]
さきほどのリリースで、トピックの編集ページからトピックの統合申請ができるようになりました。

![スクリーンショット 2022-01-24 13 24 12](https://user-images.githubusercontent.com/34590683/150725795-37cd70c4-d1d3-4da4-96b7-d22593a02cc2.png)

すでに`win10`は`windows10`に、`win11`は`windows`11に統合されています。

（https://zenn.dev/topics/win10 にアクセスすると、https://zenn.dev/topics/windows10 にアクセスしたときと同じ内容が表示されることが分かると思います）
