### ISSUE TITLE
Bookの各チャプターにタグを付与する機能のリクエスト

### ISSUE THREAD

**Issue by TBSten** [zenn-dev/zenn-community#363]
## 提案・要望
Bookの各チャプターを作成するときに、「このページは説明をする、このページは実装手順まとめ」といった感じでグループ分けしたいと思いました。そこでこれをタグ機能を実装することで実現できればいいなというリクエストです。

できれば過去に設定したタグを記憶して補完が効くようにしていただけるとなお嬉しいです。

もしすでに類似の機能があれば申し訳ありません。ご検討よろしくお願いいたします。

**Comment by cm-wada-yusuke** [comment]
> このページは説明をする、このページは実装手順まとめ

Webエディターで、本を編集するときにチャプターを絞り込み、グループ分けして編集できるようにしたい、ということですね。ご要望ありがとうございます。Zennにそのような機能はありませんが

**Comment by cm-wada-yusuke** [comment]
ちなみにChromeの拡張である 「Quick Tabs」を使えばタブのタイトルからもキーボードで検索できるので便利です。

https://chrome.google.com/webstore/detail/quick-tabs/jnjfeinjfmenlddahdjdmgpbokiacbbb?hl=ja

**Comment by TBSten** [comment]
ありがとうございます。タググループを使ってみようと思います😊

**Comment by cm-wada-yusuke** [comment]
ご検討ありがとうございます。この辺り執筆環境が人によって異なるため、キラー機能が決めづらいポイントでもあるのでこのようにご意見をいただけるのは助かります。もし不十分なケースが出てきた場合は遠慮なく再オープンしてください。
