### ISSUE TITLE
[VSCode Extensions] Zenn 用の Markdown プレビュー拡張がほしい

### ISSUE THREAD

**Issue by Ningensei848** [zenn-dev/zenn-community#364]
## 提案・要望

Visual Studio Code で使える Zenn 用の Markdown プレビュー拡張がほしい

- `zenn-cli` を起動することなく，VSCode だけで完結させたい
- ↑ これが実現すると，`github.dev` でもプレビューができるようになり，**執筆開始までのラグが最小化**できる
  - 任意の環境のブラウザで開く　→　書く　という２プロセスに短縮
  - スマートフォンやタブレットからでも編集がしやすくなる！

## 背景

zenn では，[GitHub リポジトリで投稿を管理することができる](https://zenn.dev/zenn/articles/connect-to-github)．だが，編集にはいちいち [`zenn-cli` を起動せねばならない](https://zenn.dev/zenn/articles/install-zenn-cli)．これは，モバイルユーザーを切り捨てているし，デスクトップ環境があっても執筆開始までのラグ（CLI起動→エディタを開く→ ブラウザでプレビューを見る→書く）が生じていることが気になる．

（ zenn-cli やその他 zenn の取り組み自体には非常に満足している，貶める意図はないことに留意されたい）

## 関連

- #97 
  - 非公開範囲で査読（プレビュー）してもらうのは，（GitHub の Private リポジトリで記事を管理し）`publish: false` でやるのがいいのではないか？と考えると，github.dev をつかってブラウザ上で全部完結するとみんな幸せなはず
  - #124 と #77 を組み合わせる感じ
- #238
  - 少し趣旨とはズレるが，やはりブラウザだけですべて完結する手軽さに対する要望は根強いと感じる
- #232 
  - github.dev においても push されなかったファイルの変更はブラウザにキャッシュされているらしい \[要検証\]

## 方針

[zenn-editor](https://github.com/zenn-dev/zenn-editor) でも使用している [`zenn-markdown-html`](https://www.npmjs.com/package/zenn-markdown-html) と [`zenn-content-css`](https://www.npmjs.com/package/zenn-content-css)をそのまま流用して，拡張機能を開発する．

※現時点では [`zenn-embed-elements`](https://www.npmjs.com/package/zenn-embed-elements) が拡張機能において利用できるかについては確認できていない

## 参考文献

- [The github.dev web-based editor - GitHub Docs](https://docs.github.com/ja/codespaces/the-githubdev-web-based-editor)

- [GitHubリポジトリでZennのコンテンツを管理する - Zenn.dev](https://zenn.dev/zenn/articles/connect-to-github)
- [Zenn CLIをインストールする - Zenn.dev](https://zenn.dev/zenn/articles/install-zenn-cli)

- [Web Extensions | Visual Studio Code Extension API](https://code.visualstudio.com/api/extension-guides/web-extensions)

<details>
<summary>github.dev でサポートしている拡張機能について</summary>

![](https://user-images.githubusercontent.com/20794309/148666957-b448658e-7f74-418b-afe3-b87d41369b80.png)

*[#using-extension](https://docs.github.com/ja/codespaces/the-githubdev-web-based-editor#using-extensions)*

> The web-based editor supports Visual Studio Code extensions that have been specifically created or updated to run in the web. These extensions are known as "web extensions". To learn how you can create a web extension or update your existing extension to work for the web, see "[Web extensions](https://code.visualstudio.com/api/extension-guides/web-extensions)" in the Visual Studio Code documentation.
> 
> Extensions that can run in the web-based editor will appear in the Extensions View and can be installed. If you use Settings Sync, any compatible extensions are also installed automatically. For information, see "[Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync)" in the Visual Studio Code documentation.

Web ベースのエディタは、Web で実行するために特別に作成または更新された Visual Studio Code の拡張機能をサポートしています。これらの拡張機能は "Web extensions" と呼ばれます。Web extensions を作成する方法、または既存の拡張を Web 用に更新する方法については、Visual Studio Codeのドキュメントの "[Web extensions](https://code.visualstudio.com/api/extension-guides/web-extensions)" を参照してください。

ウェブベースのエディターで実行できる拡張機能は、拡張機能ビューに表示され、インストールすることができます。設定の同期を使用する場合、互換性のある拡張機能も自動的にインストールされます。詳しくは、Visual Studio Code ドキュメントの "[Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync)" を参照してください。
</details>

**Comment by Ningensei848** [comment]
[VSCode Web Extension for Zenn Preview がほしい - Zenn.dev](https://zenn.dev/ningensei848/scraps/7d2f0e4367eadb) にも経過を書き残した．自分でも実装の道を探ったところ，以下の課題があることがわかった．

- `zenn-markdown-html` 内部で使っている `markdown-it` の処理を，専用プラグイン (e.g. `markdown-it-zenn`) として独立させる
- 同様に，今回作ることになる VSCode の拡張機能 ( e.g. _Markdown Preview Zenn Styling_ )も独立して管理
- できれば，上記２つの新規リポジトリは `zenn-editor` でモノレポ管理できたほうがいい

---

基本的に，新規で開発すべき点はどこにもなさそう．VSCode Web Extension も `npx yo code` で[テンプレート作成してくれる](https://code.visualstudio.com/api/get-started/your-first-extension)ので，あとはちょこっと直すだけ．

個人的には，`zenn-editor` で使っている `lerna` を Yarn v3 とともに使うと動かないので，いちいちダウングレードするのだけ面倒くさそうかもしれない．

**Comment by cm-wada-yusuke** [comment]
@Ningensei848 こんにちは。要望および詳細な調査とその結果の共有、ありがとうとうございます！私もよくiPad+`github.dev`で下書きを作るので共感できる内容が多いです。

ご不便をおかけして申し訳ないのですが開発チームで対応する場合はしばらくお時間をいただくことになりそうです。現状プレビューの実行環境をReact（ブラウザ）に統一しているためメンテナンスや機能追加を行えています。ここに実行環境としてVSCodeのプラグインが加わるとメンテナンス・機能追加の労力が倍以上になるため例えば「VSCodeと公開画面とで見え方が違う」といった課題が出てくる可能性があります。

Codespaces がもっとカジュアルに使えるようになったり、`github.dev`で任意のDockerfileをひとつだけ起動した状態で使えるようになったり…そういう進化の方向も出てきてくれると嬉しいですね（他力本願）。

**Comment by Ningensei848** [comment]
Update!!!
[zenn-dev/zenn-vscode-extension: ブラウザ上の VSCode で Zenn をプレビューするための拡張](https://github.com/zenn-dev/zenn-vscode-extension)

---

公式対応、まじでありがとうございます！！！！！！

早速使ってみます！！！！

cf. [Zenn公式さんはTwitterを使っています: 「🚀 Zennのアップデート✨ ZennのVSCode Web拡張(β版)をリリースしました 🥳 いままでは Zenn のサイト上や zenn-cli でしかできなかったプレビューが https://t.co/DMe3LLg3rZ 上で表示できるようになり、GitHub上で作成や編集が完結することができます！ﾔｯﾀﾈ! https://t.co/7Vt178Kwsg」 / Twitter](https://twitter.com/zenn_dev/status/1589847227627098112)
