### ISSUE TITLE
記事の削除

### ISSUE THREAD

**Issue by riita10069** [zenn-dev/zenn-community#365]
## 事象

GitHub連携をした場合、作成した記事の削除ができない。
GitHub上から、ファイルを削除しても消えない仕様になっているため。

GitHubからファイルを削除しても消えない仕様は正しいとが、UIから削除できるようにしたい。
また、GitHub連携をしたとしても、zennのUIで管理している記事があってもいいと思う。

**Comment by cm-wada-yusuke** [comment]
> 記事を削除したい

GItHub リポジトリからファイルを消して連携した上で、記事管理ページから記事を削除すると意図した状態になるでしょうか？ご確認ください。
![image](https://user-images.githubusercontent.com/17589989/148866455-14488822-6a1c-492c-9dbb-62f9d455eced.png)


> GitHub連携をしたとしても、zennのUIで管理している記事があってもいいと思う

こちらは、どの記事がGitHub管理で、どの記事がZenn管理かが混ざると意図しない更新や削除が行われる可能性があるため、現状GitHubを利用する場合は一元管理をお願いしています。ただ、GitHub連携時にもっといろいろとやれることがあるのは認識しておりますので（共同執筆・レビューなど）ご不便をおかけしますがお待ちいただければと思います。
