### ISSUE TITLE
アコーディオン中の数式がChromeで閲覧時に消失する

### ISSUE THREAD

**Issue by judau** [zenn-dev/zenn-community#366]
## 事象
アコーディオンの中に数式を書くと、Chromeで表示したときに表示されません。

※ Chromeをバージョン: 97.0.4692.71にアップデートしたところ発生するようになりました。以前のバージョンだと発生しなかったと記憶しています。

## 発生したページのURL
https://zenn.dev/log5/articles/algo-698-try

## 発生した画面のスクリーンショット

左が Chrome で、右がSafariです。
バージョンはそれぞれ
- Chrome: バージョン: 97.0.4692.71（Official Build）
- Safari: バージョン15.2 (17612.3.6.1.6)

![スクリーンショット 2022-01-14 0 06 25](https://user-images.githubusercontent.com/40707031/149359317-2224d200-39a7-47f3-ac5d-90704e19f18b.png)

## 再現方法

1.  [アコーディオン](https://zenn.dev/zenn/articles/markdown-guide#%E3%82%A2%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%82%AA%E3%83%B3%EF%BC%88%E3%83%88%E3%82%B0%E3%83%AB%EF%BC%89) を設置します。
2. 内部に数式を記述します。（下記記述例参照）
3. Google Chromeでページを表示します。（★現象発生）

【記述例】
```
:::details アコーディオン

アコーディオン内部の数式（Chromeで表示されない）
$ab=c$

:::

アコーディオン外部の数式（表示される）
$ab=c$
```

## 環境

- Device: MacBook Pro（16インチ、2021）
- OS: macOS Monterey バージョン 12.1
- Browser: Google Chrome バージョン: 97.0.4692.71（Official Build）

**Comment by catnose99** [comment]
ご報告ありがとうございます。

こちらのIssueと関連していそうです。

- #361 

調査を行いますので申し訳ありませんがしばらくお待ちください。

**Comment by catnose99** [comment]
調査メモ

https://zenn.dev/catnose99/scraps/390050a81e0774

**Comment by cm-wada-yusuke** [comment]
@judau こちら @catnose99 さんの修正により問題が解消しました。現在は アコーディオンの中でも数式が表示されるようになっています。ご連絡ありがとうございました。
