### ISSUE TITLE
[機能要望] 売上から支払いと投げ銭が出来るようにして欲しい

### ISSUE THREAD

**Issue by KASHIHARAAkira** [zenn-dev/zenn-community#367]
## 提案・要望
出来れば売上から支払いや投げ銭が出来るようにして欲しいです。
Zennで頂いたお金をZennで使いたいです。

## 背景
振込申請1回に350円必要で、このお金があれば1回投げ銭が出来る。

## 関連
調べた限り見当たらなかったのですが、既出であればcloseをお願いします。

**Comment by catnose99** [comment]
こちらは個人的にも導入したい機能なのですが、法律的な理由により現状のスキームでは厳しそうです。

ちなみに2022年4月〜Amazonギフト券への交換機能を導入する見込みで（#358 2月に皆さんに通知予定）、アマギフに交換した場合には¥350の手数料はかからなくなります。
