### ISSUE TITLE
特定条件下で数式が正しく表示されない

### ISSUE THREAD

**Issue by wsuzume** [zenn-dev/zenn-community#368]
## 事象
任意の段落で`http:`または`https:`という文字列を含むリンク記法`[xxx](http://yyy.zzz)`の直後に`()`を含むインライン数式を書くと、その段落の中でリンク記法より前にあるインライン数式がバグる。

## 発生したページのURL
https://zenn.dev/wsuzume/articles/4054bbe4948303

## 発生した画面のスクリーンショット
<img width="431" alt="スクリーンショット 2022-01-17 22 51 50" src="https://user-images.githubusercontent.com/3853291/149781075-c2153d0c-0117-4c12-91d0-5f247a682c83.png">

## 再現方法
`あああ$\omega$いいい『[uuu](https://arxiv.org)』えええ$(7)$おおお`

「発生したページのURL」に置いた記事にバグるケースとバグらないケースを列挙しています。

## 環境
- Device: Macbook Air (M1, 2020)
- OS: macOS Monterey
- Browser: chrome 97.0.4692.71（Official Build）（arm64）

**Comment by cm-wada-yusuke** [comment]
@wsuzume ご連絡ありがとうございます。こちら確認します。

**Comment by cm-wada-yusuke** [comment]
詳細なレポート記事のおかげで修正の目処が立ちました、ありがとうございます。ただいまデグレチェックなどを行っていますので、もう少しだけお時間ください。週明けごろのリリースとなる見込みです。

**Comment by cm-wada-yusuke** [comment]
@wsuzume こちら修正リリースを行いました。解消されているかと思います。お手数ですが例によって一度保存し直した後、ご確認いただければと思います。

**Comment by wsuzume** [comment]
@cm-wada-yusuke バグが修正されていることを確認いたしました。迅速にご対応いただきありがとうございます！とても快適なサービスをご提供いただきとても感謝しています！

**Comment by cm-wada-yusuke** [comment]
@wsuzume こちらこそ、たくさん記事を書いていただき、また何かあった時には詳細にレポートいただきとても助かっています。今後ともよろしくお願いいたします。
