### ISSUE TITLE
利用規約ページにおける変更履歴リンクへのリンク切れ

### ISSUE THREAD

**Issue by rosylilly** [zenn-dev/zenn-community#369]
## 事象
利用規約上部に存在する、変更履歴へのリンクが切れて、参照先が 404 Not Found になっています。

> Zennの利用規約の変更履歴はGitHubリポジトリに公開されています。

現在のリンク先は <https://github.com/zenn-dev/zenn-docs/commits/master/pages/terms.md> なのですが、おそらく master ブランチを main ブランチに変更した影響かと思われます。現在閲覧可能に見える最新の変更履歴は <https://github.com/zenn-dev/zenn-docs/blob/main/pages/terms.md> です。

## 発生したページのURL
https://zenn.dev/terms

## 発生した画面のスクリーンショット

![2022-01-19 14-45-48](https://user-images.githubusercontent.com/29084/150071441-37c2e40d-b0a4-4191-9fba-3796c888f512.png)

## 再現方法

利用規約ページ( https://zenn.dev/terms )アクセス後、スクリーンショットにて赤線ハイライト部分のリンクをクリック。

## 環境

- Device: MacBook Air (M1, 2020)
- OS: macOS 12.0.1
- Browser: Firefox v96.0.1
- Date: 2022-01-19 14:30 頃

**Comment by cm-wada-yusuke** [comment]
ご連絡ありがとうございます。こちら確認して、修正します。

**Comment by cm-wada-yusuke** [comment]
こちらリリース、解消済みです。
ご連絡ありがとうございました。
