### ISSUE TITLE
【相談】運営側で既知あるいは対応中の内容と、利用者がロードマップを見た時の乖離がある（もしくは、そのように感じられる）

### ISSUE THREAD

**Issue by shimajima-eiji** [zenn-dev/zenn-community#370]
ご多忙の中、私の一記事にもPRをいただきありがとうございます。
併せまして、本件でお手数をおかけして申し訳ございませんでした。
今後対応につきましても、ご迷惑をお掛けしないよう引き続き細心の注意をもって臨む次第です。

## 提案・要望
`「関連項目の情報ソース（リンク先）以外に、確認が必要なページがあればご教示いただきたいです。」`

さて、いただいたコメントの中で「どこかで公開されている情報ではあるが、利用者が一定の努力で探した範囲で追いきれないものがある可能性があるのではないか」というのが今回の懸念になります。
今回のようなケースはなかなかないと思いますし、優先度は低いと思いますが可能性があるため、起票させていただきました。

## 背景
今回のケースを例にしますと（関連Issueをご参照ください）いただいたコメントの情報はどこかで公開されていて、私も知り得ていた場合は改訂の注意喚起ができたのかな、と思っております。
今後対応としてはそのように行うつもりでおりますが、あくまでコメントでいただいた内容を対応することしかできません…。

今後も仕様や規約も含め、Zennを本格的に活用するための調査を進めたいと考えております。

## 関連
- https://github.com/shimajima-eiji/__Article_Zenn/pull/1#issue-1110092134

いただいたコメントに目を通し、先述の方法で情報を探しましたが、ご教示いただいた情報は執筆時点・現時点もどちらで公開されている情報なのか特定・把握できませんでした。

私が確認した情報ソースは[zennの公式アカウントから発信される記事](https://zenn.dev/zenn)と、ページ下部のものであり、そのうちTwitterについては大変恐縮ですが、全ての内容を追いきれておりませんでした。
おそらく、本件は他の方にも今後起こりうる問題なのではないかと気になり、ご相談に伺った次第です。

特筆しますと、今回ご指摘いただいて、改めて確認したのは[こちらのロードマップ](https://github.com/zenn-dev/zenn-community/projects/1)です。

## 今回とは別件の類似事項
こちらは一例ですが、API情報も公開されているのでしょうか？
（本件は開発者情報でしょうか？）

- https://github.com/zenn-dev/zenn-community/issues/209

解析作業については利用規約に書いていませんでしたが「やっていいかどうかで言うとダメなのかな」と思っておりまして、個人的にも上記Issueなどについて、Zenn-APIの解析は行っていません。

`改めまして、今回の要望になりますが、今回いただいたような「規約改訂の予定」を含めた情報について、上記関連リンク以外で公開されている情報`はございますでしょうか？

**Comment by catnose99** [comment]
ロードマップの内容は運営側が予定している情報を書いているもので、必ずしも確実な情報ではありません。

#209触れているAPIは正式に提供されているものではなく、Zennが内部的に使っているPrivate APIの話です。今後リクエスト制限をかける可能性もゼロではなく、利用を推奨するものではありません。
