### ISSUE TITLE
バグ？仕様？） /books/viewer以下に存在しないパーマリンクにアクセスを試みるとchapter1にリダイレクトされる

### ISSUE THREAD

**Issue by shimajima-eiji** [zenn-dev/zenn-community#371]
## 事象
掲題の通りです。
バグなのか仕様なのか判断ができませんでしたが、Issueテンプレートの２つのうち、バグレポートの方が適切だと思ったのでこちらを選択しています。

## 発生したページのURL
/books以下のコンテンツページであれば、存在しないパーマリンクであればどこでも発生すると思われます。

## 発生した画面のスクリーンショット
アドレス欄にご注目ください

### 正常系：chapter1のページ
<img width="987" alt="スクリーンショット 2022-01-22 4 30 27" src="https://user-images.githubusercontent.com/15845907/150589439-e364eab9-aa19-4c40-bacc-13ac79350d3f.png">

### 正常系: chapter2のページ
<img width="980" alt="スクリーンショット 2022-01-22 4 30 46" src="https://user-images.githubusercontent.com/15845907/150589520-54fe6bc8-8a7d-44b1-bbdb-e0021b0ed8f5.png">

### 異常系: chapter2のページURLをタイポした想定
<img width="994" alt="スクリーンショット 2022-01-22 4 31 07" src="https://user-images.githubusercontent.com/15845907/150589578-52e8ac31-e7aa-4324-a0df-740faa760830.png">

↑↑　about(chapter1)が表示されている　↑↑

### 当初確認したページ
手前味噌で恐縮です

- chapter1の正しいページ https://zenn.dev/nomuraya/books/for_zenn_beginner/viewer/changelog_zenn
  - 「Githubで開く」ボタン ※1 https://github.com/shimajima-eiji/__Article_Zenn/blob/main/books/for_zenn_beginner/changelog_zenn.md
- 同じく存在しないページ https://zenn.dev/nomuraya/books/for_zenn_beginner/viewer/tips_writinga
  - 「Githubで開く」ボタン ※1 https://github.com/shimajima-eiji/__Article_Zenn/blob/main/books/for_zenn_beginner/changelog_zenn.md
- 同じく存在しないページ https://zenn.dev/nomuraya/books/for_zenn_beginner/viewer/read_zenn-teamsa
  - 「Githubで開く」ボタン ※1 https://github.com/shimajima-eiji/__Article_Zenn/blob/main/books/for_zenn_beginner/changelog_zenn.md

### 他アカウントで検証(スクリーンショット参照)
- chapter1の正しいページ https://zenn.dev/zenn/books/how-to-create-book/viewer/about
- 存在しない？ページ https://zenn.dev/zenn/books/how-to-create-book/viewer/getting-starteda
  - 画面最下部右の「GitHubで編集を提案」リンク https://github.com/zenn-dev/zenn-docs/blob/main/books/how-to-create-book/about.md

## 環境
MacBook(Intel) Brave最新版で検証していますが、環境依存の問題ではない気がします。

## 懸念点
これが仕様だとすると、たとえばSNSなどでユーザーが共有時に間違えて入力したアドレスを共有すると、chapter2のページを共有したはずがchapter1のページが表示されてしまってコミュニケーションエラーを誘発する危険性が考えられます。

Articlesでも同様の操作を検証しましたが、存在しないページには404エラーとなり、期待通り？になりますので、バグと認識しました。

**Comment by catnose99** [comment]
たしかにそうですね。

404として「本のトップページに戻る」という導線を入れようと思います。

**Comment by catnose99** [comment]
存在しないチャプターのURLにアクセスした場合には本のトップページにリダイレクトするようにしました。

**Comment by shimajima-eiji** [comment]
ご対応ありがとうございました、私の方でも確認できました。
これならパーマリンクが変更された場合でも、コミュニケーションで解決しやすいと思います。
