### ISSUE TITLE
zenncnd.comが「感染したWebリソース」とセキュリティソフトから警告が出る

### ISSUE THREAD

**Issue by KASHIHARAAkira** [zenn-dev/zenn-community#372]
## 事象
VirtualBox上のUbuntuから、Firefoxでzenn.devにアクセスすると、ホストOS（windows）にあるセキュリティソフトが「感染したWebリソース」として警告を出す。
なお、ホストOSのwindows上からアクセスする場合は警告は出ない。

## 発生したページのURL
https://zenn.dev/
このページにアクセスする際（ブラウザのウィンドウに直打ちと検索結果から飛ぶのと両方共）

## 発生した画面のスクリーンショット
![スクリーンショット (7)](https://user-images.githubusercontent.com/20036649/150910933-b0d0a0d7-5aa9-41b8-915b-f062cf92faa6.png)

## 再現方法
Ubuntu on virtualbox上のFirefoxでGoogleを使って「zenn」と検索し、検索結果からzennへアクセスする。
Ubuntu on virtualbox上のFirefoxのアドレスバーからzenn.devにアクセスする。

## 環境
各バージョンは以下の通り。
＜デバイス＞
Dell latitudee7270
＜ブラウザ＞
Firefox for Ubuntu 96.0 (64-bit)
＜ゲストOS＞
VirtualBox 6.1.32 r149290
Ubuntu 20.04.3 LTS (64bit)
＜ホストOS＞
Windows 10 Pro 21H2 19044.1469(64bit)
＜セキュリティソフト＞
Zeroスーパーセキュリティ(bitdefender)　ver.24.0.26.183

**Comment by KASHIHARAAkira** [comment]
Virtualboxを通さず、Windowsのみでも同様の警告が出るようになりました。

**Comment by cm-igarashi-ryosuke** [comment]
@KASHIHARAAkira ご連絡が遅くなりすみません。こちらの警告はまだ続いていますでしょうか？もし続いている場合、セキュリティソフトのバージョンを最新にしていただき、ブラウザのゲストモードなどキャッシュが効いていない状態でアクセスできるかどうかお試しいただければと思います。

**Comment by KASHIHARAAkira** [comment]
> @KASHIHARAAkira ご連絡が遅くなりすみません。こちらの警告はまだ続いていますでしょうか？もし続いている場合、セキュリティソフトのバージョンを最新にしていただき、ブラウザをゲストモードなどにしてキャッシュが効いていない状態でアクセスできるかどうかお試しいただければと思います。

こちらこそ、返信を失念しており、申し訳ありません。
最近、ホストOSがUbuntuのPCしか使っておらず、エラーが出た環境で試していません。
それほど時間がかかることではないので、今日中にチェックして、ご報告致します！

**Comment by KASHIHARAAkira** [comment]
@cm-igarashi-ryosuke 
今、報告した環境で再現したところ、以前報告した警告は発生しませんでした。
Windows上でも確認しましたが、同様に警告は発生しませんでした。
対応いただきありがとうございます。

**Comment by cm-igarashi-ryosuke** [comment]
@KASHIHARAAkira 早速ご対応いただきありがとうございます。現状では発生していないとのことで安心しました。

おそらくパターン定義が時間差で反映されてしまったものかと思います。
本件はクローズさせていただきます。
