### ISSUE TITLE
限定公開機能

### ISSUE THREAD

**Issue by hirothings** [zenn-dev/zenn-community#373]
## 提案・要望
Qiita同様、限定公開機能が欲しいです

## 背景
チーム限定で公開したいとき, 公開前に一時的に誰かにレビューしてもらいたいときに、利用したいと思いました。

**Comment by cm-wada-yusuke** [comment]
関連：
https://github.com/zenn-dev/zenn-community/issues/97

ご提案ありがとうございます。現在作業中のAmazonギフト券対応の後、Organization含めコラボレーション面を強化していきたいと考えているので、しばしお待ちいただけると幸いです。

**Comment by cm-wada-yusuke** [comment]
記事の下書き公開範囲を変更できる機能としてリリースしました。
https://info.zenn.dev/2024-10-15-draft-preview-share

> チーム限定で公開したいとき, 公開前に一時的に誰かにレビューしてもらいたいときに、利用したいと思いました。

こちらお試しいただければと思います。提案いただき、ありがとうございました。

**Comment by hirothings** [comment]
ありがとうございます！
活用させていただきます。Issueクローズします
