### ISSUE TITLE
自身の記事に投稿されたコメント削除機能

### ISSUE THREAD

**Issue by stken2050** [zenn-dev/zenn-community#374]
## 提案・要望
自身がUPした記事に投稿されたコメントを記事主権限で削除する機能

## 背景
たとえば米国で非常に成功しているQ&A系SNSであるQuoraでは自身の回答についたコメントはその筆者権限において自由にコメントを削除することができます。
この機能によって不適切なスパムコメントであったり、諍いによる嫌がらせコメントなどコミュニティの治安、健全性を担保するためのコメント削除をユーザが運営側にサポート要請せずとも自身で行えるため、迅速な対応が可能であるとともに、運営の負担軽減にもなっているようです。

提案者の個人的ケースでは、たとえば競合サービスのQiitaにおいて、逐一嫌がらせコメントをしてくるネットユーザが存在します。非常に執拗でその人物自身プログラミングも何もできないのですが、たとえばZennに参加して有益な記事をUPした場合、機会を伺って同様に嫌がらせコメントをしてくることが容易に想像できます。

記事というのは御社サービスで収益化も担保しておられるとおり、基本著者による著作物であり、同サービスにUPした本文に連なる形で悪質なネガキャン、荒らし行為が行われた場合は、本体の記事そのものの価値が不当に毀損されることになります。
しかし、記事主、著者権限による最低限のコメント管理機能として不適切と著者がみなせば該当コメントは即刻自由に削除できる、となれば、この問題を防ぐことができますし、一旦、記事主によるコメント削除権限があると荒らしに認識されれば無力化されていることに認識しあきらめもするでしょう。

実際、提案者のようにプログラミング記事をUPしたら常に嫌がらせをしてくる、というケースは少数派ではあるでしょうから、そもそもコメント削除が濫用されることによる弊害というのは考えにくく、他方で一旦そういう執拗な荒らし行為が発生すれば、逐一運営のサポートを要請することになり、非常に煩雑なオペレーションが必要となりかねず、事前にこの機能が導入されていることによって問題を回避できます。

## 関連

コメントに対するサポート機能 #23

はてなブックマークの「コメント一覧非表示」サポート #210

ブロック機能 #342

**Comment by cm-igarashi-ryosuke** [comment]
@stken2050 ご提案ありがとうございます。

コメントの削除につきましては、健全なコミュニティ運営にとって良い影響・悪い影響の両面があると考えており、現段階ではニーズも少ないことから導入は考えていないです。

著者の権限によりコメントを非表示にする機能がありますので、こちらをご利用ください。
https://zenn.dev/zenn/articles/hide-comment
