### ISSUE TITLE
Zenn Booksの「文章量」に3桁ごとのカンマを表示

### ISSUE THREAD

**Issue by wpgekvc9yuft** [zenn-dev/zenn-community#375]
## 提案・要望
Zenn Booksの「文章量」に3桁ごとのカンマを表示してほしい

## 背景
桁数が多くなってくると見づらいため

**Comment by cm-wada-yusuke** [comment]
@wpgekvc9yuft たしかにそうですね。提案ありがとうございます！

**Comment by cm-wada-yusuke** [comment]
@wpgekvc9yuft こちらさきほどリリースし、カンマ区切りで表示されるようになりました。
