### ISSUE TITLE
mermaid.jsのGit graphがシンタックスエラーになる

### ISSUE THREAD

**Issue by yellowsman** [zenn-dev/zenn-community#377]
## 事象
Zennでmermaid.jsのGit graphを書くとシンタックスエラーとして表示されます。
同じ記述で、GitHubおよびmermaid公式のオンラインエディターでは正しく表示されることを確認しています。

GitHubでの表示
https://github.com/yellowsman/mermaid-demo/blob/main/README.md#git-graph---exclamation-experimental

公式オンラインエディターでの表示
https://mermaid-js.github.io/mermaid-live-editor/edit/#pako:eNplj70OwjAMhF8l8twBBpbMIHa6ejGJaSMap0odIYR4d8JPURFebN19su5u4JJnsNAF3Wcae4uSRg1JJpQbiqmDIJVpR3JBOgRr1ptVs7QO5EOZXs4K5Y7C4lFcijEoyjGTuN4IX95XdXp251T0R_vQ3z0zkSbl_A9Ezh0vPxgDDVQ1UvC10Cs8gvYc-RkNwfOJyqAINWNFy-hJeeeDpgz2RMPEDVDR1F7FgdVceIa2gbpM8UPdHwHlb2M

## 発生したページのURL

https://zenn.dev/ito_shigeru/articles/39b41fede7d4e8#git-graph---exclamation-experimental

## 発生した画面のスクリーンショット
![2022-02-17 11_39_51-スタート](https://user-images.githubusercontent.com/5958101/154399870-238d8931-27f5-476c-9749-ad81a3593997.png)

## 再現方法
記事内にmermaid公式のGit graphのサンプルを記述すると再現します。
https://mermaid-js.github.io/mermaid/#/?id=git-graph-exclamation-experimental

## 環境
おそらく環境依存は無いと思います。

念の為、WindowsとMacのChromeブラウザとVivaldiブラウザの各最新バージョンで表示してみましたが同じエラーが表示されていました。

**Comment by cm-wada-yusuke** [comment]
ご連絡ありがとうございます。こちら確認します。利用しているmermaid.jsのバージョンに起因するものかもしれません。

**Comment by yellowsman** [comment]
ありがとうございます！
念の為、貼り忘れていたスクリーンショットを追加しました。

確認よろしくお願いします 🙇

**Comment by cm-wada-yusuke** [comment]
@yellowsman 現状をご連絡します。

いまのところ、２点課題がありそうです。

1. レンダリングに失敗する => mermaid のパースロジックが、`EOF`で終了することを想定していないようでした。[ISSUEで報告しているので](https://github.com/mermaid-js/mermaid/issues/2871)解消を待ちつつ、Zenn側でやるとしたらトリミング処理を修正して対応します。が、[Git graphは編集中にブラウザがハングしたり](https://github.com/mermaid-js/mermaid/issues/2648)と課題もあるようなので、[リファクタリングが検討されている](https://github.com/mermaid-js/mermaid/issues/1252)ようです
2. もしレンダリングできたとしても、Git graphには最大幅を調整するオプションがなく、画面サイズに対して見切れてしまう可能性があります

![image](https://user-images.githubusercontent.com/17589989/160787628-59de761b-c359-433e-9637-1f1bf41e9a63.png)

Git graph はサポートしないほうが幸せかもしれないと思いつつ、とはいえシンタックスエラーが出続けると体験がよくないのはそのとおりです。mermaid側の対応状況をもう少し様子見しZennとしての対応を決めたいと思います。

**Comment by uttk-dev** [comment]
@yellowsman 

ご連絡ありがとうございます。
こちらシンタックスエラーになる問題は解決しましたので、クローズさせて頂きます。

ただ、

>Git graphには最大幅を調整するオプションがなく、画面サイズに対して見切れてしまう問題

は、申し訳ありませんが良い解決方法が見当たらず、依然として解決していません。
そのため、使用する際はその点を注意して頂ければと思います。

よろしくお願いします。

**Comment by yellowsman** [comment]
@uttk-dev 
対応ありがとうございます！！！ 🙇 
最大幅についても承知いたしました。

1点確認させていただきたいのですが、issueにも書かせていただいた下記Zennの記事では現在も引き続きシンタックスエラーとして表示されているのですが、こちらの表示はキャッシュが消えるなどの時間経過で解消するものでしょうか？
https://zenn.dev/ito_shigeru/articles/39b41fede7d4e8#git-graph---exclamation-experimental

**Comment by uttk-dev** [comment]
@yellowsman 

>1点確認させていただきたいのですが、issueにも書かせていただいた下記Zennの記事では現在も引き続きシンタックスエラーとして表示されているのですが、こちらの表示はキャッシュが消えるなどの時間経過で解消するものでしょうか？

あ゛っ！すいません！！！！
キャッシュが残っている場合は、古い内容が表示される可能性があります！
また対応前に書かれたMarkdownについては、こちらでのMarkdownの再変換作業がまだ行われていないため、古い内容のまま表示されます！ですので、再変換( プレビューボタンを押す )などをして頂けると直ると思います！

再変換については時間が掛かるため、対応までに少し時間が空く可能性があります！
よろしくお願いします！

**Comment by yellowsman** [comment]
@uttk-dev 
確認ありがとうございます！
記事を一部修正して更新したところシンタックスエラーになっていたMarkdownが表示されました！
改めて対応ありがとうございました！
