### ISSUE TITLE
メッセージのアイコンを上揃え（最初の行と同じ位置）にしてほしい

### ISSUE THREAD

**Issue by mebiusbox** [zenn-dev/zenn-community#381]
## 提案・要望

メッセージのアイコンは現在中央揃えになっているので，メッセージ本文が数行になる場合にはアイコンがすぐに見れない場合があります．個人的に，このようなユーザーに対してメッセージを表すアイコンは上揃えがいいかなと思うのですが，いかがでしょうか．

次のように１行なら全く問題ありません．

![image](https://user-images.githubusercontent.com/19758056/156883013-519a5042-2618-4322-bb73-f3d067cbb9d1.png)

3行ならまだ何とか．

![image](https://user-images.githubusercontent.com/19758056/156883043-b21c402d-60ff-455b-8d1f-e34bdf2a41ca.png)

それ以上だと，なんか見た目的にもよろしくない感じがします．

![image](https://user-images.githubusercontent.com/19758056/156883115-7b0092a8-bd20-4910-909d-21bfdfb57deb.png)

ちなみにいうと，アイコンを絵文字で指定できるとなお良いです．思いつきなので優先度は低めです．
よろしくお願いします．

**Comment by catnose99** [comment]
ご報告ありがとうございます。

> このようなユーザーに対してメッセージを表すアイコンは上揃えがいいかなと思うのですが，いかがでしょうか．

こちら仰る通りですね。対応しますのでしばらくお待ちください。

**Comment by catnose99** [comment]
こちら本番環境で修正を行いました。zenn-cliは次のリリースで修正されます。

アイコンの絵文字指定については、表現が広がって良さそうだと思いつつも

- 記法が複雑になる 
- 一つの絵文字だけを許容するのが難しい
- 一部の環境でしか対応していない絵文字がある

等の理由から現状難しそうです。
このissueについては一旦クローズさせていただきます。
