### ISSUE TITLE
Zenn 専用の拡張 `published`

### ISSUE THREAD

**Issue by dmikurube** [zenn-dev/zenn-community#382]
## 提案・要望

Frontmatter に `published:` 属性がありますが、これより優先度が高く Zenn 専用に解釈される、たとえば `zenn_published:` のような属性があると嬉しいです。

## 背景

一つの GitHub リポジトリを Zenn 専用にせず、いくつかの書き物を一箇所の GitHub レポジトリにまとめての運用をしようとしています。 (たとえば自サイトの Jekyll / GitHub Pages でも使う、のような)

Zenn で Canonical URL を指定できるならクロスポストしてもいいのですが、現状の Zenn では実装されていません。 (#78)

記事ごとに「この記事は Zenn にポスト、この記事は自サイトに」のような切り替えをしたいのですが、この `published:` 属性は Zenn でも Jekyll でも両方で使われるため、片方で publish すると、もう片方でも publish されてしまい、クロスポストになってしまいます。

「Zenn では publish する / Jekyll では publish しない」は `_config.yml` で `exclude` する方法があるのですが、逆の「Zenn では publish しない / Jekyll では publish する」をする方法がありません。

そこで frontmatter に `published:` より優先的に解釈される `zenn_published:` のような属性があれば、後者も実現できると考えているのですが、いかがでしょうか?

## 関連

* #78 
* #183 (`published` の拡張、という点で)

**Comment by cm-igarashi-ryosuke** [comment]
@dmikurube ご提案ありがとうございます。背景を詳しく書いていただいてありがとうございます。良く分かりました。そうですね、、、確かにこのケースであればご提案の方法で上手くいきそうですが、基本的にFront Matterは各サービスで独自に決められたものであり、「一箇所で同じファイルで管理する」とすると、他にもいろいろな問題が出てくるのではないかと思います。

やるとしたらJekyllのように独自のconfigを持たせて、特定のファイルを無視したり、articlesディレクトリの代わりに他のパスを指定できたり、というのはありだと思うので、今後のGitHub連携の改善の中で検討していきたいと思います。
