### ISSUE TITLE
Firefoxにてスクラップでのチェックボックスの表示がおかしい

### ISSUE THREAD

**Issue by szne** [zenn-dev/zenn-community#383]
## 事象
初めてissueを立てます、不手際がありましたら申し訳ございません。
スクラップにてチェックボックスを作成すると、Firefoxにてチェックボックスの下にリストの点のようなものが表示されているのが確認できます。
safariで確認したところ、発生しなかったためブラウザによるバグだと思われます。

## 発生したページのURL
https://zenn.dev/szn/scraps/a691ec2962cc42

## 発生した画面のスクリーンショット
![スクリーンショット 2022-03-13 18 51 46](https://user-images.githubusercontent.com/84981684/158054113-7e69e3fb-f050-4d49-babf-d9fe7e910b69.png)

## 再現方法
スクラップに
```
- [ ] hogehoge
- [x] hogehoge
```
と入力し、Firefoxで閲覧

## 環境
- Device: [MacBook Air (13-inch, Early 2015)]
- OS: [Mac OS 12.2.1]
- Browser: [Firefox 98.0 (64 ビット)]

**Comment by catnose99** [comment]
ご報告ありがとうございます。こちらでも再現できました。
近日中に対応します。

**Comment by catnose99** [comment]
こちら修正をリリースしました。ご報告ありがとうございました。

**Comment by szne** [comment]
対応お疲れ様です！
