### ISSUE TITLE
PWAアプリケーション化

### ISSUE THREAD

**Issue by ichii731** [zenn-dev/zenn-community#384]
## 提案・要望
アプリとしてインストールできるPWAに対応していただけるとすごく助かります。

## 背景
毎回ブラウザ開いてzenn.devにアクセスして…のような動作をせずにアプリとしてアクセスしていと思ったため御提案させて頂きました。
ぜひご検討お願い致します。

## 関連
https://web.dev/pwa
（Issueでは無いですがdocsリンク）

**Comment by cm-igarashi-ryosuke** [comment]
@ichii731 ご提案ありがとうございます。

アクセスの手順を短くしたいということでしたら、以下の記事のようにZennのWebサイトのリンクをホーム画面に追加されてはいかがでしょうか？（わたしもこの方法を使っています！）
https://zenn.dev/waddy/articles/follow-timeline-in-smp

**Comment by ichii731** [comment]
確かによく考えればそちらでよかったですね
試してみます！

**Comment by cm-igarashi-ryosuke** [comment]
@ichii731 あらためてPWAを試してみたところ、モバイル環境ではリンクよりも使い勝手が良く、PC環境においてもメリットが大きいことに気づき、PWAに対応をいたしました！

https://info.zenn.dev/2024-10-02-pwa

ぜひご利用ください。

改めましてご提案いただきありがとうございました！
