### ISSUE TITLE
msgブロック内のコードブロックが一部はみ出している

### ISSUE THREAD

**Issue by sor4chi** [zenn-dev/zenn-community#385]
## 事象

msgブロック内に記載したコードブロックが一部コンテンツ枠内を超えて飛び出している

## 発生したページのURL

https://zenn.dev/satory074/articles/satory074_2021091401

## 発生した画面のスクリーンショット

![ScreenCapture 2022-03-24 0 37 24](https://user-images.githubusercontent.com/80559385/159738704-4e0607d4-0ec5-46ca-9647-0676ba6fd91d.png)

## 再現方法

https://zenn.dev/satory074/articles/satory074_2021091401
当該URLにアクセスし該当箇所へスクロール

## 環境

- Device: [Mac mini (M1, 2020)]
- OS: [macOS Monterey v12,3]
- Browser: [chrome 99.0.4844.83]

**Comment by tannerjohn65** [comment]
こちらご報告いただきありがとうございます。
情報提供いただいたURLから、事象を確認しました。確認させていただきます。

**Comment by uttk-dev** [comment]
@tannerjohn65 

ご報告ありがとうございます。

こちら、先ほど修正したバージョンをリリースしましたので、クローズさせて頂きます。
キャッシュが残っている場合、古い内容が表示されることがありますので、キャッシュを削除してからページを確認して頂けると直っていると思います。

よろしくお願いします。

**Comment by sor4chi** [comment]
> @sor4chi
> 
> 
> 
> ご報告ありがとうございます。
> 
> 
> 
> こちら、先ほど修正したバージョンをリリースしましたので、クローズさせて頂きます。
> 
> キャッシュが残っている場合、古い内容が表示されることがありますので、キャッシュを削除してからページを確認して頂けると直っていると思います。
> 
> 
> 
> よろしくお願いします。

迅速な対応ありがとうございました、PR内の開発チームの楽しそうな雰囲気に惚れました🕶🤝

今後ともよろしくお願いします🙇‍♂️
