### ISSUE TITLE
有料の本もバッジを送れるようにしてほしい

### ISSUE THREAD

**Issue by kurowassan1212** [zenn-dev/zenn-community#387]
## 提案・要望
有料の本もバッジを送れるようにして頂けたら嬉しいです。

## 背景
単純に疑問なのですが、有料の本はなぜバッジが送れない仕様になっているのでしょうか？個人的には有料の本でバッジが送れても困る人は誰もおらずWinWinのような気がしますが...どうでしょうか??

**Comment by cm-wada-yusuke** [comment]
要望ありがとうございます、そうですね、当初、「購入もできてサポートもできたら混乱するかも？」という懸念があったのですが、「購入した人だけがおかわりバッジを送れる」というようにするとその心配もなさそうです。チームで検討します！

**Comment by catnose99** [comment]
こちら有料の本に対しては購入済みのユーザーであればバッジを贈ることができるように変更しました。

**Comment by kurowassan1212** [comment]
早速ご対応頂きありがとうございます！感謝します！😀😀
