### ISSUE TITLE
スクラップで"JSONで内容を出力"を実行した場合、コードブロック内の連続する半角空白が無視される

### ISSUE THREAD

**Issue by nikogoli** [zenn-dev/zenn-community#389]
## 事象
bug というか markdown の仕様の影響のように感じますが、ユーザーの意図とは異なる結果が得られるので bug として報告します

コードブロックを含むスクラップにおいて"JSONで内容を出力"を実行した場合、出力結果の JSON の "body_markdown" に含まれるコードブロックのインデントが、スクラップのものと一致しません。

厳密には 、スクラップにおいて"JSONで内容を出力"を実行した場合、
- コードブロックにおける『2つ以上連続する半角空白の塊』が、全て『半角空白1つ』に置き換えられる
- それにより、あらゆる(半角空白を用いた)インデントも、全て『半角空白1つ』になる
- その結果、2段以上インデントしていた部分も、全て1段インデントの部分と同じ状態になる

ということが起こります。
また、別の変化として、「引用符 `"` の前に `\` が追加される」ということも起こります

## 発生したページのURL
https://zenn.dev/nikogoli/scraps/acf3d80d6aca51

## 発生した画面のスクリーンショット
![20220412010824](https://user-images.githubusercontent.com/49331838/162783888-ce7c8869-0321-40b3-9566-f0a7299d2371.png)

　　↓
```
{ "title": "json化テスト", "closed": false, "archived": false, "created_at": "2022-04-12", "comments": [ { "author": "nikogoli", "created_at": "2022-04-12", "body_markdown": "```\nfunction indented (){\n if (true){\n if (true){\n if (true){\n console.log(\"this is pen\")\n //\n }\n }\n }\n}\n```", "body_updated_at": "2022-04-12" } ] }
```
https://zenn.dev/api/scraps/acf3d80d6aca51/blob.json のスクリーンショット

![20220412012451](https://user-images.githubusercontent.com/49331838/162786441-0518ac9d-dad9-4738-8eb4-4d32fce5c0d7.png)

コードブロックを復元すると以下のようになります
```
function indented (){
 if (true){
 if (true){
 if (true){
 console.log(\"this is pen\")
 //
 }
 }
 }
}
```

- 1段インデントした `if (true)` の前の半角空白が2つから1つに減っている
- 2段 / 3段インデントした`if (true)` の前に半角空白が1つしかない
- console.log 内の空白部分が縮められて `"this is pen"` になっている
- 引用符 " の前に \ が追加されている

## 再現方法
コードブロック内に連続した半角空白がある場合は常に発生すると思います
diff や 言語指定、ファイル名の有無は影響しませんでした

- Browser: chrome 100.0.4896.75（Official Build） （64 ビット）

**Comment by cm-wada-yusuke** [comment]
@nikogoli こちら、Contet-Type を指定する必要がありました。チームメンバーが修正してくれましたので、ご確認ください。わたしが試す限りは、意図どおりに修正されていそうです。
