### ISSUE TITLE
タイトルの60文字制限がもう少し緩和されるとありがたいです

### ISSUE THREAD

**Issue by terrierscript** [zenn-dev/zenn-community#39]
他サイト等からインポートを試みようとした際、60文字の制限というのが少々厳しく感じます。
スパムの対応考慮・デザイン面の都合等もあるかと思いますが、もう少し長いとありがたく感じます。

**Comment by catnose99** [comment]
なるほど
たしかにちょっと短すぎるかも…？
検討します。

**Comment by catnose99** [comment]
以下の両方を変更する
- クライアントのバリデーション
- サーバーのバリデーション

**Comment by terrierscript** [comment]
私の所持しているしている記事ですと下記のようなものがありました。

> styled-componentsでいい感じにresponsive用のmedia queryを扱いたいときのちょっとしたHoCs (64)
> redux-observableで作ったintervalのobservableをHot Module Replacementで止まるようにする (72)

おそらくですが英数字の名詞を含むと膨れてしまうのではないかと思います。少々ルールが複雑かもしれませんが、半角120文字のようなルールであれば解消出来るかもしれません

あまりちゃんと検証してないのですが、下記のような判定が使えるかもしれません
`[..."abcあ😀"].reduce( (count,char) => count + Math.min(new Blob([char]).size,2) , 0)`

参考： https://stackoverflow.com/questions/5515869/string-length-in-bytes-in-javascript

**Comment by catnose99** [comment]
おぉ！ありがたいです！🙏
こちら参考にさせていただきます。

**Comment by terrierscript** [comment]
あくまで簡易版で[半角カナ等が考慮から漏れている](https://zenn.dev/terrierscript/articles/2020-09-19-multibyte-count#comment-d7b59b2ddf0025bbacd3)という指摘もあったので、参考程度にしていただければと思います

**Comment by catnose99** [comment]
半角カナなら無視できる範疇かもですね
ありがとうございます

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、影響箇所が多く実装コストに見合わないため対応しないこととなりました。
