### ISSUE TITLE
本に栞の機能がほしい

### ISSUE THREAD

**Issue by fuu38** [zenn-dev/zenn-community#390]
## 提案・要望
本のリーダーに、
- 前回読み終わった場所を自動で開く
- 任意の章へのショートカットを作成する  

などの、しおりのような機能があると嬉しいです。
## 背景
どこまで読んだか分からなくなることがあるので、このような機能があると助かります。

**Comment by tannerjohn65** [comment]
こちらご意見いただきありがとうございます。　他の機能追加含めてチームで検討させていただきます！！！

**Comment by cm-wada-yusuke** [comment]
@fuu38 

> 前回読み終わった場所を自動で開く
これは、わたしもほしいです！

> 任意の章へのショートカットを作成する
これは、わたしはブラウザの「あとでよむ」機能を使っています。
Zenn側で提供されているとうれしいな〜と感じるポイントってなにかありますか？

**Comment by fuu38** [comment]
> わたしはブラウザの「あとでよむ」機能を使っています。

この機能を初めて知りました！
たしかにこの機能を使えば良さそうですね😊ありがとうございます🙇

**Comment by uttk-dev** [comment]
@fuu38 

提案ありがとうございます。
この度、本の閲覧履歴を自動で保存する機能をリリースしましたので、こちらの issue をクローズさせてもらいたいと思います。

使用方法については、以下のツイートをご参照ください。

https://twitter.com/zenn_dev/status/1541687828672700416

よろしくお願いします。

**Comment by fuu38** [comment]
実装ありがとうございます！🥳🙏
