### ISSUE TITLE
GitHub のコード埋め込みのシンタックスハイライトが壊れています

### ISSUE THREAD

**Issue by odanado** [zenn-dev/zenn-community#391]
## 事象

GitHub のコード埋め込みのシンタックスハイライトが壊れています

bash のコードを埋め込んでいますが、`/*` がコメント扱いされています
おそらく C/C++ 系の言語としてシンタックスハイライトされているように見えます

## 発生したページのURL

https://zenn.dev/odan/articles/17a86574b724c9

## 発生した画面のスクリーンショット

<img width="725" alt=" 2022-04-25 18 01 04" src="https://user-images.githubusercontent.com/6040962/165056637-beba2d85-1a47-414c-b4ef-09489591d525.png">

## 再現方法

↑の記事にアクセス

## 環境

- Device: MacBook Pro  (Apple M1 Pro)
- OS: macOS Monterey
- Browser: Chrome 100.0.4896.127

**Comment by cm-wada-yusuke** [comment]
@odanado ありがとうございます。こちら確認します。

**Comment by SnowCait** [comment]
YAML でも同様でした。

**Comment by uttk-dev** [comment]
@SnowCait @odanado 

バグ報告ありがとうございます。
こちらのバグ、修正しましたのでクローズしたいと思います。

ブラウザキャッシュが残っている場合、古いページが表示されることがありますので、その際はキャッシュを削除してからご確認して頂けると直ると思います。

よろしくお願いします！
