### ISSUE TITLE
記事のtypeに多様性があれば執筆の幅が広がります。

### ISSUE THREAD

**Issue by MasaruKitajima** [zenn-dev/zenn-community#392]
## 提案・要望
記事の`type`にバリエーションを増やして欲しい

## 背景
実例ですが、私が現在数名の方に依頼されている記事があります。

- そもそも**デジタル**とは何か？
- オブジェクト指向言同士で、なぜこんなに差異が多いのか？
  - この記事で記述予定なのは
    - アラン・ケイによる`Smalltalk`の概説
    - オブジェクト指向は`Smalltalk`の為の造語である
    - ビャーネの`C++`による再定義
    - を概説した後に、実は現在オブジェクト指向言語と言われているものは二つの異なる定義によるオブジェクト指向の影響を受けているが影響度は言語によって異なる事、オブジェクト指向だけではなく他のパラダイムも採用している為である事を概説する予定

上記の様な記事は_tech_よりも_thoughts_や_fundamental_に近いが、_ idea_ではあり得ない

ただしZennの方針として

> 基本的（または原則的）に新しい技術動向に関する知見が必要であり、IT産業の短い歴史の中で何度となく繰り返されたパラダイムシフトや情報理論・ソフトウェア工学などを執筆する場としては提供していない。

と言う事でしたら、執筆媒体を変更しますので本_issue_にその旨をコメントして_close_されて結構です。

**Comment by cm-wada-yusuke** [comment]
@MasaruKitajima 

ご提案ありがとうございます。同様の要望を過去もらったことがありますが、こちらの分類はあくまで「読者が内容を判別しやすいための仕組み」です。そのため、パット見たときにおおよそどちらかに分類されるかを重視していただければと思います。

> 情報理論・ソフトウェア工学などを執筆する場としては提供していない

Zennとしては執筆を歓迎しております。実際、以下のような記事が掲載されてます。

[情報工学を学んだことによる変化](https://zenn.dev/manamin0521/articles/07d9b63e277a4c)
[学習メモ：ゲーム理論の入門](https://zenn.dev/uniker9/articles/intro-to-game-theory)
[モデルベース要件定義テクニック・RDRA2\.0 ハンドブック \- 読書感想文](https://zenn.dev/worbridg/articles/80127fa76d0684)
[2021年の「オブジェクト指向」を考える](https://zenn.dev/takahashim/articles/d34b1a3b244e46)

このような内容は皆様、「idea」を選んでらっしゃるようです。

こちらもご参照ください。

[投稿カテゴリーの選び方](https://zenn.dev/tech-or-idea)

**Comment by MasaruKitajima** [comment]
ご返信をありがとうございます。
仰る通り以前も同じリクエストを出しています。
[投稿カテゴリーの選び方](https://zenn.dev/tech-or-idea)
は確認していますが、情報理論・ソフトウェア工学などはどちらの分類にも属さないと言うのが、大学で教鞭を執った者としての見解です。

- **_idea_**
  - プログラミングやソフトフェア、ハードウェア、インフラなどの技術に関する記事ならTechを選びます。
- **_idea_**
  - キャリアやマネジメントなど技術に直接関係しないトピックや、リンクを並べたまとめ記事などにはIdeaを選びます。
 
つまり技術(Applied technologies)の基礎(Fundamentals)となる学問(Science)は、上のどちらにも属しません。確かに_idea_の

> 技術に直接関係しないトピック

だけを抽出すると該当しますが、前置されている

> キャリアやマネジメントなど

や、後置されている

> リンクを並べたまとめ記事など

を見ると、やはり分類としては不適切だと考えます。そもそも私が記述したい内容や、例示頂いた方の投稿は[idea](https://www.merriam-webster.com/dictionary/idea)と言う単語の意味に照らすとご理解頂けるかと思います。

情報理論・ソフトウェア工学などは[fundamental](https://www.merriam-webster.com/dictionary/fundamental)になりますし、それらに基づく経験や知見は[knowledge](https://www.merriam-webster.com/dictionary/knowledge)になります。

例示頂いた[情報工学を学んだことによる変化](https://zenn.dev/manamin0521/articles/07d9b63e277a4c)は、個人的意見ですので_idea_でも良いでしょうが、情報理論・ソフトウェア工学は**確立された理論体系**であって**個人的見解**ではない、と言う点が大きく異なります。

メディア論やコミュニケーション論を元にお話しすると、個人（によらず一次ソース以外の全て）の情報には何らかの偏向が意識的・無意識的を問わず必ず加わります。

- [情報工学を学んだことによる変化](https://zenn.dev/manamin0521/articles/07d9b63e277a4c)
- [2021年の「オブジェクト指向」を考える](https://zenn.dev/takahashim/articles/d34b1a3b244e46)

を読むと、筆者の**個人の知見・経験・思想**が含まれているのがお判り頂けるかと思いますが、これらが**偏向**です。筆者と同等の**知見・経験**があり**思想**にも**納得できる・同意できる・認めても良い**と言う方にしか理解できないものです。

_tech_も同様の事が言えますが、これらの**個人的知識や経験**に基づかない**学問**としての投稿が可能な場が無いと考えます。

ですので、今回のご質問をさせて頂いた内容については執筆はしない予定です。これは矜持の問題かも知れませんが_tech_と_idea_の定義を見る限り、どちらにも属さないと言う判断をせざるを得ないからです。

今更ですがZennが場を提供してくださる事には改めて謝意を表明したいと思います。。[note](https://note.com/)が何でもあり、な中にあってITに特化した場である事には深く感謝します。ですからZennの方針には従います。

色々と書いて参りましたのは、あくまでも古参エンジニアとして、また大学の非常勤講師としての経験に基づく提言だとご理解頂ければ幸いです。

今後Zennがより若手エンジニアにとって多くの知見が得られる場となる事を希望しています。

長文、失礼致しました。

**Comment by cm-wada-yusuke** [comment]
@MasaruKitajima 

返信ありがとうございます。

> 色々と書いて参りましたのは、あくまでも古参エンジニアとして、また大学の非常勤講師としての経験に基づく提言だとご理解頂ければ幸いです。

はい、丁寧に解説いただきありがとうございます。私も大学教育で情報工学を学んだ者として、現状提供している `tech` と `idea` が十分に網羅できる分類ではいことは承知しています。なかでも academic な記事を書こうとしたときに適切な分類が悩ましいというご指摘はもっともです。

ここからはチームで相談した話ではなく、完全に私個人の意見です。

ご指摘は理解した上で、**まだ**新しいtypeは追加できない、というのが結論です。プラットフォームとして、順番としては まず `tech` にも `idea` にも分類できないacademicな記事がたくさん発生したときに、はじめて、じゃあそれらの分類のために新しいtypeを作りたいよね、という流れを踏みたいと思っています。

typeを新しく作ります。でも、まだ記事は数記事しかありません。という状況だと、読者が「`fundamental`にはどれだけたくさんの面白そうな記事があるんだろう！」と期待してページにアクセスしたとき、数記事しか表示されないのは体験として避けたいものです。

「あったほうがいい」という考えのもと色々な機能は実装できますが、その分、副作用があります。常に主作用と副作用のトレードオフを考えたいと思っています。

---

今回は執筆しないとのことで承知しました。プラットフォームとしては、たとえ適切な分類なtypeがない、そんな状況でも「アカデミックな記事はZennで書こうかな？」「論文の下書きをスクラップにまとめようかな」といって使ってもらえるよう、努力して参ります。貴重なご意見ありがとうございました。
