### ISSUE TITLE
new:article を実行した時に images/ にも 同名の slug ディレクトリができて欲しい

### ISSUE THREAD

**Issue by hayata-yamamoto** [zenn-dev/zenn-community#393]
## 提案・要望

タイトル通りですが、要望が二つほどあります。

1. `new:article --slug <slug-name>` を実行した際に、 `images/<slug-name>` のディレクトリができるようにして欲しい
    - book の方は当方にはニーズがないのですが、他の方は欲しているかもしれません
3. 記事中の画像呼び出しは、 `/images/<slug-name>/sample.png` ではなく、同一 Slug ディレクトリ内の画像を直接指定できるようにして欲しい。
    - 例） `[画像](/images/sample-directory/sample.png)` → `[画像](sample.png)`

## 背景

読者への分かりやすさを考え、記事の中に画像を多数入れるような書き方をしていると、`images/` に多数の画像を置くことになってしまい、画像の管理に困っています。

現在は、執筆者思い思いのディレクトリを切って、 `/images/<directory-name>/xxx.png` のように宣言しています。個人で、執筆するのにはこれでも十分なのですが、複数人で運営するタイプのアカウント（企業アカウントや公式アカウント）を管理する際には、別途規約を決めるなどをしないと「誰がどんな画像をどこに置いたのか」が分かりにくくなってしまっています。

`new:article` した記事で使う画像は 同一の slug ディレクトリから呼び出す方が、執筆しやすいとなれば執筆者に `images/<slug-name>` 配下に画像を置くことをお願いしやすいため助かります。

## 関連

探しましたが見つけられませんでした

**Comment by tannerjohn65** [comment]
お世話になっております。本件、ご意見いただきありがとうございます。
上記の内容についてですが、他のタスクや現状の仕様への影響範囲が広いことなどから、ご要望として受け取り今後検討させていただきます！

現状については、ファイル名を、**<slug-name>_xxx.png** の表記にするなど、運用でカバーいただけますと幸いです。
引き続き、何卒よろしくお願いいたします。

**Comment by hayata-yamamoto** [comment]
ありがとうございます！
