### ISSUE TITLE
GitHubのコードリンクの展開が機能しない場合がある

### ISSUE THREAD

**Issue by kawamataryo** [zenn-dev/zenn-community#394]
## 事象

いつもワクワクする素晴らしい機能の提供をありがとうございます！！

GitHubのコードリンクの展開が機能しないURLがあったので共有です。

## 発生したページのURL

まだ下書きの記事なので、githubリポジトリのリンクです🙏

https://github.com/kawamataryo/zenn-articles/blob/57382d09c4bb7afa3dce9c04743e7657b6488767/articles/suppress-ts-errors.md#L120

## 発生した画面のスクリーンショット

元のテキスト

```
Vitest は[Vite](https://ja.vitejs.dev/)以外のプロジェクトでなくても、単体で使うことができます。

以下実際のテストコードです。Jest 同様 Parameterize なテストも書けるので、効率的にパターンを網羅することができました。
TypeScript の設定等も不要で即利用できる点、高速に動作する点がとても良かったです。

https://github.com/kawamataryo/suppress-ts-errors/blob/main/src/lib/__tests__/suppressTsErrors.test.ts#L5-L182

# おわりに
```

結果

![image](https://user-images.githubusercontent.com/11070996/167049729-6ca2572d-0fdc-48e4-8f15-214e6344273b.png)

## 再現方法

URL中に`__<hogehoge>__`があると機能しない？（確証は持てていません）

## 環境

- Browser: Version 100.0.4896.127 (Official Build) (arm64)

**Comment by catnose99** [comment]
@kawamataryo 
ご報告ありがとうございます。
こちらはzennで利用しているmarkdownパーサ markdown-it の仕様でして、パーサを置き換えない限り根本的な解決が難しそうです。

- ref: #221

ご指摘の通り`__<hogehoge>__`があるとURLとして認識される以前に強調記法だと捉えられてしまうという問題です。
お手数をおかけしますが、
```
https://github.com/kawamataryo/suppress-ts-errors/blob/main/src/lib/%5F%5Ftests%5F%5F/suppressTsErrors.test.ts#L5-L182
```
のようにアンダースコア（`_`）をエンコードする（`%5F`に置き換える）ことでリンクとして正しく認識されるようになると思います。

お手数をおかけしますがよろしくお願いします。

**Comment by kawamataryo** [comment]
@catnose99 

早速返信ありがとうございます！！
詳細把握しました

対応方法の案内とても助かります🙏
そちらで対応します！

**Comment by catnose99** [comment]
ご理解いただきありがとうございます！
よろしくお願いします！
