### ISSUE TITLE
detailsやmessageのネスト機能

### ISSUE THREAD

**Issue by LumaKernel** [zenn-dev/zenn-community#395]
## 提案・要望

```
:::details 折りたたみ
  :::message
  こんにちは
  :::
  
  :::message
  さようなら
  :::
:::
```

![image](https://user-images.githubusercontent.com/29811106/167057742-ce8f3d74-96d1-4d23-851d-756a5b603fc5.png)

## 関連

もし remark-admonitions を利用していれば、以下のPRを取り込んだものをzenn側で管理していただくなどしていただければ実現できるかと思います。
https://github.com/elviswolcott/remark-admonitions/pull/42

もしくはこのPR作成者さんが `@lebalz/remark-admonitions` という名前で公開しています。

- GitHub: https://github.com/lebalz/remark-admonitions
- npm: https://www.npmjs.com/package/@lebalz/remark-admonitions

**Comment by cm-igarashi-ryosuke** [comment]
@LumaKernel ご報告ありがとうございます。こちらzennではmarkdown-itを使っておりまして、その仕様上、外側の `:` の数を、内側の `:` の数より多くすることでネストさせることができます。

```
:::: details 折りたたみ  
  ::: message
  こんにちは
  :::

  ::: message
  さようなら
  :::
::::
```

![image](https://user-images.githubusercontent.com/13619209/167752291-7ae88e91-f07b-48ee-a29e-aa7ca6892a69.png)

[マニュアルページ](https://zenn.dev/zenn/articles/markdown-guide#zenn-%E7%8B%AC%E8%87%AA%E3%81%AE%E8%A8%98%E6%B3%95)にも記載を追加しておきます。

**Comment by cm-igarashi-ryosuke** [comment]
@LumaKernel ご報告ありがとうございます。zennではmarkdown-itを使っておりまして、その仕様上、外側のコロンの数を、内側のコロンの数より多くすることでネストさせることができます。

```
:::: details 折りたたみ  
  ::: message
  こんにちは
  :::

  ::: message
  さようなら
  :::
::::
```

![image](https://user-images.githubusercontent.com/13619209/167752955-7dc7b57c-5a87-47fb-aa85-e28e7b67897b.png)


参考: https://github.com/markdown-it/markdown-it-container/issues/33

[マニュアルページ](https://zenn.dev/zenn/articles/markdown-guide#zenn-%E7%8B%AC%E8%87%AA%E3%81%AE%E8%A8%98%E6%B3%95)にも記載を追加しておきます。
