### ISSUE TITLE
本の有料ページをチラ見できる機能の提案

### ISSUE THREAD

**Issue by kurowassan1212** [zenn-dev/zenn-community#396]
## 提案・要望
有料本の限定ページをチラ見できる機能があれば、ユーザーも本の概要を把握しやすくなり買いやすくなるんじゃないかな？と思っていたので今回提案させて頂きました。

## 背景
有料本を販売しているのですが、現在の有料ページだと未購入のユーザーは本の内容をタイトルのみでしか判断できません↓
![2022-05-09_12h49_37](https://user-images.githubusercontent.com/50498401/167337474-e89959b8-4747-408a-be01-78e1100be1d1.jpg)
それが良いか悪いかはわかりませんが、本の有料ページもチラ見できるとユーザーも本の大体の概要を知る事ができ購買意欲につながるのではないか？と考えています。「本のページのチラ見」というのは以下のように最初の目次一覧などが見れたり、記事の一部が表示されている状態の事です。
<img width="942" alt="2022-05-09_12h39_08dwadwa" src="https://user-images.githubusercontent.com/50498401/167336794-edd44f53-fa83-45b3-891b-8d055ecca0d4.png">
お伝えさせて頂きました。いつもお世話になっております。

**Comment by tannerjohn65** [comment]
こちらご提案いただきありがとうございます！
本の有料ページの部分的な無料提供についてですが、GitHub連携の際に仕様上難しいことや部分公開をデフォルトとした場合、既に公開されている本の著者の方が想定されている公開範囲との相違が発生する可能性があることから、実現することが難しいです。。

代替案といたしまして、本の[チャプターごとに無料公開](https://zenn.dev/zenn/books/how-to-create-book/viewer/free-chapter)することができる機能があるため、そちらの利用を検討いただけますと幸いです。

引き続き、よろしくお願いいたします。

**Comment by kurowassan1212** [comment]
なるほど、わざわざご返答頂きありがとうございました！これからもよろしくお願いいたします。

**Comment by daichi-takezawa** [comment]
再三すいません🙏🏻やっぱりこの機能の実装難しいでしょうか？

Zennで本を書いて有料販売していますが、この機能があれば確実に売り上げが伸びると個人的に確信しております。Zennの売り上げにも繋がると思うので再度検討して頂ければ嬉しいのですが...
やはり難しいようであればこの機能の要望は諦めます🙇🏻‍♂️

**Comment by daichi-takezawa** [comment]
再三すいません🙏🏻やっぱりこの有料ページのチラ見機能の実装難しいでしょうか？

Zennで本を書いて有料販売していますが、この機能があれば確実に売り上げが伸びると個人的に確信しております。Zennの売り上げにも繋がると思うので再度検討して頂ければ嬉しいのですが...

私が想像しているイメージと近いサイトがあったのでリンクと画像を貼っておきます↓
https://subscription.packtpub.com/book/game-development/9781784397777/1
![2022-12-22_02h02_11](https://user-images.githubusercontent.com/50498401/208962465-e92efbf6-0db6-4896-b739-fd4eb7c27d34.jpg)
このサイトの本ではZennの有料本のように無料ページと有料ページがあり、有料ページはチラ見できるようになっています。現時点ではZennの有料ページの内容は一切わからない状態なので、やはりユーザーとしては無料ページで品質を確認できても不安は残るかなと思っています。ただ、こういったチラ見できる機能があればユーザーとしても安心して購入しやすい環境になるかなと思っています。

やはり検討した上で難しいようであればこの機能の要望は諦めます🙇🏻‍♂️よろしくお願いします。
