### ISSUE TITLE
記事間のリンクを作成し zenn cli で確認する方法

### ISSUE THREAD

**Issue by hnakayam** [zenn-dev/zenn-community#397]
## 提案・要望

記事間のリンクを作成し zenn cli で確認する方法を希望します。
詳しくは以下の背景を参照ください。

## 背景

zenn cli で執筆中に自分の複数記事間のリンクを設定したいと考えました。
画像ファイルを参照する場合には 画像ファイルを共通の/images ディレクトリに保存し、/images/xxxx.png のような形で参照可能です。
そこで別記事を参照するために /articles/xxxx のようなリンク (.mdは省略)で目的の別ページに飛ぶことができました。
ところがこのように作成したリンクは published: trueに設定し公開すると、意図通り別ページに飛べません。
あたりまえですが<ユーザー名>が必要でした。つまり /<user名>/articles/xxxx と変更することで公開後でも飛べるようになりましたが、逆にpreview環境では飛べなくなりました。

つまり、記事間のリンクを表す新記法を考案し実装するか、あるいは単にzenn cli でリンク先が /<user名>/articles/xxxx のように見える形式であったときに 「/<user名>」のパスを無視できればよいだけの気もします。明示的に別ユーザーの記事をサポートしたい場合には形式的なユーザー名("self"的な)を導入する考えもあるかもしれません。
他に正しい、あるいは想定されたリンク作成方法があればお知らせください。

これに関連して(すでにお気づきかもしれませんが) "articles" "books" "images"のようなユーザー名を作成できないようにしておくのが良いかもしれません。

**Comment by cm-wada-yusuke** [comment]
@hnakayam 
ご提案ありがとうございます。画像と同じように、ご自身の記事のリンクを相対リンクで設定したいということですね。
現在Zennには相対リンクを解釈する機能はなく、おそらく将来的にも導入は難しい可能性が高いです。貼られた相対リンクに対して、Zennのリンクかどうかを判定するのは難しく、コストも高くつくためです。お手数ですが他のリンクと同様、完全なURLを取得してから貼っていただく運用としていただけると助かります。

自分の記事間専用のリンクを貼る記法も方法としてはありですが、独自記法が増えるとその分ポータビリティ（Zenn以外でも展開できる要素が減ってしまう）点、独自記法を覚える手間vs完全なURLを貼っていただく手間でどの程度使われるか未知数、という点から手が出しにくい事情もあります。

ご期待に添えず申し訳ありません。

**Comment by hnakayam** [comment]
なるほど、公開済みのarticlesであればfull URLで指定するというのも可能ですね。
実は複数ページをpreview環境で作成し複数人でレビューした後に公開する、という運用を考えていて、毎回 ページ間リンクが飛べないという指摘が出るので何とかならないかと思ったところでした。
