### ISSUE TITLE
本を別アカウントに移行したい

### ISSUE THREAD

**Issue by kboy-silvergym** [zenn-dev/zenn-community#398]
いつもZennを好んで使わせてもらってます！kboyです。

## 提案・要望

zennで作成した本２冊を別アカウントに紐付け変更できたらいいなと思っています。

具体的には、以下の２冊の本を、[kboy](https://zenn.dev/kboy) から [flutteruniv](https://zenn.dev/flutteruniv) へ紐付け変更したいです。

https://zenn.dev/kboy/books/ca6a9c93fd23f3
https://zenn.dev/kboy/books/a5b8b502dcdac4

以上です。できたら嬉しいな。。という温度感です。

**Comment by cm-igarashi-ryosuke** [comment]
@kboy-silvergym いつもご利用いただきありがとうございます。ユーザー間の紐付け変更は、以下のような観点から厳しいです。

- URLが変わってしまうので、リダイレクトの仕組みを入れるなどを検討する必要がある。
- 既に売上（購入・サポート）が発生している場合、過去にさかのぼってユーザーの収益を変更する必要がある。
- 悪用されると売上の横取りをされる可能性があり、十分なセキュリティを講じる必要がある。

クローズさせていただきます 🙇
