### ISSUE TITLE
BOM付きUTF8対応?

### ISSUE THREAD

**Issue by hnakayam** [zenn-dev/zenn-community#400]
## 提案・要望
zenn-cliで展開する記事でBOM付きUTF8に対応してもらうと助かります。

## 背景
git と zenn-cli を利用して記事の管理を行っており、現状非常に満足しています。
作成した記事を開くときにいちいちエンコーディングを設定するのが面倒だったので、今回BOM付きUTF8で保存してみました。すると記事を公開したときに「デプロイ中断 articles/XXXXXX.md のFrontMatterが見つかりませんでした」とエラーになりました。
試しにBOMなしUTF8に戻すと問題なく公開されました。

## 関連
なし

**Comment by cm-wada-yusuke** [comment]
@hnakayam zenn-cli をご利用いただきありがとうございます。

- 記事を編集するためのエディタは何を利用していますか？サクラエディタでしょうか？
- ファイルを常にBOM付きで保存しなければならない事情があるでしょうか？エディタのデフォルト設定でBOMなしUTF8にすることは難しいですか？

以上、ご確認お願いいたします。

**Comment by hnakayam** [comment]
エディタはVisual Studio Codeを (Windows上で)利用しています。Windows上なのでデフォルトはANSI (日本ではShftJIS)になります。

実はいまWindows上でも伝統的なShiftJISのコード系からUTF8へのコード系に移行している最中です。そのため、明示的にUTF8を示すためにBOM付きでUTF8保存するケースが増えています(BOM無であればとりあえずANSI-ShiftJisとみなす等)。

例えばVisual Studio 2019でもC＋＋ソースコードをBOM付きUTF8で保存することが可能で、問題なく編集/ビルド/実行可能です。

**Comment by cm-wada-yusuke** [comment]
@hnakayam 詳細にありがとうございます。Visual Studio Code はWindows OSでもデフォルトでUTF8を使うそうなので、hnakayam さんの設定でShift-JISになさっているということですね。

対応を検討しますが、この先BOMナシのドキュメントがどの程度生き残るか、困っている人がどのくらいいるか調査させてください。BOMを弾くだけではあるのですが、記事本文のmarkdownファイルの他にも、本のための設定yamlファイルなど考慮するファイルがあります。今後機能を拡充していく上で、常にBOMを考慮するかどうかも検討したいポイントです。

お手数ですが、しばらくの間、

- Zennの記事は Visual Studio Code で専用のワークスペースとして開いていただき、ワークスペースの設定で BOMなしUTF8 を扱うようにする

として対処いただけると幸いです。設定方法は[こちら](https://www.javadrive.jp/vscode/setting/index4.html)を参照ください。
