### ISSUE TITLE
スクラップのGitHub連携

### ISSUE THREAD

**Issue by y-temp4** [zenn-dev/zenn-community#402]
## 提案・要望
記事と同じようにスクラップをGitHub連携し、GitHubを使ってコンテンツの管理ができるようにしても良いかな、と思いました。

## 背景
Zennの記事と同じように、書いたスクラップが自分のコンテンツとして管理できると安心があるなぁと思いました。

## 関連
なし

**Comment by tannerjohn65** [comment]
こちらご意見いただきありがとうございます！
Scrapsは個人の学習メモや備忘的な役割として気軽に使ってもらい、蓄積された学習メモをArticle/BookにまとめていただきたいということもありGitHub連携への対応は行っていません。
今後、同様の要望が増えた場合は検討する可能性もありますが、現状としては他の機能追加を優先させてください！

引き続き、よろしくお願いいたします！

**Comment by y-temp4** [comment]
承知しました！ご確認いただき、ありがとうございます😄

**Comment by tannerjohn65** [comment]
再度検討する際に、起票するためこちらはCloseさせていただきます。
引き続き、よろしくお願いいたします！

**Comment by Kubota-Yoshiharu** [comment]
> Scrapsは個人の学習メモや備忘的な役割として気軽に使ってもらい、
> 蓄積された学習メモをArticle/BookにまとめていただきたいということもありGitHub連携への対応は行っていません。

スクラップをGitHub連携する機能を追加頂けると、
学習メモや備忘録をローカルから任意のエディタで編集し随時反映させるということができるようになり嬉しいので、
再度ご検討頂けると幸いです。
この機能はArticle/Bookとは相反しないと考えております。

**Comment by noraworld** [comment]
こちら、すでにクローズされてからしばらく経過していますが、改めてご検討いただけますと幸いです。Zenn の Article 機能は積極的に活用させていただいておりますが、Scrap は一度も使用したことはありません。

その理由は、**GitHub との連携ができないというただ一点だけ** です。連携できれば間違いなく活用したい機能ですので、どうかもう一度ご検討いただけますと大変ありがたいです。どうぞよろしくお願いいたします 🙏
