### ISSUE TITLE
記事画面でmdのDOM挿入時に画像表示が失敗している箇所を発見

### ISSUE THREAD

**Issue by sor4chi** [zenn-dev/zenn-community#404]
## 事象

記事を閲覧中、画像表示に失敗しhtmlのimgタグが剥き出しになっている箇所を発見しました。
連携元のgithubリポジトリでは正しくレンダリングされていたのでバグだと思い報告しました。

## 発生したページのURL

https://zenn.dev/noouchi4/articles/01b1695854e0ac37bc0b

## 発生した画面のスクリーンショット

![image](https://user-images.githubusercontent.com/80559385/174480779-1899bbac-7245-449f-9637-b08cb7e88f58.png)

## 再現方法

上記URLにアクセス

## 環境

iPhone12、safari、iOS15.4.1

**Comment by cm-igarashi-ryosuke** [comment]
@sor4chi ご報告ありがとうございます。

記事本文のmarkdownを確認しましたところ、imgタグが使われておりました。
https://github.com/NaokiOouchi/articles/blob/master/articles/01b1695854e0ac37bc0b.md?plain=1#L209-L227

zenn.dev ではimgタグをサポートしていないため、文字列としてそのまま表示されております。

不具合ではありませんので、クローズさせていただきます。
