### ISSUE TITLE
月次の自動出金できるようにしてほしい

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-community#405]
## 提案・要望

書籍の出金を、月末などに自動で行なってほしい。

## 背景

現状、書籍の売上の出金が手動なので、自分で忘れないように気にしつつ実施する必要があります。
できれば、毎月自動で出金されると、帳簿上も管理が容易です。
口座は登録されているので、出金金額未満である、 Amazon ギフト券を望む、など以外では、自動で月末に出金するなどは可能かなと思ってリクエストしました。

## 関連

N/A

**Comment by cm-wada-yusuke** [comment]
提案ありがとうございます。確かに、安定して収益を得られている方にとっては、ほしい機能ですね。

現状、単純に人手が不足しており、優先的には対応できません（特に口座番号ミスなどで振り込みに失敗した場合などのオペレーション）が、あったほうがいい仕組みだおともうので、気長にお待ちいただけると幸いです。

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ニーズが限定的であり実装コストに見合わないため対応しないこととなりました。

お手数をおかけしますがご理解いただけますと幸いです。
