### ISSUE TITLE
NewArticleページが500エラー

### ISSUE THREAD

**Issue by umi-tyaahan** [zenn-dev/zenn-community#406]
## 事象
新着一覧ページを開くと、500エラー表示となる。

## 発生したページのURL
https://zenn.dev/articles

## 発生した画面のスクリーンショット
![newarticle](https://user-images.githubusercontent.com/59476344/177016660-07f6a24a-7e84-4134-af0d-41f3648235dc.png)

## 再現方法
https://zenn.dev/articles
のURLを開く

## 環境
以下で再現した。

- PC
- OS : windows10
- Browser: Chrome バージョン: 103.0.5060.66（Official Build） （64 ビット）

- android
- OS : android 9
- Browser: Chrome 102.0..5005.125

**Comment by cm-wada-yusuke** [comment]
@umi-tyaahan ご連絡ありがとうございます。開発チームでも事象を確認しました。現在、根本原因の調査中です。優先して調査します。進展あり次第報告します。なお、再発した場合、少なくとも日中であれば開発チームで復旧可能ですので対応します。

**Comment by cm-wada-yusuke** [comment]
原因を特定できまして、恒久対応を検討中です。引き続き、再発した場合は開発チームで復旧します。

**Comment by cm-igarashi-ryosuke** [comment]
恒久対応が完了しましたのでクローズします。

ご報告いただきありがとうございました。
