### ISSUE TITLE
Android OSのChromeで記事を開くとフリーズすることがある

### ISSUE THREAD

**Issue by cm-igarashi-ryosuke** [zenn-dev/zenn-community#407]
## 事象

- Android OSのChromeで記事を開くとフリーズすることがある
- はてなブックマークアプリでも発生する

## 発生したページのURL

https://zenn.dev/kobito/articles/5e246e85615435
https://zenn.dev/kahirokunn/articles/89ce38fdbf924a

## 環境

ケース1
- Chrome 103.0.5060.70
- Android 12; Pixel 5 Build

ケース2
- Chrome 103.0.5060.70
- Android 10（Rakuten Hand）

ケース3
- Chrome: 103.0.5060.70
- Android 11; SO51 Aa Build/58.1.B.6.17

ケース4
- Chrome 101.0.4951.7
- Android 13 ビルド TPB1.220310.029.A1（Google Pixel 5a 5g）

**Comment by cm-igarashi-ryosuke** [comment]
関連?: https://github.com/PrismJS/prism/issues/3339

**Comment by cm-wada-yusuke** [comment]
実機：Galaxy, Android10, Chrome 103.0.5060.70
再現せず

エミュレータ： Pixlel 4, Android12, Chrome 103.0.5060.70
１度発生したが以後再現せず

エミュレータ：Pixel 5, Android12, Chrome 103.0.5060.70
再現せず

AWS Device Farm: Pixel5, Android12, Chrome 103.0.5060.70
再現せず

**Comment by cm-wada-yusuke** [comment]
情報提供感謝します

-  https://twitter.com/ina6ra/status/1543904723526615041?s=20&t=hc4KWSu86Ix-7K9N95VO6g
- https://twitter.com/ina6ra/status/1543903214961311745?s=20&t=hc4KWSu86Ix-7K9N95VO6g

**Comment by cm-wada-yusuke** [comment]
さらに欲しい情報：

- どれくらいの確率で発生するか（必ず発生する、最初の１回のみ、たまに、ひんぱんに）
- 画面のどこで発生するか（ある程度スクロールしたら、開いた瞬間）
- 通信環境で違いがでるか（キャリア通信のとき発生しやすい、Wifiのとき発生しやすい）

**Comment by rassi0429** [comment]
いつもお世話になっています。
私の環境でもこのフリーズが複数のサイトで起こっていて、GitHubを巡回していたら進行形のissueがあったので、情報提供します。
フリーズする環境
- Google Pixel 5a 5g
- Android 13 ビルド TPB1.220310.029.A1
- Chrome 101.0.4951.7
現象
- 上記のリンクを踏むと必ずすぐWebViewがクラッシュする
- タイミングはページ全体のロードが終わるか終わらないかのタイミング(読み込み始めて1秒未満)
- Wi-Fi、5Gで試したが現象は変わらず。  

以下は録画になります。
https://twitter.com/ciel_vr/status/1544212923932807169

追記
Beta(Beta 104.0.5112.29)のバージョンでは問題なくページを読むことができました。

**Comment by cm-wada-yusuke** [comment]
@rassi0429 とても助かります！！！！！！！！！！！！！！感謝！！！

**Comment by cm-wada-yusuke** [comment]
@rassi0429 お時間があるときにお願いしたいのですが、このページを同じ端末で開いたときにどうなるか教えていただけるでしょうか。
https://qiita.com/kahirokunn/items/80b2afa13ee9a1304f74

- Zennと同じように固まる
- Zennと全く同じではないが、固まりそうになる
- サクサク読める

**Comment by rassi0429** [comment]
@cm-wada-yusuke 
こちらのリンクは、読み込み時に１０秒以上フリーズしたのち、スクロールができるようになりました。

頻繁に「Chromeは応答していません」という警告が出ますが、待機を押すと読むことができました。

以下録画になります
https://twitter.com/ciel_vr/status/1544224416329912320

**Comment by cm-wada-yusuke** [comment]
@rassi0429 お時間いただき感謝します。さらに調査が進みそうです :bow:

**Comment by tannerjohn65** [comment]
本件情報提供いただきありがとうございました！　調査を実施いたしましたが、現状は再現しませんでした。
そのため、こちらのIssueはクローズとさせていただき、今後再現することがあれば改めて調査いたします！

情報提供いただきありがとうございました。大変助かりました！
