### ISSUE TITLE
記事の管理画面で自分の記事が検索しやすいと嬉しいです。

### ISSUE THREAD

**Issue by saitou-T** [zenn-dev/zenn-community#408]
## 提案・要望
記事の管理画面で自分の記事を検索しやすいようにしていただけると助かります。

## 背景
記事が増えてくると自分の記事を探しにくくなる問題があります。最近、下書き記事が増え、とくに管理がしにくくなっています。
自分の書いた記事を日時順だったり、カテゴリ別にまとめられると見返しやすいため、記事の管理画面での検索機能強化を検討していただけたら嬉しいです。

**Comment by cm-wada-yusuke** [comment]
起票ありがとうございます。こちらもうすこしユースケースを詳しく教えて下さい。具体的になにをするときに管理画面の記事一覧で困ってるでしょうか？

例えば「いつ作成したか忘れたが、下書きの記事の執筆を再開したい」というケースが多いでしょうか？

**Comment by saitou-T** [comment]
メモ代わりにも使っているため、自分の記事を見返したい時があります。
その際、「あの情報をどこの記事に書いたっけ？」となって管理画面の記事一覧をスクロールして探すのですが、なかなか見つからないことがあります。

**Comment by cm-wada-yusuke** [comment]
@saitou-T ありがとうございます。例えばそのケースでは、記事タイトルによる検索ではちょっと不足していて、記事の本文まで検索できる必要がある、というイメージでしょうか？

両者でDBにかかる負荷や実装コストがかわってくるため確認させていただいています。

**Comment by saitou-T** [comment]
イメージとしては、はてなブログの記事管理画面が理想的です。
![hatena](https://user-images.githubusercontent.com/23697609/178415170-8a909140-aa65-4ee8-a33b-6bb6db58cc07.png)
記事（下書き記事も含む）の本文まで検索できたら嬉しいですが、管理画面で記事タイトルの絞込みができるだけでも大変ありがたいです。

「スクラップの管理」ページにある「キーワード検索」機能が「記事の管理」ページにも置いてあるようなイメージです。

**Comment by cm-wada-yusuke** [comment]
なるほどなるほど完全に理解しました、ありがとうございます。
完全な代替にならないことは承知していますがしばらくはブラウザの検索機能でしのいでいただければと思います。
細かいところまで例示していただき助かりました。チームで検討します。

**Comment by cm-wada-yusuke** [comment]
記事の検索機能がリリースされました。
使ってみていただいて、不十分なケースがあればReopenして教えていだければと思います。

https://info.zenn.dev/search-article-dashboard
