### ISSUE TITLE
スライド共有サービスのドクセルの埋め込みができたら嬉しいです。

### ISSUE THREAD

**Issue by saitou-T** [zenn-dev/zenn-community#409]
## 提案・要望
スライド共有サービスのドクセルの埋め込みができたら嬉しいです。

## 背景
SlideShareが使いにくくなった影響で、ドクセルへ移管する方向へ動いています。そのため、ドクセルの埋め込みが可能になると嬉しいです。

**Comment by cm-wada-yusuke** [comment]
起票ありがとうございます！日本語にも対応していて（というか日本語ネイティブで）親しみやすいですね。検討します。

**Comment by cm-dyoshikawa** [comment]
関連: https://github.com/zenn-dev/zenn-editor/issues/321

**Comment by cm-dyoshikawa** [comment]
本日Docswellスライドの埋め込みに対応しました。

https://info.zenn.dev/2024-09-18-embed-docswell-slides

そのため本Issueはクローズいたします。
起票いただきありがとうございました 🙇
