### ISSUE TITLE
Unreal EngineのBlueprintロジックの共有（サイトの埋め込み）ができると嬉しいです。

### ISSUE THREAD

**Issue by saitou-T** [zenn-dev/zenn-community#410]
## 提案・要望
以下リンク先はBlueprintロジックを共有するサイトです。
https://dev.epicgames.com/community/snippets/9pM/unreal-engine-forloopwithdelay-without-each-array
このサイトの埋め込み、もしくは、サイトのようにBlue Printのロジックを埋め込める機能があると嬉しいです。

## 背景
Unreal EngineではBlueprintというブロック状のコードをつなぎ合わせてプログラミングすることが主流となっています。
Blueprintは共有がしにくく、今までは主に画像を使ってBlue Printのロジックを共有されてきましたが、最近リンク先のような、Blueprintを共有できるサービスが開始されました。

サイトの埋め込みができれば、記事の見やすさが向上し、良質なコンテンツに繋がるためぜひ埋め込み機能の追加を検討していただきたいです。

**Comment by cm-wada-yusuke** [comment]
ありがとうございます。サービスごとに記法を追加するのか `iframe` を許可するのか含めて検討します。

**Comment by kurowassan1212** [comment]
このBlueprintのサイトの埋め込み機能、あったら非常に助かるので私も欲しいと思っています。ぜひよろしくお願いします。🙇🏻‍♂️

**Comment by cm-wada-yusuke** [comment]
こちら Figma とあわせて対応を検討します。しばらくおまちください。
https://github.com/zenn-dev/zenn-community/issues/433

**Comment by cm-wada-yusuke** [comment]
対応しました。ぜひご利用ください。
https://zenn.dev/zenn/articles/markdown-guide#blueprintue

なお、私が調べる限り、URLの仕様や正規表現が公開されているわけではなさそうでしたので、URL検出の正規表現は完全ではない可能性があります。意図せず埋め込みになってしまった、逆に、埋め込みになってほしいのにならない、などの挙動がありましたら一報いただけると助かります。

UnrealEngine へコントリビュートしてくださっている皆様、いつも良質な記事をありがとうございます！

**Comment by saitou-T** [comment]
ありがとうございます！
さっそくなのですが、「＋」ボタンより、埋め込みできるサイト一覧にblueprintueがなく、少し不便に感じました。

それと、表示できないURLがありました。
https://blueprintue.com/render/○○○
この○○○の部分にアンダースコアが含まれているとうまく表示されないようです。

**Comment by daichi-takezawa** [comment]
実装ありがとうございます🙏🏻🙏🏻活用していきます。

**Comment by cm-wada-yusuke** [comment]
@saitou-T 

早速ご指摘ありがとうございます！確認して修正します。

> さっそくなのですが、「＋」ボタンより、埋め込みできるサイト一覧にblueprintueがなく、少し不便に感じました。

そうですよね。ご不便をおかけします。blueprintUEについてはURLの仕様や正規表現が公開されているわけではなさそう（調査不足の可能性もあります）ということもあり、また今後の仕様変更やメンテナンスの将来性も考慮させていただき、「＋」ボタンには最初は含めない判断としました。のちのち「＋」から挿入できるようにする可能性もあります。ご理解いただけると幸いです。

**Comment by daichi-takezawa** [comment]
すいません、こちら↓のバグって現在修正中という認識でよろしかったでしょうか？

> それと、表示できないURLがありました。
[https://blueprintue.com/render/○○○](https://blueprintue.com/render/%E2%97%8B%E2%97%8B%E2%97%8B)
この○○○の部分にアンダースコアが含まれているとうまく表示されないようです。

まだ「_」と「-」が含まれるURLだと表示されないのですが...


![2022-09-23_14h21_16](https://user-images.githubusercontent.com/50498401/191896584-a61541b1-05b7-488d-912f-7926409ed9e5.jpg)

**Comment by cm-wada-yusuke** [comment]
@daichi-takezawa おまたせしており申し訳ありません。今週はやいうちにリリースします。

**Comment by cm-wada-yusuke** [comment]
@daichi-takezawa おまたせしました！変換ロジックを修正してリリース済です。お手数なのですが、問題が発生しいてるMarkdown文書について、

- Webのエディタで編集している場合（スクラップなど）=> 本文変えずに更新
- GitHub 連携している 記事やチャプター => 本文に変更を加えてから再デプロイ

としていただくと blueprintue のHTMLが修正されるはずです。よろしくおねがいします。

**Comment by daichi-takezawa** [comment]
ありがとうございます🙏🏻
