### ISSUE TITLE
執筆中の自動保存を本保存にして欲しい

### ISSUE THREAD

**Issue by itte1** [zenn-dev/zenn-community#412]
## 提案・要望

記事や本を執筆中に、保存ボタンを押さなくても保存される機能がオプションで欲しいです。

公開中の記事の編集などは、保存のタイミングで公開されてしまいますので実装方法に検討が必要かと思いますが、
個人的には公開中の記事が編集中に公開されても気にしませんので、保存ボタンを押さなくても保存されるようになると嬉しいです。

## 背景

小まめに保存するようにはしていますが、
執筆中の記事間を移動するときに、「保存せずに終了しますか？」に対して誤ってOKボタンを押してしまい、文章が消えてしまうことがあります。

また、私だけかもしれませんがPCが突然フリーズすることがあり、再起動するしかなく、LocalStorageへの自動保存も上手くいっていないときがあるようで執筆途中の文章が消えてしまうことがあります。

文章が消えたときはショックでモチベーションが低下してしまいます。

Officeソフトやテキストエディタでもオートセーブが普及してきており、保存ボタンに慣れていない人も多いかと思います。
ぜひご検討のほどよろしくお願いいたします。

**Comment by cm-wada-yusuke** [comment]
localStorage はネットワーク環境がない状況でも保存できるメリットがありますが、たしかに自動保存がサーバーに保存されると便利ですね。Officeソフトやテキストエディタ と異なるのはどうしてもネットワーク負荷が発生する点です。そのあたり考慮しつつ検討します。より良い執筆環境を用意したい思いはあるのでしばしお待ちいただければと思います。

ちょっとしたアンケートなのですが、GitHub 連携での任意のテキストエディタを使っての執筆は難しい事情があるでしょうか？

**Comment by itte1** [comment]
@cm-wada-yusuke 
ご検討いただきありがとうございます。

テキストエディタでの執筆につきましては、物理的にできない理由はありませんが、
今のところデメリットのほうが多いと考えていて利用する予定はありません。

元々、VSCodeを使ってMarkdownでHPを更新していましたが、以下の理由から次第に更新しなくなっていました。

・読者との（心理的）距離が遠い
・環境構築に少なからず時間がかかる
・プレビューやデプロイのコマンドをしばらく使わないと忘れる
・Markdownもよく忘れる（Zennは？を押せばすぐに確認できます）
・mdファイルや画像ファイルのファイル名、パスを意識しなければならない
・pushしないと他のPCやスマホから更新を確認できない
・プログラムもVSCodeで書いているのでプログラムと記事のウィンドウ区別がしにくい

そのような中で、御社のZennを知り、デザインとユーザーインターフェースが優れていたため利用させていただいております。
おかげで頻繁に更新することができるようになりました。テキストエディタに戻したらまた更新しなくなると思います。

**Comment by cm-wada-yusuke** [comment]
@itte1 詳細にありがとうごさいます、よくわかりました。よりよい執筆環境のためWebエディタも充実させていきたいと思います。

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ニーズが限定的であり実装コストに見合わないため対応しないこととなりました。
