### ISSUE TITLE
「組織(organization)」というユーザーグループを作成可能にして欲しい

### ISSUE THREAD

**Issue by Sn005** [zenn-dev/zenn-community#413]
## 提案・要望
個別ユーザーが所属する「組織」ないしはそれに準ずるユーザーグループが欲しいです。
この機能を追加することで、特定グループに所属しながら、個人のアカウントで発信できます。
これにより、グループ所属の発信 or プライベートでの発信を切り分けられ、意識を変えたアウトプットが可能になると見込んでいます。
また発信した記事を個人の資産にすることも可能です。

## 背景
現在技術ブログの運用をzennで行いたく調整中です。
ですが、zennで運用されている法人技術ブログを見ると、全て所属組織名でアカウントを保持し、そこから記事を投稿している状態です。
この状態だと、記事を書いた本人の資産になりにくく、社の技術ブログとしてアウトプットするモチベーションが下がる要因になります。
私が所属する組織のエンジニアはzennが好きなメンバーが多く、私としてもその方向に寄せたいのですが、メンバーの資産にならないという理由でStopしています。

ユーザー定義から見直す話となり、難易度が高いissueですが、是非ご検討頂けると幸いです。

**Comment by cm-wada-yusuke** [comment]
絶賛実装中です！応援よろしくおねがいします！
https://github.com/zenn-dev/zenn-community/issues/275

**Comment by Sn005** [comment]
@cm-wada-yusuke 
ありがとうございます！
楽しみにお待ちしております！

**Comment by Sn005** [comment]
@cm-wada-yusuke 
こちらリリースありがとうごさいます！

https://info.zenn.dev/about-publication

**Comment by cm-wada-yusuke** [comment]
@Sn005 キャッチアップありがとうございます！まだクローズドベータですが、もし琴線に触れたらご応募ください！（既に応募済みでしたらすいません！）

**Comment by cm-wada-yusuke** [comment]
キャッチアップいただいたので、以後、こちらのISSUEで管理します
https://github.com/zenn-dev/zenn-community/issues/275
