### ISSUE TITLE
本のページ数の上限を増やしてほしい

### ISSUE THREAD

**Issue by kurowassan1212** [zenn-dev/zenn-community#414]
## 提案・要望
本のページ数の上限を増やして頂けると嬉しいです。

## 背景
いつもお世話になっております。この本↓を現在書いているものですが、現時点で91ページでこのままだと本の上限ページに達してしまいそうです。
https://zenn.dev/daichi_gamedev/books/unreal-engine-tutorial

短めで見やすい本という意味で100ページ制限を設けている（？）のかなと思いますが、上限があると1ページの文章量が多くなってしまったり、追加したいページもあきらめなければなりません..。といった理由で個人的にはページ数の上限を増やして頂けると嬉しいです。元々100ページ制限前提の元作っていたので、上限が今後も変更される予定が無ければ100ページ以内になんとか収めたいと思います。ご検討の程よろしくお願いします🙇🏻‍♂️

**Comment by cm-wada-yusuke** [comment]
いつもありがとうございます、週明け、150へ上限をあげます。
それにしてもすごい分量ですね。内容も濃くたくさんの方が参考にしていると思います。
引き続きよろしくおねがいします。

**Comment by kurowassan1212** [comment]
ありがとうございます。助かります🙇🏻‍♂️

**Comment by cm-wada-yusuke** [comment]
こちら150へ引き上げました。よろしくおねがいします。

なお、構造化についても別途検討していまして、根本的には別のアプローチで解決を図らせていただく可能性もあります。ひとまずは150チャプターの対応とさせてください。
