### ISSUE TITLE
記事のアイキャッチ絵文字について、Emoji 13, 14 に対応してほしい

### ISSUE THREAD

**Issue by korosuke613** [zenn-dev/zenn-community#418]
## 提案・要望

zenn.dev の記事編集画面において、記事のアイキャッチ絵文字に Emoji 13、14 の絵文字を使えるようにしてほしいです。

## 背景

zenn.dev の記事編集画面において、記事のアイキャッチ絵文字として Emoji [13](https://unicode.org/emoji/charts-12.0/emoji-released.html)、[14](https://unicode.org/emoji/charts/emoji-released.html)で定義されている絵文字を設定することができません。具体的には CLDR Short Name を入力しても Search Results に該当絵文字が表示されません。

例：Emoji 13 で追加された [1F972](https://unicode.org/emoji/charts-13.0/emoji-released.html#1f972)(🥲)を設定しようと`smiling face with tear`を入力しても候補に出てこない。	
<img width="539" alt="image" src="https://user-images.githubusercontent.com/20027695/180922295-9e070cd6-b08e-4291-b19d-8120165e1cc0.png">

Emoji 13、14 の絵文字において上記を確認しております。これらの絵文字を利用したいです。

### Additional information
GitHub 連携の場合、Emoji 13が設定できることを確認しております。Emoji 14を設定した場合はランダムな絵文字が表示されました。

例：Emoji 13 で追加された [1F977](https://unicode.org/emoji/charts-13.0/emoji-released.html#1f977)(🥷) 
- [Markdown](https://github.com/korosuke613/zenn-articles/blob/0e42cbbc991c7be4d3a60ead6e96201a66488dfa/articles/productivity-weekly-20210811.md)
- [記事](https://zenn.dev/korosuke613/articles/productivity-weekly-20210811)

**Comment by korosuke613** [comment]
Issue本文を修正いたしました。

**Comment by cm-igarashi-ryosuke** [comment]
@korosuke613 詳細な情報をありがとうございます。

zenn.dev で利用している emoji Picker の [emoji-mart](https://github.com/missive/emoji-mart) のバージョンを上げれば対応できそうです。

影響等を確認しますので、しばらくお待ち下さい。

**Comment by cm-igarashi-ryosuke** [comment]
@korosuke613 

> zenn.dev で利用している emoji Picker の [emoji-mart](https://github.com/missive/emoji-mart) のバージョンを上げれば対応できそうです。

こちらなんですが、Emoji 13 以降に対応するには emoji-mart を 5.0.0 以上に上げる必要がありました。
しかし、5系のTypeScriptの型定義がまだ無いようなので（ https://github.com/missive/emoji-mart/issues/576 ）、しばらく対応を待ちたいと思います。

> GitHub 連携の場合、Emoji 13が設定できることを確認しております。Emoji 14を設定した場合はランダムな絵文字が表示されました。

こちらは対応いたしました。
現在、GitHub連携からEmoji 14の emoji が利用可能です。

**Comment by korosuke613** [comment]
@cm-igarashi-ryosuke 
GitHub連携でEmoji 14の絵文字が反映されるのを確認しました。

ご調査・ご対応ありがとうございます！

**Comment by cm-igarashi-ryosuke** [comment]
まだ zenn.dev の記事編集画面 での対応ができていません（ emoji-mart のバージョンアップが必要）

**Comment by cm-wada-yusuke** [comment]
勝手にクローズしてすいませんでしたァ！先走りました 🙇

**Comment by cm-igarashi-ryosuke** [comment]
emoji-mart のバージョンアップ対応しました。zenn.dev上で Emoji 14 が選択できるようになっています。

今後も随時Emojiのアップデートを行っていきます。
