### ISSUE TITLE
Scraps タブでリロードしてから Articles タブに遷移しようとすると遷移できない

### ISSUE THREAD

**Issue by takurinton** [zenn-dev/zenn-community#419]
## 事象

プロフィールページにて、Scraps、または Comments のタブを選択した状態でリロードを行い、その後 Articles のタブに遷移しようとすると URL はプロフィールの URL になるが画面が Scraps（Comments の場所でリロードしていた場合は Comennts）のままになる。

## 発生したページのURL

https://zenn.dev/takurinton?tab=scraps

## 発生した画面のスクリーンショット

スクショだとわかりにくいので動画にしました。動作は事象の部分に書いた通りです。

https://user-images.githubusercontent.com/50351271/182009991-c4c4f953-1e81-42fd-8635-fa7d473e1694.mov

## 再現方法

事象の部分に書いた通りです。

## 環境

- Device: M1 Macbook Pro
- OS: Montery(v12.2)
- Browser:  
  - 以下の3つのブラウザで確認しました 
  - Brave（バージョン: 1.37.116 Chromium: 100.0.4896.127（Official Build） （arm64））
  - Chrome （バージョン: 96.0.4664.45（Official Build） （arm64））
  - Safari （バージョン15.3 (17612.4.9.1.5)）

**Comment by catnose99** [comment]
丁寧なご報告をありがとうございます。
私の環境でも問題を再現できました。
ご不便をおかけしますが、修正まで今しばらくお待ちください。

**Comment by cm-wada-yusuke** [comment]
こちら @catnose99 により修正リリース済、解消されたことを確認しました。ご連絡ありがとうございました。
