### ISSUE TITLE
決済手段に PayPal を使えるようにして欲しい

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [zenn-dev/zenn-community#42]
現在決済手段としてはクレカと銀行口座がありますが，できれば PayPal 決済も加えてほしいです。これなら決済情報をばら撒かなくても済みますし。

**Comment by tannerjohn65** [comment]
現状、利用している決済サービスの仕様上実現が難しいため、クローズさせていただきます。今後、決済を見直すタイミングがあれば改めて検討いたします。
