### ISSUE TITLE
Do not auto-darken the screen.

### ISSUE THREAD

**Issue by konojunya** [zenn-dev/zenn-community#420]
## 提案・要望

I believe it is possible to adjust the ScreenLock API to prevent darkening 

ref: https://developer.mozilla.org/ja/docs/Web/API/Screen_Wake_Lock_API
ref: https://w3c.github.io/screen-wake-lock/

## 背景

When reading long sentences or books, the screen automatically dims and sometimes you have to tap the screen with your finger.

## 関連

It would be possible to implement it this way

**Comment by cm-wada-yusuke** [comment]
ご連絡ありがとうございます。ブラウザの対応状況を考慮すると、すぐに導入するのは難しそうです。が、ScreenLockというものがあるのはチームで共有させていただきます、ありがとうございます。

https://developer.mozilla.org/ja/docs/Web/API/Screen_Wake_Lock_API#%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E3%83%BC%E3%81%AE%E4%BA%92%E6%8F%9B%E6%80%A7

**Comment by cm-wada-yusuke** [comment]
ブラウザ対応が進まないためクローズします。
