### ISSUE TITLE
FirefoxでTwitterカードのプレビューが表示されない

### ISSUE THREAD

**Issue by xerroxcopy** [zenn-dev/zenn-community#421]
## 事象
macOS 12.5において、Firefox103.0.1ではTwitterカードのプレビューが表示されない。Troubleshootingモードでも同様なのでおそらくアドオンの影響ではないのではないかと考えている。
Safari 15.6, Chrome 103.0.5060.134 (Official Build) (x86_64)であれば表示される

## 発生したページのURL
https://zenn.dev/xerroxcopy/articles/287f373adb8f3b

## 発生した画面のスクリーンショット
Firefox: 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/13182777/182727796-8013e1f1-5dc6-4e64-8e26-4df728ae4166.png">
Chrome:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/13182777/182727905-f07deb66-46ef-429c-9b0f-30d89ec415c6.png">

## 再現方法
常にこのようになる。

## 環境

- Device: iMac Retina 5k 27-inch, 2019
- OS: macOS Monterey 12.5
- Browser: Firefox103.0.1

**Comment by uttk-dev** [comment]
@xerroxcopy 

ご報告ありがとうございます。

こちらで確認した結果、[デスクトップ版 Firefox の強化型トラッキング防止](https://support.mozilla.org/ja/kb/enhanced-tracking-protection-firefox-desktop) を **"厳格"** に設定すると再現させることができたのですが、こちらの設定はどうなっていますでしょうか？ もし **"厳格"** 設定している場合は、お手数ですが **"標準"** または **"カスタム"** に変更して再度ご確認して頂ければと思います。

もし設定を変更しても問題が発生する場合は、こちらの Issue にご報告頂ければと思います。

よろしくお願いします。

**Comment by xerroxcopy** [comment]
@uttk-dev 
ありがとうございます。なんと、こんなものがあったんですね…！解決しました。お手数をおかけしてしまいすみません。
