### ISSUE TITLE
codesandboxのURLに「,」を許容してほしい

### ISSUE THREAD

**Issue by tockri** [zenn-dev/zenn-community#422]
## 提案・要望

現状、CodeSandboxを埋め込む記法で
```
@[codesandbox](https://codesandbox.io/embed/481l76l2x9?module=/src/Todo/TodoController.js,/src/Todo/TodoList.js)
```
のように記述すると多分「,」が入っていることにより
```
「https://codesandbox.io/embed/」から始まる正しいURLを入力してください
```
という表示になります。[CodeSandboxのmoduleパラメータは「,」区切りで複数ファイルを指定できる仕様](https://codesandbox.io/docs/embedding)なので、「,」を許容してもらえると嬉しいです。

## 背景
複数ファイルを開いた状態のCodeSandboxを埋め込みたいです。
例： https://codesandbox.io/embed/481l76l2x9?module=/src/Todo/TodoController.js,/src/Todo/TodoList.js

CodeSandbox側の問題だとは思うのですが、「,」をURLエンコードすると複数タブが表示されません。
例： https://codesandbox.io/embed/481l76l2x9?module=/src/Todo/TodoController.js%2C/src/Todo/TodoList.js
「/」を「%2F」にエンコードしても同様です。

**Comment by uttk-dev** [comment]
@tockri 

Issue の作成ありがとうございます。
https://github.com/zenn-dev/zenn-editor/pull/326 で CodeSandBox の埋め込みURLに「 , 」を許容するように修正しました。
リリースまで少し時間がかかるため、反映まで少々お待ち頂ければと思います。

よろしくお願いします。

**Comment by uttk-dev** [comment]
CodeSandBoxの埋め込みURLに「 , 」が含まれていても埋め込めることを確認したため、この Issue はクローズさせて頂きます。もし問題が再発するようでしたら、お手数ですが再度ご報告頂ければと思います。

よろしくお願いします。

**Comment by tockri** [comment]
@uttk-dev ありがとうございました！
