### ISSUE TITLE
コードブロックの表示ウィンドウの高さを指定したい

### ISSUE THREAD

**Issue by arkbig** [zenn-dev/zenn-community#423]
## 提案・要望
\```txt
Fenced Code Blocks
このコードブロックの行数が多い場合、GitHub埋め込みのように高さ制限されスクロールできる状態で表示したいです。
\```

## 背景
長いコードの全体を記載したい時、縦に間伸びしてしまうのが不便です。
GitHub埋め込みはスクロールがありいいのですが、シンタックスハイライトを指定したり200行を超えるものを表示したい場合に使えませんでした。

**Comment by uttk-dev** [comment]
@arkbig 

提案ありがとうございます。
他の優先度が高いタスクがあるため、対応には時間が掛かるかもしれませんが、開発チームに持ち帰って検討したいと思います。

**Comment by cm-wada-yusuke** [comment]
ドキュメントに存在するが見えない状況では、Cmd+F（ページ内検索）したときにヒットはするもののどこにあるのかわからない、という状況を引き起こすため対応は見送りとさせてください。

**Comment by arkbig** [comment]
ご検討ありがとうございました。見送りということでかしこまりました。

個人的には欲しい時もあるので、ユーザースタイルシートやブックマークレットで対応できないかみてみたいと思います。

```css
div.code-block-container{
  overflow: scroll;
  height: 40em;
}
```

のように指定すれば、Ctrl+Fでヒットするときにスクロールはしてくれました。ただ、ハイライトだけしてあとは自分でスクロールして探す場合はどこにあるか分かりづらいです。（全体スクロールバーにハイライトはあるけど、内部スクロールを位置合わせしないといけない）
見た目やブラウザ互換性の問題、操作性の好みもあると思うので時間があるときに個人環境で解決を試してみます。
