### ISSUE TITLE
注釈にマウスオーバーでツールチップが出るようにして欲しい

### ISSUE THREAD

**Issue by shu-i-chi** [zenn-dev/zenn-community#425]
## 提案・要望
Zennの記事を読む際に、注釈にマウスオーバーすると**注釈の内容を、特にリンク込みでツールチップに表示する**ようにして欲しいです。

イメージしているもの：Wikipediaの脚注ツールチップ
https://ja.wikipedia.org/wiki/%E3%83%84%E3%83%BC%E3%83%AB%E3%83%81%E3%83%83%E3%83%97

あるいは、注釈のリンクから脚注エリアにジャンプした際、踏んだ注釈に**対応した脚注のところを、背景の色付けなどでわかりやすく**してほしいです。

## 背景
記事中に、例えばある関数のAPIドキュメントへのリンクを張る場合に、「最後におさらい・俯瞰できるように、テキストリンクではなく、注釈にリンクを置くようにしておこう」となる場合があります。

こういう注釈の使い方をした場合、リンクを踏んでページ末尾の脚注部分にジャンプすると、「あれ、どのリンク見ようとしてるんだっけ...」となりがちになってしまいます。

（以下は、注釈10のリンクを踏んで「脚注」エリアにジャンプした例です）
![注釈10のリンクを踏んで「脚注」エリアにジャンプした例](https://user-images.githubusercontent.com/73956541/187075967-d8cd79d9-e555-4643-969c-a298e6105264.png)

例えばWikipediaの脚注ツールチップの場合、マウスオーバーで脚注エリアに記載してあるリンクもページ遷移なく表示されるので、別タブで開く...などの工夫もでき、便利です。また、読む際の流れも阻害されません。

![wikipediaの脚注ツールチップ例](https://user-images.githubusercontent.com/73956541/187076136-e580d3ed-f505-4c3e-90d1-d8d28bb52a96.png)

あるいは、注釈のリンクから脚注エリアにジャンプした際に迷子にならないように、対応した脚注のところを、背景の色付けなどの表示上の差別化でわかりやすくする、といった方法でも、私の場合の困りごとの解決にはなります。

### その他
* そもそも私の注釈の使い方が上手くないだけ...というのもあると思いますが、棚に上げさせていただきます...
* ツールチップもツールチップで、ごちゃごちゃするかもしれないですが、やはりページジャンプが発生しないのは結構嬉しいです

以上、よろしくお願いいたします。

**Comment by catnose99** [comment]
こちら開発チームで検討を行いました。


ジャンプ先の脚注が分かりづらいという課題を何らかの形で対応できないか検討したところ、アクティブな脚注をハイライトすることはすぐに実現可能であることがわかりました。こちらの修正はすでにzenn.devでもリリース済みです。

Wikipediaのようなツールチップの表示の体験はとても良いのですが、Zenn CLIやVSCode拡張などでmarkdownをプレビューするときに一貫したUIを提供することが現状難しそうであるため、一旦見送りとなりました。

以上、よろしくお願いします。

**Comment by shu-i-chi** [comment]
ご検討いただきありがとうございました。
リリースいただいた「アクティブな脚注をハイライト」機能、とてもありがたいです！
また、迅速にご対応いただいて、感謝の気持ちです。

以上、よろしくお願いします。
