### ISSUE TITLE
WebP形式画像のサポート

### ISSUE THREAD

**Issue by WinterYukky** [zenn-dev/zenn-community#426]
## 提案・要望

WebP形式の画像を記事に埋め込める機能がほしいです。

## 背景

アニメーション画像を記事に埋め込む場合、現在はGIF形式の画像を埋め込む必要があります。
しかし、アップロードできる画像の最大サイズが設定されておりGIF形式だとサイズオーバーすることがしばしばあります。
逆に同じアニメーション画像でもWebP形式だとサイズオーバーしないパターンがこれまでに何度かあったためWebP画像のサポートがあるとよりリッチな記事が投稿しやすくなると考えました。

**Comment by cm-igarashi-ryosuke** [comment]
@WinterYukky 

> 逆に同じアニメーション画像でもWebP形式だとサイズオーバーしないパターンがこれまでに何度かあったためWebP画像のサポートがあるとよりリッチな記事が投稿しやすくなると考えました。

なるほど、貴重な情報をありがとうございます！

WebPの対応状況、ブラウザによっては制約はあるものの、ほとんど問題なく対応してそうですね。
https://caniuse.com/webp

すぐにとは行かないですが、前向きに検討させていただきます。

**Comment by cm-igarashi-ryosuke** [comment]
@WinterYukky zenn上でWebP形式をアップロードできるように対応しました。

zenn-cliももうまもなく対応する予定です。
zenn-cliを使われる場合はもう少しお待ち下さい。

**Comment by cm-igarashi-ryosuke** [comment]
@WinterYukky zenn-cliの対応も完了しました。最新バージョンにアップデートしてご利用ください。

**Comment by WinterYukky** [comment]
@cm-igarashi-ryosuke 
早速の機能追加ありがとうございます！webp画像をアップロードできることは確認できたのですが、プレビュー画面ではアニメーションは無効になるのでしょうか？
プレビューでアニメーションされていないことに気が付いて記事公開までは試せていない状態です。
![webp-preview](https://user-images.githubusercontent.com/49480575/194866630-99cbd270-d430-4763-a788-bbe487b63b88.gif)

### 使用したwebp画像
[webp-example.zip](https://github.com/zenn-dev/zenn-community/files/9745884/webp-example.zip)

webp画像は[ScreenToGif](https://github.com/NickeManarin/ScreenToGif)を使用して出力しています。

**Comment by cm-igarashi-ryosuke** [comment]
@WinterYukky エディタからアップロードする際、画像サイズなどを最適化する処理がされた結果、アニメーションの情報が欠落してしまっていました。修正しますので少々お待ち下さい 🙏

**Comment by cm-igarashi-ryosuke** [comment]
@WinterYukky 修正完了しました 🙏

**Comment by WinterYukky** [comment]
@cm-igarashi-ryosuke 
アニメーションの動作確認できました。驚くほど対応が早くて素敵です✨
機能要望に応えていただき、ありがとうございました。
