### ISSUE TITLE
リンクURLで文字置き換えが発生すると困る

### ISSUE THREAD

**Issue by covemause** [zenn-dev/zenn-community#427]
## 事象
リンクURLもしくはテキストで実在するサイト「https://xn--walker-s-n43g.co.jp/media/what-is-bubble/」を記入し、プレビューで見ると「https://えwalker-s.co.jp/media/what-is-bubble/」になる。

## 発生したページのURL
https://zenn.dev/chugoshi/articles/6fe98277defba3

## 発生した画面のスクリーンショット
![URLバグ](https://user-images.githubusercontent.com/28245851/187716852-a028422e-c5bf-462b-8a67-3e9d9bbba65d.JPG)

## 再現方法
スクリーンショット参照

## 環境
環境依存は不明

- Device: PC
- OS: Windows10Pro OSビルド19043.1052
- Browser: chrome 104.0.5112.102

**Comment by uttk-dev** [comment]
Issue の報告ありがとうございます。

こちらで調べたところ、`xn--` から始まるドメインは [Punycode](https://ja.wikipedia.org/wiki/Punycode) と呼ばれるもので、文字が置き換えられるのは仕様によるものですので、こちらで対応することは難しいです。

お手数ですが、[Punycode](https://ja.wikipedia.org/wiki/Punycode) ではない別のURL( おそらく https://walker-s.co.jp/media/what-is-bubble/ )を使用して頂ければと思います。

**Comment by covemause** [comment]
@uttk-dev 調査いただきありがとうございました。仕様という事で理解しました。
