### ISSUE TITLE
記事と同じリポジトリのGitHubテキスト埋め込みで最終行が省略される

### ISSUE THREAD

**Issue by risu729** [zenn-dev/zenn-community#429]
## 事象
GitHubのテキストを埋め込んだ際、最終行が省略されてしまいます。

以下、検証した手順です。
1. 記事をローカルで編集し、Gistにあったコードをリポジトリ([zenn-content](https://github.com/risu729/zenn-content))内のcodeディレクトリに移動。(プレビューでは404となる状態)
2. git push し、Zennでビルドされたものを確認したところ、コードの最終行が省略されている。
3. 以下プレビューで確認しています。
4. 最終行が1文字のみでないファイルでも省略される。
5. スクロールバーが表示されるテキストの行数かによらず省略される。(200行を超える場合は200行目まで正常に表示)
6. 他リポジトリのファイルは省略されない。
7. GitHub連携を解除したが、プレビュー、公開済み共に省略されたまま。
8. 2つのリポジトリをGitHub連携したが、別リポジトリのファイルは最終行も正常に表示される。

(`Lines 1 to 38 in main`の表示は省略後の行数になっていました)

## 発生したページのURL
公開済み記事 https://zenn.dev/risu729/articles/java-enum-bitmask-conversion

検証用記事(下書き) https://zenn.dev/risu729/articles/github-embed-test
https://github.com/risu729/zenn-content/blob/main/articles/github-embed-test.md

## 発生した画面のスクリーンショット

[公開済み記事](https://zenn.dev/risu729/articles/java-enum-bitmask-conversion)
![published](https://user-images.githubusercontent.com/79110363/188199642-1a580033-bb79-44d7-a921-4bb548754692.png)

プレビュー
![preview1](https://user-images.githubusercontent.com/79110363/188199638-103ac6a5-991f-419a-a190-176ae42bcfb3.png)
![preview2](https://user-images.githubusercontent.com/79110363/188199640-a3f8be2c-14c7-4466-955d-a927762206cf.png)

## 再現方法
GitHub連携をした状態で、同一リポジトリ内のテキストリンクを記事に埋め込む。
Zenn CLIでのプレビュー、公開済みの記事いずれでも発生しました。

## 環境
- OS: Windows 10 Home 21H2
- Browser: Chrome 104.0.5112.102

---
発生条件が絞れておらず申し訳ないのですがよろしくお願いいたします。

**Comment by uttk-dev** [comment]
@risu729 
詳細なご報告ありがとうございます。
こちらのバグを修正しましたので、この Issue はクローズさせて頂きたいと思います。

注意点として、埋め込み要素はキャッシュがしばらく残っている場合がありまして、その場合はバグが残ったままになっていることがあります。そのため、確認の際はしばらく時間を置いてから確認して頂ければと思います。

もし時間を置いてもバグが直っていないようでしたら、お手数ですが再度こちらのIssueにご報告頂ければと思います。

よろしくお願いします！

**Comment by risu729** [comment]
先ほど確認してみたところ、正常な表示を確認できました。
迅速な修正ありがとうございます。
