### ISSUE TITLE
コードブロックのカラースキームを変更できるようにしてほしい

### ISSUE THREAD

**Issue by suquiya** [zenn-dev/zenn-community#43]
Zennはいろいろと見やすいのが気に入っています。ただ、コードブロックのカラースキームがちょこちょこ見辛いのが気になります。
他のサイトのコードをEmbedすればよいのかもしれませんが、できれば数種類でいいので、コードブロックのカラースキームを切り替えできればいいな…と。例えばユーザ設定で設定したカラースキームで記事のコードブロックを閲覧できたりとかできると助かるかなと思いまして。
どうぞよろしくご検討お願いいたします。

**Comment by uttk-dev** [comment]
提案ありがとうございます。
開発チームで検討しましたが、他のデザインとの兼ね合いで対応が難しいためクローズさせて頂きます。
ご期待に添えず申し訳ありませんが、ご理解頂ければ幸いです。
