### ISSUE TITLE
GitHubテキスト埋め込みで開始行のみ指定が1行のみ指定となる

### ISSUE THREAD

**Issue by risu729** [zenn-dev/zenn-community#430]
## 事象
GitHubテキスト埋め込みで開始行のみ指定がその行のみの指定となります。

## 発生したページのURL
https://zenn.dev/zenn/articles/markdown-guide#github

## 発生した画面のスクリーンショット
![screenshot](https://user-images.githubusercontent.com/79110363/188207743-6d9eb38b-ea4c-4812-9901-62e3b34f7de9.png)

**Comment by uttk-dev** [comment]
@risu729 
Issue の作成ありがとうございます。
開始行のみ指定された場合は、**開始行のみを表示する**ようになっているため、
こちらの挙動は正しい挙動となっています。

理由と致しましては、
GitHub 上でも開始行のみを指定した場合は開始行のみを表示する仕様になっているため、
Zenn でもその仕様に合わせた方がユーザーの混乱を避けやすいと判断したためです。

例： https://github.com/zenn-dev/zenn-editor/blob/33ab0a916ef1fb08271fe03fa694d11d7bd77e66/package.json#L25 の GitHub 上でのプレビューは以下のようになります 👇

<img width="872" alt="image" src="https://user-images.githubusercontent.com/97154037/188346449-d1acd068-8c29-4723-b174-3a4a19e83fce.png">

**Comment by risu729** [comment]
GitHubの挙動を確認せず、文章を誤解したままIssueを立ててしまいました。
ご迷惑をお掛けして大変申し訳ありません。ご丁寧な対応いただきとてもありがたいです。

**Comment by uttk-dev** [comment]
@risu729 
いえいえ、こちらこそ Issue を作成して頂きありがとうございます。

>文章を誤解したままIssueを立ててしまいました。

確かに、[記事](https://zenn.dev/zenn/articles/markdown-guide#github)内の表現では誤解を生みやすいですね。
後ほど見直して修正したいと思います。

**Comment by risu729** [comment]
お手数おかけしてすみません。
よろしくお願いいたします。
