### ISSUE TITLE
お問い合わせフォームは機能しているのだろうか？

### ISSUE THREAD

**Issue by stken2050** [zenn-dev/zenn-community#432]
https://zenn.dev/faq
において、

>課題が解決しなかった場合は [お問い合わせフォーム](https://docs.google.com/forms/d/e/1FAIpQLSdsDaXjtcHDtqMgxr-KVnLBfBrzOXLyMRGiF0qSoNTFAttZVA/viewform)をご利用ください。問題の報告や機能要望などは [zenn-community](https://github.com/zenn-dev/zenn-community)で投稿してください。

とあります。
同時にまた、このレポジトリのREADMEにおいても、
https://github.com/zenn-dev/zenn-community

> ### zenn-community
>このリポジトリは、Zennのユーザが要望や質問などを投稿できる場所です。
>セキュリティやプライバシーに関わる質問・報告は、[お問い合わせフォーム](https://docs.google.com/forms/d/e/1FAIpQLSdsDaXjtcHDtqMgxr-KVnLBfBrzOXLyMRGiF0qSoNTFAttZVA/viewform)からご連絡ください。
> - 該当するカテゴリがない場合は、[お問い合わせフォーム](https://docs.google.com/forms/d/e/1FAIpQLSdsDaXjtcHDtqMgxr-KVnLBfBrzOXLyMRGiF0qSoNTFAttZVA/viewform)からご連絡ください。

と、かなり繰り返し、お問い合わせフォームへ誘導されている実態があります。

https://docs.google.com/forms/d/e/1FAIpQLSdsDaXjtcHDtqMgxr-KVnLBfBrzOXLyMRGiF0qSoNTFAttZVA/viewform

というのはGoogleFormであり、ある種割り切った実装であると評価できるものの、実際に問い合わせたい内容があり、このフォームから問い合わせを送ってみたのですが、まず確認メールも送られてこず、最悪なことに２週間ほど経過するのですが返信も一切ありませんでした。

このようにユーザが運営に何か問い合わせても問い合わせ事実のメールログすら残らず、返信も一切ないとすると、これは無視されている、ということになります。

そしてこのような実態はユーザサイドに可視化されているわけもなく、実際に問い合わせてみて返信がないことを確認したユーザのみがこのような事情を知る、という状況になっており、実情を知られてないかぎり放置しているのだな、と少なくとも私は不信感を抱くようになりました。

以上の事実について、開発運営者の認識を教えてください。

**Comment by tannerjohn65** [comment]
別途、問い合わせ内容に対してメールにて返答をお送りいたしましたので、本Issueはクローズします。

**Comment by stken2050** [comment]
メールにて返答を確認しましたが、本件につきましては、個別対応についてではなく、なぜこういうことが起こるのか？という事案そのものについて確認しております。
なぜ、ユーザの問い合わせについて無視するような運用が行われているのでしょうか？

**Comment by tannerjohn65** [comment]
Zennは少人数のチームで開発・運用をしながらお問い合わせや要望にも対応しています。
チームの時間は有限であり、お問合せフォームから送られた内容全てに回答できるわけではないことをご理解ください。

> このようにユーザが運営に何か問い合わせても問い合わせ事実のメールログすら残らず、返信も一切ないとすると、これは 無視されている、ということになります。

ご指摘を受け、お問合せフォームに下記の改善を行いました。
- 送信された内容が送信者のメールアドレスに送られるようにしました
- 必ずしもすべてのお問い合わせに回答できるわけではない旨を記載しました

**Comment by stken2050** [comment]
まず、このやりとりを第三者が見れば明らかだと思うのですが、
当方としては、しきりに誘導されている「お問い合わせ」が無視されている、という社会通念上、至極真っ当で普通のことを問うているわけです。

それに対して、
>Zennは少人数のチームで開発・運用をしながらお問い合わせや要望にも対応しています。

別途、問い合わせ内容に対してメールにて返答をお送りいたしましたので、本Issueはクローズします」
というのは、問答として全く成立していないことも明白です。
そこを確認すれば、

>Zennは少人数のチームで開発・運用をしながらお問い合わせや要望にも対応しています。

なるほど。

>チームの時間は有限であり、

真っ当な問い合わせに一般論で説き伏せるようなマネをしてユーザをバカにしているのか？

>お問合せフォームから送られた内容全てに回答できるわけではないことをご理解ください。

ならばそう書いておけ

となりますが、改善を行いましたと、自ら伏線を回収している、ということですね。

別に自分はクレーマーでもなんでもないが、こんな対応は学生以下です。社会人としては恥ずかしいと思ったほうがいい。

**Comment by dadada215** [comment]
stken2050さんが仰る関係のない第三者ですが、基本的にWebサービスは問い合わせフォームが無い所が多い中で、メール含めこういった場所を設けて一個一個律儀に返信しているZennは素晴らしいサービスと思っています。この事が原因で問い合わせフォームが無くなるなんて可能性もあるかもしれませんし、公共の場で「社会人としては恥ずかしい」「学生サークル以下」という言葉は侮辱罪にあたりますし辞めた方が良いかと

**Comment by stken2050** [comment]
逆に、こういう
>チームの時間は有限であり、お問合せフォームから送られた内容全てに回答できるわけではないことをご理解ください。

というようなどこかで聞いたことのある回答が普通に返ってくる、ということは、送り手がそういう返答が社会的に普通にまかり通るという無自覚さに起因するのでしょうから、その無自覚さを指摘すれば侮辱罪だ、とかいうのも辞めたほうがいいでしょう。
自分は実際に侮辱名誉毀損の刑事告訴もしたことがありますが、それだけに安易にそういう法的手段を濫用する愚かさもよく認識しています。

あなたがZennを素晴らしいサービスと感じるのは自由で、実際に私も良さを認めるものの、総論と各論てのは別であるわけで、逆に今どき、**これだけユーザ数も多いサービスで問い合わせ窓口すら存在しないところとか本当に存在するのですか？？** 場当たり的でいい加減な擁護をしているようにしか思えません。
実際に、問い合わせフォームにしきりに誘導しておきながら無視されている、機能しているのか？と苦情、批判が入った程度で、問い合わせフォームがなくなる、となれば呆れ返るしかないです。

**Comment by catnose99** [comment]
今回いただいたお問い合わせは、発生していない事案についての内容であったこと、また本文に過激な表現が含まれていたことから回答を見送る判断をしました。

ほとんどのお問い合わせには返信をしていますが、日々多くのお問い合わせが来ることもあり、内容によっては回答が遅れる場合や返信ができない場合があります。
よろしくお願いします。

**Comment by kentutorialbook** [comment]
事実を正確に記すと「また本文に過激な表現が含まれていたこと」というような事実はなく、私が書いたのは、昨今社会問題となっているSNSにおける匿名悪用の誹謗中傷についてであり、その一例として「はてなブックマーク」を起点として発生した凶悪な事件への言及です。SNSでの凶悪事件について言及したことが「本文に過激な表現が含まれていた」だから回答を見送る判断をした、というのはおかしな話であり、本件のコメントにしても当方をブロックした上でおおよそ虚偽の事実関係を示しながら事実がわかれば納得されないような説明をされているわけですね。

ちなみに
「ほとんどのお問い合わせには返信をしていますが、日々多くのお問い合わせが来ることもあり、内容によっては回答が遅れる場合や返信ができない場合があります。」
という上記でも、ならそう書いておけば良い、という点について、
「必ずしもすべてのお問い合わせに回答できるわけではない旨を記載しました」
と改善したとあるのですが、こちらのREADMEでもしきりに誘導されている

https://docs.google.com/forms/d/e/1FAIpQLSdsDaXjtcHDtqMgxr-KVnLBfBrzOXLyMRGiF0qSoNTFAttZVA/viewform

を見ればそのような改善は見られません。どこか別のところに書いてるのかもしれませんが、異常は事実確認です。
いずれにせよ今回どういう運営なのかよくわかりましたし、以降の返信は不要です。

**Comment by tannerjohn65** [comment]
誤解を招く表現があり失礼いたしました。

> - 必ずしもすべてのお問い合わせに回答できるわけではない旨を記載しました

上記の表記につきまして、回答後の画面にて表示をしていましたが、分かりやすいように問い合わせフォームの上部にも記載を行いました。

よろしくお願いいたします。
