### ISSUE TITLE
figma を埋め込みたい

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-community#433]
## 提案・要望

figma live embed を埋め込みたい

## 背景

figma ファイルでシェアしたいが。

埋め込みの UI からサポートするか、 `<iframe>` を埋め込みたい。

https://www.figma.com/developers/embed

## 関連

N/A

**Comment by cm-wada-yusuke** [comment]
起票ありがとうございます、URLの正規表現もシェアされているのはありがたいですね。対応を検討します。

**Comment by cm-wada-yusuke** [comment]
対応しました、ぜひご利用ください。

https://zenn.dev/zenn/articles/markdown-guide#figma

**Comment by Jxck** [comment]
ありがとうございます！！
書籍で活用していきます。

**Comment by Jxck** [comment]
@cm-wada-yusuke この機能ですが、「ファイルかプロトタイプ」に限定されている理由はなんでしょうか？
figma 側は frame 単位での embed が可能なので、そちらで埋め込みたいです。
そうでないと、埋め込む画像ごとにプロトタイプかファイルを作る必要があり、図の管理が面倒になります。

例えば、以下のような感じです。

```
<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FRQig21VLvHtVpfQBSRUQWw%2FLogo%3Fnode-id%3D238%253A334" allowfullscreen></iframe>
```

**Comment by cm-wada-yusuke** [comment]
@Jxck 連絡ありがとうございます。こちらXSS対策で本家から多少改変した正規表現を入れていたのですがそれが nodeid（フレーム）を認識できないものになっていました。修正しますのでお待ちください。

**Comment by cm-wada-yusuke** [comment]
@Jxck リリースしました。こちらの記述で埋め込めると思います。よろしくおねがいします。

```
@[figma](https://www.figma.com/file/RQig21VLvHtVpfQBSRUQWw/Logo?node-id=238%3A334)
```

**Comment by Jxck** [comment]
ありがとうございます。確認しました。

https://zenn.dev/jxck/scraps/000b26d295f017

![image](https://user-images.githubusercontent.com/322289/193996356-a76af0c2-149d-4b04-9dcf-0e86313895e3.png)

(色々試したけど iframe の中で中央寄せができないのは figma の仕様なんですかね、、)

**Comment by cm-wada-yusuke** [comment]
@Jxck 
> 中央寄せ

理想はこういう状態ですか？

![image](https://user-images.githubusercontent.com/17589989/194218202-81d9e623-f1dd-4bf4-aeb6-70854fe25a4a.png)

Figma の [Share] ボタンで取得できる iframe コードをそのまま貼り付けてもTOPがくっついた状態になるので、こちらからでは制御が難しそうです。なにか制御できそうな方法が見つかったら対応したいと思います。
