### ISSUE TITLE
記事の公開日・更新日にそれぞれ datePublished、dateModified を付けてほしい

### ISSUE THREAD

**Issue by kaisugi** [zenn-dev/zenn-community#434]
#### 公開日

before

```html
<time dateTime="2021-10-18T04:08:25+00:00" class="ArticleSidebar_date__dpzqL">2021/10/18</time>
```

after

```html
<time dateTime="2021-10-18T04:08:25+00:00" class="ArticleSidebar_date__dpzqL" itemprop="datePublished">2021/10/18</time>
```

#### 更新日

before

```html
<time dateTime="2021-10-18T04:08:25+00:00" class="ArticleSidebar_date__dpzqL">2021/10/18</time>
```

after

```html
<time dateTime="2021-10-18T04:08:25+00:00" class="ArticleSidebar_date__dpzqL" itemprop="dateModified">2021/10/18</time>
```

---

あるいは、https://developers.google.com/search/docs/advanced/appearance/publication-dates?hl=ja の3にあるように JSON を追加するのでもよいかもしれません（ちなみに Qiita はそうしていました）

## 背景

Zenn の各記事において、Google 検索の検索結果に表示されている日付が更新日ではなく公開日になっている例が見られます。

例: 私の https://zenn.dev/hellorusk/articles/ddee520a5e4318 という記事は随時更新しているのですが、Google 検索の画面では以下のように公開日（2021/10/17）が表示されているままです。

![スクリーンショット 2022-09-06 9 04 53](https://user-images.githubusercontent.com/36184621/188522287-b8488a19-87d2-49cc-987d-4a5f8ab9a8ee.png)

可能であれば、随時更新していることが伝わるように、更新日で表示されてほしいなと思います。

Google が更新日の情報を取得できるように、datePublished 、dateModified を明示するのがよいのかなと思いました。

https://developers.google.com/search/docs/advanced/appearance/publication-dates?hl=ja

**Comment by cm-wada-yusuke** [comment]
詳細に提案いただきありがとうございます！こちら導入したいと思います、しばらくお待ち下さい。

**Comment by cm-wada-yusuke** [comment]
itemPropに `dateModified` を入れてしばらく様子をみていたのですが、検索結果に反映されないですね…
JSONにしたほうがいいのかなとおもいつつ、XSSのリスクがあるのでちょっと慎重になっています。もうすこし調査の時間をください。

```
<time dateTime="2022-10-21T00:24:19+00:00" class="ArticleSidebar_date__dpzqL" itemProp="dateModified">2022/10/21</time>
```
↓
<img width="725" alt="image" src="https://user-images.githubusercontent.com/17589989/199141035-569b0ef5-f200-462d-a623-b49e9d9aa4e3.png">

**Comment by kaisugi** [comment]
実は、既に同じ対応をとっているはずの Qiita の自分の記事も、なぜか Google 側が更新日を取ってくれていないのですよね...
こればかりは Google 側の問題なので仕方ないと思います！
この Issue は close で大丈夫です。ご対応ありがとうございます。

**Comment by cm-wada-yusuke** [comment]
[いただいたページ](https://developers.google.com/search/docs/advanced/appearance/publication-dates?hl=ja) をみると、Google 側も itemProp よりはJSONでやってほしい雰囲気を感じますね。

>既に同じ対応をとっているはずの Qiita の自分の記事も、なぜか Google 側が更新日を取ってくれていないのですよね...
そうなのですね。情報ありがとうございます。また動きがあったらISSUEを復活させます。
