### ISSUE TITLE
記事のCard下部をクリックしても記事詳細画面に遷移するようにしてほしい

### ISSUE THREAD

**Issue by kk3939** [zenn-dev/zenn-community#436]
## 提案・要望
記事のカード下部？をクリックした場合でも記事詳細画面に遷移してほしい。

## 背景
カードをクリックした際に`<div class="ArticleCard_meta__~~~~~">~~~~</div>`要素をクリックするとリンク先に遷移しない。気づかず何回もクリックしてしまったので、わかりづらく改善してもらえると嬉しい。

※ここでいう`<div class="ArticleCard_meta__~~~~~">~~~~</div>`とは、以下の画像の部分である。

![スクリーンショット 2022-09-11 1 01 02](https://user-images.githubusercontent.com/45879786/189491687-39b9e562-5a03-49d8-80d8-df91a1ee75e0.png)

## 関連
意図的にしているのかもしれないし、バグだったとしても優先度が高くないと思うので、Feature requestとして登録しました。
ご検討のほどよろしくお願い致します。

**Comment by catnose99** [comment]
こちらバグでしたので対応しました。ご指摘ありがとうございました。

**Comment by kk3939** [comment]
@catnose99 早い対応ありがとうございます！🙇‍♂️
