### ISSUE TITLE
リポジトリ連携によりデプロイされた記事や本が反映された時に発火するhookが欲しい

### ISSUE THREAD

**Issue by sor4chi** [zenn-dev/zenn-community#437]
## 提案・要望

タイトルのままなのですが、記事や本のデプロイが反映されたタイミングでユーザーが設定可能なwebhookを発火してくれる機能が欲しいです。

## 背景

zenn.devのrssを用いて自分の記事を表示するサイトをNext.jsで作っているのですが、On-Demand ISRをする際にデプロイ元のリポジトリでgithub actionsを用いてhookを発火させると、反映前にそのActionが動いてしまい最新のrssを取得できないため、きっちり反映後のタイミングを取得する手段が欲しいと思いリクエストさせていただきました。
（不安定動作にはなりますが定数秒待つという方法は取れるとおもいます）

**Comment by catnose99** [comment]
ありがとうございます。
RSSがしばらくキャッシュされているため、webhookでデプロイ完了時に通知した場合にも最新のRSSを取得できない可能性があるため、そのあたりを含めて検討してみます。
対応する場合も対応まではしばらく時間がかかりそうです。

現状だとGitHub Actionsなどで定期的にVercelにデプロイをし直していただく等の対応が必要になりそうです。

https://zenn.dev/nikaera/articles/vercel-github-actions

ご不便をおかけしますが、よろしくお願いします。

**Comment by sor4chi** [comment]
ご返信ありがとうございます、なるほど確かにzennはon-demand cacheじゃないですもんね...
時間がかかりそうな件、把握しました。

参考リンクありがとうございます🙇こちらでもうまくやりくりできないか検討してみます。
検討のほどよろしくお願いいたします。

**Comment by uttk-dev** [comment]
現在は対応しない方針になりました。
