### ISSUE TITLE
アップロードした画像の削除

### ISSUE THREAD

**Issue by SnowCait** [zenn-dev/zenn-community#438]
## 提案・要望
アップロードした画像の管理（削除）を行えるようにしていただけるとありがたいです。
もしくは記事から参照のない画像を自動削除していただけると嬉しいです。（既にあったらすみません）

## 背景
誤ってアップロードしてしまった画像（特にパスワードやトークン等の秘匿情報を含んでしまっていたもの）を削除したいと思いました。
URL は推測しにくくなっているとはいえやはり残ってしまうのは少し気になるなーと。

**Comment by cm-wada-yusuke** [comment]
すべてのアップロード画像を管理するとかなりの数になってしまうので、構成含め検討します。ただ、たしかにセンシティブな情報を含めてしまった画像は後から消せるようにしたいですね。
