### ISSUE TITLE
本に載せたYouTubeが稀に「この動画は再生できません」と表示されます

### ISSUE THREAD

**Issue by daichi-takezawa** [zenn-dev/zenn-community#439]
## 事象
本のページを移動させた時などにアップしたYouTubeが稀に「この動画は再生できません」と表示される。一度更新すると元に戻るみたいです。

## 発生したページのURL
https://zenn.dev/daichi_gamedev/books/unreal-engine-tutorial/viewer/blueprint-movingactor
この本にアップしている多数のYouTubeでなぜか稀に「この動画は再生できません」と表示される事を確認しています。動画自体は埋め込みができない設定などにはしていない事は確認済みです。

## 発生した画面のスクリーンショット
![2022-09-21_12h15_08](https://user-images.githubusercontent.com/50498401/191407166-055908ed-1618-47ec-bd62-4c4b2d01a772.jpg)

## 再現方法
本のページから異なるページへ移動した時によく起こります。

## コメント
スマホでも同じ本を見てみましたがスマホだと問題なく表示されました。使っているのはWindowsです。たまにですし、更新すれば通常通り元にもどるようなので今の所大きな支障はありませんが一応お伝えさせて頂きました。よろしくお願いします。

**Comment by cm-igarashi-ryosuke** [comment]
@daichi-takezawa ご報告ありがとうございます。

おそらく、こちらの事象と関連があるかと思いました。
https://github.com/zenn-dev/zenn-editor/pull/352#issuecomment-1234963514

再現方法、チャプターの順序を入れ替えたということでしょうか？それとも、youtubeの埋め込みだけを別のチャプターに移動したということでしょうか？詳しく教えていただけると幸いです。こちらでも再現確認と調査をしてみます。

**Comment by daichi-takezawa** [comment]
ご対応ありがとうございます。再現方法はこんな感じ↓にページをめくった時の事を指しています。
![dwadadwa (779)](https://user-images.githubusercontent.com/50498401/191455521-8c6263b9-53f0-4f4f-a768-a23784da6ea6.gif)


ただもう一度キャッシュ等も削除して再度全てのページを確認しましたが、動画が再生できないという現象は確認できなかったのでちょっとどのタイミングでこのバグが起こるのか正確にはわからないです...

**Comment by cm-igarashi-ryosuke** [comment]
@daichi-takezawa 詳細な情報をありがとうございます。

こちらでも確認してみました。該当の本では発生しませんでしたが、はじめて埋め込むYouTube動画ではやはり発生しました。おそらくYouTube側になんらかのキャッシュが存在する間は発生せず、初回アクセスorキャッシュの有効期限が切れてはじめてアクセスした場合に発生するのではないかと推測しています。キャッシュの有効期限はHTTPレスポンスから確認することはできませんでした。

体感的に稀に発生するという頻度であればしばらく様子見とさせてください。より顕著に発生するような感じであれば、 https://github.com/zenn-dev/zenn-editor/pull/352 のような対応を含め検討したいと思います。解決にならず申し訳ないです。

**Comment by daichi-takezawa** [comment]
いえ、お伝えだけしておこうと思っていたのでここまで対応してくださって満足しています。丁寧な対応ありがとうございました🙇🏻‍♂️これからもZenn使わせて頂きます🙏🏻

**Comment by cm-igarashi-ryosuke** [comment]
@daichi-takezawa #392 にて対応をいたしました。これから作成・変更されるコンテンツについては対応が反映されますが、既存のコンテンツについては少し時間をおいて反映させる予定ですので、ご承知おきください 🙏

**Comment by daichi-takezawa** [comment]
ありがとうございます!助かります!
