### ISSUE TITLE
Publicationの記事レビュー機能に関するご意見募集

### ISSUE THREAD

**Issue by cm-igarashi-ryosuke** [zenn-dev/zenn-community#440]
## 提案・要望
Publicationの記事レビュー機能に関するご意見をこのissueにて募集します。

## 背景
zennチームでは、記事のレビュー機能の仕様について議論を重ねてきましたが、組織によってレビュー機能に求める要件が異なることが予想されるため、現状では「Publicationのメンバーなら下書きを閲覧できる」という最低限の機能にとどめています。

今後レビュー機能を改善するため、みなさまが、どのような運用フローの元、どのようなレビュー機能を求めているか、ぜひご意見をお聞かせください。

※ご意見は参考情報であり、多数意見がそのまま反映されるものではないということは予めご了承ください。

**Comment by ensan-hcl** [comment]
こんにちは。所属組織でしばらくPublicationを使っております。とても良い機能だと感じています。

現状はGoogle Document、Notionなどでレビューを行い、Zennで限定公開でレイアウト等をチェックし、問題なければPublishする、という運用をしています。記事レビューには非エンジニアも参加することがあるため、GitHub連携によるレビューフローは現状採用していません。

困っている点として、限定公開まで来た記事で小さな誤字が見つかった場合の修正フローが大仰だと感じています。Google DocsやNotionでは誰でも編集できるので勝手に編集してしまうのですが、Zennではわざわざauthorに連絡して作業してもらわないといけないため、指摘自体が躊躇されてしまいます。

アイデアとしては、管理者権限よりも弱めた「エディター権限」のようなものがあれば「小さい誤字なら勝手に修正する」というような運用ができてスムーズになると思います。
あるいはQiitaの「編集リクエスト」のようなものがPublication内部で運用できれば、authorはリクエストを確認してacceptするだけで済むようになると思います。

この辺りが楽になると非常に使いやすいです。

**Comment by cm-igarashi-ryosuke** [comment]
締め切らせていただきます。ご意見いただきありがとうございました。
