### ISSUE TITLE
zenn-cli の preview 環境を Safari で開くと published_at のバリデーションエラーが発生する

### ISSUE THREAD

**Issue by swiftty** [zenn-dev/zenn-community#441]
## 事象
`published_at` を付加した際、正しいフォーマットにも係わらず下記エラーメッセージが表示される

```
published_at（公開日時）は `YYYY-MM-DD` または `YYYY-MM-DD hh:mm` のフォーマットで指定してください
```

合わせてフォーマットを日時のみ（`YYYY-MM-DD`）にすると `原因不明のエラーが発生しました` と表示される
また chrome で見た際はどの場合でも正しく動作した

## 環境

- OS: macOS 12.5.1
- Browser: Safari 15.6.1
- zenn-cli: 0.1.128

**Comment by uttk-dev** [comment]
@swiftty 

こちらのバグを修正したバージョン(`zenn-cli@0.1.129`)をリリースしましたので、
この Issue はクローズさせて頂きたいと思います。 

バグ報告ありがとうございました！
