### ISSUE TITLE
モバイルで記事を表示した際、最上部にいいねボタンだけでなく「いいね数の表示」がほしいです

### ISSUE THREAD

**Issue by ttskch** [zenn-dev/zenn-community#442]
## 提案・要望

モバイルで記事を表示した際、最上部にいいねボタンだけでなく「いいね数の表示」がほしいです。

## 背景

モバイルで記事を表示した際、その記事のいいね数を知るためには記事の終端部分までスクロールする必要があります。

長い記事だとかなりの量スクロールしなければならず、またページ最下部ではなく記事の終端部分なので良いところでスクロールを止めなければならないのでなお面倒です😓

ページ最上部にいいねボタンだけでなくいいね数が表示されているととてもありがたいです。

## 関連

なし

**Comment by uttk-dev** [comment]
@ttskch 

提案ありがとうございます。
開発チームに持ち帰って、検討したいと思います。
ただ他の重要なタスクなどに注力しているため、対応に時間がかかる可能性がありますので、
その点はご留意ください。

**Comment by cm-igarashi-ryosuke** [comment]
@ttskch 大変長らくお待たせいたしました。モバイル表示でヘッダー部のいいねボタンの下に「いいね数」を表示するようにしました。

チーム内でも大変好評です。
ご提案いただきありがとうございました。
