### ISSUE TITLE
アイコンを変更後にOGP内のアイコンが変更されない。

### ISSUE THREAD

**Issue by ken7253** [zenn-dev/zenn-community#444]
## 事象
zennのアイコンを変更した後に公開した記事のOGP画像上にあるユーザーアイコンに古いものが使用されてしまう。

1ヶ月ほど前にアイコンを変更したあとに作成・公開した記事のOGP画像に古いユーザーアイコンが適用されていました。
昔の記事のOGPもアイコン変更時に更新するというのは厳しいと思いますが、アイコン変更後に投稿した記事に関しては新しいアイコンが表示されているとありがたいです。

## 発生したページのURL
https://zenn.dev/ken7253/articles/env-variable-type-definition

## 発生した画面のスクリーンショット

![image](https://user-images.githubusercontent.com/57705206/194274128-a87274bf-92e5-438d-94ff-60e6bc4312ac.png)

TwitterをWebで確認した際のOGP

![image](https://user-images.githubusercontent.com/57705206/194274183-39f248d8-711c-4870-a81c-4b121459d1c7.png)

現在のアカウント画像

## 再現方法

1. アカウントの画像を変更
2. zenn-cliにて記事作成
3. 記事の公開
4. ツイッターにリンクを共有

## 環境
環境依存である可能性は低いですが確認時のブラウザは下記です。

- Google Chrome 105.0.5195.127 (Official Build) （64 ビット） (cohort: Stable)

**Comment by uttk-dev** [comment]
@ken7253 

Issue での報告ありがとうございます。

こちらで調べたところ、アイコン画像にGoogleアカウントのアバター画像を使用しているようでした。
この場合、Google側のキャッシュにより1〜2日ほど反映に時間がかかる場合があります。

また、Zenn では OG 画像生成に Cloudinary を使用しているため、Cloudinary 側のキャッシュも有効になっているのですが、
Googleアカウントのアバター画像を使っていると、Cloudinary 側のキャッシュが長時間更新されないようです。

そのため、OG画像にアイコンの変更をすぐ反映させたい場合は、お手数ですが [Zenn のプロフィール編集ページ](https://zenn.dev/settings/profile) からアイコン画像をアップロードして頂く必要があります。

よろしくお願いします。

**Comment by ken7253** [comment]
ご確認ありがとうございます！なるほどですね。
お手数おかけしてしまい申し訳ありません🙇

> そのため、OG画像にアイコンの変更をすぐに反映させたい場合は、お手数ですが [Zenn のプロフィール編集ページ](https://zenn.dev/settings/profile) からアイコン画像をアップロードして頂く必要があります。

こちらの方法でアイコンを変更させていただきます！
ご対応ありがとうございました！
