### ISSUE TITLE
mermaid.js の gitGraph が表示されない

### ISSUE THREAD

**Issue by korosuke613** [zenn-dev/zenn-community#446]
## 事象

mermaid.js によるダイアグラム表示について、[gitGraph](https://mermaid-js.github.io/mermaid/#/gitgraph) が表示されません。
また、エラーメッセージも表示されません。

## 発生したページのURL

zenn.dev の記事編集ページです。

## 発生した画面のスクリーンショット

コード
<img width="400" alt="スクリーンショット 2022-10-12 0 30 19" src="https://user-images.githubusercontent.com/20027695/195134808-3673de78-6d69-4e10-a23a-5346f5075ab2.png">

プレビュー
<img width="400" alt="スクリーンショット 2022-10-12 0 30 27" src="https://user-images.githubusercontent.com/20027695/195134829-29a09dbc-9583-4a42-9d67-934b2ad65e1d.png">

記事（非公開）
<img width="400" alt="スクリーンショット 2022-10-12 0 34 00" src="https://user-images.githubusercontent.com/20027695/195135605-99cf760b-9fa1-436e-8e82-c69ebbbad752.png">

## 再現方法

以下のコードブロックを zenn.dev のエディタに貼り付けます。
このスニペットは [mermaid.js の gitGraph ページにあるサンプルコード](https://mermaid-js.github.io/mermaid/#/gitgraph?id=gitgraph-diagrams)です。

````markdown

```mermaid
gitGraph
   commit
   commit
   branch develop
   checkout develop
   commit
   commit
   checkout main
   merge develop
   commit
   commit
```

````

**Comment by uttk-dev** [comment]
@korosuke613 

報告ありがとうございます。
修正して Git Graph が表示されることが確認できたため、この Issue はクローズしたいと思います。
よろしくお願いします！

**Comment by korosuke613** [comment]
ご対応ありがとうございました！
