### ISSUE TITLE
コードブロック内の半角2つを全角1つと同じ幅にしてほしい

### ISSUE THREAD

**Issue by akicho8** [zenn-dev/zenn-community#448]
## 提案・要望

コードブロック内の半角2つを全角1つと同じ幅になっているとありがたいです

元のテキスト (GitHub上でも表示が崩れて困っているのはいったん置いておく)
```
|------------+------|
| 商品       | 価格 |
|------------+------|
| あ         |  120 |
| あい       |  120 |
| あいう     |  120 |
| あいうえ   |  120 |
| あいうえお |  120 |
|------------+------|
```

テキストエディタ上の表示
<img width="620" alt="スクリーンショット 2022-10-12 18 10 46" src="https://user-images.githubusercontent.com/808955/195301679-b4d56d93-709d-4212-92c2-a3981444a585.png">

Zenn Editor 上での表示
<img width="276" alt="スクリーンショット 2022-10-12 18 10 17" src="https://user-images.githubusercontent.com/808955/195301698-18cecf0b-e275-41ef-9c7d-12e11194f76c.png">

## 背景

最終的には綺麗に見えるMarkdownの表を作るのが目的ではなく、テキストだけを使った表を生成するプログラムの出力をそのままコードブロックに入れたいのが目的の場合、表示が崩れるのが困っています

**Comment by catnose99** [comment]
これはたしかに自分も気になっているところです。
日本語対応の等幅フォントをWebフォントとして読み込むことで解消できると思われますが、通信負荷やパフォーマンスやライセンス等の問題から現状難しそうです。申し訳ないですがクローズさせていただきます。
