### ISSUE TITLE
Google AnalyticsをPublicationに対しても設定できるように

### ISSUE THREAD

**Issue by subroh0508** [zenn-dev/zenn-community#449]
## 提案・要望
Publicationに対しGAのトラッキングIDを設定できると嬉しいです！
※Publicationに招待されたアカウントのGAとは別に設定する想定です。

## 背景
Publicationに投稿された記事についてアクセスの解析をしたいのですが、現状ですと解析情報が各アカウントのGAに分散してしまうため、不便と感じています。

**Comment by cm-igarashi-ryosuke** [comment]
@subroh0508 ご意見ありがとうございます。Publication単位での統計機能、GAやその他の方法を含め検討しています。2023年前半には提供できればという感触です。しばらくご不便をおかけしますがお待ちいただけると幸いです。
