### ISSUE TITLE
Markdown表の機能拡張

### ISSUE THREAD

**Issue by mocapapa** [zenn-dev/zenn-community#450]
## 提案・要望
Markdownでは通り一遍の表しか作成できない。
コラム結合、ロウ結合等の、htmlで言うところのcolumsnap, rowspanができる表を作成したい。

## 背景
某qiitaの記事をimportするときに某qiitaでも表記の表は作成できなかったが、HTMLでテーブルを記述してcolumnspan, rowspanを駆使して、希望する表を作成した。

**Comment by tannerjohn65** [comment]
リクエストいただきありがとうございます。現状、他の優先度が高いタスクがある/影響範囲が広いこともあるため、今後実現方法含めて検討いたします🙏

**Comment by tannerjohn65** [comment]
こちら再度チームで検討いたしましたがMarkdownの標準的な記法で対応ができず、現状実現が難しいためクローズいたします。
