### ISSUE TITLE
記事のオーナーを変更したい

### ISSUE THREAD

**Issue by 052hide** [zenn-dev/zenn-community#451]
## 提案・要望

- Publicationのオーナー権限を持つユーザーは、自身が保有する記事を他のPublicationメンバーに委譲できるようにする
- いいね数などを引き継げるようにする
- 元のURLにアクセスした場合は変更先の記事ページへリダイレクトされるようにする

## 背景

- Publicationベータリリース以前は組織の代表者の個人アカウントで記事を投稿していた
- Publicationがベータリリースされたので、過去の記事も個人に委譲しPublicationに紐付けられるようにしたい

**Comment by cm-igarashi-ryosuke** [comment]
@052hide こちらから依頼していただくと対応できます。

https://zenn.dev/zenn/articles/transfer-article

機能として提供するには制約が多く条件も複雑なので、このような形での対応となっております。

**Comment by 052hide** [comment]
@cm-igarashi-ryosuke

ありがとうございます！
そちらの記事の手順で依頼させていただきます。
