### ISSUE TITLE
ユーザー/キーワードに基づくミュート

### ISSUE THREAD

**Issue by unvalley** [zenn-dev/zenn-community#452]
## 提案・要望

ユーザーやキーワードに基づいたミュート機能が欲しいです．
Twitterにあるミュート機能と同じように，「あるユーザーによる記事・書籍」や「あるキーワードが含まれた記事・書籍」をトレンドや検索結果から除外するイメージです．
トレンドと検索結果の改善の提案として捉えていただけると嬉しいです．

## 背景

zennには多くの有益な記事・書籍があり，開発や技術のキャッチアップに助けられています．
一方で，一部には煽るようなタイトルを書くユーザーもおり，トレンドを眺める際のストレスになっています．

**Comment by tannerjohn65** [comment]
お世話になっております、本件リクエストいただきありがとうございます。
現状、チーム内で投稿フィードに表示される情報について、よりユーザーの方がアクセスしたい内容が表示されるように見直しを行っている最中です。
他の手段も含めて、よりユーザーの方がアクセスしたい情報にアクセスできるように検討いたします。

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ミュート機能についてはニーズが限定的であり実装コストに見合わないため対応しないこととなりました。

背景の事情は理解できますので、今後のサービス開発・コミュニティ運営でも考えていきたいと思います。
