### ISSUE TITLE
検索画面で表示されないトピックがある

### ISSUE THREAD

**Issue by akaboshinit** [zenn-dev/zenn-community#453]
## 事象

Cloudflare Workersについて試している際、ZennにあるCloudflare Workersを再度見直そうと調べると
検索の中に"Cloudflare Workers"のトピックが表示されませんでした。

ですが”Cloudflare Workers”で調べた後に出る”関連するトピック”では”Cloudflare Workers”のトピックは存在します
検索後の画面: https://zenn.dev/search?q=Cloudflare%2520Workers
トピック: https://zenn.dev/topics/cloudflareworkers

また、トピック全体の画面に表示される
”このトピックを指定するには cloudflareworkers と入力”
文言の "cloudflareworkers" でも同じく検索に引っ掛からなくなっています

## 発生したページのURL

検索画面
https://zenn.dev/search

## 発生した画面のスクリーンショット

Cloudflare Workersで検索した場合の検索画面

<img alt="Cloudflare Workersで検索した場合の検索画面" src="https://user-images.githubusercontent.com/69136342/197347062-5e57fc33-5bb2-4ef6-b5f9-8c302fcd3805.png" width="400">

検索で想定される"Cl"ほどの短文で検索した場合の検索画面

<img alt="検索で想定される'Cl'ほどの短文で検索した場合の検索画面" src="https://user-images.githubusercontent.com/69136342/197347063-550782cd-490c-4bf3-99f2-56a8fe960631.png" width="400">

pathにも使われている"cloudflareworkers"で検索した場合の検索画面

<img alt="cloudflareworkersで検索した場合の検索画面" src="https://user-images.githubusercontent.com/69136342/197347065-25319229-278a-4465-a34d-721d8d09f053.png" width="400">

## 再現方法

zenn検索画面 ( https://zenn.dev/search )で"Cloudflare Workers"を入力

## 環境

環境依存は無いと考えられる

---
素晴らしいサービスをありがとうございます🐕zennがより良いサービスになることを願っています🦧

**Comment by cm-igarashi-ryosuke** [comment]
@akaboshinit ご報告ありがとうございます！

検索画面（ https://zenn.dev/search ）に表示されるトピックですが、こちらは「人気のトピック」となっておりまして、あらかじめ読み込まれた使用頻度の高いトピックが検索フォームに入力された文字でインクリメントサーチされる仕組みになっております。

現在、 `Cloudflare Workers` は「人気のトピック」には含まれないので、インクリメントサーチでは表示されません。

`Cloudflare Workers` を入力し、Enterキーを押すことで、「関連するトピック」として検索結果が表示されます。

![image](https://user-images.githubusercontent.com/13619209/197435357-cd8ef685-d992-4584-b655-68c55cf4ef98.png)

また、 `cloudflareworkers` で検索した場合はトピックがあるのにも関わらず「検索結果が見つかりませんでした」と表示されます。この事象については、ヒットしたコンテンツが1件もないため「関連するトピック」を表示する領域がないためこの様に表示されています。この点については改善したいと考えています。

![image](https://user-images.githubusercontent.com/13619209/197435540-2b6b65df-c0b7-4a73-b15f-02a278f4522f.png)

**Comment by cm-igarashi-ryosuke** [comment]
> また、 cloudflareworkers で検索した場合はトピックがあるのにも関わらず「検索結果が見つかりませんでした」と表示されます。この事象については、ヒットしたコンテンツが1件もないため「関連するトピック」を表示する領域がないためこの様に表示されています。この点については改善したいと考えています。

この問題について検討したのですが、現状の仕組みでは影響の大きさに対して実装コストがかかりすぎることから、対処しないこととします。今後、検索エンジンなどの置き換えが行われれば解決される可能性があります。
