### ISSUE TITLE
自身が所属し、かつフォローしている Publication に対して自身が記事を投稿した際にその情報を Following に表示させないでほしい

### ISSUE THREAD

**Issue by korosuke613** [zenn-dev/zenn-community#454]
## 提案・要望

自身が所属し、かつフォローしている Publication に対して、自身が記事を投稿すると、Following タブに自身が記事を投稿した旨が表示されます。

フォローしている Publication に自身が投稿したという情報を表示させないでほしいです。

<img width="700" alt="スクリーンショット 2022-10-23 3 32 20" src="https://user-images.githubusercontent.com/20027695/197357342-45e4bf51-4a3d-49a9-a4c3-b09636711689.png">

## 背景

自身が所属している Publication をフォローしている理由は、同じ Publication に所属する他のユーザが記事を投稿したときにそれを Following タブで知りたいからです。

自身が投稿したという情報を表示させないでほしい理由は、自身が投稿したという情報は自身にとってわかりきっており、Following タブを見ている際にノイズとなるからです。

**Comment by cm-igarashi-ryosuke** [comment]
@korosuke613 ご提案ありがとうございます！

先ほど修正してリリースいたしました。

**Comment by korosuke613** [comment]
素早いご対応ありがとうございました😊！
