### ISSUE TITLE
macOS (Intel) の環境で control と P を同時に押すとカーソルの移動機能とプレビュー機能が同時に働く

### ISSUE THREAD

**Issue by terasakisatoshi** [zenn-dev/zenn-community#455]
## 事象

編集画面で コントロールキーと P 同時に押す(`Control-P` と呼ぶことにする) と Preview 画面に遷移する. 同時にカーソルも一行上に行く.

## 発生したページのURL

本や記事を作成する画面で生じる

## 発生した画面のスクリーンショット

`Control-P` を複数回入力している様子をキャプチャーした様子です.

https://user-images.githubusercontent.com/16760547/197538506-c5b89701-9674-4385-9baf-f20af41de069.mov

## 再現方法

本や記事を作成する画面で生じる

## 環境

macOS (Intel)

<img width="304" alt="image" src="https://user-images.githubusercontent.com/16760547/197539160-4d458640-ac9a-4731-92fa-c455316e7480.png">

Google Chrome: Version 106.0.5249.119 (Official Build) (x86_64)

## 期待する動作

macOS では `Control-P` はカーソルを一行上に持っていくショートカットキーとして割り当てられているので Preview に移行する機能がはたらかないこと.

参考: https://support.apple.com/en-us/HT201236

> Control-P: Move up one line.

コマンドキーと P を同時に入力 `Command-P` でプレビュー機能が働くのでユーザ側は

1. カーソルを一行上に移動させるならば `Control-P` を入力
2. プレビュー機能を利用したいならば `Command-P` を入力

というようにキーバインドを棲み分けてほしい.

**Comment by uttk-dev** [comment]
@terasakisatoshi 

報告ありがとうございます。
ショートカットキーの変更はユーザーへの影響が大きいため、
一度開発チームに持ち帰って、検討したいと思います。

なるべく早く対応したいと思っていますが、
他の優先度の高いタスクがあるため、対応に時間がかかる場合があります。
その点、ご留意いただければと思います。よろしくお願いします。

**Comment by tfutada** [comment]
何か回避策はないでしょうか？

**Comment by cm-wada-yusuke** [comment]
こちら改修で入り込んだバグでした、申し訳ないです、近日中に修正リリースしますのでお待ち下さい。

**Comment by cm-wada-yusuke** [comment]
先程リリースし、解消されました。MacOSにおいてはCmd+Pでのみプレビューモードとなります。ご報告ありがとうございました。

**Comment by terasakisatoshi** [comment]
@uttk-dev 
@cm-wada-yusuke 

:bow:
対応いただきありがとうございました．本日 2022/11/02 現在の挙動は期待した挙動になっています．

https://user-images.githubusercontent.com/16760547/199515444-c21a2e57-4a69-4135-9838-1ef65f4e1bcc.mov
