### ISSUE TITLE
プレビューモードのキーバインド変更

### ISSUE THREAD

**Issue by anneau** [zenn-dev/zenn-community#456]
## 提案・要望

現状、Ctrl + Pでプレビューモードに変更されますが、別のキーバインドに変更してほしいです。

## 背景

Macのカーソル移動で一段上の行に移動する時Ctrl + Pを使うため、キーバインドの衝突が起きてしまいます。

https://www.find-job.net/startup/mac-shortcut

↑この辺りのキーバインドは使用を避けてもらえると嬉しいです、、

**Comment by tannerjohn65** [comment]
こちら、ご報告ありがとうございます。
キーバインドの変更については既にリクエストをいただいており以下のIssueにて対応するため、こちらのIssueはクローズさせていただきます。
今後、検討/対応していく予定です！
https://github.com/zenn-dev/zenn-community/issues/455
