### ISSUE TITLE
スクラップの「編集」で下書きが存在する場合は、キャンセルボタンを押した際に削除確認アラートを出してほしい

### ISSUE THREAD

**Issue by TakashiAihara** [zenn-dev/zenn-community#457]
## 提案・要望

スクラップの「編集」で下書きが存在する場合は、キャンセルボタンを押した際に削除確認アラートを出してほしい。

## 背景

編集で長文を追記し「更新」ボタンを押そうとしたところ、誤ってすぐ横にある「更新」ボタンを押してしまい、
書き溜めた内容が消え去った。
ワンアクションではデータが消えないようにしてほしい。

https://user-images.githubusercontent.com/47384567/198754834-7396d795-8385-45f9-995b-5aadb24e3285.mp4

**Comment by cm-igarashi-ryosuke** [comment]
@TakashiAihara ご提案ありがとうございます。確かにアラートがあったほうが良いですね。順次対応したいと思います。

**Comment by catnose99** [comment]
こちら対応しました！
