### ISSUE TITLE
GitHubアカウントでログインできない

### ISSUE THREAD

**Issue by czbone** [zenn-dev/zenn-community#458]
## 事象
GitHubのアカウントで認証してログインしていましたが、突然ログアウト状態になりました。
「Log in」ボタンを押してダイアログを表示しても、Googleアカウントでのログイン用のボタンしか表示されません。
ログインできない状態なので、書きかけの記事などオリジナルのコンテンツにまったくアクセスできません。

## 発生したページのURL
サイト内のすべてのページ

**Comment by czbone** [comment]
私の勘違いでした。キャンセルします。

**Comment by cm-igarashi-ryosuke** [comment]
@czbone はい、GitHubアカウントでの認証はもともとありません。突然ログアウトしてしまった原因としましては、昨日のリリースの影響で一部のユーザーさまのログインセッションが無効になってしまったことが確認されており、その影響と考えられます。ご不便をおかけしまして申し訳ございませんでした。
