### ISSUE TITLE
技術記事への検証環境用のフィールド追加

### ISSUE THREAD

**Issue by lovetanpopo** [zenn-dev/zenn-community#46]
技術系の記事だと、記事を書いたタイミングのバージョンに依存していたりすることが多々あると思います。
探す側が探しやすいように、また、書く側も環境記載を忘れないように、専用のフィールドを用意して見は如何でしょうか？

**Comment by catnose99** [comment]
面白いアイデアだと思います。
同様のことをやるとしても少し先になると思うので一旦closeさせていただきます。

**Comment by catnose99** [comment]
これ良いかもなー
