### ISSUE TITLE
GoogleログインのボタンとGoogleログインガイドラインに関して

### ISSUE THREAD

**Issue by Yudai-Saito** [zenn-dev/zenn-community#461]
## 提案・要望
こんにちは、Zennのログインボタンに関しての質問になります！
Googleログインのブランドの取り扱いガイドラインに抵触する可能性がある点が2点ありましたので見解をいただければと思います。

### ボタンのカラー
ガイドラインによると、ボタンの背景は青(#4285F4)または白(#FFFFFF)のいずれかと指定されてあります。
ZennのGoogleログインのボタンを確認してみると#eff6fb99が設定されています。  

- [ログインブランドの取り扱いガイドライン/カラー](https://developers.google.com/identity/branding-guidelines?hl=ja#color)

### ボタンのパディング
ロゴとボタンテキストの間に24dpの間隔が設定されていないと思われます。  

- [ログインブランドの取り扱いガイドライン/パディング](https://developers.google.com/identity/branding-guidelines?hl=ja#padding)

## 背景
- Login with Googleのカラーが指定のものでない。
- アイコンとテキストの間のパディングが適切でない。  

![image](https://user-images.githubusercontent.com/42965816/200471502-8d7b94ae-3040-4baf-ac83-5d69bc0440f6.png)

**Comment by cm-igarashi-ryosuke** [comment]
@Yudai-Saito ご指摘ありがとうございます！ガイドラインに沿った表現に修正したいと思います。

**Comment by cm-igarashi-ryosuke** [comment]
@Yudai-Saito ガイドラインを確認しました。視認性や他のサードパーティーログインと同等に表現されていれば、ある程度はサイトのデザインに合わせてカスタマイズすることを許容されていると解釈しました。

カラーについては標準色（白）にしてもサイトのデザインを損なうことがないため、白に変更しました。
ボタンのパディングについては、dpという単位ををCSSで正確に表現することが難しく、他のGoogleログインを採用している大手サイトを見ても厳密に従っていないケースが多いため、カスタマイズの範疇として現状維持としました。
