### ISSUE TITLE
SVG に対応して欲しい

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-community#465]
> 対応する拡張子は .png .jpg .jpeg .gif のみ

記事に用いる画像は drawing tools などで書いた図も多く、 SVG で吐くことが可能なものが多くあります。
SVG であれば、ラスタよりもサイズが小さいことが多く、一つのファイルで様々な解像度に対応でき、環境によって潰れたりもしません。

恐らくラスタを前提として CDN 側の画像配信システムが作られていると思いますが、できたら SVG をそのままアップロードしたいです。

**Comment by cm-igarashi-ryosuke** [comment]
@Jxck ご提案ありがとうございます！

SVGの対応については過去に検討したのですが、SVGには任意のScriptを埋め込めることからXSSなどリスク対応が必要になります。一方でSVGでなければならないユースケースはほぼないと考えており、サービスとしてリスクを負ってまでユーザーに与えられるメリットは少ないため、対応しないという結論になりました。

現状でSVGに対応していないことで、特に困っていることなどはありますでしょうか？
