### ISSUE TITLE
画像が横並びにできるようにしてほしい。

### ISSUE THREAD

**Issue by dogTK** [zenn-dev/zenn-community#466]
## 提案・要望

SSIA

**Comment by tannerjohn65** [comment]
記事の執筆時に画像を横並びに複数表示したいというリクエストかと思いますが、記法追加については標準的なMarkdownの記法から逸れることやEditorへの影響が広いことから現状は対応が難しいです。。。
こちらは、ワークアラウンドとなりますが、Tableの列として画像を埋め込むと横並びの表示は可能であるため、既にご存知かもしれませんがご紹介させていただきます。

```
|![img_name_1.png](path_to_img)|![img_name_2.png](path_to_img)|
|---|---|
|img_name_1|img_name_2|
```

引き続き、よろしくお願いいたします。

**Comment by cm-wada-yusuke** [comment]
スマホ表示での横並びをどう表示するか？など考慮するべき点があり、現時点では対応が難しいです。上記ワーアラウンドをご検討ください。
