### ISSUE TITLE
Twitterの埋め込みで、スクリーンネームがアンダースコアから始まり、アンダースコアで終る場合に スクリーンネームが斜体扱いになり、上手く機能しない

### ISSUE THREAD

**Issue by logore** [zenn-dev/zenn-community#469]
## 事象
Twitterの埋め込みで、スクリーンネームがアンダースコアから始まり、アンダースコアで終る場合に スクリーンネームが斜体扱いになり、上手く機能しない

## 発生したページのURL
https://twitter.com/_meditations_/status/1592472894340304896

## 発生した画面のスクリーンショット
![abc](https://user-images.githubusercontent.com/106620095/202318612-1e0c760f-8625-4599-8627-d42ab9977fd2.png)

## 再現方法
記事の管理画面で、「https://twitter.com/_meditations_」
または、「https://twitter.com/_meditations_/status/1592472894340304896」
を入力し、プレビューを実行

## 環境

- Device: [Unbranded]
- OS: [Windows 10]
- Browser: [Brave バージョン: 1.45.127  Chromium: 107.0.5304.110（Official Build） （64 ビット）]

**Comment by uttk-dev** [comment]
@logore 

報告ありがとうございます。
Twitter の埋め込みは `@[tweet]( URL )` の形でも埋め込みでき、そちらの場合だと表示できることを確認したので、`@[tweet]( URL )` の方を使用して頂けばと思います。
よろしくお願いします。

**Comment by logore** [comment]
@uttk-dev



> @logore
> 
> 報告ありがとうございます。 Twitter の埋め込みは `@[tweet]( URL )` の形でも埋め込みでき、そちらの場合だと表示できることを確認したので、`@[tweet]( URL )` の方を使用して頂けばと思います。 よろしくお願いします。

色々調べてみると、既知の問題でした。
わかりました。ありがとうございます。
