### ISSUE TITLE
通知に表示されるタイトルを長くしてほしい

### ISSUE THREAD

**Issue by SnowCait** [zenn-dev/zenn-community#470]
## 提案・要望

通知に表示されるタイトルを長くするか、カーソルをあてたときに全文が表示されるようにしてほしいです。
スマホやタブレットを考えると前者の方がいいかもしれません。

## 背景

タイトルの頭に `GitHub Actions` や `Serverless Framework` などの長めの固定文字を付けると通知でそれらの文字しか表示されずどの記事に Like が付いたか確認できない。
Serverless Framework で始まる記事を複数書いているのですがどれも「〇〇さんがServerless Framew...にLikeをつけました」と表示されます。

検索性を考えて入れているのですが通知で記事を区別できず微妙に不便だなぁと。
現在は末尾に入れて回避しているのですが文頭に入れたい場合もあるのでレイアウトの都合もあるかと思いますが検討していただけると嬉しいです。

## 関連

なし

**Comment by tannerjohn65** [comment]
こちらご提案いただきありがとうございます！
言及いただいたように、レイアウトの変更などが発生することから実施するかどうかも含めて検討させていただきます。

現状、通知に表示された記事を閲覧すると該当記事を確認できることと他のタスクを優先的に実施しているため、やるかやらないかの判断含めて時間がかかることをご理解のほどよろしくお願いいたします。

引き続き、よろしくお願いいたします。

**Comment by cm-igarashi-ryosuke** [comment]
少し前になりますが、通知の表示エリア（横幅）を少し大きくする対応を行いました。表示されるタイトルも長くなっております。
