### ISSUE TITLE
.vscode をビルド時に無視してほしい

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-community#471]
books/.vscode があると Zenn 上で以下のビルドエラーが出ます。

> books/.vscodeはディレクトリ名（slug）が不正です。slugは半角英数字（a-z0-9）、ハイフン（-）、アンダースコア（_）の12〜50字の組み合わせにする必要があります

諸々の設定ファイルとかを入れたいので、 `.vscode` もしくは `.` 始まりのディレクトリは無視してほしいです。

**Comment by uttk-dev** [comment]
@Jxck 

ありがとうございます。
影響範囲が大きいため、開発チームに持ち帰って検討してみたいと思います。
ただ、他の優先しているタスクがあるため対応に遅れる可能性がありますので、ご留意頂ければと思います。
よろしくお願いします。

**Comment by uttk-dev** [comment]
@Jxck 

こちら対応しましたので、クローズさせて頂きます。
使用する際は zenn-cli を最新のバージョンにアップデートしてからご利用下さい。
よろしくお願いします。
