### ISSUE TITLE
OGP画像にもPublicationの情報を表示してほしい

### ISSUE THREAD

**Issue by ensan-hcl** [zenn-dev/zenn-community#472]
## 提案・要望
現在、Publicationに投稿した記事であっても、OGP画像にそのことが表示されません。OGP画像にもPublicationの情報が表示されるようにしてほしいです。

## 背景
Publicationの導入以前は記事名に団体名を含めることで対処していました。しかしPublicationを使うとZenn内では「Username in Publication」という形で表示されるので、記事名に団体名を含めるとくどくなってしまいます。
OGP画像の方でも「Username in Publication」という形で表示されれば、仕様も統一されて良いと思います。

**Comment by tannerjohn65** [comment]
こちらご意見いただきありがとうございます！現状の運用もお伝えいただき参考になります🙏 　
確かに、Publication名の記載があっても分かりやすくて良さそうですね。前向きにチームで検討してみたいと思います。

引き続き、よろしくお願いいたします。

**Comment by cm-igarashi-ryosuke** [comment]
こちら対応済みですのでクローズします。

**Comment by ensan-hcl** [comment]
ご対応ありがとうございます！！すごく良いです🎉🎉🎉
