### ISSUE TITLE
トップページの記事一覧に特定の記事（かなり前のものも含む）が表示される

### ISSUE THREAD

**Issue by tenkoh** [zenn-dev/zenn-community#473]
## 事象
トップページを訪れる際にTech,Ideaともに特定の記事が高頻度に出現します。
トップページのサジェスト機能として意図通りの動作なのでしょうか？

## 発生したページのURL
https://zenn.dev

## 発生した画面のスクリーンショット
例えばこのスクリーンショットにおける1番下の記事です。
他の記事は数日内の投稿ですが、2020年の投稿が表示されています。古い記事の中からランダムに表示されたりするのであれば、そういうものかな？とも思いますが、いくつかの特定の記事だけを何度も見かけているように思います。

![image](https://user-images.githubusercontent.com/49544584/204908241-bde23549-45bb-4b38-81fa-f03298fb77e2.png)

## 再現方法
トップページを訪れる（ユーザごとに表示する記事を変えているようであれば、これでは再現できない可能性があります）

## 環境
環境依存はないと考えます

**Comment by cm-igarashi-ryosuke** [comment]
@tenkoh ご報告ありがとうございます。意図しない記事が表示されてしまっていることを認識しました。なるべく早期に修正いたします。

**Comment by cm-igarashi-ryosuke** [comment]
@tenkoh こちらの問題を修正しましたのでクローズします。ご報告ありがとうございました。

**Comment by tenkoh** [comment]
お世話になります。
本issueですが、修正後も時折再現しています。
Tech欄にて再現した際のキャプチャを添付します。
![image](https://user-images.githubusercontent.com/49544584/211231426-bedec116-a0d7-4c6e-a622-f8245cf90bc3.jpeg)

**Comment by cm-wada-yusuke** [comment]
ご連絡ありがとうございます。
こちらですが、ある程度意図した結果になります。お正月休みやゴールデンウィークなど、長期休暇で一定期間の投稿数が少なくなると発生しやすくなります。調整の過程で、昔の記事が一切出ないようにすることも考えたのですが、そうすると直近の記事の評価をいたずらに上げることになり、トップページのノイズになりえる、というトレードオフがありました。

いまは、「昔の記事がすこし出てしまうのは許容して、なるべく質の高い記事がトップページに出るようにする」という落とし所にしています。「ideaのすべての記事が2年以上前になってしまった」とかでない限りは、運営の意図どおりとみなしてください。
