### ISSUE TITLE
Scraps もRSSフィードに流してほしい

### ISSUE THREAD

**Issue by hurutoriya** [zenn-dev/zenn-community#475]
## 提案・要望

現状 Scraps に関しておもしろ記事を見かけるのですが、RSSにその情報が連携されていないので、RSSフィードに流してほしいです。
もし、Scraps は、あえて入れていないのなら、ScrapsのためのRSSを別途作成していただけると非常に嬉しいです。

## 背景

特定の人が書いたすべての記事をRSSで追跡したい

**Comment by tannerjohn65** [comment]
お世話になっております。
ScrapsのRSS連携についてですが、[こちらの記事](https://zenn.dev/zenn/articles/zenn-feed-rss#2.-%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%81%94%E3%81%A8%E3%81%AE%E3%83%95%E3%82%A3%E3%83%BC%E3%83%89:~:text=zenn.dev/feed-,2.%20%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%81%94%E3%81%A8%E3%81%AE%E3%83%95%E3%82%A3%E3%83%BC%E3%83%89,-https%3A//zenn.dev)を参照いただけると記載があるように```include_scraps=1``` のクエリ文字列を指定すると連携が可能です！　こちらをご利用いただければ幸いです。

引き続き、よろしくお願いいたします。
