### ISSUE TITLE
著者×キーワードで検索できるようにして欲しいです。

### ISSUE THREAD

**Issue by Kyome22** [zenn-dev/zenn-community#476]
## 提案・要望
全体検索で著者名とキーワードのAND検索ができるようにして欲しいです。

## 背景
あるトピックについて、信頼している著者が執筆しているか検索できると嬉しいです。

**Comment by cm-igarashi-ryosuke** [comment]
@Kyome22 ご提案ありがとうございます。詳細な検索条件を指定できると良いですよね。検討してみます。

関連: #332

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ニーズが限定的であるため実装は見送ることとなりました。

ユーザーのトップページからの絞り込みなどは引き続き検討していきたいと思います。
