### ISSUE TITLE
記事をシェアするときに「リンクをコピー」も追加して欲しい

### ISSUE THREAD

**Issue by harunonsystem** [zenn-dev/zenn-community#477]
## 提案・要望
タイトル通りになりますが、記事をシェアするときに「リンクをコピー」して、Twitter以外のSNSなどにも共有しやすいようにしていただきたいです。

他社事例
|note|amazon|
|--|--|
|![スクリーンショット 2022-12-09 13 01 37](https://user-images.githubusercontent.com/34958457/206621303-c525a051-a131-4cc2-9c84-a9fb7948ec94.png)|![スクリーンショット 2022-12-09 13 19 39](https://user-images.githubusercontent.com/34958457/206623210-0d0229b7-42a2-4025-837a-4706935f1c5e.png)|

## 背景

自分の使い方になってしまいますが、Twitterにシェアするだけだと現行のUIで問題ないのですが[Mastodon](https://github.com/mastodon)/[Misskey](https://github.com/misskey-dev/misskey)のようなSNSにもシェアすることが多いので。

**Comment by tannerjohn65** [comment]
こちらリクエストいただきありがとうございます、事例なども共有いただき助かります。
本件についてチームで検討させていただきます！

引き続き、よろしくお願いいたします。

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ニーズが限定的であるため実装は見送ることとなりました。
