### ISSUE TITLE
スクラップのコメント順を一番上に最新のコメントが表示できるようにしてほしい

### ISSUE THREAD

**Issue by daichi-takezawa** [zenn-dev/zenn-community#478]
## 提案・要望
細かい要望になるのですが現在スクラップのコメントは最新のコメントが一番下に表示される仕様になっていますが、Twitterのように最新のコメントが一番上になるようにした方が良いのでは無いでしょうか？という提案です
## 背景
私の本ではスクラップは本のアップデート情報や、質問欄として活用させてもらっています。この形式だと最新のコメントが重要になりやすいのですが、現状は最新コメントを確認するために「一番下にジャンプをクリック」という一手間を挟まなければなりません。なのでせっかく本のアップデート情報などコメントをしても一番下にあり、見られにくいという状況になっておりコミュニティを上手く活用できていないと感じています。

なので最新のコメントが一番上に表示される形になれば読者の方も一目でアップデート情報などを確認できるので、Twitterのように最初に固定コメント、その後最新コメントから順に古いコメントに下に流れていくという仕様の方が良いのかなと考えています。

ただ、メモ欄のようにスクラップを使用するのであれば最新コメントが一番下に表示された方が見やすいかなと思ったりしたので、このような形で意見の提案をさせてもらいました。意見だけ受け取って頂けたら助かります。よろしくお願いします。

**Comment by tannerjohn65** [comment]
本件リクエストいただきありがとうございます。スクラップの表示順の変更については、利用される方への影響が大きいので慎重に検討したいと思います。他のタスクの優先状況から、検討に時間がかかると思います。ご認識いただけると幸いです🙏

**Comment by daichi-takezawa** [comment]
いえ、厳しいのは承知の上でコメントしたので、いつか検討して頂ければ幸いです。
ありがとうございました🙏🏻

**Comment by daichi-takezawa** [comment]
提案ありがとうございます🙏🏻

ミニマップというのはこの事でしょうか？↓
![2022-12-20_13h01_36](https://user-images.githubusercontent.com/50498401/208580862-ce60838e-d347-4ac1-8d1f-b18017889ac5.jpg)
正直これはあまり意味が無いように感じるので、個人的にはいらないかなと思います。

確かにこれらの点はわかります↓
「スクラップごとに並び順がかわると体験に一貫性がなくなってしまう
ユーザーごとにスクラップ並び順を変えると書き手の意図する読み順と一致しなくなってしまう」

ただ、私的にはそもそもユーザーはスクラップを徘徊するような事はないので一貫性を求めていない、それよりもパッと見て最新のコメントが目に映る方が重要ではないかというのが私の意見になります。

なので順番を逆にできる機能または、全てのスクラップのコメント順をいっその事全て逆にしてしまうというのが個人的には良いんじゃないかなと思います。

ただ他の方の意見は知らないので、ちょっとそこの辺りはどちらが良いかどうかはわからないですが..

**Comment by cm-wada-yusuke** [comment]
チームで検討しまたが、見送りとさせてください。上述体験の話に加え、ユーザー設定によって順番がかわるようにすると、表示効率が落ちる（キャッシュが利用できない）ためです。
