### ISSUE TITLE
`zenn-validator` パッケージを Native ESM または CommonJS のモジュールとして import/require 可能な状態で公開して欲しい

### ISSUE THREAD

**Issue by azarashi2931** [zenn-dev/zenn-community#479]
## 提案・要望

- SSIA

## 背景

- 現状の `zenn-validator` パッケージは Node.js で直接実行されるスクリプトから import/require することを想定されていません。
  - 具体的には、ソースコードのモジュール定義は ESM であるものの、`zenn-validator` 内部の `import` が拡張子なしで行われているため、Native ESM として Node.js でそのまま実行できません。
  - また、`package.json` の `type` も `module` ではありません。
  - これはパッケージの利用者がバンドラ等を用いてモジュール解決することを想定しているためだと思われます。

- そのため、Zenn と連携した GitHub リポジトリの CI で `zenn-validator` を用いて frontmatter のチェックをするためのスクリプトを書く場合、素直に Node.js でそのまま実行できるスクリプトの形で書くことができず、バンドラ等を導入する必要があります。
  - このバンドラがなくても動く形で `zenn-validator` を公開して欲しい、というのが今回の困り事です。

## 関連

- 実際に行いたいのはバリデーションなので、https://github.com/zenn-dev/zenn-editor/issues/186 のように Zenn CLI にバリデーション機能が追加される方向で解決されても私としては構いません。
  - ただしこの方向の場合、外部ツールで frontmatter から記事のメタデータを取得するようなツールをサードパーティが作成しにくくなります。
- 「`zenn-validator` を外部で使用することを想定していないのでこの変更を受け入れない」ということはもちろんあり得ると思います。その場合は上記の Zenn CLI にバリデーションのためのサブコマンドを追加する方向を検討していただけるとありがたいです。
- いずれの場合でも変更を受け入れてくださる場合は PR を作成します。

## 具体的な変更

- ここで説明する変更は https://github.com/zenn-dev/zenn-editor/tree/1142b026872f7ba34c0b3d2f18505dbf87a79c30 を対象にしたものです。

- Native ESM
  - なんらかのトランスパイラを用いて内部の import に拡張子を付け足すことになると思います。
    - あるいは、TypeScript のソースコードの時点で `.js` の拡張子を各 `import` に付け足します。
  - 以下の2通りの実装で検証しました。
    - 手動で全ての TypeScript のソースコードの時点で `import` するパスに拡張子 `.js` を追加する方向で検証したところ、以下の変更でテストにパスするようになりました。これは全て `zenn-validator` パッケージ内の変更です。 
      - `package.json` に `"type": "module"` を追加
      - `jest.config.js` を ESM に変更
      - `jest.config.js` に `moduleNameMapper` で `*.js` -> `*` のモジュール名のマッピングを追加
    - ESBuild の設定に手を入れる方向で検証したところ、以下の変更でテストにパスするようになりました。これは全て `zenn-validator` パッケージ内の変更です。
      - `package.json` に `"type": "module"` を追加
      - `jest.config.js` を ESM に変更
      - https://github.com/evanw/esbuild/issues/622 に従って ESBuild にプラグインを追加するためのビルドスクリプトを作成
    - `yarn build` で呼び出させるビルドコマンドを上記のスクリプトに差し替え

- CommonJS
  - 以下の変更でテストにパスするようになりました。
    - `packages/zenn-validator/tsconfig.json` の `module` を `CommonJS` に変更
    - `packages/zenn-validator/package.json` の `build:src` コマンドの ESBuild のオプションに `format=cjs` オプションを追加
    - `packages/zenn-cli/vite.config.ts` に [依存関係の事前バンドル | Vite](https://ja.vitejs.dev/guide/dep-pre-bundling.html#%E3%83%A2%E3%83%8E%E3%83%AC%E3%83%9D%E3%81%A8%E3%83%AA%E3%83%B3%E3%82%AF%E3%81%95%E3%82%8C%E3%81%9F%E4%BE%9D%E5%AD%98%E9%96%A2%E4%BF%82) に従って設定を追加

## 変更の影響範囲

- https://www.npmjs.com/package/zenn-validator?activeTab=dependents を見る限り、`zenn-validator` に依存したパッケージは npm に公開されていません。
- 私のように今の `zenn-validator` に依存するスクリプトを書いた人がいる場合は、それが壊れる可能性があります。
  - 少なくとも GitHub の public リポジトリにそのようなスクリプトはありません。
  - https://github.com/search?q=-repo%3Azenn-dev%2Fzenn-editor++zenn-validator&type=code

**Comment by azarashi2931** [comment]
「具体的な変更」のセクションを見れば分かる通り、Native ESM の方針は `zenn-validator` パッケージ内に変更の範囲が収まり、なおかつ ESM は Vite との親和性も高いため、もしこの提案が受け入られるのなら Native ESM に寄せる方針を選択する方が良いと個人的には考えています。

上記の検証に使ったコードはどのパターンのものも手元にあるので受け入れ可能であるということならすぐにでも PR を作成できます。

**Comment by uttk-dev** [comment]
@azarashi2931 

提案ありがとうございます。
こちらとしても zenn-validator をより多くの人々に使ってもらいと考えているので、提案に賛成です 🙌

対応するとなると、今後の将来性を鑑みるに Native ESM での対応が望ましいですが、現状まだまだ発展途上で課題があると思いますので、CommonJS での対応になるかと思います。

>いずれの場合でも変更を受け入れてくださる場合は PR を作成します

PR の作成は大歓迎です！何か分からないところなどあれば、お気軽に聞いてください 💪
よろしくお願いします！

**Comment by azarashi2931** [comment]
ありがとうございます！

CommonJS にした場合、`zenn-validator` を利用している `zenn-cli` パッケージの `vite.config.ts` に手を入れることになるのですが、それは構わない、ということでしょうか？

また、将来的に Native ESM にも対応したいが今は ESM のエコシステムが発展途上なので CommonJS で、ということなら、Conditional Exports で両方のパッケージを公開しても良いのではないかと思います。この場合は CommonJS でもパッケージを公開できますし、`zenn-cli` パッケージの `vite.config.ts` に手を入れる必要もありません。この方法の場合でも受け入れてくださる場合は PR を作成します。

**Comment by uttk-dev** [comment]
@azarashi2931 

ありがとうございます。
Conditional Exports も考えましたが、既知の問題 ( [参照](https://www.wantedly.com/companies/wantedly/post_articles/410531#h3-パッケージ形式の今後について) ) があるため、少し導入には踏み切れない部分があります。なので現状としては、`zenn-cli` パッケージの `vite.config.ts` に多少の変更があってもいいので CommonJS にした方がいいのではないかと思っています。

また、これは私個人の意見ですが、Native ESM を導入するであれば、 CommonJS はやめて Native ESM に魂を売り渡したい気持ちがあります 🫠

**Comment by azarashi2931** [comment]
了解しました。では CommonJS の方向で PR を作成します！

**Comment by azarashi2931** [comment]
PR を作成しました。レビューお願いします！

**Comment by uttk-dev** [comment]
@azarashi2931 

先ほど v0.1.134 をリリースしましたので、`zenn-validator@latest` で CommonJS として `zenn-validator` が使えるようになると思います。
よろしくお願いします。
