### ISSUE TITLE
コードブロックに行番号を表示する機能

### ISSUE THREAD

**Issue by NONONOexe** [zenn-dev/zenn-community#481]
## 要望
コードブロックに行番号を表示する機能が欲しいです。

## 困ったときのシチュエーション
少し長めのコードを紹介したいときに全体を見せたのち、一部分を切り出して説明しようと思ったら行番号が書けず不便に思いました。

**Comment by tannerjohn65** [comment]
こちらリクエストいただきありがとうございます！
本件、検討してみたのですが、diffプラグイン利用時に競合が発生する可能性があることやその他優先度の高い対応事項があることから現状は対応するのが難しいです。。

コードブロックの一部を切り出して解説される場合、既にご検討されているかもしれませんが
```
//ポイント①
console.log("foo")

//ポイント②
console.log("bar")
```

上記のようにコメントアウトなどでご対応いただけると幸いです 🙏 
引き続き、よろしくお願いいたします。

**Comment by NONONOexe** [comment]
承知しました。取り急ぎはそのような形でやれそうなため、問題なさそうです。
丁寧に対応いただきありがとうごさいます！

全体としては想像以上に使いやすく驚かされた部分も多かったため、今後のアップデータにも期待しています。

**Comment by cm-wada-yusuke** [comment]
ワークアラウンドの検討ありがとうございます。一度クローズさせていただきます。
