### ISSUE TITLE
line-break: strict; を設定して欲しい

### ISSUE THREAD

**Issue by ijies** [zenn-dev/zenn-community#482]
## 提案・要望
line-break: strict; を設定して欲しい

## 背景
長音（「ー」）などが行頭にきている場合があり、読みづらいため。

**Comment by tannerjohn65** [comment]
お世話になっております。こちらご連絡ありがとうございます。
`line-break: strict; ` 長音（ー）以外の取り扱いにも変更が生じるため、チームで検討してから実施するかを判断したいと思います！
なお、年始以降の検討になることをご承知ください 🙏

**Comment by cm-wada-yusuke** [comment]
こちら body に適用しました。しばらく様子見します。行頭に長音記号がくることがなくなり、見栄えがよくなったと感じます。教えていただき、ありがとうございました！
