### ISSUE TITLE
tab文字の幅を選択できる or タブ文字をスペースに変換　する様にしてほしい

### ISSUE THREAD

**Issue by sugiura-hiromichi** [zenn-dev/zenn-community#484]
## 提案・要望
今の所zenn上ではcode block内のタブ文字は８文字幅で表示されます。この表示をユーザーがカスタムできる様にしてほしいです。
（個人的にはインデントを３文字にしてるので２か４の選択制にするよりも任意の（常識的な）整数値を指定する形式にしていただけるととてもありがたいです）

また、それが適切でないと考えられる場合、代替措置としてタブ文字をスペースに変換できる様にしてほしいです。

## 背景
使っているエディタの設定上、インデントには基本的にタブ文字を使っています。またMakefileなどもよく使います。なのでエディタ上からzennへコピペすると、とても見辛くなってしまい困っています。<br/>
最近githubでタブ文字の表示を2,4,8のうちから選べる様になりました。zenn上でもできると便利です。

## 関連
<https://github.com/zenn-dev/zenn-community/issues/32>

このissueを見た感じdefaultを８にしておいた方がいい？

**Comment by uttk-dev** [comment]
@sugiura-hiromichi 

提案ありがとうございます。
開発チームに持ち帰って相談したいと思いますが、
他のタスクがあるため対応に時間がかかる場合がありますので、
あらかじめご留意頂ければと思います。

よろしくお願いします。

**Comment by cm-wada-yusuke** [comment]
提案ありがとうございます。

> 代替措置としてタブ文字をスペースに変換できる様にしてほしいです。

コードを貼り付ける前と貼り付けたあとのコピーで中身が変わってしまうのは極力避けたいため、こちらは最後の手段としたいです。

そうなると、

> この表示をユーザーがカスタムできる様にしてほしいです。

こちらを考えたいのですが、想定を詳しく教えて下さい。以下のどれが一番近いでしょうか。

1. URLに`?tabSize=3`とするとソースコードのタブサイズが反映される
2. ログインユーザーが閲覧設定として、恒久的にタブサイズを保存でき、閲覧時にそれが反映される
3. ログインユーザーが投稿設定として、投稿ごとにタブサイズを設定でき、記事のスタイルにそれが反映される
4. 執筆者がMarkdown書式でコードブロックごとにタブサイズを設定できる

**Comment by sugiura-hiromichi** [comment]
対応ありがとうございます。
自分としては、2の
>ログインユーザーが閲覧設定として、恒久的にタブサイズを保存でき、閲覧時にそれが反映される

ことを想定しています。インデント幅は人主体で変わっているため、あくまで閲覧時の設定としてカスタマイズできたらいいなと考えています。

**Comment by cm-wada-yusuke** [comment]
ありがとうございます。閲覧側で設定できれば、自分が期待したとおりにすべての記事がスタイルされて見やすそうですね。ただ、Zennのログイン設定で入れるとなると、ログイン前とログイン後で記事のスタイル（タブサイズ）が変わり、体験の一貫性がなくなってしまうことを懸念しています。

かわりといってはなんですが、Chromeには以下のような任意のCSSをサイトごとに設定できる拡張があり、便利に使えそうです。
https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=ja

生CSSを設定することもできます。tab-sizeを3に設定したときのようすです。

![image](https://user-images.githubusercontent.com/17589989/210922860-f2267c3c-64b5-47ea-bfd4-93ceecf8d0c3.png)

![image](https://user-images.githubusercontent.com/17589989/210922692-5e5172b0-be5e-47cb-8b20-f554278f57de.png)

こちらで充足できれば幸いです。

**Comment by sugiura-hiromichi** [comment]
その様な方法があるとは知りませんでした。自分の使っているブラウザには対応していませんでしたが、教えていただいたアドバイスを元に自分なりに解決することができました。有難うございます。

**Comment by cm-wada-yusuke** [comment]
解決できてよかったです！どのような困りごとがあるかは常に気にしているのでこの件に限らずぜひまたご連絡いただけると嬉しいです。
