### ISSUE TITLE
Zennで公開している本へのリンクを作成するとリンクカードにはURLのみが表示される

### ISSUE THREAD

**Issue by mebiusbox** [zenn-dev/zenn-community#485]
## 事象
記事やスクラップなどで、自身が公開している本へのリンクを作成すると、表示されるリンクカードにはURLだけが表示され、他のリンクカードと結果が異なる．ただ、別のアカウントが作成された本をリンクするとタイトルなどが正しく表示されている（何個か試しました）．また、自身が作成した記事も問題ありません．問題が発生するのは本へのリンクです．

## 発生したページのURL
https://zenn.dev/mebiusbox/scraps/90bc293a07430d

## 発生した画面のスクリーンショット
![2023-01-07_07h15_59](https://user-images.githubusercontent.com/19758056/211109107-1462f3e3-dee2-4508-b210-0997341dc54f.png)

## 再現方法
記事やスクラップに自身が作成した本へのリンクを作成する

- OS: [Windows]
- Browser: [chrome 108.0.5359.125]

**Comment by mebiusbox** [comment]
今日、確認してみたら表示が正常になっていたので、時間がかかっていたのかもしれません．一旦クローズします．

**Comment by cm-wada-yusuke** [comment]
ご連絡、スクショありがとうございます。こちらでも頭に入れておき再発した場合調査します。
