### ISSUE TITLE
リスト機能の追加要望

### ISSUE THREAD

**Issue by nitadori528-hym** [zenn-dev/zenn-community#486]
## 提案・要望
後で見返したい記事を用途毎にまとめる、リスト機能が欲しいです。
ご検討よろしくお願いします

## 背景
この記事いいなと思い後で見返すためにいいねを使っているのですが、だんだんその量が増えており、探すのが大変になってきているのでリスト機能が欲しいなと思いました

**Comment by uttk-dev** [comment]
@nitadori528-hym 

提案ありがとうございます。
似たような機能が以前に提案されていまして、他のサービスなどを使用した方が便利なため実装を見送っています ( [参照](https://github.com/zenn-dev/zenn-community/issues/130#issuecomment-855618150) )。
そのため、ブックマークサービスやブラウザのリーディングリスト機能( [chromeの場合](https://support.google.com/chrome/answer/7343019) )などで対応して頂ければと思います。

**Comment by nitadori528-hym** [comment]
なるほど...
承知しました！
ありがとうございました！
