### ISSUE TITLE
コードブロック入力時のオートインデントをON/OFFできるようにしてほしい

### ISSUE THREAD

**Issue by tetsu-koba** [zenn-dev/zenn-community#487]
## 提案・要望

コードブロック入力時のオートインデントをON/OFFできるようにしてほしい

```
これがコードブロックです。
```
## 背景

私はコードブロックを書くときに、まず他のところからコピペして、それを修正することが多いです。
改行を入力したときにオートインデントが働いて、前の行にそろえて空白が自動的に挿入されるのですが、私にとってはこれは邪魔です。
オートインデントはOFFにしていただきたいのですが、この機能を便利に使っている方もいると思うのでユーザーごとにON/OFFをカスタマイズできるようにしていただくのがよいと思います。

**Comment by cm-wada-yusuke** [comment]
すみません、改行時のインデントが何によるものか調べる時間をください。

**Comment by cm-wada-yusuke** [comment]
Shift + Enter でインデントを無効にした状態で改行できます。試してみていただけるでしょうか。

---

設定のカスタマイズは以下の理由により難しいです。申し訳ないです：

ZennのMarkdownエディタが利用している、SimpleMDEが内部的に利用している CodeMirror のオプションを調整することでインデントを無効にできるとわかりました。
https://codesandbox.io/s/codemirror-forked-14cguj?file=/src/index.js:449-460

現状Zennからはデフォルトのオプションのまま使っているため、`smartIndent` が有効になっています。カスタマイズして無効にすることもできますが、

- 他のオプションも併せて検討
- カスタマイズを許容すると一環した執筆体験を提供することが難しくなる
- 細かいエディタ環境のカスタマイズは、[GitHub連携+お好みのエディタ](https://zenn.dev/zenn/articles/editor-guide#2.-%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E3%81%AE%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF%E3%83%BC-%2B-cli) で行ってほしい

**Comment by tetsu-koba** [comment]
調査回答ありがとうございます。
私はこのsmartIndentは無効にして欲しいという希望を伝えます。
これが本当に望ましい挙動なのか(無効のほうがよいと思う人の方が多いのではないか）を検討していただければと思います。
