### ISSUE TITLE
本のページ数の上限をできれば増やしてほしい

### ISSUE THREAD

**Issue by daichi-takezawa** [zenn-dev/zenn-community#491]
## 提案・要望
本のページ数の上限を増やしてほしいです

## 背景
いつもお世話になっております。Zennで書かせて頂いているこの本↓がページ数の上限の150ページに達してしまいそうです。
https://zenn.dev/daichi_gamedev/books/unreal-engine-tutorial
元々150ページ以内に収めるつもりでしたが書いていましたが、ページ数の上限をもう少し増やしていただければ、もっと色々な項目を見やすくまとめる事ができるかなと思っております。検討頂けると嬉しいです。よろしくお願い致します。

**Comment by tannerjohn65** [comment]
@daichi-takezawa  
こちらリクエストいただきありがとうございます！　本の更新も実施いただき感謝です。
本のページ上限を引き上げます。 150ページから200ページに上限を増やして対応しようと思いますが、200ページで足りそうでしょうか？

**Comment by cm-wada-yusuke** [comment]
すいません、こちらですが上限をあげますが、無尽蔵に上げられるわけではなく、いったん200ページとさせてください。

私が以下の点を失念していました：
- チャプター数が多すぎるとパフォーマンス上の影響が未知数なので、少しずつ上げていきたい（一気に300とかは怖いです）
- チャプター数が多すぎるとメニューのスクロール量が多くなり視認性が下がるので、チャプターの構造化を検討したい（こちらがわの課題です #293  ）

**Comment by daichi-takezawa** [comment]
ありがとうございます🙏🏻200ページもあれば充分です。助かります🙏🏻

(あと個人的な意見なんですが現在僕の本は150ページ程あるのですが、視認性が下がって見辛いとはそこまで感じていません。200ページぐらいなら全然問題無いかと私的には思っています。ほとんどの本の場合は10~30ページ程なので本のページがチャプター毎にまとまってしまったら逆に本の内容が薄く見えてしまう可能性があるのでは？とも思っています。一応お伝えさせて頂きました)

**Comment by cm-wada-yusuke** [comment]
あ、そうですね！言い方が悪かったですが、すでにあるチャプターをこちらで無理やりまとめようとは思っていなくて、構造化する選択肢も用意するかどうか、という話でした。daichi様のようにすでにたくさんチャプターを用意してくださっている著者の方はフラットなチャプター構造を前提で組んでいただいていると思いますし、そこを触るつもりはないです。

> 200ページぐらいなら全然問題無い
ご意見ありがとうございます！

**Comment by daichi-takezawa** [comment]
ありがとうございます!理解しました!

**Comment by cm-igarashi-ryosuke** [comment]
@daichi-takezawa チャプター数の上限を200に引き上げました。また何か不都合がありましたらお知らせください。

**Comment by daichi-takezawa** [comment]
ありがとうございます🙏🏻🙏🏻

**Comment by cm-wada-yusuke** [comment]
@daichi-takezawa こちらからたどる形になり恐縮ですが、現在依頼ベースで個別にチャプター数を引き上げておりますので、一般ユーザーは100のままです。ということでドキュメント側の表記は100のままで大丈夫です。ご連絡ありがとうございます。
https://zenn.dev/link/comments/1c0e8edad15ded

**Comment by daichi-takezawa** [comment]
もしかしたらそうかなと思いました。確認ありがとうございます🙏

**Comment by cm-wada-yusuke** [comment]
いえいえ、普通にドキュメント更新が漏れていることもあるのでご指摘助かります！
