### ISSUE TITLE
記事のブックマーク機能が欲しい（"いいね"とは別）

### ISSUE THREAD

**Issue by dadada0220** [zenn-dev/zenn-community#492]
## 提案・要望
参考にしたい記事をいつでも読み返せるようにブックマーク機能が欲しいです。

## 背景
"いいね"とは別扱いが良いと思っており、以下のような考えです。

### 現状
良いと思った記事に対していいねを押したいが、今はブックマークの役割としていいねを使っている。
これだと、良いと思った記事にいいねを気軽に押せない（いいねした記事一覧が溢れてしまうため）。

### 理想
- いいね機能：良いと思った記事に対して気軽に押す（著者を応援したい気持ち）
- ブックマーク機能：後で見返したい記事に対してブックマークをする（記事にブックマーク数も出たらいいなと）

「良いと思った記事 = 後で見返したい」とは一概にはならないので、ブックマーク機能があれば良いなと思ったので要望を出させて頂きました。

**Comment by tannerjohn65** [comment]
こちらリクエストいただきありがとうございます。チームで対応を検討いたします。
現状、他に優先度の高い実施事項に対応しているため、検討に時間がかかることをご認識いただけると幸いです。

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ニーズが限定的であるため実装は見送ることとなりました。

ライブラリ（https://zenn.dev/dashboard/library）の改善は引き続き考えていきたいと思います。
