### ISSUE TITLE
 RSSフィードで投稿カテゴリー別に記事を取得出来るようにして欲しい

### ISSUE THREAD

**Issue by h3y6e** [zenn-dev/zenn-community#493]
## 提案・要望

Zennには`Tech`と`Idea`の2つの[投稿カテゴリー](https://zenn.dev/tech-or-idea)が存在しますが、現在の[RSSフィード](https://zenn.dev/zenn/articles/zenn-feed-rss)ではそれを区別することが出来ない為、トレンドのフィード、ユーザーごとのフィード、トピックごとのフィードに対してそれぞれ投稿カテゴリー別に記事を取得出来るようにして欲しいです。

クエリ文字列を用いる等で、投稿カテゴリー毎にフィードを用意していただくことは可能でしょうか？

## 背景

特にトピックに対してRSSでの購読を行っているのですが、Techに関する記事のみを収集したいと思うことがありました。

## 関連

- https://github.com/zenn-dev/zenn-community/issues/52#issuecomment-699464159 では「トレンドtech」と「トレンドidea」がTODOとして残されていますが、トピック(やユーザー)に対してもこれを適用して欲しいです。

**Comment by tannerjohn65** [comment]
こちらリクエストいただきありがとうございます、関連Issueの記載も助かります。
本件について対応方針含めてチームで検討いたします。
現状、他に優先度の高い実施事項に対応しているため、お時間をいただく可能性があることをご認識いただけると幸いです🙏

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ニーズが限定的であるため実装は見送ることとなりました。
