### ISSUE TITLE
【質問】ZennのWeb APIについて

### ISSUE THREAD

**Issue by myConsciousness** [zenn-dev/zenn-community#496]
こんにちは。

#209 と #250 に類似した質問になりますが、公式に公開されたZennのWeb APIはありますでしょうか。

**Comment by cm-wada-yusuke** [comment]
@myConsciousness いいえ、公開しているAPIはありません。私たちから、特定の企業や外部サービスに対して、個別にユーザーの情報を提供しているということもありません。

**Comment by myConsciousness** [comment]
> @myConsciousness いいえ、公開しているAPIはありません。私たちから、特定の企業や外部サービスに対して、個別に記事などの情報を提供しているということもありません。

ありがとうございます。

先に挙げた過去のIssueを読んでいたところ外部開発者向けのAPIがあるかどうかについて明確な答えがなかったので改めて質問させていただきました。回答に納得しましたのでクローズとさせてください。
