### ISSUE TITLE
テーブルの列を区切る`|`とコードブロック内の`|`が区別されず、表示がおかしくなります。

### ISSUE THREAD

**Issue by sasano8** [zenn-dev/zenn-community#497]
## 事象

テーブルの列を区切る`|`とコードブロック内の`|`が区別されず、表示がおかしくなります。

`|`はコードブロックとして描画されて欲しいです。 

## 発生したページのURL

(https://zenn.dev/sasano8/articles/python-006-dictionary#%E3%83%81%E3%83%BC%E3%83%88%E3%82%B7%E3%83%BC%E3%83%88)

## 発生した画面のスクリーンショット

![スクリーンショット_20230207_073022](https://user-images.githubusercontent.com/30338578/217102329-fad8f9bc-6d6c-4246-b857-32e8ad696549.png)

## 再現方法

次のような、テーブルの列を区切る`|`とコードブロック内の`|`を一緒に使用するmarkdownを用意します。

```
| 要求      | コード例 | 備考 | バージョン |
| ---- | ---- | ---- | ---- |
| マージ/更新 | `dic1 |= dic2` | キーが衝突する場合、右辺の値で上書き  | ^3.9 |
```

## 環境

- OS: Windows11
- Chrome: 109.0.5414.120

**Comment by cm-wada-yusuke** [comment]
バックスラッシュでエスケープいただければと思います。

```
 | 要求      | コード例 | 備考 | バージョン |
| ---- | ---- | ---- | ---- |
| マージ/更新 | `dic1 \|= dic2` | キーが衝突する場合、右辺の値で上書き  | ^3.9 |
```

**Comment by sasano8** [comment]
> 

承知しました。
プロダクトで使用しているmarkdown viewerは何か教えて頂けると、そちらにも問い合わせできて幸いです。

**Comment by cm-wada-yusuke** [comment]
@sasano8 [markdown-it](https://github.com/markdown-it/markdown-it/issues/777) をベースにしています。HTMLへの変換処理は[公開](https://github.com/zenn-dev/zenn-editor/tree/canary/packages/zenn-markdown-html)していますのでそちらもご参照いただければと思います。
