### ISSUE TITLE
通知の「〇〇さんがサービスにLikeをつけました」の名前をクリックしたらユーザーのプロフィールに遷移するようにしてほしい。

### ISSUE THREAD

**Issue by daiki0381** [zenn-dev/zenn-community#499]
## 提案・要望
通知の「〇〇さんがサービスにLikeをつけました」の名前をクリックしたらユーザーのプロフィールに遷移するようにしてほしい。

## 背景
どんな人がLikeを押してくれたのか知りたいが、現状だとユーザー名と表示名が異なる場合、相手のプロフィールを見つけることができない。

**Comment by tannerjohn65** [comment]
こちらリクエストいただきありがとうございます。　追加で確認させてください 🙏 
現状の挙動としては通知からLikeをつけたユーザーの方のアイコンをクリックすれば、そのユーザーページに遷移する挙動になっているかと思います。

上記の挙動に追加して文字列（記事名など）をクリックした際にもLikeをつけたユーザーの方のページに遷移してほしいということでしょうか？？

**Comment by daiki0381** [comment]
@tannerjohn65 
ありがとうございます🙇‍♂️ こちら確認不足でした💦 アイコンをクリックすれば、ユーザーページに遷移することを確認できました！対応頂かなくて大丈夫です🙆‍♂️
