### ISSUE TITLE
個人とPublicationで連携するGitHubを別にしたい

### ISSUE THREAD

**Issue by hagiwara0324** [zenn-dev/zenn-community#500]
## 提案・要望
個人とPublicationで連携するGitHubを別にしたい。

## 背景
Publicationとして投稿する場合に、GitHubリポジトリは共通で使っているものにしたい。

現在だと、個人の設定としてGitHubリポジトリと連携するしかなく、共通アカウントを一つ作成してそこに共通で使っているGitHubリポジトリを連携させて管理するしかないように思われる。（しかしそうすると、Publicationの意味があまりない...）

**Comment by uttk-dev** [comment]
@hagiwara0324

提案ありがとうございます。

Zenn では、 記事・本は著者本人の持ち物であり、退職後も本人が管理できるべきだと考えています。
その観点から、共通で使われているリポジトリを連携できる機能は、著者本人が管理しにくくなってしまう懸念があるため、少し対応が難しそうです。

**Comment by hagiwara0324** [comment]
@uttk-dev 
早速のご返答ありがとうございます。
対応についても理解しました。

ここからは私の意見で参考になればと思います。

私個人として下記方針であるべきだと思っております。
> Zenn では、 記事・本は著者本人の持ち物であり、退職後も本人が管理できるべきだと考えています。

その一方で、私の組織ではいわゆる非エンジニアが多くなかなか個人として記事投稿するのに気が引けるというメンバも多いです。
まずは誰かにレビューをしてもらったり管理をしてもらいたいという話も聞いています。
そこではじめの一歩として、組織として記事投稿をして情報をシェアすることで慣れてもらいたいという考えがあります。
（後は、著者本人が管理するようにしていきたいとは思っています。）

ご参考になれば幸いです。

このIssueってクローズとかした方がよいですかね？

**Comment by uttk-dev** [comment]
@hagiwara0324 

ご意見ありがとうございます。開発チームに共有して今後の開発の参考にさせてもらいます🙏

>このIssueってクローズとかした方がよいですかね？

こちらでクローズするので大丈夫ですよ。( もちろん、ご自身が問題無いと判断された場合もクローズして大丈夫です🙆‍♂️ )
