### ISSUE TITLE
codesandboxの埋め込みにて、「Open Sandbox」ボタンをクリックすると、指定したURLに遷移しない

### ISSUE THREAD

**Issue by YamabikoLab** [zenn-dev/zenn-community#502]
## 事象
codesandboxの埋め込みにて、「Open Sandbox」ボタンをクリックすると、指定したURLとは異なるURLへ画面遷移する。
URLには表示したいファイルのURLを指定しました。

わたしが記事に書いたcodesandboxの埋め込み内容
```
@[codesandbox](https://codesandbox.io/embed/github/YamabikoLab/react-hook-form-sample/tree/develop/?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.tsx&theme=dark)
```

「Open Sandbox」クリックしたときの遷移先
```
https://codesandbox.io/s/github/YamabikoLab/react-hook-form-sample/tree/develop/?from-embed
```

## 発生したページのURL
下記のスクラップに問題の現象が発生するサンプルを作成しました。
ご確認お願い致します。
https://zenn.dev/link/comments/e2e621e7751d40

## 発生した画面のスクリーンショット
下記の画面で「Open Sandbox」ボタンをクリックする
![image](https://user-images.githubusercontent.com/88073693/220329309-dd56ab71-0418-4aa8-9f61-c68ac8aeeeda.png)

下記の画面に遷移してしまう。
![image](https://user-images.githubusercontent.com/88073693/220329498-d6fc45e3-f542-4403-a985-1ce949bf73a1.png)

期待する遷移先は下記の画面です。
![image](https://user-images.githubusercontent.com/88073693/220329705-ed1b6a99-2dcb-4ac3-ba9e-2f54ab72199e.png)

codesandbox埋め込みに指定したURLを直接実行していただくと、期待する画面が表示されます。
```
https://codesandbox.io/embed/github/YamabikoLab/react-hook-form-sample/tree/develop/?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.tsx&theme=dark
```

## 再現方法
1.codesandboxの埋め込みURLに表示したいファイル名を指定したURLを指定する。
2.記事にて「Open Sandbox」ボタンをクリックする
3.埋め込みURLで指定したURLに遷移しない。

## 環境
chromeを使用しています。

**Comment by cm-igarashi-ryosuke** [comment]
@YamabikoLab 
わたしも試してみましたが、`module` はiframe内で開いているファイルを制御するためのオプションで、「Open Sandbox」のボタンのリンク先には影響しないようでした。

参照: https://codesandbox.io/docs/learn/sandboxes/embedding#embed-options

https://user-images.githubusercontent.com/13619209/220497710-b0497fec-8b1d-47b1-b67b-ea56ee8ef2aa.mov

これは標準的な動きでありZennの問題ではないためクローズします。
またなにか疑問に思うことがありましたらオープンしてください。

**Comment by YamabikoLab** [comment]
>これは標準的な動きでありZennの問題ではないためクローズします。

承知しました。
ご確認ありがとうございました！
