### ISSUE TITLE
スクラップ内でのアンカー機能

### ISSUE THREAD

**Issue by yktakaha4** [zenn-dev/zenn-community#505]
日々便利に使っています。ありがとうございます

## 提案・要望

- 現在のスクラップ機能にはパーマリンクを作成する機能がありますが、同一のスクラップ内で別の投稿を参照させたいときに新規ウィンドウが表示される仕様になっていると思います
- こちらについて、同一スクラップ内でアンカーのような形式で参照ができるとよいように感じました
  - 画面遷移せず、当該の投稿に対してスクロールするような動作をイメージしています
  - アンカーリンクを発行する機能を新規に実装するか、同一スクラップを示すURLの場合にアンカー的な挙動で遷移をおこなうか…といった実装の詳細については、個人的には強い希望はありません

## 背景

以下のようなスクラップを書いていて、 `人月の神話` のリンクをクリックした際の挙動を見て、前述の機能があるとよいなと思ったため
https://zenn.dev/link/comments/a1b7c7bcbaa10a

## 関連
なし

**Comment by tannerjohn65** [comment]
お世話になっております。本件、リクエストいただきありがとうございます。
同一ページ（スクラップ）内のリンクは、新規ページではなく同一ページでスクロールする挙動のイメージですね。こちらチームで検討いたします！

**Comment by uttk-dev** [comment]
@yktakaha4 

提案ありがとうございます。
スクラップの投稿時間を表示する部分をフラグメントリンクにしました。

https://user-images.githubusercontent.com/97154037/223901475-79cd4d00-22ed-49a6-8040-8aa190c4f7a3.mov

<br />

Markdown で内部リンクを書く際は、上記のリンクから `#comment-{slug}` の部分をアドレスバーからコピーしていただき、`[xxx](#comment-{slug})` のような形で記述する感じで対応して頂ければと思います。( `[xxx](#comment-{slug})` のリンクであれば画面遷移せずに当該の投稿を表示できます )

よろしくお願いします！

**Comment by yktakaha4** [comment]
こちら返信が遅くなりすみませんが、私のスクラップを更新して期待する動作ができることを確認しました
積極的に使っていきたいと思います
ご対応いただきありがとうございました :pray:
