### ISSUE TITLE
OGPが表示されません

### ISSUE THREAD

**Issue by korosuke613** [zenn-dev/zenn-community#506]
## 事象

Zennで書いた記事をTwitterでシェアしています。
最近ツイート時にOGPが表示されなくなりました。

- https://twitter.com/Shitimi_613/status/1630091781546340352
- https://twitter.com/Shitimi_613/status/1626143975383126016

また、ページ内の`<head>`タグ下`<meta property="og:image" content="...">`にあるURLにアクセスしたところ、400エラーが返ってくることを確認しました。

また、Publicationに紐づいていない記事（[例](https://zenn.dev/korosuke613/articles/productivity-weekly-20220810)）については問題なく表示されることを確認しています。

## 発生したページのURL

- [Productivity Weekly (2023-02-22号)](https://zenn.dev/cybozu_ept/articles/productivity-weekly-20230222)
- [Productivity Weekly (2023-02-08号)](https://zenn.dev/cybozu_ept/articles/productivity-weekly-20230208)
- 他にもあります。[`cybozu_ept` Publication](https://zenn.dev/p/cybozu_ept)に投稿されているkorosuke613の記事はおそらく全て同じ現象が起きます

## 発生した画面のスクリーンショット

![image](https://user-images.githubusercontent.com/20027695/221491816-95858a63-01ca-4b60-bf9a-2dc77d41cffa.png)
![image](https://user-images.githubusercontent.com/20027695/221491926-180d3f90-30de-46ca-89e8-fd69f802d4c5.png)

[Productivity Weekly (2023-02-22号)](https://zenn.dev/cybozu_ept/articles/productivity-weekly-20230222) のOGPへのリンクはステータスコード400を返します。

```
❯ curl -I https://res.cloudinary.com/zenn/image/upload/s--Aoac1Qpb--/c_fit%2Cg_north_west%2Cl_text:notosansjp-medium.otf_64:Productivity%2520Weekly%2520%25282023-02-22%25E5%258F%25B7%2529%2Cw_1010%2Cx_90%2Cy_100/co_rgb:6e7b85%2Cg_south_west%2Cl_text:notosansjp-medium.otf_30:%E3%82%B5%E3%82%A4%E3%83%9C%E3%82%A6%E3%82%BA%20%E7%94%9F%E7%94%A3%E6%80%A7%E5%90%91%E4%B8%8A%E3%83%81%E3%83%BC%E3%83%A0%20%F0%9F%92%AA%2Cx_220%2Cy_135/g_south_west%2Cl_text:notosansjp-medium.otf_34:Futa%2520Hirakoba%2Cx_220%2Cy_84/bo_3px_solid_rgb:d6e3ed%2Cg_south_west%2Ch_90%2Cl_fetch:aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3plbm4tdXNlci11cGxvYWQvYXZhdGFyL2I0ZGFiZjEwMjAuanBlZw==%2Cr_20%2Cw_90%2Cx_92%2Cy_82/bo_4px_solid_white%2Cg_south_west%2Ch_50%2Cl_fetch:aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3plbm4tdXNlci11cGxvYWQvYXZhdGFyLzdjOTZjZGNlNTguanBlZw==%2Cr_max%2Cw_50%2Cx_139%2Cy_64/og-base.png
HTTP/2 400
content-type: image/gif
etag: "d41d8cd98f00b204e9800998ecf8427e"
expires: Mon, 27 Feb 2023 07:09:29 GMT
last-modified: Mon, 27 Feb 2023 06:39:30 GMT
x-cld-error: Invalid encoding in transformation
content-length: 0
date: Mon, 27 Feb 2023 06:42:50 GMT
<省略>
```

## 再現方法

- [Productivity Weekly (2023-02-22号)](https://zenn.dev/cybozu_ept/articles/productivity-weekly-20230222) をツイートする
- https://res.cloudinary.com/zenn/image/upload/s--Aoac1Qpb--/c_fit%2Cg_north_west%2Cl_text:notosansjp-medium.otf_64:Productivity%2520Weekly%2520%25282023-02-22%25E5%258F%25B7%2529%2Cw_1010%2Cx_90%2Cy_100/co_rgb:6e7b85%2Cg_south_west%2Cl_text:notosansjp-medium.otf_30:%E3%82%B5%E3%82%A4%E3%83%9C%E3%82%A6%E3%82%BA%20%E7%94%9F%E7%94%A3%E6%80%A7%E5%90%91%E4%B8%8A%E3%83%81%E3%83%BC%E3%83%A0%20%F0%9F%92%AA%2Cx_220%2Cy_135/g_south_west%2Cl_text:notosansjp-medium.otf_34:Futa%2520Hirakoba%2Cx_220%2Cy_84/bo_3px_solid_rgb:d6e3ed%2Cg_south_west%2Ch_90%2Cl_fetch:aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3plbm4tdXNlci11cGxvYWQvYXZhdGFyL2I0ZGFiZjEwMjAuanBlZw==%2Cr_20%2Cw_90%2Cx_92%2Cy_82/bo_4px_solid_white%2Cg_south_west%2Ch_50%2Cl_fetch:aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3plbm4tdXNlci11cGxvYWQvYXZhdGFyLzdjOTZjZGNlNTguanBlZw==%2Cr_max%2Cw_50%2Cx_139%2Cy_64/og-base.png にアクセスする

**Comment by korosuke613** [comment]
また、2023/2/5時点だと正常にアクセスできるOGPが取得できることを確認しています。

![image](https://user-images.githubusercontent.com/20027695/221495130-2f3a4e1a-9908-46d2-a543-b11444d2c861.png)
---
私のホームページでは、Zennに投稿した記事を定期的にRSSで取得し、記事の情報を埋め込む仕組みがあります。
「Productivity Weekly (2023-01-25号)」を投稿した際に自動で次のプルリクエストが作成されるのですが、その時は正常にアクセスできるOGPを取得できました。
https://github.com/korosuke613/homepage-2nd/pull/128/files#diff-65d7ebec76bb7a7f7375f7b40e2ac4e32d3cf4552e0dc5a86d9f1a037f4aec29R521

**Comment by cm-igarashi-ryosuke** [comment]
@korosuke613 ご報告ありがとうございます。最近、OGPにPublication名も表示されるようにしたのですが、特定の条件で画像が生成されない場合があることがわかりました。近日中に修正しますのでお待ち下さい 🙏

**Comment by cm-igarashi-ryosuke** [comment]
@korosuke613 修正が完了しましたのでお知らせします。

- 記事ページの `og:image` は参照できるようになっています。
- RSSフィードはキャッシュが更新され次第（最大2時間）、イメージのURLが更新されます。
- Twitterなどの外部サイトについては、サイト側でキャッシュを持っている場合がありますので、更新に時間がかかる場合があります。

また何かお気づきの点がありましたらお知らせください。ありがとうございました。

**Comment by korosuke613** [comment]
@cm-igarashi-ryosuke 
OGPが表示できるようになったことを確認しました！
ご対応ありがとうございました😊
