### ISSUE TITLE
GitHub連携で、ヘッダ無しのファイルをアップロードしたときのエラーメッセージがわかりにくい

### ISSUE THREAD

**Issue by shonuma** [zenn-dev/zenn-community#507]
## 提案・要望
GitHub連携で記事を投稿する際、ヘッダ無しのファイルを上げたときのエラーメッセージがわかりにくいと感じています。

## 背景
CLIを利用した場合はテンプレートが生成されるので問題ないのですが、利用せずにファイルを作り始めてしまいこちらのエラーが出てしまいました。
- https://zenn.dev/zenn/articles/install-zenn-cli

途中で原因に気づきエラーは解消したのですが、エラーメッセージでヘッダなしの可能性を示唆できると原因解決が早くなるのではないかと思いました。

実際に出力されたエラー
```
articles/testentry.mdはslug（testentry）が不正です。slugは半角英数字（a-z0-9）、ハイフン（-）、アンダースコア（_）の12〜50字の組み合わせにする必要があります
```

## 関連
N/A

**Comment by tannerjohn65** [comment]
お世話になっております。こちら起票いただきありがとうございます。
確かに表示内容について改善できるかと存じます。エラーメッセージの表記について検討いたします。

**Comment by cm-wada-yusuke** [comment]
以下のようにガイドラインへのリンクを追加し、エラーメッセージをわかりやすく修正しました。ご提案ありがとうございました。

![image](https://user-images.githubusercontent.com/17589989/228139591-e3f7f502-45b3-4bb9-a9d0-d011c76116e3.png)
