### ISSUE TITLE
名前の中に含まれる絵文字の上部が切れている

### ISSUE THREAD

**Issue by mickie895** [zenn-dev/zenn-community#508]
## 事象
記事のリンクのレイアウトにて、名前の中に含まれている絵文字の上部が見切れています。

## 発生したページのURL
トップページや各記事のRead Nextで確認しています。

## 発生した画面のスクリーンショット
![screenshot](https://user-images.githubusercontent.com/52966624/223328424-655bb437-22a7-43eb-8de9-f1d739fb481e.png)

## 再現方法

該当ユーザの記事を表示する（高確率でその方の記事がRead Nextに選ばれるため）

## 環境
- Windows10
  - ディスプレイの表示スケール：100%
- Microsoft Edge バージョン 110.0.1587.63 (公式ビルド) (64 ビット)
  - 拡大率100%
  - 1920x1080のディスプレイにて全画面表示を行っている

**Comment by cm-igarashi-ryosuke** [comment]
@mickie895 ご報告ありがとうございます。再現することを確認できました。近いうちに修正したいと思います。

**Comment by cm-igarashi-ryosuke** [comment]
@mickie895 修正が完了しました。クローズします。
