### ISSUE TITLE
スクラップの最上部に結論・まとめを追加できるようにしてほしい

### ISSUE THREAD

**Issue by masa5714** [zenn-dev/zenn-community#509]
## 提案・要望
スクラップの一番上に結論やまとめ（もしくはまとめた記事リンク）を追加できるようにして頂きたいです。

## 背景
スクラップは調査や試行錯誤の方針や結果を書き出すために利用しています。
そのため、中身が汚れがちです。
自分だけの利用であれば特に問題ないのですが、Zennはドメインパワーが強く、Google上位表示されやすい傾向にあります。情報収集されている方に向けた結論やまとめが１番上に表示できると綺麗な情報に仕上がるのではないか、と考えた次第です。

例えば、下記のような僕が書いた記事では、
https://zenn.dev/masa5714/scraps/ddd1c7d3dfa00a
期待させるような記述があり、最後に「ムリでした。」では検索で閲覧した人にとっては邪魔な情報でしかありません。
このスクラップでは1コメント目とタイトルを編集して結論を追記していますが、極力スクラップコメントは当時のままにしたいと考えています。

結論を最上部で伝えた上で調査・試行錯誤した結果を見れると閲覧者の情報の受け取り方も変わると思います。

---

ちなみに...

https://github.com/zenn-dev/zenn-community/issues/478

上記の Issues で見送りされている要望に似ているようで少し異なります。
今回の要望は結論やまとめを最上部に表示するリクエストとなります。
1件のみ特殊コメントとして追加・編集できる想定です。

もしくは綺麗にまとめた記事のリンクを最上部に表示できるようにするとか...？

ぜひともご検討頂けますと幸いでございます。

**Comment by cm-wada-yusuke** [comment]
@masa5714 整理して書き込んでいただいたスレッドを「ピン留め」することで最上部に固定できますが、こちらでは要望は満たせないでしょうか？

![image](https://user-images.githubusercontent.com/17589989/225869589-5bf0014d-6f65-4c68-8c3c-1f62c79a355e.png)

**Comment by masa5714** [comment]
@cm-wada-yusuke 
ありがとうございます。
ピン留め機能があるの知りませんでした！
こちらで十分です。大変失礼しました！

**Comment by cm-wada-yusuke** [comment]
@masa5714 要件満たせそうでよかったです。お気になさらず、私も知らない機能もたくさんあります…。引き続きよろしくおねがいします！
