### ISSUE TITLE
Scrapsの1コメントの最大文字数（20000文字）を超えた場合、保存時に変更内容が失われてしまうのを回避したい

### ISSUE THREAD

**Issue by kun432** [zenn-dev/zenn-community#510]
## 提案・要望
Scrapsの1コメントの最大文字数（20000文字）を超えた場合、保存時に変更内容が失われてしまうのを回避する仕組みがほしい。

## 背景
Scrapsで1コメントあたりの最大文字数を超えた場合、右下にエラーメッセージが表示され編集モードから抜けてしまう。これにより変更した内容が保存されずに失われてしまう。

1コメントあたりの文字数が多いのが良くないということなのかもしれないが、

- 保存時に最大文字数を超えていれば一旦保存できないようにしておいて、最新のコメント欄に分割してコピペする
- 現在の文字数が制限に近い場合は何かしらのAlertを表示する

と言うような感じで、せめてユーザ側でロストを回避できるような対応があると嬉しい。

## 関連

特になし（過去issueを見てみましたが類似するようなものは見当たりませんでした。検索ミスなら申し訳ありません）

**Comment by cm-igarashi-ryosuke** [comment]
@kun432 ご報告ありがとうございます。また、ご不便をおかけし申し訳ありません。

変更内容が失われてしまうのは意図しない動作なので、失われないように修正したいと思います。

**Comment by cm-wada-yusuke** [comment]
こちら修正、リリースされ、開発メンバーで解消していることを確認しました。ご報告ありがとうございました。
