### ISSUE TITLE
新着記事の一覧が目につくようなレイアウト

### ISSUE THREAD

**Issue by nlpstudy2017** [zenn-dev/zenn-community#512]
## 提案・要望
zennのトップページを、新着記事の一覧が目につくようなレイアウトにしていただきたいです。

## 背景
現状、トップページ上に掲載される記事のほとんどは、過去のヒットした記事であるように見受けられます。しかしその割には、新着記事の一覧が目につかないようなレイアウトになっています。新着記事の中にも有益なものが出てくるので、手軽に新着記事の一覧を確認できないと、正直不便に思います。

**Comment by tannerjohn65** [comment]
ご提案ありがとうございます。体験に影響が大きいため慎重に検討したいしたいと思います。他のタスクなどがあるため、検討に時間がかかることをご理解頂ければ幸いです。

**Comment by cm-igarashi-ryosuke** [comment]
新着記事は有益な記事もありますが人によってはノイズになる可能性の高い記事もあると思いますので、トップページに配置するということは考えていません。

ただ現状のトップページも十分とは考えていませんので、パーソナライズなども含め引き続き改善は検討していきます。
