### ISSUE TITLE
コメント機能自体を無効化する機能を追加してほしい

### ISSUE THREAD

**Issue by s1204IT** [zenn-dev/zenn-community#513]
## 提案・要望
コメント機能自体を無効化する機能を追加してほしい

## 背景
コメント欄が知識の無い方の集いになってしまい、わざわざ非表示にするのも面倒なので、最初からコメントを無効化出来る機能が欲しいと思った。

**Comment by tannerjohn65** [comment]
お世話になっております、こちらリクエストありがとうございます。
上記の変更はサービスへの影響が大きいため、慎重にチームで検討いたします。

引き続き、よろしくお願いいたします。

**Comment by tannerjohn65** [comment]
お世話になっております。こちらについて検討いたしましたが、技術記事に対するフィードバックとしてコメントをご活用いただきと考えており、現状非表示にすることで対応いただきたい所存です。そのためこちらはCloseさせていただきます。
