### ISSUE TITLE
記事にYouTubeプレイリストを埋め込むと「YouTubeのvideoIDが不正です」というエラーが表示される

### ISSUE THREAD

**Issue by kboy-silvergym** [zenn-dev/zenn-community#516]
### 事象

以下のYouTubeプレイリストを記事に埋め込んでいて、ついこの前までは**リンクとしてプレビューが表示されていた**のですが、先ほど見たら「YouTubeのvideoIDが不正です」というエラーが表示されていました。
https://www.youtube.com/playlist?list=PLuLRJz1UnJzHX1dDN-jnaa7gQ3Av7eEmJ

現在は、代わりにplaylistの一番上の動画urlである以下を貼って対処していますが、できればプレイリストのurlを貼りたいと思っています。
https://www.youtube.com/watch?v=I6TpDuSFbTc&list=PLuLRJz1UnJzHX1dDN-jnaa7gQ3Av7eEmJ&index=1

### 発生したページのURL

https://zenn.dev/flutteruniv_dev/articles/flutter-roadmap

### 再現方法

記事に以下のurlを貼る
https://www.youtube.com/playlist?list=PLuLRJz1UnJzHX1dDN-jnaa7gQ3Av7eEmJ

**Comment by uttk-dev** [comment]
@kboy-silvergym 

報告ありがとうございます。
調査して対応したいと思いますが、他の重要なタスクがあるため対応に時間が掛かる可能性がありますので、ご理解頂けると幸いです。

**Comment by uttk-dev** [comment]
@kboy-silvergym 

こちらのバグ、先ほど修正されたことを確認しましたのでクローズします。報告ありがとうございました！
既に保存されている記事や本などの場合は再変換が必要なため、お手数ですが再変換 + 保存で対応して頂ければと思います。
よろしくお願いします！

**Comment by kboy-silvergym** [comment]
ご対応ありがとうございます！

**Comment by kboy-silvergym** [comment]
こちらの記事でも直ったことを確認できました 🙏 
https://zenn.dev/flutteruniv_dev/articles/flutter-roadmap
