### ISSUE TITLE
コードブロック内部でディレクトリ構成(ツリービュー)をハイライトしてほしい

### ISSUE THREAD

**Issue by RNm-dove** [zenn-dev/zenn-community#517]
### 提案・要望

よくこのようなディレクトリ構成をコードブロックで書いて表現しています。標準のコードブロックのプレビューだと、背景が黒色でフォルダ名/ファイル名が白色で行間が広いため、見にくいです。ディレクトリ構成特有のハイライトがあるとみやすいなと思いました。例えば、[prismのプラグインページにあるTreeview](https://prismjs.com/plugins/treeview/)など。

```
├── controllers
│   ├── userController.ts
│   └── chatController.ts
├── services
│   ├── userService.ts
│   └── chatService.ts
├── models
│   ├── user.ts
│   └── chat.ts
└── configs
```

### 背景

ディレクトリ構成はアプリ開発においては重要な技術ノウハウになるため技術ブロクではテーマとしてしばしば取り扱われます。自分もよくディレクトリ構成を書くことがあるので、ハイライト機能があると読者も見やすくなり嬉しいなと思いました。

**Comment by uttk-dev** [comment]
@RNm-dove 

提案ありがとうございます。
良さそうな案だと思うので開発チームに持ち帰って取り入れられないか相談してみますね。

P.S. 他のタスクなどの関係で、対応に時間がかかる場合がありますので、その点はご理解頂ければと思います🙏

**Comment by RNm-dove** [comment]
@uttk-dev 
わかりました！ありがとうございます!

**Comment by uttk-dev** [comment]
@RNm-dove 

こちらの提案ですが開発チームに相談した結果、今のところ対応しないことになりました。
理由としては、

1. 使用頻度が低そう
2. 人によっては見づらくなる
3. 現状の Markdown 記法でも問題なくツリー構造を記述できる or 意図を伝えられる
4. ビルドファイルが肥大化する ( 肥大化する割にはメリットが薄い )
5. 意外と実装( or メンテナンス )に手間がかかる

などの意見が出ており、現状の Zenn では取り入れる必要性が薄いとの判断になりました。
せっかく提案して頂いて申し訳ないですが、ご理解頂けますと幸いです 🙇‍♂️
