### ISSUE TITLE
コミュニティガイドラインに則していないことを手早く伝える機能が欲しい

### ISSUE THREAD

**Issue by tenkoh** [zenn-dev/zenn-community#519]
### 提案・要望

いつもサービスをありがたく使わせて頂いています。

本Issueは純粋な機能改修というよりは、運営としての方針を問うような性質を含んでおります。

提案：コミュニティガイドラインに則していないことを手早く伝える機能が欲しい。

- 実装案1：「ただの個人メモのような記事」に対し、📝に❌したような絵文字評価ボタンを導入する。
- 実装案2：「コミュニティに貢献していない（例：不正確な内容を含む、評判稼ぎだ、など）」に対し、👨‍👧‍👦に❌したような絵文字評価ボタンを導入する。
- 実装案(共通)：いいね👍とは異なり評価者は通知されない。

ポイントは何でもかんでも「よくない👎」というのではなく、コミュニティガイドラインを軸として、そのどこに合致していないかを示すことだと考えています。

### 背景

- 「投稿する前に本当にコミュニティガイドライン読んだ！？」というような記事を見かける頻度が増えてきました。
- とりうる選択肢はミュートか、適切な評価指標を取り入れるかの二択かな、と思います。
- 本Issueは後者の評価指標での解決を提案するものです。
- ミュートについては別Issueがありましたので、こちらでは触れません。

**Comment by cm-igarashi-ryosuke** [comment]
@tenkoh ご提案ありがとうございます！

以下、チームとしてではなく個人としての回答です。

ユーザーからのフィードバックによって数値化するというのは良いアイディアですね。

ただ、以下のような懸念も考えられます。

- 一概に基準を決められない（例えば、-5まではセーフで-6はアウト、など）
- 仕組みをハックされる恐れがある（例えば、あの人は気に入らないから集団でネガティブフィードバックをしよう、など）
- 上記のような問題があるため、運営が都度判断することになり、運営の負担が大きくなる。
- 運営が介入すると公平性の問題が発生する（この記事はセーフなのに、あの記事はNG？、など）
- ネガティブな感情が増幅されコミュニティが殺伐とする（この記事はアウト？セーフ？などをみんな考えてしまう）

なので、利用規約に違反するレベルでない限り、そこに介入するのは難しいと考えています。

また、ガイドラインに沿わない記事を書く人は初心者であることが多く、エンジニアコミュニティの文化についてもよく分かっていない人が多いと思います。ある程度は多めに見てあげてほしいです。Zennが良いコミュニティであれば、いずれ気づいてくれると思います。

**Comment by tenkoh** [comment]
すいません、うまく意図が伝わっていないようなので補足させて下さい。

ユーザーの評価による数値化や、それにより著者に不利益を与える意図はIssueに書いておりません。（実装例中に評価という言葉を使ったのが良くなかったです。すいません。）
おっしゃられる通り、様々な懸念があってとても現実的ではないと思います😅

私の提案の意図は「ガイドラインあるよ？意識してみたらもっと良くなるよね？」という意思を表しやすくしてはどうかな？というものです。

おっしゃられるようにガイドラインに則していない投稿は、初心者🔰の方に多いと思うのですが、そこにコメントで「ガイドラインが〜」なんて書くと、書く方も書かれた方もしんどいなぁというのが困り事です。

評価ボタンという書き方が良くなかったのかもしれません。正確に意図を書くと、「ここはメモを書くところじゃ無いよ」お気持ち表明ボタン📝❌、という提案になります。そして最初に書いた通り、それは各自のなんとなくの基準では無く、コミュニティガイドラインに則って理由を述べられるべきだろう、と思います。

コミュニティ全体の質を維持するために、そんな仕組みはどうかな？と思い、提案申し上げました。

**Comment by cm-igarashi-ryosuke** [comment]
@tenkoh 
失礼しました。趣旨を読み違えていました。

> そこにコメントで「ガイドラインが〜」なんて書くと、書く方も書かれた方もしんどいなぁというのが困り事です。

確かに、そうですね。課題として認識しました。

ただ、ユーザーからのフィードバックにすると、やっぱり伝え方が難しいですね。むしろ、サービスとしてもガイドラインを認識してもらう努力をしても良いかなと思いました。例えば、「アカウントが作成されてから一定期間は、投稿する直前のタイミングでガイドラインの要約を表示する」など。

チームでも考えてみたいと思います。

ご提案感謝いたします。

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、やはり「ネガティブなフィードバックを伝えること」の体験設計が難しく、Zennとしてはそのような投稿が少なくなるような施策をする方向にしようという結論になりました。

あらためまして貴重なご意見を感謝いたします。
