### ISSUE TITLE
Following tabに表示されたスクラップのコメントに文字化けが起こる場合がある

### ISSUE THREAD

**Issue by sizumita** [zenn-dev/zenn-community#524]
### 事象

Followingタブに他ユーザーがスクラップにコメントしたことが表示されているときにコメント内容が表示されますが、コードブロック内の文字が表示されているときに特殊文字（<など）がエスケープされた状態で表示されます。

### 発生したページのURL

https://zenn.dev/following
https://zenn.dev/yusukebe/scraps/781edf30b8ed21#comment-7bba889530cc2f

### 発生した画面のスクリーンショット

<img width="871" alt="スクリーンショット 2023-06-08 12 05 37" src="https://github.com/zenn-dev/zenn-community/assets/17804838/08484cd3-6062-4c01-baec-5a593032b40d">

ページ内容
<img width="814" alt="スクリーンショット 2023-06-08 12 10 58" src="https://github.com/zenn-dev/zenn-community/assets/17804838/10336072-f0a5-4119-99bc-a9712ee71b8e">

**Comment by uttk-dev** [comment]
@sizumita 

報告ありがとうございます。
開発チームに持ち帰って修正できるか検討したいと思いますが、他に優先度の高いタスクなどがあるため、修正に時間がかかる or 場合によっては修正できない可能性がありますので、その点はご理解いただけたらと思います。
よろしくお願いします。

**Comment by sizumita** [comment]
ありがとうございます。よろしくお願いいたします。

**Comment by cm-igarashi-ryosuke** [comment]
@sizumita こちら修正済みですのでクローズします。ご報告ありがとうございました。
