### ISSUE TITLE
コメントからユーザー詳細に飛ぶクエリにユーザー名ではなく表示名が使われている

### ISSUE THREAD

**Issue by kzhgit** [zenn-dev/zenn-community#527]
### 事象

記事にコメントしたユーザーをクリックするとユーザー詳細に飛べるようになっているかと思いますが、
リンク先にユーザー名ではなく表示名が使われています。

例えば、私のユーザー名と表示名は以下です。
ユーザー名|表示名
---|---
kaz_z|kazuho

このとき、コメントからユーザー詳細に飛ぼうとすると以下のリンクになってしまっています。
`https://zenn.dev/kazuho`
（正: `https://zenn.dev/kaz_z`）

それによって起こる問題として以下のようなものがあります。
- 表示名とユーザー名が一致していない場合は404ページが表示される
- 表示名が誰かのユーザー名だった場合、別人のユーザー詳細に飛んでしまう

### 発生したページのURL

各記事のコメント欄

### 発生した画面のスクリーンショット

<img width="498" alt="スクリーンショット 2023-06-25 16 35 18" src="https://github.com/zenn-dev/zenn-community/assets/62587552/6be9d001-6989-4958-a2af-e3a21ae2ffaa">

**Comment by uttk-dev** [comment]
@kzhgit 

バグ報告ありがとうございます。
こちら先ほど修正&リリース完了して、直っていることを確認したためクローズさせて頂きます。
もし直ってない場合は、一度ブラウザキャッシュなどのキャッシュを削除してから再度試して頂くと直っていると思います。
よろしくお願いします！
