### ISSUE TITLE
メッセージ内にアコーディオンを設置するとメッセージの閉じコロン（:::）が表示されてしまう

### ISSUE THREAD

**Issue by akiGAMEBOY** [zenn-dev/zenn-community#528]
### 事象

メッセージを設置する際、通常は開始コロン（:::message）から始まり、閉じコロン（:::）で構成されますが、
そのメッセージ内にアコーディオン（::::details ＆ ::::）を設置すると、
メッセージの閉じコロン（:::）がmarkdownとして認識されずに記事に表示されてしまいます。

※ 表示されてしまったメッセージの閉じコロン（:::）またはアコーディオンの閉じコロン（::::）を消去することで期待通りの動きとなる。
　 ただし、メッセージ内に複数のアコーディオンを設置したい場合は実現できない。

- markdown表示
  ```markdown
  :::message
  **messageのタイトル**
  
  messageの内容。
  ::::details message内のdetals
  detailsの内容
  ::::
  :::
  ```

- 実際の表示
  :::message
  **messageのタイトル**
  
  messageの内容。
  ::::details message内のdetals
  detailsの内容
  ::::
  :::
  👆 `:::`が表示されてしまう。

本件、私が仕様外の操作をしているのか不明ですが、
一旦、バグとして報告させて頂きます。

### 発生したページのURL

特定のURLで発生する事象ではない。

### 発生した画面のスクリーンショット

![image](https://github.com/zenn-dev/zenn-community/assets/120698319/59b9202d-012b-4863-8e9e-6c67f22bc9b9)

### 再現方法

事象に記載しているmarkdownを記述すると再現される。

### 環境

環境依存はないと思われる。

**Comment by cm-igarashi-ryosuke** [comment]
@akiGAMEBOY ご報告ありがとうございます。`:::` をネストさせるには、外側の要素に `:` を追加します。

```
::::message
**messageのタイトル**

messageの内容。
:::details message内のdetals
detailsの内容
:::
::::
```

ご参考: https://zenn.dev/zenn/articles/markdown-guide#%E8%A6%81%E7%B4%A0%E3%82%92%E3%83%8D%E3%82%B9%E3%83%88%E3%81%95%E3%81%9B%E3%82%8B%E3%81%AB%E3%81%AF

不具合ではありませんのでクローズいたします。

**Comment by akiGAMEBOY** [comment]
頂いた情報で実現できる事、こちらでも確認できました。
ご対応ありがとうございます。

メッセージはコロン3つ。アコーディオンはコロン4つ。という制約だと、
勘違いしていました。失礼しました💦

今後とも宜しくお願いします。
