### ISSUE TITLE
zenn preview実行時の編集（プレビュー）画面に目次（toc）がほしい

### ISSUE THREAD

**Issue by ito0804takuya** [zenn-dev/zenn-community#529]
### 提案・要望

（公開した記事には目次が付いていますが）、zenn preview実行後の記事の編集（プレビュー）画面に目次（toc）がほしいです。

### 背景

zenn previewを実行して、localで記事を編集しているときに、見出しの階層（h1, h2, h3, h4）が揃っているかをチェックしたいときがあります。
そのとき、目次があれば編集中の記事全体を俯瞰してチェックできるため、要望します。

### 関連

https://github.com/zenn-dev/zenn-community/issues/399

**Comment by uttk-dev** [comment]
@ito0804takuya 

提案ありがとうございます！
zenn preview の目次機能は検討しましたが、
今のところ他に優先したいタスクや技術的な課題が残っており、すぐに対応することは難しそうです。
対応するにしても時間がかかると思いますので、気長にお待ち頂ければ幸いです。

また、issue 管理のため関連で挙げられている https://github.com/zenn-dev/zenn-community/issues/399 の方へ統合したいと思いますので、こちらの issue はクローズさせて頂きます。もし、追加の提案がある場合はそちらの issue へコメントお願いします🙏

**Comment by ito0804takuya** [comment]
@uttk-dev 
早速ご返答いただき有難うございます。
内容、承知しました。
首を長くしてお待ちしております。

**Comment by cm-dyoshikawa** [comment]
@ito0804takuya 

こちらのIssue、対応しました！

https://info.zenn.dev/#2023-09-12-zenn-cli-toc-preview

`npm i zenn-cli@latest` などでパッケージを最新にして頂くと利用頂けるかと思います。

ご提案頂き、ありがとうございました！

**Comment by ito0804takuya** [comment]
確認しました！
ご対応・ご連絡いただき有難うございました。

2023年9月12日(火) 11:14 cm-dyoshikawa ***@***.***>:
