### ISSUE TITLE
一部の Mermaid 構文の描画で Syntax error が発生している

### ISSUE THREAD

**Issue by cm-rwakatsuki** [zenn-dev/zenn-community#530]
### 事象

記事中の一部の Mermaid 構文のレンダリングで Syntax error が発生しています。

一方で記事のソースとなる GitHub 側では正常に描画が行われています。
https://github.com/yamatatsu/zenn-contents/blob/main/articles/2021-09-19-aws-cdk-iot-l2.md

### 発生したページのURL

https://zenn.dev/yamatatsu/articles/2021-09-19-aws-cdk-iot-l2

### 発生した画面のスクリーンショット

<img width="1418" alt="image" src="https://github.com/zenn-dev/zenn-community/assets/57384023/907b6b9b-5bca-408a-ace7-6e2863a42d02">

<img width="1418" alt="image" src="https://github.com/zenn-dev/zenn-community/assets/57384023/c6bb4f6b-dd50-41c9-ac0c-ffa62fe6fd43">

**Comment by cm-wada-yusuke** [comment]
こちら確認します、ありがとうございます。

**Comment by cm-wada-yusuke** [comment]
根本原因がわかっていないのですが、対処療法を入れました。私たちも継続して監視しますが、再発を確認したら教えていただけると嬉しいです。

**Comment by cm-rwakatsuki** [comment]
迅速なご対応ありがとうございました！改善されていることを確認できました。
