### ISSUE TITLE
【質問】開発者コミュニティの情報発信源としての利用はガイドラインに反しますか？

### ISSUE THREAD

**Issue by lacolaco** [zenn-dev/zenn-community#531]
[OSSのユーザーコミュニティ](https://community.angular.jp/)を運営しているのですが、活動報告やイベントの開催告知など、日常的な情報発信源としてzennのPublication機能が使えないか検討しています。背景には、これまでTwitterを主な発信源としていたところ昨今の情勢により、まともに使えるメディアではなくなってきたことがあります。

機能面では不足ないように思っているのですが、問題はそのような用途での利用がzennのコミュニティガイドラインに違反しているのではないかということです。

https://zenn.dev/guideline

> これからコミュニティへ参加される方に特に意識していただきたいことは、Zennは情報共有コミュニティであるということです。コミュニティに投稿する内容は、どんなに小さくても良いのでコミュニティに貢献する内容にしましょう。

この懸念が払拭できない限りはzennのPublicationをコミュニティの情報発信源として利用することはできないと考えています。この点についてフィードバックがもらえたら助かります。

**Comment by cm-igarashi-ryosuke** [comment]
@lacolaco 
Zennの運営チームです。Zennでは、開発者コミュニティによるPublicationの利用を歓迎いたします！
活動報告やイベントの開催告知に利用されることは問題ありませんが、SNSと比べて、日常的な情報をユーザーに届けるには向かないと思いますので、適材適所でご利用いただければと思います。

**Comment by lacolaco** [comment]
@cm-igarashi-ryosuke ご回答ありがとうございます！そう言っていただけると安心できました。
解決できたのでcloseさせていただきます。
