### ISSUE TITLE
Publicationのオーナー上限を増やしたい

### ISSUE THREAD

**Issue by riya-amemiya** [zenn-dev/zenn-community#533]
### 提案・要望

Publicationのオーナー上限を現状の3人から5~10程度に増やしたいです。

### 背景

3人では現状のオペレーション上運用するのが難しいため

**Comment by cm-igarashi-ryosuke** [comment]
ご意見ありがとうございます。

利用規約の[Publication特約](https://zenn.dev/terms?type=publication)にあります通り、オーナーはPublicationに関する責任を負うものとなります。オーナーの人数が多くなりますと、何か問題があった時に責任の所在が分かりにくくなってしまうため、いまは3人と限定させていただいております。（今後、アップデートの予定があります。）

ご不便をおかけしますが、ご理解いただけますと幸いです。

**Comment by cm-igarashi-ryosuke** [comment]
ご意見ありがとうございます。

利用規約の[Publication特約](https://zenn.dev/terms?type=publication)にあります通り、オーナーはPublicationに関する責任を負うものとなります。オーナーの人数が多くなりますと、何か問題があった時に責任の所在が分かりにくくなってしまうため、いまは3人と限定させていただいております。

ご不便をおかけしますが、ご理解いただけますと幸いです。

**Comment by riya-amemiya** [comment]
ご返信ありがとうございます。
では、プロフィールの編集だけできる、メンバーの招待だけできるのような限定的な権限を付与できるロールの追加はどうでしょうか？

**Comment by cm-igarashi-ryosuke** [comment]
@riya-amemiya 

返信が滞っておりすみません。

> では、プロフィールの編集だけできる、メンバーの招待だけできるのような限定的な権限を付与できるロールの追加はどうでしょうか？

先ほど、「メンテナー」というロールを追加しました。
プロフィール編集はできませんが、メンバーの管理はできます。
https://info.zenn.dev/2023-11-21-publication-maintainer

こちらでオペレーション上の課題は解決されますでしょうか？
お試しいただけると幸いです。

**Comment by riya-amemiya** [comment]
@cm-igarashi-ryosuke 

ご返信、機能追加ありがとうございます。
問題解決できそうです。社内で早速試してみます。
本件クローズでお願いします。ご対応ありがとうございました！

**Comment by cm-igarashi-ryosuke** [comment]
@riya-amemiya 
承知しました。
ではIssueはクローズいたしますが、引き続き何かありましたらコメントいただければと思います。

ご意見いただきありがとうございました！
