### ISSUE TITLE
フォロー解除時に確認を出してほしい

### ISSUE THREAD

**Issue by Srgr0** [zenn-dev/zenn-community#534]
### 提案・要望

表題の通りですが、すでにフォローしているユーザーのフォローを解除する際、確認を表示していただきたいです。

### 背景

現在Zennでは、フォローしているユーザーをフォロー解除するときに確認が表示されません。
そのため、すでにフォローしていることを見落として再度フォローを押し、誤ってフォローを解除してしまう可能性があります。

**Comment by cm-igarashi-ryosuke** [comment]
ご意見ありがとうございます。

> すでにフォローしていることを見落として再度フォローを押し、誤ってフォローを解除してしまう可能性があります。

確かにその通りですが、確認を表示することでスムーズな操作感が損なわれてしまうデメリットもあります。
基本的な考えとしてリカバリが容易な操作には確認を表示していません。

ご理解いただけますと幸いです。
