### ISSUE TITLE
いいねした記事一覧ページにてタグでフィルターする機能

### ISSUE THREAD

**Issue by 0yukkey0** [zenn-dev/zenn-community#535]
### 提案・要望

自分がいいねした記事一覧のページでtopicsのタグで絞り込みができるようにしていただきたいです。

### 背景

様々な記事をいいねしていると古い記事が埋もれてしまったり、タグ別で記事を眺めたいことがあったのであると嬉しいなと思いました。

記事APIにトピックタグを保持されているようですので実現可能性はあるかなと思い提案させていただきました。
ぜひ、ご検討のほどよろしくお願いいたします。

**Comment by uttk-dev** [comment]
@0yukkey0 

提案ありがとうございます。

>様々な記事をいいねしていると古い記事が埋もれてしまったり、タグ別で記事を眺めたいことがあったのであると嬉しいなと思いました。

その機能はどちらかというと「ブックマーク」や「あとで読む」機能に近いモノだと感じました。

Zenn では過去に「あとで読む」機能などの提案を頂いていますが、ブラウザのブックマーク機能や、より便利なブックマークサービスがある中で、Zenn にそのような機能をつけても使われない可能性が高いと思っています。( [参考](https://github.com/zenn-dev/zenn-community/issues/130) )

また開発リソースを集中させるため、実装する機能を絞っていますので、上記の理由も相まって対応するのは難しいと思います。

**Comment by 0yukkey0** [comment]
@uttk-dev 
>「ブックマーク」や「あとで読む」機能に近いモノだと感じました

たしかに仰るとおりでした｡
ほかサービスにブックマーク機能があるなかで､zenn内専用のブックマーク機能がどのくらい使われるかを考えると優先度は高くないのは納得です｡

本 issue はクローズで問題ありません｡
