### ISSUE TITLE
決済内容に Zenn だとわかる情報を含めてほしい

### ISSUE THREAD

**Issue by januswel** [zenn-dev/zenn-community#536]
### 提案・要望

次のうち、両方もしくは 1 番だけでも対応していただけるとうれしいです

1. 決済内容に「Zenn」という文字列をいれる
2. 決済内容に記事名や書籍名をいれる

### 背景

クレジットカードの決済内容が「オンライン決済」のみなので、あとで明細確認したときに「これなんだっけ？」となってしまう

**Comment by cm-wada-yusuke** [comment]
Stipe決済なのですが、Stripeに表示の設定は入れており、あとはカード会社や銀行がどう表示するか、という判断のようです。

https://support.stripe.com/questions/why-do-customers-see-statement-descriptors-that-don-t-match-what-i-ve-set-in-stripe

決済からしばらく時間が経過するとおそらくカード会社側で以下のような補足情報を入れてくれると思うので、そちらでご容赦いただければと思います。
![image](https://github.com/zenn-dev/zenn-community/assets/17589989/40960536-6152-48ea-81d0-483886f2f12e)

**Comment by januswel** [comment]
情報提供ありがとうございます！！
わかりました 👍🏼
