### ISSUE TITLE
IPv6に対応してほしい

### ISSUE THREAD

**Issue by koyashiro** [zenn-dev/zenn-community#537]
### 提案・要望

IPv4 でしか <https://zenn.dev/> に接続できないため、 IPv6 でもアクセスできるように対応して欲しいです。

### 背景

IPv6で <https://zenn.dev/> にアクセスできない。

**Comment by cm-igarashi-ryosuke** [comment]
@koyashiro ご提案ありがとうございます。

どのような背景でIPv6対応を必要とされているか教えていただけますか？

**Comment by cm-wada-yusuke** [comment]
整理のため一度クローズします。再度必要になりましたらリオープンしていただければと思います。
