### ISSUE TITLE
コードブロックに折り返す機能が欲しい

### ISSUE THREAD

**Issue by mingos** [zenn-dev/zenn-community#540]
### 提案・要望

コードブロックに折り返す機能が欲しいです。

### 背景

コードブロック内で1行の文字数が多い場合、見切れてしまうので折り返して欲しいです。
C#などの言語ではどうしても文字数が多くなりがちなのでこの機能があると嬉しいです。

**Comment by uttk-dev** [comment]
@mingos 

提案ありがとうございます。
イメージとしては、VSCode の word wrap 昨日みたいな感じですかね？ ( [参考](https://www.javadrive.jp/vscode/setting/index7.html) )

**Comment by mingos** [comment]
@uttk-dev 

ご返信ありがとうございます。
はい、まさにこのword wrapの機能が欲しいです。

**Comment by uttk-dev** [comment]
@mingos 

なるほど、ありがとうございます！イメージできました！

ただそうなると、コードブロックがユーザーによって表示が変わってしまうため、やるとしたらユーザー(表示)設定でやると思うんですが、現状 Zenn に似たような設定項目がないので、その辺の設定周りの UI / UX や記事自体の閲覧体験も含めて設計する必要があり、今の開発状況では対応が難しいかもしれません。

とりあえず開発チームに持ち帰って対応するかしないかも含めて相談したいと思いますので、今は一旦保留にさせて下さい 🙏

**Comment by mingos** [comment]
@uttk-dev 

記事を書く側がコードブロックのマークダウンの書式で折返しのON/OFFを指定できると理想的ですが難しそうですかね。
検討だけでもしていただけるとありがたいです。
よろしくお願い致します。

**Comment by uttk-dev** [comment]
@mingos 

>記事を書く側がコードブロックのマークダウンの書式で折返しのON/OFFを指定できると理想的ですが難しそうですかね。

それも考えたんですが、人によっては折り返しして欲しくない人もいると思いますので、なるべくはユーザー各々が設定して快適に見れるようにしてもらった方がいいかなと個人的に思ってます。

**Comment by cm-wada-yusuke** [comment]
@mingos コードブロックごとに折り返せるよう右上にボタンを追加したので、試してみてもらえるでしょうか。
※ ページのリロードが必要な場合があります

**Comment by mingos** [comment]
@cm-wada-yusuke  ありがとうございます！折返し確認できました。
ただ、折返しボタンの画像が表示されないようです。添付画像の赤枠で囲った部分です。
![image](https://github.com/zenn-dev/zenn-community/assets/19461/7e5cc56d-2119-46a6-a364-f3be8f123b68)

**Comment by mingos** [comment]
すいません、いまリロードしたらボタンの画像が表示されました。

**Comment by cm-wada-yusuke** [comment]
ありがとうございます。一応CDNのキャッシュもこちらでクリアしておきますね
