### ISSUE TITLE
Trending Alltime Latest ボタンのクッリク時の挙動の改善

### ISSUE THREAD

**Issue by yagikota** [zenn-dev/zenn-community#541]
### 提案・要望

トピックごとのArticles画面(添付画像)で、Trending Alltime Latest ボタンで記事をソートできる機能があるが、ボタンクリック時にソートしてほしいです。

https://zenn.dev/topics/go にアクセスした際の画面
<img width="1224" alt="Screenshot 2023-08-03 at 14 29 33" src="https://github.com/zenn-dev/zenn-community/assets/69202609/4e183f7d-eda3-4f41-88bc-47d369b3af5f">

### 背景

Trending Alltime Latest ボタンによる記事のソート機能が以下のような挙動になる。

 ボタンを押下(この時点で反映されない)→リロード→ソートが反映される

**Comment by cm-igarashi-ryosuke** [comment]
@yagikota ご報告ありがとうございます。早急に対応いたします。

**Comment by cm-igarashi-ryosuke** [comment]
@yagikota ボタン押下時にソートが切り替わるよう、挙動を修正いたしました。ご報告いただきありがとうございました。

**Comment by yagikota** [comment]
早々にご対応いただきありがとうございます😊
