### ISSUE TITLE
Mermaidのバージョンを上げて欲しい

### ISSUE THREAD

**Issue by kyoh86** [zenn-dev/zenn-community#543]
### 提案・要望

現状動いているのが（少なくとも手元のPreview機能では）Mermaidの9.4.3なんですが、Mermaidの最新版はメジャーバージョンが上がって10.3.1になっています。
機能的な不足がだいぶ目立って、不自由を感じるので可能であればバージョンアップしていただけないでしょうか。

### 背景

Sequence DiagramのActor Creation and Destructionを使おうとして使えないことに気づきました。
https://mermaid.js.org/syntax/sequenceDiagram.html#actor-creation-and-destruction-v10-3-0

**Comment by cm-wada-yusuke** [comment]
これがブロック要因になってたのですが、クローズされてますね…ちょっと状況を確認します！
https://github.com/mermaid-js/mermaid/pull/4109

**Comment by cm-wada-yusuke** [comment]
@10.3.1にバージョンを上げましたので、お手すきでご確認いただければと思います。こちらではサンプルに指定いただいた以下のSequence図が表示できることを確認しました。


```mermaid
sequenceDiagram
    Alice->>Bob: Hello Bob, how are you ?
    Bob->>Alice: Fine, thank you. And you?
    create participant Carl
    Alice->>Carl: Hi Carl!
    create actor D as Donald
    Carl->>D: Hi!
    destroy Carl
    Alice-xCarl: We are too many
    destroy Bob
    Bob->>Alice: I agree
```

**Comment by kyoh86** [comment]
@cm-wada-yusuke 迅速なご対応ありがとうございます！
表示できてますね。zenn-cliのpreviewでも同様にご対応いただけると助かります。

**Comment by kyoh86** [comment]
確かめてみましたが、現在何か別件？の問題が起きてるようですね、ちょっと後日あらためて確認してみます。
![image](https://github.com/zenn-dev/zenn-community/assets/5582459/74535824-b0f5-4bed-a778-de7f374f4f2b)

**Comment by kyoh86** [comment]
できることが確認できました。ありがとうございます！

**Comment by cm-wada-yusuke** [comment]
@kyoh86 ご確認、ありがとうございました:pray:
