### ISSUE TITLE
URLのリンクが全てエラー表示される

### ISSUE THREAD

**Issue by daichi-takezawa** [zenn-dev/zenn-community#544]
### 事象

既にご存知かもしれませんが、Zennの本や記事に貼ってある全URLのリンクで以下の様にエラー表示されます。

### 発生したページのURL

すべての本や記事で現象が発生していると思われます。

### 発生した画面のスクリーンショット

![2023-08-17_00h45_30](https://github.com/zenn-dev/zenn-community/assets/50498401/ecc44b29-a2d6-44cc-be31-c53f8b27cb79)

**Comment by daichi-takezawa** [comment]
![F3qdjZBbwAEN9Ck](https://github.com/zenn-dev/zenn-community/assets/50498401/a1db4cc0-8996-47fd-bfd4-f0c9ff130610)

URLだとこっちの画像のエラーになるみたいです。mermaidだと上記の画像だと思われます。

**Comment by temasaguru** [comment]
現在直っているようです！

**Comment by daichi-takezawa** [comment]
良かったです!

**Comment by uttk-dev** [comment]
こちら解決済みのようなので、クローズさせて頂きますね。
