### ISSUE TITLE
Publicationの設定から設定したナビゲーションを、各記事でも表示してほしい

### ISSUE THREAD

**Issue by nanasi880** [zenn-dev/zenn-community#545]
### 提案・要望

Publicationには最大4つのナビゲーションを設置することができるかと思います。
以下のような設定画面で設定するものです。
https://zenn.dev/dashboard/publications/${Publication名}/settings?type=navigation

このナビゲーションは現在、Publicationのトップページに表示されていますが、Publicationに投稿された記事の末尾にもナビゲーションを表示するようにできませんでしょうか？
記事作者の下部にPublicationの情報も表示されるかと思いますが、そのあたりに表示があると良いと考えています。

### 背景

ナビゲーションは公式Webページや採用ページへ誘導するようなユースケースがあるかと思いますが、記事からPublicationに移動しないとナビゲーションが見れないのでは訴求力が低いと考えています。

**Comment by uttk-dev** [comment]
@nanasi880 

提案ありがとうございます。
Publication の固定メッセージではリンクを含めることができるので、そちらで対応できないでしょうか？ 

参考: [Publicationの使い方](https://zenn.dev/zenn/articles/how-to-use-publication#%E9%AB%98%E5%BA%A6%E3%81%AA%E8%A8%AD%E5%AE%9A)

**Comment by nanasi880** [comment]
ありがとうございます。
ご案内いただいたもので要件を満たせますので、本件はクローズさせていただきます。
