### ISSUE TITLE
メッセージに青や緑系の色を追加してほしい

### ISSUE THREAD

**Issue by 3w36zj6** [zenn-dev/zenn-community#546]
### 提案・要望

2020年頃に以下の記事のコメント欄で他の方が言及されていますが、独自記法の[メッセージ](https://zenn.dev/zenn/articles/markdown-guide#%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8)について、現状では警告色のようなイメージの色しか用意されていないため、単純な追加情報などの用途により適した穏やかなイメージのある青や緑系の色が欲しいです。

> こんにちは。
独自記法のメッセージについてですが、default(黄色)と"alert"(赤)以外に、"info"(青)、"tips"(緑)を追加するのはどうでしょうか？
現状の選択肢だけだとどうしても警告色っぽいイメージになってしまうので、単純な追加情報などに適した色合いがあるといいなと思いました。
>
> 参考になるかわかりませんが、以下のページの"admonition" sectionのようなイメージです:
> 
> [Showcase · Documenter.jl](https://juliadocs.github.io/Documenter.jl/dev/showcase/)

Ref: https://zenn.dev/link/comments/0256a717697d5d479b92

**Comment by tannerjohn65** [comment]
こちらご要望いただきありがとうございます！
上記についてはチームでも検討したのですが、Zennでは読者が快適に読めるように強調のパターンは増やさない方針となっています。（いろんな色で装飾されているより、一定決まっていた方が読みやすいと考えています）
ご意見いただいたなか恐縮ですが、現状は対応の予定がないのでクローズさせていただきます 🙏
