### ISSUE TITLE
サムネイル画像の入るタイトル文字列が変更に動的に対応するようにしてほしい。

### ISSUE THREAD

**Issue by yushikato0131** [zenn-dev/zenn-community#547]
### 提案・要望

サムネイル画像の入るタイトル文字列が変更に動的に対応するようにしてほしい。

### 背景

ひとつの記事を更新する際にタイトルに日付をいれて更新した事を示す場合などありますが、
タイトルを変更してもサムネイルには反映されないような気がします。
勘違いでしたらすみません。

**Comment by uttk-dev** [comment]
@yushikato0131 

報告ありがとうございます。

こちらで確認したところ、記事のタイトルを変更した後にサムネイル画像 ( OGP画像 ) を確認すると正しくタイトルが反映されていることを確認しました。 

そのため、もしかするとサムネイル画像を表示しているサービス例えば X (旧 Twitter) などのキャッシュが原因で、過去のサムネイルが表示されている可能性があります。その場合は Zenn では対応できませんのでご了承ください。

もし別の要因でしたら、問題が発生しているZennのコンテンツ(記事・本・スクラップ)のURLなどを共有して頂ければと思います。

よろしくお願いします。

**Comment by yushikato0131** [comment]
ご回答有難うございます。
おっしゃる通り X (旧 Twitter)での表示でした。
ブラウザキャッシュはクリアした状態でしたが、状況は変わらずでした。
https://zenn.dev/mjxo/articles/da6ad38f92da66

正しく理解がなく失礼いたしました、
ZENN側で対応出来る範囲外のようですので、クローズいただいて問題ありません。
有難うございました。

**Comment by uttk-dev** [comment]
@yushikato0131 

ありがとうございます。
念の為、私の方でも教えて頂いた記事のOGP画像を確認しましたが、
正しく反映されているようでしたので、この issue はクローズしたいと思います。

**Comment by yushikato0131** [comment]
お手数おかけしました。有難うございました。
