### ISSUE TITLE
スクラップ記事の並び替えができるようにして欲しい。

### ISSUE THREAD

**Issue by derbuihan** [zenn-dev/zenn-community#548]
### 提案・要望

スクラップ機能にコメントの並び替えや途中の挿入ができるようにしてほしい。
Jupyter Notebookのようなイメージです。

### 背景

Zennのスクラップ機能は、メモ帳として便利に使っております。
ある程度コメントが貯まってくると整理のために、並び替えしたり途中に文章を挟みたくなります。
例えば一番上のコメントを書き換えようとすると、全てのコメントを一個ずつコピペでずらす必要が出てきて非常にめんどくさいです。

**Comment by uttk-dev** [comment]
@derbuihan 

提案ありがとうございます。

こちら一度チームで検討しましたが、既存機能のピン留め機能と競合する部分があることや、「ピン留め」を考慮しつつ並び替えの表示をすると表示ロジックが複雑になりすぎる点などから対応しないこととなりました。

せっかくの提案で申し訳ないですが、ピン留め機能などで対応して頂ければと思います。

![image](https://github.com/zenn-dev/zenn-community/assets/97154037/9a5a01f8-94af-4d0b-8e85-ff1301ed6f36)

**Comment by derbuihan** [comment]
@uttk-dev 

返信ありがとうございます。
ピン留め機能があるの知りませんでした。ぜひ活用させていただきます。
