### ISSUE TITLE
フォローが外せない

### ISSUE THREAD

**Issue by ichiwa** [zenn-dev/zenn-community#549]
### 事象

フォローしている人のフォローを外すことができない。

### 発生したページのURL

基本的にフォローボタンのあるところ全部だと思われる。

### 発生した画面のスクリーンショット

<img width="595" alt="スクリーンショット 2023-08-25 15 51 13" src="https://github.com/zenn-dev/zenn-community/assets/3645994/90274722-dc60-4d57-bc1a-ac91b244aec6">

### 再現方法

フォロー中一覧からフォロー中の人のフォローを押す。

### 環境

- Chrome
- Mac

**Comment by cm-igarashi-ryosuke** [comment]
@ichiwa ご報告ありがとうございます。再現することを確認しました。なる早で修正します 🙏

**Comment by cm-igarashi-ryosuke** [comment]
@ichiwa 修正しました 🙏
