### ISSUE TITLE
本文更新日や文章量、何分で読めるかの情報が出てきていない

### ISSUE THREAD

**Issue by korosuke613** [zenn-dev/zenn-community#550]
### 事象

2023/08/27 時点で zenn.dev の記事ページに本文更新日や文章量、何分で読めるかの情報が出ていないことに気づきました。

以前は表示されていたかと思います。

いつからこれらの情報が出ていないのかはわかりませんが、これらの情報があると読む方としては嬉しいです。

仕様なのかバグなのかわかっていませんが、もしもどこかでアナウンス済みであればすみません🙇

#### 表示されている例1
https://zenn.dev/daichi_gamedev/articles/4ee023a1bc2d06#%E3%81%9D%E3%82%82%E3%81%9D%E3%82%82zenn%E3%81%A8%E3%81%AF%EF%BC%9F

いつのスクリーンショットかわかりませんが、サイドバーに、公開日、本文更新日、文章量が表示されています。

#### 表示されている例2
<img width="795" alt="image" src="https://github.com/zenn-dev/zenn-community/assets/20027695/e007c034-1076-4c22-8000-e8bbd7a9283b">

これは自身で以前撮影したスクリーンショットであり、いつ撮影したか覚えていませんが、何分で読めるかの情報が出ています。

### 発生したページのURL

https://zenn.dev/cybozu_ept/articles/productivity-weekly-20230816

他の記事のページでも発生しています。

### 発生した画面のスクリーンショット

<img width="1320" alt="image" src="https://github.com/zenn-dev/zenn-community/assets/20027695/585a5feb-b161-4cf8-bc9f-036ba451e998">

2023/08/27 17:35 (JST) 時点

### 再現方法

zenn.dev 上の任意の記事を開く

### 環境

- OS: macOS 13.4（22F66）
- ブラウザ: Microsoft Edge 116.0.1938.54 (公式ビルド) (arm64)

**Comment by cm-wada-yusuke** [comment]
@korosuke613 フィードバックありがとうございます。現在、画面上の情報を整理しており、その一環で項目を非表示または新しく増加させて効果測定を行っています。文章を読める目安は、その一環で非表示とした項目です。スクロール量である程度予測がつくから、というのが理由ですが、「読む方としては嬉しい」というフィードバックをいただいたことはチーム内で共有します。

本件に関しては現時点で仕様ということで、クローズさせてください。

**Comment by korosuke613** [comment]
@cm-wada-yusuke 
承知しました！フィードバックありがとうございます！
