### ISSUE TITLE
APNG (Animated PNG) の添付に対応して欲しい。

### ISSUE THREAD

**Issue by Kyome22** [zenn-dev/zenn-community#552]
### 提案・要望

アニメーションで挙動を提示したい時にAPNGを利用できるようになると嬉しいです。

### 背景

アニメーションで挙動を提示したい時にGIFが利用可能ですが、GIFだと使える色数が少なく結果画質が落ちるため、読者に伝えられる情報が劣化すると思っています。そこでGIFよりも使える色数が多いAPNGを利用できるようにしていただきたいです。

**Comment by cm-wada-yusuke** [comment]
テスト

![image](https://github.com/zenn-dev/zenn-community/assets/17589989/b410bd21-8dad-49a9-b21e-82331bdf794f)

![image](https://ics.media/entry/3718/images/animate_zlib.png)

https://zenn.dev/link/comments/b05a92d20e389c


@Kyome22 Zennへ投稿すると静止画になるということですね。ちょっとすぐできそうかだけ確認します！

**Comment by cm-wada-yusuke** [comment]
@Kyome22 こちらですがバックエンドの画像最適化処理で PNG の動画・静止画を判別する必要が出てくるため、すぐの対応は難しいです、もうしわけないです。Animated webp は利用できますのでそちらでカバーしていただければと思います。

https://zenn.dev/waddy/scraps/fd7415a3109827#comment-b05a92d20e389c

**Comment by Kyome22** [comment]
@cm-wada-yusuke 
ご検討ありがとうございます！
Animated webpが利用できるとのことですので、こちらの利用を試してみます。
