### ISSUE TITLE
Zenn に記述する際に縦のテーブルがほしい

### ISSUE THREAD

**Issue by DarkWindEX** [zenn-dev/zenn-community#553]
### 提案・要望

Zenn の Markdown 記法にてテーブルの Head が横に並びますが、縦に並ぶテーブルも用意してほしいです。

**Comment by cm-igarashi-ryosuke** [comment]
@DarkWindEX ご提案ありがとうございます。

標準的なMarkdownの仕様には、Headが縦に並ぶテーブルを表現する記法はありません。

実現するとしたら、MarkdownではなくHTMLで記述していただくことになると思いますが、こちらもハードルが高く実現までの見通しが立っていない状況です。気長にお待ちいただければと思います 🙏 

関連: https://github.com/zenn-dev/zenn-community/issues/281
