### ISSUE TITLE
「ZennのMarkdown記法一覧」に有効な diff 記法について詳しく記載してほしい

### ISSUE THREAD

**Issue by k1350** [zenn-dev/zenn-community#554]
### 提案・要望

 [Zennとdiff記法について](https://zenn.dev/kkiyama117/articles/2021-01-25-markdown-diff-unified) という非公式の記事で Zenn で有効な diff 記法について説明されているのですが、公式の[ZennのMarkdown記法一覧](https://zenn.dev/zenn/articles/markdown-guide#diff-%E3%81%AE%E3%82%B7%E3%83%B3%E3%82%BF%E3%83%83%E3%82%AF%E3%82%B9%E3%83%8F%E3%82%A4%E3%83%A9%E3%82%A4%E3%83%88) には詳しい記載がありません。

公式の記事でも zenn で有効な diff 記法について詳しく記載していただけると助かります。

### 背景

下記のように diff のコードブロックで HTML タグを書くと

![image](https://github.com/zenn-dev/zenn-community/assets/40417367/c57f7cb5-4ac2-4a58-bb0b-c4ac081e2f7e)

HTML タグの前に半角スペースが無い場合、その部分もマイナス差分扱いでハイライトされてしまいます。

![image](https://github.com/zenn-dev/zenn-community/assets/40417367/1a7d5463-5849-499b-92e2-4120927f8b71)

これは `<` `>` が diff 扱いになるのだと知っていれば理解できる挙動なのですが、私は diff 記法に詳しくなく、Markdown の diff ハイライトの説明は `+` `-` 記号を用いたパターンしか見たことがなかったので混乱しました。

`<` `>` は HTML を書くと自然に出てくる記号なので、これが diff 扱いになる条件になっているのならばドキュメントに記載していてほしいと思いました。

**Comment by k1350** [comment]
追記です。

[diff のシンタックスハイライト](https://zenn.dev/zenn/articles/markdown-guide#diff-%E3%81%AE%E3%82%B7%E3%83%B3%E3%82%BF%E3%83%83%E3%82%AF%E3%82%B9%E3%83%8F%E3%82%A4%E3%83%A9%E3%82%A4%E3%83%88) の説明に記載してある

> なお、diffの使用時には、先頭に+、-、半角スペースのいずれが入っていない行はハイライトされません。

という文章について、この文脈における「ハイライト」とは「diff のシンタックスハイライト」なのか「言語のハイライト」なのかわかりづらく、理解に時間を要しました。

また `<` なども diff を示す記号であることを考慮すると文章が不正確なので、

「diff と言語のハイライトの併用時には、行頭に差分を示す記号（+, -, <, > など）または半角スペースを入れてください。」

のような書き方のほうが良いのではないかと思いました。

**Comment by uttk-dev** [comment]
@k1350 

提案ありがとうございます。
ちょっとチームに持ち帰って対応できるか確認しますね。

**Comment by cm-dyoshikawa** [comment]
@k1350 

本件のご提案誠にありがとうございました。
チームで協議させて頂きました。

> 「diff のシンタックスハイライト」なのか「言語のハイライト」なのか

につきまして、恐れ入りますが、当面は現行の表現方法のままとさせて頂きます。

`>` `<` については仕様であるため[追記対応](https://github.com/zenn-dev/zenn-docs/pull/67)いたしました。

上記ご確認いただけますと幸いです。

**Comment by cm-dyoshikawa** [comment]
対応完了のためクローズします 🙇
