### ISSUE TITLE
一度 github連携を解除するとオンラインエディタでプレビューが表示できない

### ISSUE THREAD

**Issue by TBSten** [zenn-dev/zenn-community#558]
### 事象

以前githubリポジトリ連携を連携解除した後、オンラインエディタで記事を開きプレビューを表示すると以下のようなメッセージが表示されます。

<img width="1194" alt="スクリーンショット 2023-10-06 15 48 11" src="https://github.com/zenn-dev/zenn-community/assets/81161390/f8429305-42da-4bc1-9ef2-a88ee697325e">

### 発生したページのURL

以下などの「以前githubレポジトリ上で管理していた記事」についてプレビューが表示できないようです。

- https://zenn.dev/articles/droid-notification-permission/edit

逆に新規にオンラインエディタで作成したページはプレビューが表示できることを確認しています。

### 発生した画面のスクリーンショット

ブラウザの検証機能で通信内容を確認してみたので一応ご共有しておきます。

|エラーが発生する（以前githubで管理していた）記事のプレビュー時|エラーが発生しない（新規にオンラインエディタで作成した）記事のプレビュー時|
|---|---|
|<img width="801" alt="スクリーンショット 2023-10-06 15 54 15" src="https://github.com/zenn-dev/zenn-community/assets/81161390/241b6cae-a8a3-493b-891a-9d1ac6bc0afd">|<img width="801" alt="スクリーンショット 2023-10-06 15 58 05" src="https://github.com/zenn-dev/zenn-community/assets/81161390/16a5a585-ed87-4e02-991e-3d4ab2be0f1e">|

### 再現方法

以前githubリポジトリ連携を連携解除した後、オンラインエディタで記事を開きプレビューを表示する。

**Comment by cm-wada-yusuke** [comment]
詳細にありがとうございます。こちら、確認します。

**Comment by cm-igarashi-ryosuke** [comment]
@TBSten こちらの問題は解消しました。ご報告ありがとうございました。

**Comment by TBSten** [comment]
<img width="892" alt="スクリーンショット 2023-10-13 6 00 49" src="https://github.com/zenn-dev/zenn-community/assets/81161390/cf3f4ae8-02c9-4c53-88c5-74bef6150c2d">

確認できました！

ご対応ありがとうございましたー！

![ビッグ_感謝](https://github.com/zenn-dev/zenn-community/assets/81161390/7a7d4e56-66f9-423e-a98f-9f291730564d)
