### ISSUE TITLE
予約投稿したときにtopicsが反映されない

### ISSUE THREAD

**Issue by karamem0** [zenn-dev/zenn-community#559]
### 事象

GitHub連携で記事を作成しています。`published_at`を指定して記事を公開予約したときに、実際に公開された記事でトピックが反映されません。

手動デプロイにより強制的に同期すると正常にトピックが反映されます。

### 再現方法

以下の形式でFront Matterを設定します。

```
---
title: "ほげほげ"
emoji: "💻"
type: "tech"
topics: ["hoge"]
published: true
published_at: 2023-10-13 12:00
---
```

**Comment by cm-dyoshikawa** [comment]
@karamem0 
ご報告いただき誠にありがとうございます！
本件の再現が取れましたので現在対応中です。
ご不便をおかけしますが、お待ちいただけますと幸いです。

**Comment by cm-dyoshikawa** [comment]
@karamem0 

本件の修正を実施しリリースいたしましたので、クローズいたします。
引き続き、もし何かありましたらまたIssue起票頂けますと大変うれしく思います。

この度はご報告頂き誠にありがとうございました 🙇
