### ISSUE TITLE
currencyが異なるカードでの決済を可能に

### ISSUE THREAD

**Issue by inuro** [zenn-dev/zenn-community#56]
おそらくStripe側の仕様（あるいは使っているプランの仕様）だと思いますが、通過が日本円ではないカードで決済を試みるとdeclineされてしまいます。日本円以外の通貨のカードも対応できないでしょうか。

![IMG_74C32826CC9E-1](https://user-images.githubusercontent.com/674425/93830648-a1fe2b80-fc25-11ea-9eda-847d5afe5aaa.jpeg)

背景にある事情としては、

- 日本語話者のエンジニアであっても日本国内に住んでいるとは限らない
- 海外在住者は現地通貨でのカードを使っている
- 仮想カードインタフェースを提供しているサービスが海外に多い（今回のはSquare Cash）

あたりです。

**Comment by catnose99** [comment]
対応可能か調べてみます。
ただnote.comのようなサービスでも[海外発行のクレカは非対応](https://help.note.com/hc/ja/articles/360010037434-%E3%82%AF%E3%83%AC%E3%82%B8%E3%83%83%E3%83%88%E3%82%AB%E3%83%BC%E3%83%89%E3%81%AE%E7%99%BB%E9%8C%B2%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84)とのことなのでハードルは高いのかもしれません。

Stripeならそのあたりをクリアできる仕組みがあるのかも？

**Comment by inuro** [comment]
GMOペイメントゲートの図などを見ると、カード会社との間に挟まって通貨換算を担ってくれているようなので、Stripeにもそのオプションがあれば話は早そうですね。「グローバル対応の決済プラットフォーム」と謳っているのだからあると期待したいです。
https://www.gmo-pg.com/service/mulpay/multi_currency/
https://stripe.com/jp/payments

**Comment by inuro** [comment]
あるいはApplePayなどのウォレット払いというのも良いオプションかと思います（issue別の方が良いかな？）。
https://stripe.com/jp/payments/features#payment-options

**Comment by catnose99** [comment]
このissueで大丈夫です！
なるほど、Stripeのダッシュボードを見る限りApplePayなら比較的すぐに対応できるかもです。
しばらくお待ちください

**Comment by catnose99** [comment]
Apple Pay対応のIssueを作りまいｓた。
https://github.com/zenn-dev/zenn-roadmap/issues/65

**Comment by cm-wada-yusuke** [comment]
こちら、Apple Pay、Google Pay での決済に対応しました。海外からの支払いはこれらの支払い方法をお試しください。

**Comment by inuro** [comment]
素晴らしい。
