### ISSUE TITLE
画像ファイル名に日本語が含まれていると表示されない

### ISSUE THREAD

**Issue by lacolaco** [zenn-dev/zenn-community#561]
### 事象

GitHub連携で `/images` ディレクトリ内の画像ファイルを参照する際、画像ファイル名（おそらくはパスの一部でも発生しそう）に日本語が含まれている（おそらく非ASCIIなら発生しそう）と、プレビュー時・公開ページでファイルが見つからず404で表示されません。

日本語が使えないこと自体はリネームすればいいのでそれほど大きな問題ではないですが、ドキュメントに書かれていない振る舞いなので、日本語が使えるようになるかドキュメントに制限事項として書かれたりデプロイ時にエラーになったりするかのどちらかを期待したいです。

<img width="764" alt="image" src="https://github.com/zenn-dev/zenn-community/assets/1529180/8f8acefe-6a31-41b3-82c4-ca04fd51ec74">

### 発生した画面のスクリーンショット

```
![](/images/angular-mat-suffix-show-only-when-focused/3c6255ea-b6c7-4055-8126-638d2819f0c3/5236dbbb-d480-47f6-bf88-31078006447b/あああcapture.gif)
```

に対して

<img width="774" alt="image" src="https://github.com/zenn-dev/zenn-community/assets/1529180/f327ca7a-9917-4a66-a38a-b43c3debc2a0">

### 再現方法

ファイル名に日本語を含める

**Comment by cm-dyoshikawa** [comment]
@lacolaco 

ご報告いただきありがとうございます。
本件、チームでも再現することを確認いたしましたので、対応方針を検討いたします 🙇

**Comment by cm-dyoshikawa** [comment]
@lacolaco 

本件の修正をリリースいたしました。以後のGitHubデプロイでは日本語が含まれた画像ファイルを扱えるようになっているかと思います。

ご報告いただき誠にありがとうございました！
