### ISSUE TITLE
スマホでmermaidの円グラフのラベルを表示してほしい。

### ISSUE THREAD

**Issue by yutyan0119** [zenn-dev/zenn-community#562]
### 提案・要望

いつもありがとうございます。
Androidスマホでmermaidの円グラフを表示した際に円グラフのラベルが表示されないです。
スマホからでもPC版サイトのチェックボックスを入れれば見ることは出来ます。

ラベルがないとかなり情報が欠如してしまうので、可能ならば表示してほしいです。

## 再現例
https://zenn.dev/usagi1975/articles/2023-02-17-233300_mermaid_memo#pie
![image](https://github.com/zenn-dev/zenn-community/assets/78634880/588f718e-e8a0-46d6-b84e-d6e745c57d9d)

## 環境
- Pixel6
- Android 14
- Chrome 117.0.5938.153

**Comment by cm-igarashi-ryosuke** [comment]
@yutyan0119 ご報告ありがとうございます！こちらでも再現することを確認できました。引き続き、調査を行い、対応を検討いたします。

**Comment by cm-igarashi-ryosuke** [comment]
@yutyan0119 確認したところ、mermaid.jsの仕様でした。スクリーンサイズにより凡例部分を出し分けているようです。
https://github.com/mermaid-js/mermaid/issues/2073

この課題に対する[PR](https://github.com/mermaid-js/mermaid/pull/4288)も作成されていたので、様子見としたいと思います。

**Comment by cm-wada-yusuke** [comment]
@yutyan0119 mermaid.js のバージョンをアップデートした結果、スマホ表示でも凡例が表示されるようになりました。ご連絡ありがとうございました。
