### ISSUE TITLE
プロフィールのGitHubユーザー名の末尾にびっくりマーク「!」を入れて更新しても「!」が追加されない

### ISSUE THREAD

**Issue by Kai-suzuki1** [zenn-dev/zenn-community#563]
### 事象

例えば「Hoge!」のように入力しても設定編集画面トップで表示されるGitHubマークには「!」が表示されておらず、「@Hoge」をクリックして飛ばされた先もユーザー名「Hoge」のGitHubアカウント。
<img width="144" alt="image" src="https://github.com/zenn-dev/zenn-community/assets/93758486/e4e413eb-2d2e-4a41-a2e5-4a9dee4b5a86">
※ちなみに「!」は半角のびっくりマークです。

### 発生したページのURL

https://zenn.dev/marehalo

### 発生した画面のスクリーンショット

名前を変更
<img width="320" alt="image" src="https://github.com/zenn-dev/zenn-community/assets/93758486/96378be2-a149-428b-90e6-706f3bd1fdde">

変更後の設定編集画面トップ
<img width="120" alt="image" src="https://github.com/zenn-dev/zenn-community/assets/93758486/b30b6ef9-dc2c-46ba-b98f-9bf7baa2482f">

### 環境

- MacBook Pro
- macOS(Sonoma)

**Comment by cm-dyoshikawa** [comment]
@Kai-suzuki1 

起票いただきありがとうございます。

GitHubユーザ名に `!` は使用できないと思われます。
そのため、本件は仕様としてご認識頂ければと考えております。

**Comment by cm-wada-yusuke** [comment]
Zennのプロフィール更新時にバリデーションエラーを表示できると良いのですが、GitHub側の仕様が明確ではないためZennのバックエンド側で利用できないと思われる文字列を削ぎ落とす仕様としています。ご了承ください。

**Comment by Kai-suzuki1** [comment]
@cm-wada-yusuke  @cm-dyoshikawa 
ご回答いただきありがとうございます！
詳しい仕様を知らずすいませんmm
また、迅速なご返信ありがとうございました
