### ISSUE TITLE
アーカイブしたスクラップの一括削除機能、または一定時間経過後に自動削除する機能

### ISSUE THREAD

**Issue by bilzard** [zenn-dev/zenn-community#566]
### 提案・要望

アーカイブしたスクラップの一括削除機能、または一定時間経過後に自動削除する機能があると個人的に助かります。

### 背景

過去に作ったけど時間が経ち、情報として公開する価値がなくなったものをまとめて削除したい。
アーカイブは消さずに残す運用でも良いが、間違って消したものと紛れてややこしくなりそう。

**Comment by cm-wada-yusuke** [comment]
@bilzard 参考までに、一括で消したい対象のスクラップっていくつくらいありますか？

**Comment by bilzard** [comment]
@cm-wada-yusuke 現状2ページです（50〜100くらい？）。

**Comment by cm-wada-yusuke** [comment]
@bilzard なるほど、それはひとつずつ消していくのは大変ですね。ただ、それだけたくさんのスクラップが積み上がる状況、めったにない操作だと思いまして、機能を用意したいのはやまやまなのですがかなり優先度は落ちてしまうと思います。

---

チョ〜〜っとここからは運営メンバーではなくいちZennユーザーの話として聞いてください。

一括削除するスクリプトを書いてみました。これを 
https://zenn.dev/dashboard/scraps?status=archived

こちらの画面でChromeのブラウザコンソールに貼り付けて実行していただくとconfirmモーダルが重なっていくので、あとは「削除する」を連打すれば画面上のすべてのスクラップが消せます。

- **本当に消えるので[エクスポート](https://zenn.dev/settings/export)などできる限りの対策をして実行してください**
- **申し訳ないですが自己責任でご利用ください**
- 消したくないものはお手数ですが個別にアーカイブを解除してもらえると助かります

```js
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const remove = async (article) => {
    await sleep(500);

    const buttons = article.querySelectorAll("button");

    // 各 button 要素の aria-label が「メニューを開く」の場合、クリックする
    for (const button of buttons) {
      if (button.getAttribute("aria-label") === "メニューを開く") {
        button.click();
      }
    }
    await sleep(500);

    // メニューが開いたら、その中の button 要素を取得
    const menu = article.querySelector('[data-testid="popover-menu"]');
    console.log({menu})
    const menuButtons = menu.querySelectorAll("button");
    console.log({menuButtons})

    // 各 button 要素のテキストが「アーカイブする」の場合、クリックする
    for (const button of menuButtons) {
      if (button.querySelector("span").textContent === "完全に削除する") {
        button.click();
      }
    }
  }

const articles = document.querySelectorAll("article[class*='ScrapItem_container']");

for (const article of articles){
    await sleep(1000);
    remove(article);
}
```

実行イメージ
https://github.com/zenn-dev/zenn-community/assets/17589989/c3a333c5-c52a-44b2-b92a-2b838478ac35

**Comment by bilzard** [comment]
了解しました。

**Comment by cm-wada-yusuke** [comment]
再度要望があった場合・複数要望が出た場合にリオープンします。
