### ISSUE TITLE
ツイート埋め込み機能が x.com でも機能して欲しい

### ISSUE THREAD

**Issue by termoshtt** [zenn-dev/zenn-community#567]
### 提案・要望

- [ツイート埋め込み機能](https://zenn.dev/zenn/articles/markdown-guide#%E3%83%84%E3%82%A4%E3%83%BC%E3%83%88)がURLが twitter.com でないと機能しないが、X（旧Twitter）からURLをコピーすると x.com になるため、手動で書き換える必要がある。 x.com でも機能するようにして欲しい

再現方法
-------

```markdown
@[tweet](https://x.com/termoshtt/status/1710662637829447992?s=20)
https://x.com/termoshtt/status/1710662637829447992?s=20
```

![image](https://github.com/zenn-dev/zenn-community/assets/1238153/398b90fa-1ecb-43db-ae55-07285b869889)

version
--------

```shell
$ npx zenn --version
0.1.148
```

**Comment by cm-wada-yusuke** [comment]
連絡ありがとうございます、X対応順次進めます。

**Comment by cm-dyoshikawa** [comment]
@termoshtt コメントいただきありがとうございました。

本件、以下のように対応いたしましたのでご確認いただけますと幸いです。

https://info.zenn.dev/#2023-11-30-x-com-tweet
