### ISSUE TITLE
アプリでのAPIおよびRSSの利用とコンテンツの表示について

### ISSUE THREAD

**Issue by Taichiro-S** [zenn-dev/zenn-community#569]
#250 に関連しておりますが、ZennのRSSフィードや(非公式？)APIを利用したモバイルアプリを作成しようと考えています。アプリケーション内では、記事の概要等を表示したいと考えております。APIおよびRSSの利用と、コンテンツの表示について質問させていただきます。

## APIとRSSの利用について
#250 や他のAPIに関連した質問を見た限りではAPIの仕様は確定していないとのことですが、アプリで利用させていただくことは可能なのでしょうか。リクエスト数は1日10回程度を予定しています。
RSSについては公式に公開されておりますが、リクエスト数の上限等、アプリでの利用に関して気をつけるべきことはありますでしょうか？

## コンテンツの表示について
アプリ内で各記事のタイトルや概要など、トピックのRSSフィードで取得できる内容を表示したいと考えています（元記事へのリンクは必ず掲載します）。これらの内容の表示は、Zennの利用規約（6条：利用者コンテンツについて、権利者の許可を得ることなく、無断で転載または二次配布等を行うことはできません。）に違反しないでしょうか？

ご指導をいただけますと幸いです。

**Comment by cm-wada-yusuke** [comment]
@Taichiro-S 

> APIの仕様は確定していないとのことですが、アプリで利用させていただくことは可能なのでしょうか

インターネットに公開しているAPIである以上、外部から利用することは問題ありません。しかし、こちらのAPIはあくまでZennのフロントエンドのために構築したAPIです。予告なく仕様を変更したり、レート制限をかける可能性があります。また、APIを利用することによって生じるいかなる損害に対して責任を負えません。ご了承ください。

> RSSについては公式に公開されておりますが、リクエスト数の上限等、アプリでの利用に関して気をつけるべきことはありますでしょうか？
ご自由にご利用ください。負荷状況によって予告なく制限をかける場合もあります。利用アプリ側でキャッシュするなど、サーバー側の状況に寄らない実装を工夫いただければと思います。

> アプリ内で各記事のタイトルや概要など、トピックのRSSフィードで取得できる内容を表示したいと考えています
RSSフィードで公開している内容は問題ありません。

**Comment by Taichiro-S** [comment]
ご回答ありがとうございます。
ありがたく使わせていただきます！
