### ISSUE TITLE
【質問】Publicationの再登録・非表示について

### ISSUE THREAD

**Issue by tetter27** [zenn-dev/zenn-community#570]
Publicationの仕様について質問させてください。

1. Publicationを削除した場合、同じ名前、URLで再登録することは可能でしょうか。
再登録可能な場合、第三者が再登録することは可能でしょうか。
2. Publicationを非表示にすることは可能でしょうか。
(Publicationが削除されていないが、Publicationの検索・記事からの確認などが不可能な状態を想定)

**Comment by cm-dyoshikawa** [comment]
@tetter27 

ご質問ありがとうございます。

> Publicationを削除した場合、同じ名前、URLで再登録することは可能でしょうか。

はい、可能になります。

> 再登録可能な場合、第三者が再登録することは可能でしょうか。

仕様上は可能です。一方で、Publiactionの審査段階で明らかに不適切な申請については却下する場合があります。また、承認後も不適切な動きが見られた場合は運営の判断でなんらかの対応を検討する場合があります。

> Publicationを非表示にすることは可能でしょうか。
> (Publicationが削除されていないが、Publicationの検索・記事からの確認などが不可能な状態を想定)

現状、そのような仕様はございません。

**Comment by tetter27** [comment]
ご回答いただきありがとうございます。

現在のPublication再登録の整理について理解いたしました。
