### ISSUE TITLE
アドベントカレンダーを作成する機能が欲しいです

### ISSUE THREAD

**Issue by ysknsid25** [zenn-dev/zenn-community#574]
### 提案・要望

こちらの方のようにアドベントカレンダーはQiitaで作成して、記事はZennで書いている
というような状況になっています。
https://qiita.com/advent-calendar/2023/cloud-run

これをZennの中で完結させることでZenn本体にランディングが増え、他の記事への参照も増えるのではないでしょうか。

**Comment by cm-wada-yusuke** [comment]
Zennのメリットについて考えていただきありがとうございます。たしかに、チーム内でもよくあがる話で、私もユーザーの利便性や技術コミュニティの盛り上がりを考えたときにZennで仕組みがあると喜ばれるだろうな、という予感はあります。

Zennは執筆者の体験向上を重視しており、日々継続して開発しています。一番大きい部分は、ざっくりですが、1年のうち1ヶ月のための開発よりも、オールタイムで有益となりえる施策を優先している、という考えがあります。

一方で可能性を閉ざすものではないです。状況が変わったり、Zennの開発組織が拡大してGOに踏み切れるときがやってくるかもしれませんが、現状のわたしの認識としては以上になります。よろしくお願いします。
