### ISSUE TITLE
GitHub連携時、記事の管理から削除した記事が復活してしまう

### ISSUE THREAD

**Issue by eduidl** [zenn-dev/zenn-community#575]
### 事象

記事の管理のページで投稿した記事を1つ削除したが、連携しているGitHubのリポジトリからは消えなかったため、別件でリポジトリを更新したタイミングで削除した記事が新規投稿として公開されてしまった。

### 発生したページのURL

https://zenn.dev/dashboard

**Comment by cm-dyoshikawa** [comment]
@eduidl
ご連絡ありがとうございます。
こちらは仕様通りの挙動のため、対象記事を非表示にするには下記いずれかの対応が必要となります。

- GitHub連携している対象記事を非公開設定にする
- GitHub連携を解除し、ダッシュボードの投稿管理から当該記事を削除する

ご確認よろしくお願いいたします。

**Comment by cm-wada-yusuke** [comment]
上記に加えて、

- ダッシュボードから記事を削除したうえで、GitHubリポジトリから当該コンテンツを削除する

こちらでも対応可能です。よろしくお願いいたします。
