### ISSUE TITLE
特定の条件下でインラインマークアップが認識されない

### ISSUE THREAD

**Issue by Ruawolf** [zenn-dev/zenn-community#577]
### 事象

環境：zenn-cli
末尾に記号を含むインラインマークアップ（例：\*TEXT!\*）の直後にテキストを記述するとマークアップが認識されません。
末尾が記号でない場合や、インラインマークアップの後にスペースを入れた場合は認識します。

### 発生した画面のスクリーンショット

![image](https://github.com/zenn-dev/zenn-community/assets/142268083/ea5a8783-3a04-42a9-a9f2-2a95b817d2b8)

**Comment by cm-wada-yusuke** [comment]
報告ありがとうございます、こちら確認します。

**Comment by cm-wada-yusuke** [comment]
@Ruawolf こちら確認しました。Markdownパーサーとしてこのような変換結果になってしまうようで、Zenn側のアプリケーションで対処することは難しそうです。お手数ですが、空白などをうまく利用して回避いただけますと幸いです。

GitHubでも同様の変換結果になりそうです。

*TEXT!*TEXT
**(テキスト)**テキスト
~~%~~テキスト

空白を入れて回避した例です。

```
*TEXT!* TEXT
**(テキスト)** テキスト
~~%~~ テキスト
```
↓
*TEXT!* TEXT
**(テキスト)** テキスト
~~%~~ テキスト
