### ISSUE TITLE
タイムラインページにおける、記事投稿イベントのデザイン崩れ

### ISSUE THREAD

**Issue by bicstone** [zenn-dev/zenn-community#579]
### 事象

タイムラインページにおいて、「個人による記事やスクラップの投稿イベント」と、「Publication記事の投稿イベント」でアバターの横幅が10px異なっているため、記事が並ぶとガタガタになっており気になっています。
お手数をおかけしますが、ご確認のほどよろしくお願いいたします。

### 発生したページのURL

https://zenn.dev/following

### 発生した画面のスクリーンショット

<img src="https://github.com/zenn-dev/zenn-community/assets/47806818/0eb6ff74-03eb-4ef3-83bf-8e44272ba15b" width="300" />

<img src="https://github.com/zenn-dev/zenn-community/assets/47806818/d7a7a739-1723-49a5-b43a-d1abed4c0e15" /><img src="https://github.com/zenn-dev/zenn-community/assets/47806818/9bd8652c-8af0-4c66-86ba-dd1642d428ef" />

### 再現方法

Publicationとユーザーをフォローしてから、followingページにアクセスする

### 環境

複数の環境で再現

**Comment by cm-dyoshikawa** [comment]
@bicstone ご報告ありがとうございます。こちら確認いたします。

**Comment by cm-dyoshikawa** [comment]
@bicstone こちら、修正済みです。ご報告いただきありがとうございました。

**Comment by bicstone** [comment]
修正確認いたしました。
ご対応いただきありがとうございます！
