### ISSUE TITLE
Firefoxで記事編集時にプレビューがうまく表示されない

### ISSUE THREAD

**Issue by raiga0310** [zenn-dev/zenn-community#582]
### 事象

最新バージョンのFirefoxにおいて､記事を編集する際に本文に入力した状態でプレビュー画面に遷移したときに､下記の画像のようにエラーが表示される｡

### 発生したページのURL

https://zenn.dev/articles/48f7b774720fd2/edit

### 発生した画面のスクリーンショット

![image](https://github.com/zenn-dev/zenn-community/assets/44018535/1c2146a6-6f6b-4034-be12-1f4dc461714c)

### 再現方法

記事編集画面にてなにか入力してC-pでプレビュー画面に遷移

### 環境

- Device: Windows 11
- Browser: Firefox 121.0.1

**Comment by cm-wada-yusuke** [comment]
@raiga0310 ご報告ありがとうございます。こちら確認します。

**Comment by cm-wada-yusuke** [comment]
Mac の Firefox だと再現できず、時間がかかっています。もう少々おまちください

![image](https://github.com/zenn-dev/zenn-community/assets/17589989/63d6044b-2794-4784-a613-e1053e7d3a43)

**Comment by cm-wada-yusuke** [comment]
Windows11 
Firefox 122.0

![image](https://github.com/zenn-dev/zenn-community/assets/17589989/75824fea-fd52-4555-8174-5aa26ec84435)

**Comment by raiga0310** [comment]
@cm-wada-yusuke ありがとうございます｡こちら拡張機能のフィルタでZennを除いた所､正常に作動しました｡ありがとうございます｡

**Comment by cm-wada-yusuke** [comment]
@raiga0310 ご確認ありがとうございました！
