### ISSUE TITLE
GitHubのようにテキストを選択した状態でURLをペーストしたときにマークダウン形式に変換してほしい

### ISSUE THREAD

**Issue by negibokken** [zenn-dev/zenn-community#583]
### 提案・要望

Zennのスクラップの便利さに気づき活用させていただいています。いつもありがとうございます。

GitHubのテキストエリアのようにテキストを選択した状態で、URLをペーストしたときにマークダウン形式に変換する機能がほしいです。

(GitHubの例)

https://github.com/zenn-dev/zenn-community/assets/3014624/4c3f1ff1-68c3-4112-977a-e74de9cbaf2a

### 背景

HTMLの仕様のようにリンクが多い文章を引用しつつまとめているときに一手間を減らせればいいなと思っています。
HTMLの仕様をコピーしてZenn上にペーストして、リンクを張るとときには、`[`を入力してカーソルを移動させて`](`を入力し、URLをペーストして`)`を入力する、というステップを踏む必要があります。

これが選択してペーストするだけにできるといくつか必要なキー入力を減らせるので嬉しいです。
特にリンクが多かったり、引用しつつ記事を仕上げるときに書き心地をあげられるのではないかと思っています。

ご検討をよろしくお願いいたします。

**Comment by cm-dyoshikawa** [comment]
起票ありがとうございます。

たしかに仰るようなことができると多くのユーザに便利かと思いました！
チーム内で検討させて頂きたいと思います。

**Comment by cm-igarashi-ryosuke** [comment]
@negibokken こちら対応いたしました！
https://info.zenn.dev/2024-02-08-editor-update

GitHubなどでこのような機能があることを知らなかったのですが、慣れるとすごく便利ですね。
ご提案いただきありがとうございました！

**Comment by negibokken** [comment]
@cm-igarashi-ryosuke 早速ご対応いただきありがとうございます！とても嬉しいです😄
