### ISSUE TITLE
スクラップのコメントを並び替える機能がほしい

### ISSUE THREAD

**Issue by negibokken** [zenn-dev/zenn-community#584]
### 提案・要望

スクラップのコメントの順番を並び替えるための機能がほしいです。

### 背景

スクラップで、あるテーマについて色々とまとめているときに、テーマ内のトピック1について調べてコメントを投稿しているときに、途中でテーマ内のトピック2についても気になることがあり、後で調べるためにそのことを残しておきたいときがあります。このときスクラップには、トピック1についてコメントを重ねていきたい状況なので、トピック2を気にしていることを外部のエディタなどで記録しておく必要があり、Zennだけで完結させられればいいなと思っています。

もし並び替えができると、ひとまず気になるトピックについてコメントを残しておいて、引き続きトピック1について掘り下げるコメントを、トピック1のコメントの後に続けることができてスクラップが見やすくなるなと思っています。

**Comment by cm-dyoshikawa** [comment]
起票ありがとうございます。

https://github.com/zenn-dev/zenn-community/issues/548#issuecomment-1690957290

こちら検討したことがあったのですが、

> 既存機能のピン留め機能と競合する部分があることや、「ピン留め」を考慮しつつ並び替えの表示をすると表示ロジックが複雑になりすぎる

ことから申し訳ないのですが見送っております。

引用元で言及されているピン留め機能、またスクラップコメントの投稿後編集を活用していただければ幸いに思います。

**Comment by negibokken** [comment]
@cm-dyoshikawa ご回答ありがとうございます。すでに回答済みだったのですね、失礼しました…。難しいとのことなので、ご提示いただいた機能を活用しつつスクラップを作っていこうと思います。ありがとうございました！
