### ISSUE TITLE
エディターにてインライン脚注内に裸のURLが含まれている場合、下線が脚注を越えてしまう

### ISSUE THREAD

**Issue by mkpoli** [zenn-dev/zenn-community#585]
### 事象

ZennのMarkdownエディターにおいて、裸のURL（`https://zenn.dev/`）がインラインの脚注に含まれている場合、以下のようにリンクを示す下線から伸びて脚注の四角括弧（`[]`）を越えてしまう問題です。

<ul>
  <li>
      現在の振る舞い：<code>^<ins>[https://zenn.dev]NOBIRU</ins></code>
  </li>
  <li>
      想定される動作：<code>^<ins>[https://zenn.dev]</ins>NOBINAI</code>
  </li>
</ul>

もちろん、カード表示は脚注にはそもそも正しく表示されないので、裸のURLを脚注に使うことを避けるべきで、以下のような記法で回避できます。

<ol>
  <li>
      Markdownリンク記法
      <code>^<ins>[[Zenn](https://zenn.dev)]</ins>NOBINAI</code>
  </li>
  <li>
      カード回避記法
       <code>^<ins>[&lt;https://zenn.dev&gt;]</ins>NOBINAI</code>
  </li>
</ol>

しかし、文法的に正しくパースされている以上、定義された動作と表示上の動作にズレが生じているため、バグとは言えると思いますが、優先度は低そうです。いずれにしても、四角括弧のパース処理に問題が起きていると思われます。

### 発生したページのURL

`https://zenn.dev/articles/<*>/edit` (`<*>` = 任意の文章 ID)

### 発生した画面のスクリーンショット

![image](https://github.com/zenn-dev/zenn-community/assets/3502597/5dc8d373-7346-4a4f-8856-e1b314516412)

**Comment by cm-igarashi-ryosuke** [comment]
@mkpoli 詳細にご報告いただきありがとうございます。こちらの問題は、近日中に修正される見込みです。少々お待ちください。

**Comment by cm-igarashi-ryosuke** [comment]
@mkpoli こちらの問題は修正済みです。

```
^[https://zenn.dev]NOBIRU
^[[Zenn](https://zenn.dev)]NOBINAI
^[<https://zenn.dev>]NOBINAI
```
↓レンダリング結果
![image](https://github.com/zenn-dev/zenn-community/assets/13619209/155d9b1d-83d4-4169-a644-fefd1cde07c1)

ご報告いただきありがとうございました。
