### ISSUE TITLE
details の入れ子構造の時にスタイルが崩れる

### ISSUE THREAD

**Issue by 4geru** [zenn-dev/zenn-community#588]
### 事象

下記の時に style が崩れます
<img width="830" alt="スクリーンショット 2024-01-30 19 49 19" src="https://github.com/zenn-dev/zenn-community/assets/8898432/0d0fa619-a97a-4c51-bbc7-c4629938c1b9">

```
:::: details 折りたたみ
  :::: details 折りたたみ
  test
  :::
::::
```

期待しているのは次のような状態です。

<img width="825" alt="image" src="https://github.com/zenn-dev/zenn-community/assets/8898432/c5a67b27-3917-4aba-9a04-30c1be6b1c00">

CSS の設定で解決できると思います。

### 発生したページのURL

- local の cli
- scrap のコメント欄

**Comment by cm-igarashi-ryosuke** [comment]
@4geru ご報告いただきありがとうございます。こちら https://github.com/zenn-dev/zenn-editor/pull/488 で修正をしました。CLIやサイトへの反映にはもう少し時間がかかりますが、反映次第クローズさせていただきます。

**Comment by cm-igarashi-ryosuke** [comment]
@4geru 修正をサイトに反映しました。CLIは最新版にアップデートの上ご利用ください。ありがとうございました。

**Comment by 4geru** [comment]
@cm-igarashi-ryosuke 確認ありがとうございます
