### ISSUE TITLE
プレビュー画面にドラッグで移動して戻れなくなる

### ISSUE THREAD

**Issue by shimo164** [zenn-dev/zenn-community#592]
### 事象

記事を編集中、右方向にドラッグするとプレビュー画面に遷移する。クリックボタンを押したしたままだと左方向に戻れるが、離すと編集画面には戻れない。

> `[](url)`

### 発生した画面のスクリーンショット

![Peek 2024-02-15 14-05](https://github.com/zenn-dev/zenn-community/assets/24565156/08f26d9f-d820-482a-9065-17b6cd50c415)

### 再現方法

- 編集画面で左クリック
- 右方向にドラッグするとPreview画面になる
  - 左クリックを押したままであれば編集画面に戻ることができる 
  - Preview画面では、「コンテンツがありません」の表示
- プレビューボタンを押すと白い画面になる
- 再度プレビューボタンを押すと、Preview画面になる。
  - 記述した平文が表示される(編集できない)
- 編集画面には戻れない
  - (記事を閉じて開き直せば再開できる)

**Comment by cm-igarashi-ryosuke** [comment]
@shimo164 ご報告いただきありがとうございます。再現することを確認いたしました。順次対応いたします。

**Comment by cm-igarashi-ryosuke** [comment]
@shimo164 こちらの問題は修正が完了しました。ご報告を感謝いたします。ありがとうございました。
