### ISSUE TITLE
CloudflareのEmail Protectionによってメールアドレスでないものが隠されてしまう

### ISSUE THREAD

**Issue by InkoHX** [zenn-dev/zenn-community#594]
### 事象

`https://deno.land/std@0.100.0/path/mod.ts`というURLの`std@0.100.0`という部分が[`[email protected]`](https://zenn.dev/cdn-cgi/l/email-protection)に置き換わってしまいます。

他にDeno関連の記事を見てみましたが、上記の現象は見られませんでした。

### 発生したページのURL

https://zenn.dev/kawarimidoll/articles/0f5bc71ae633f3

### 発生した画面のスクリーンショット

![image](https://github.com/zenn-dev/zenn-community/assets/33122816/111f8189-19b6-42ee-bf57-d95384f6af75)

### 環境

- Browser: Firefox Developer Edition 123.0b9 (64-bit)
  -  JavaScript有効
  - 拡張機能全て無効化

**Comment by cm-wada-yusuke** [comment]
@InkoHX ご連絡ありがとうございます。エッジサーバーのメールアドレス難読化設定が意図せず有効になってました。現在は解消されていると思います。お手すきでご確認いただけると嬉しいです。ご報告助かりました。ありがとうございます。

**Comment by InkoHX** [comment]
確認できました。ご対応ありがとうございました！

**Comment by cm-wada-yusuke** [comment]
さっそくのご確認ありがとうございました！
