### ISSUE TITLE
Publicationのカバー画像を画質劣化しない形式でアップロードしたい

### ISSUE THREAD

**Issue by bicstone** [zenn-dev/zenn-community#595]
### 提案・要望

現状、Publicationのカバー画像をアップロードすると、 サイズ `1500px`×`500px` ・ quality `90%` のJPG画像に変換されています。
そのため、PCの高解像度のディスプレイで閲覧すると画質劣化を感じます。

例えば、png形式、`4500px`x`1500px`など画質劣化しない形式でアップロードができるように改修して頂くことは可能でしょうか?
(Publication Proの限定特典にするというのも良いと思います!)

### 背景

画質劣化してしまっていると感じたPublicationの例

- https://zenn.dev/p/monicle
- https://zenn.dev/p/zozotech
- https://zenn.dev/p/aldagram_tech
- https://zenn.dev/p/dataheroes

**Comment by moyamaa** [comment]
Zennサポートです。お返事が遅れて申し訳ありません。また、この間PublicationProをご利用いただいての
ご提案・ご要望を頂き誠にありがとうございます。頂いた機能についてもぜひ前向きに検討させていただきます。
よろしくお願いいたします。

**Comment by bicstone** [comment]
ご確認ありがとうございます。よろしくお願いいたします！

**Comment by cm-igarashi-ryosuke** [comment]
@bicstone お待たせいたしました。カバー画像のサイズを従来よりも大きく保つよう、設定を修正しました。

いったんissueはクローズさせていただきますが、もしまだ劣化が気になるなどありましたら、コメントいただければと思います。

ありがとうございました！
