### ISSUE TITLE
下書きのプレビューページに、レビューページへのリンクが欲しいです

### ISSUE THREAD

**Issue by bicstone** [zenn-dev/zenn-community#596]
### 提案・要望

Zenn Publication Proの「下書きプレビュー」ページに、「レビュー」ページへのリンクをつけて頂くことは可能でしょうか？
「下書きのプレビューを表示中」の右端に「レビュー↗」のリンクが追加されるイメージです。

### 背景

現状は「レビュー」ページから「下書きプレビュー」ページへのリンクはあるものの、その反対がないため要望させて頂きました。
(私だけだったら恐縮なのですが、「下書きプレビュー」を見てからレビューするという方法をとっているため、リンクがあると便利です)

**Comment by moyamaa** [comment]
Zennサポートです。お返事が遅れて申し訳ありません。また、この間PublicationProをご利用いただいての
ご提案・ご要望を頂き誠にありがとうございます。こちらのご提案についてもぜひ前向きに検討させていただきます。
よろしくお願いいたします。

**Comment by bicstone** [comment]
ご確認ありがとうございます。よろしくお願いいたします！

**Comment by bicstone** [comment]
プレビューページにレビューへのリンクが追加されたことを確認しました！
とても便利になりました！ご対応頂きありがとうございます 🙇🏻

**Comment by cm-dyoshikawa** [comment]
@bicstone リリースに本Issueを紐付けさせていただきました 🙇 

https://info.zenn.dev/2024-08-29-review-flow-improved

起票いただきありがとうございました。

**Comment by bicstone** [comment]
改めてご対応いただきありがとうございました！
レビュー機能がより使いやすくなりました！感謝申し上げます。
引き続きよろしくお願いいたします。
