### ISSUE TITLE
タグ(トピック)のフォロー機能

### ISSUE THREAD

**Issue by tsukiyama-3** [zenn-dev/zenn-community#597]
### 提案・要望

explore の Popular Topics のトピックスがランダム？になっていると思いますが、フォローしているタグだけの Popular Topics のようなエリアが欲しいです。

### 背景

興味のある分野だけ流し見をしたいのですが、現状だと一つタグを検索してみることしかできないので Popular Topics のようにタブを切り替えるように確認したいためです。

**Comment by cm-igarashi-ryosuke** [comment]
@tsukiyama-3 ご提案ありがとうございます！興味があるトピックの新着情報を手早く確認したいということですね。今後の機能改善の検討材料として参考にさせていただきます。

**Comment by cm-igarashi-ryosuke** [comment]
@tsukiyama-3 ご要望いただいた「トピック単位で確認できる」とは少し違うのですが、フォローしたトピックの新着情報をトップページのFollowingタブやメール通知にてご確認いただけるようになりました。

https://info.zenn.dev/2024-06-03-topic-following-available

ひとまずこの形でご利用いただいてフィードバックいただけると幸いです 🙏

**Comment by tsukiyama-3** [comment]
ご対応ありがとうございます！
いくつかトピックをフォローしてみました。
しばらく使ってみて気が付いたことがあれば共有いたします🙇

**Comment by cm-dyoshikawa** [comment]
機能が実現されたことから、クローズいたします。
