### ISSUE TITLE
現在リンクが機能していないようです

### ISSUE THREAD

**Issue by daichi-takezawa** [zenn-dev/zenn-community#603]
### 事象

Zennでお世話になっております。現在リンク表示が正しく機能していないようです。以下のようにリンクの部分が表示されません。既に存じ上げてるかもしれませんが、お伝えしておきます。

### 発生したページのURL

Zennのすべての記事や本っぽいです

### 発生した画面のスクリーンショット

![2024-04-01_21h33_40](https://github.com/zenn-dev/zenn-community/assets/50498401/72403011-3cb4-4a0e-9bc7-d13beda637e3)

**Comment by daichi-takezawa** [comment]
解決してました!

**Comment by cm-igarashi-ryosuke** [comment]
@daichi-takezawa ご報告いただきありがとうございました！

昨日（2024-04-01）の18:00~22:30頃にかけて、埋め込みが機能しない問題が発生していました。
現在は復旧しております。
