### ISSUE TITLE
記事編集画面内でCtrl + Fによるページ内検索をできるようにしてほしい

### ISSUE THREAD

**Issue by masa5714** [zenn-dev/zenn-community#605]
### 提案・要望

記事を書いているときに Ctrl + F でページ内検索を使うことが度々あります。

仮想スクロールが採用されている影響でページ内検索が使えません。（最近変わった？）
自分の記事を読んで誤字を修正したくても目視で探すことになり修正する気持ちが削がれてしまっています。

エディタのパフォーマンス上の都合かと思いますが、代わりにエディタ横に目次でジャンプできるようになるとすごく助かります。よろしくお願いいたします。

### 背景

- 誤字を探すのが大変
- 部分的にテキストを追加するときに箇所を探すのが大変
- プレビューを見たあとにエディタに戻るとスクロール位置が変わって、書いてたところを探すのが大変

**Comment by cm-dyoshikawa** [comment]
起票ありがとうございます。

> 仮想スクロールが採用されている影響でページ内検索が使えません。

こちら、チーム内で動作確認したところ、記事編集画面（ `https://zenn.dev/articles/[slug]/edit` ）において記事本文に対する Ctrl+F（MacではCmd+F）の検索は機能しておりました。
こちらの確認環境は

- Mac
    - Google Chrome
- Windows
    - Google Chrome
    - Microsoft Edge
になります。

再現したOS、ブラウザ、各バージョンを教えていただくことは可能でしょうか？

**Comment by masa5714** [comment]
@cm-dyoshikawa 
ご確認頂きありがとうございます。

当方の環境は
- Windows 11
- Google Chrome（ 123.0.6312.88 (Official Build) （64 ビット） ）
で利用しています。

また、 Microsoft Edge（ 123.0.2420.65 (公式ビルド) (64 ビット)  ）でも確認してみましたが同様の挙動となっておりました。

開発者ツールで覗いてみると無限スクロールの挙動が確認され、画面外の要素はDOMから消えております。

**Comment by cm-dyoshikawa** [comment]
@masa5714 

情報のご提供ありがとうございます。
再度確認したところ、一定以上分量のある記事での再現を確認できました。失礼いたしました。

いただいた課題の解決方法について、チームで検討いたします。

**Comment by masa5714** [comment]
@cm-dyoshikawa 

前提条件の共有漏れ、失礼いたしました。
現象が再現できたようで良かったです。

ご検討のほどよろしくお願いいたします！

**Comment by cm-igarashi-ryosuke** [comment]
@masa5714 

大変お待たせいたしました。
さきほど、エディタに検索機能を追加いたしました。
https://info.zenn.dev/2024-04-30-release-search-in-editor

issueはクローズさせていただきますが、もしフィードバック等ございましたら引き続きこちらのissueにお寄せいただければと思います。

ご報告いただきありがとうございました。

**Comment by masa5714** [comment]
@cm-dyoshikawa @cm-wada-yusuke 
動作が確認できました。記事管理が捗りそうです！
とても素晴らしい改善をありがとうございました！
