### ISSUE TITLE
[リクエスト] Xでの共有文章の改善

### ISSUE THREAD

**Issue by nakasyou** [zenn-dev/zenn-community#607]
### 提案・要望

「X(Twitter)にポスト」ボタンを押したときに生成されるテキストの改善要望です。
現状、
```
{タイトル} | {ユーザー名} {URL} #zenn
```
となっています。

これを、
```
{タイトル} | {ユーザー名} #zenn {URL}
```
のようにハッシュタグとURLの位置を交換していただきたいです。

### 背景

Xの仕様上、文の最後のURLはOGPに置き換えられます。
そのため、ハッシュタグがURLの後にあるため、見栄えが(個人的に)悪くなってしまっていると感じます。

![IMG_2936](https://github.com/zenn-dev/zenn-community/assets/79000684/7923eb2c-5100-40e9-a9e5-776036e7c41d)
![IMG_2938](https://github.com/zenn-dev/zenn-community/assets/79000684/3066963d-eb3f-493a-8f43-723aed62d7fe)

前者と後者では、私は後者の方がスマートだと思います。

**Comment by cm-wada-yusuke** [comment]
提案までしていただきありがとうございます。ファーストインプレッションとしてはいい感じだと思いました。このあたりと照らしあわせつつ、検討してみます。

https://create.twitter.com/ja/articles/how-to/2021/twitter-101-hashtags

**Comment by cm-wada-yusuke** [comment]
@nakasyou いいアイデアだったのですが、現時点では見送らせてください、申し訳ないです。

以下理由です。

- Zennではツイートリンクの取得に X(Twitter）APIの [Web Intent URL](https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent) を利用しています。このAPIに `title` や `text` 、 `hashtags` を指定できます
- APIでパラメータを指定すると自動でツイートテキストが生成されるのですが、それが現在の順序になっています
- こちらで順序を制御するには、ハッシュタグを含めるように `text` パラメータで指定する方法がありそうですが [参考](https://stackoverflow.com/questions/35708776/twitter-web-intent-change-order-of-text-url-hashtag) やりたいことに対してやや大掛かりになってしまいそうです

**Comment by nakasyou** [comment]
@cm-wada-yusuke
> いいアイデアだったのですが、現時点では見送らせてください、申し訳ないです。

問題ありません、こちらこそ、ご検討ありがとうございました！
