### ISSUE TITLE
数式に数式番号を振った場合、十分な横幅があるにもかかわらずスクロールできる要素になる

### ISSUE THREAD

**Issue by teruyamato0731** [zenn-dev/zenn-community#608]
### 事象

記事を作成し、markdownの中に以下を記述すると数式の中に数式番号が表示される。

```
$$
\begin{align}
J_w \ddot{\theta}_w &= T - \frac{f}{r} \\
\end{align}
$$
```

しかしながら数式番号を表示させると、内容がどれだけ短く、十分な横幅があっても横にスクロールが可能な要素になる。
十分な横幅があるなら、スクロール不可能な要素になってほしい。

### 発生したページのURL

自身が作成したscrap
https://zenn.dev/teruyamato0731/scraps/6472424d6562d7

数式の記法を参考にしたarticleでも同様の事象が発生している
https://zenn.dev/artakase/articles/4961142a918d26

### 発生した画面のスクリーンショット

上が数式を表示したもの。下が数式を表示しないもの。

PCからの表示
![image](https://github.com/zenn-dev/zenn-community/assets/77840326/a64c8e5f-3e0b-403c-b394-6f0cd2ca4454)

Androidも同様。
![image](https://github.com/zenn-dev/zenn-community/assets/77840326/143765ba-a74c-4458-b5b9-1dfe44340ac0)

※この記事は記述途中なので内容が変わる可能性があります。

### 再現方法

マークダウンの中に以下を記述。
```
$$
\begin{align}
J_w \ddot{\theta}_w &= T - \frac{f}{r} \\
\end{align}
$$
```

### 環境

- PC
  - Device: HP Pavilion aero
  - OS: Ubuntu 24.04
  - Browser: Chrome 124.0.6367.118
- Android スマホ
  - Device: Google Pixel 6a
  - OS: Android 14
  - Browser: Chrome

**Comment by cm-igarashi-ryosuke** [comment]
@teruyamato0731 ご報告いただきありがとうございます。

環境によってスクロールバーが表示されてしまうようですね。
順次対応いたしますのでお待ちいただければと思います。

関連?: https://github.com/zenn-dev/zenn-editor/pull/216

**Comment by cm-igarashi-ryosuke** [comment]
@teruyamato0731 大変お待たせいたしました。こちらの問題は修正しました。

もし不完全な部分がありましたら再度お知らせいただければと思います。
ご報告いただきましてありがとうございました。
