### ISSUE TITLE
スクラップのコメントについて新旧問わず日付を確認する方法を提供して欲しい

### ISSUE THREAD

**Issue by Paalon** [zenn-dev/zenn-community#611]
### 提案・要望

比較的古いコメントについては、日付が見えるが、３ヶ月前など、新しいコメントについては、正確な日付を確認する方法がなく、情報源として引用するときに困るので、確認する方法（マウスホバリングやクリックなどなんでもいいので）を提供して欲しい。

![スクリーンショット 2024-05-28 12 39 37](https://github.com/zenn-dev/zenn-community/assets/11065457/9b3663c6-e74f-4a00-ba63-106adf9b16e1)
![スクリーンショット 2024-05-28 12 36 08](https://github.com/zenn-dev/zenn-community/assets/11065457/1bf48cec-0520-44a4-ba26-18cbb6a6b81b)

### 背景

情報を引用するときに困る。

**Comment by cm-igarashi-ryosuke** [comment]
@Paalon ご意見いただきありがとうございます！

絶対日時も見えた方がいいですね。順次対応したいと思います。

> 情報を引用するときに困る。

この部分がよくわかっていないのですが、引用するときにURLだけではなく引用元の作成日も一緒に載せたいということでしょうか？具体的にどんなケースなのか気になりました。差し支えなければ教えて下さい 🙇

**Comment by Paalon** [comment]
例えば、この記事のように

https://zenn.dev/paalon/articles/c15519a1d4e836#%E5%8F%82%E8%80%83%E3%81%AB%E3%81%97%E3%81%9F%E5%85%AC%E5%BC%8F%E4%BB%A5%E5%A4%96%E3%81%AE%E3%82%82%E3%81%AE

引用する際に、手に入るならば、月日の情報も記入して載せておきたいということです。

**Comment by cm-wada-yusuke** [comment]
@Paalon こちら、スクラップのスレッドの日付をhoverしたときに絶対日時が表示されるようにしましたので、ご確認ください。

**Comment by Paalon** [comment]
確認しました。ありがとうございます。
