### ISSUE TITLE
ヘッダーの通知がリロードすると復活する

### ISSUE THREAD

**Issue by naopusyu** [zenn-dev/zenn-community#612]
### 事象

ヘッダーにある通知が閲覧後は消えるがリロードすると復活するようです

### 発生したページのURL

ヘッダーがある全てのページで発生していると思われます

### 発生した画面のスクリーンショット

<img width="120" alt="スクリーンショット 2024-05-30 9 09 49" src="https://github.com/zenn-dev/zenn-community/assets/97194355/70809264-bd12-4f8d-877b-c98fa43b6b50">

**Comment by cm-igarashi-ryosuke** [comment]
@naopusyu ご連絡いただきありがとうございます。

通知バッジが復活してしまう不具合を認識いたしました。対応までしばしお待ちください 🙇

**Comment by naopusyu** [comment]
@cm-igarashi-ryosuke 
ご確認ありがとうございます😊
引き続き対応をよろしくお願いします🙇

**Comment by cm-igarashi-ryosuke** [comment]
@naopusyu 先ほど修正が完了いたしました。

重ねて、ご報告に感謝いたします。ありがとうございました。

**Comment by naopusyu** [comment]
@cm-igarashi-ryosuke 
ご対応ありがとうございます！
