### ISSUE TITLE
zennのgitリポジトリ同期で本文がなくても下書きとして上げたい

### ISSUE THREAD

**Issue by akim-muto** [zenn-dev/zenn-community#613]
### 提案・要望

gitリポジトリで同期する記事ファイルに本文がなくて、空行が一行だけでも下書きとしてアップされるか、アップロードされずエラーにもならないようにしてほしい。

### 背景

タイトルと記事の枠だけ作っておきたいことがあるので、できると便利。

よろしくお願いします！！

**Comment by cm-dyoshikawa** [comment]
起票いただきありがとうございます。
本件、チーム内で検討いたします。

優先度の高いタスクから取り組んでいるため、順次の対応になってしまう点ご了承ください 🙇

**Comment by cm-igarashi-ryosuke** [comment]
@akim-muto 下書きの場合は本文がなくてもデプロイ可能に修正いたしました。（zenn.devで記事を作成する際のバリデーションと合わせました。）

ご提案いただきありがとうございました！
ぜひご活用ください。
