### ISSUE TITLE
未Approveの記事のみフィルタリングして表示できるようにして欲しい

### ISSUE THREAD

**Issue by kana-chan** [zenn-dev/zenn-community#614]
### 提案・要望

Publicationの記事の管理ページにて、
以下のような記事をフィルタリングできる機能が欲しいです。

- 自分がレビュワーに設定されていて
- 自分はまだApproveしていなくて
- 自分自身の記事ではなくて
- 公開状態ではないもの

のみ表示されるようなフィルターが欲しいです。

### 背景

会社全体で、zennへのアウトプットを積極的に行っていく流れなのですが、
下書き状態の記事が増えるにつれて、どの記事が自分のレビューを待っているのか？が分かりづらく、レビューを行うことに対するストレスが少し出てきました。

自分がレビューすべき記事が一覧できれば、記事投稿のペースも上がると思うので、ぜひお願いしたいです！

**Comment by cm-igarashi-ryosuke** [comment]
@kana-chan ご提案ありがとうございます！課題を認識いたしました。開発チームで検討いたします。

**Comment by cm-wada-yusuke** [comment]
課題を共有いただき助かります 🙇

**Comment by cm-igarashi-ryosuke** [comment]
@kana-chan お待たせいたしました。先ほど、レビュー未完了記事を一覧表示する機能をリリースしました。

https://info.zenn.dev/2024-07-02-reviewing-article-list

issueはクローズさせていただきますが、何かあればまたコメントいただければ幸いです。
貴重なご意見をいただきましてありがとうございました。
