### ISSUE TITLE
スクラップにコメントできない

### ISSUE THREAD

**Issue by oreo2990** [zenn-dev/zenn-community#619]
### 事象

スクラップにコメントできません。例えば、「あ」を投稿しようとしても画面に「Unexpected token '<', "<!DOCTYPE "... is not valid JSO」という通知が出ます。

### 発生したページのURL

https://zenn.dev/oreo2990/scraps/835fadf62f81ce

### 発生した画面のスクリーンショット

![スクリーンショット 2024-07-12 11 59 56](https://github.com/user-attachments/assets/d4d0b1ea-0d07-4e0f-8b9f-1d3bb114f415)

![スクリーンショット 2024-07-12 12 02 56](https://github.com/user-attachments/assets/7cf540ba-98ea-4a75-abd0-108d6be7ce68)

### 再現方法

https://zenn.dev/oreo2990/scraps/835fadf62f81ce

上記スクラップにコメントしようとする

**Comment by cm-dyoshikawa** [comment]
@oreo2990 

起票いただきありがとうございます。

ご不便をかけ申し訳ありません。
こちら、現在運営チームでWAFの設定を調整していることの影響と思われます。
状況が安定するまで期間を頂く可能性があり、お待ちいただけますと幸いです。

**Comment by oreo2990** [comment]
@cm-dyoshikawa 
ご確認いただきありがとうございます。
下記、承知いたしました。

> こちら、現在運営チームでWAFの設定を調整していることの影響と思われます。
状況が安定するまで期間を頂く可能性があり、お待ちいただけますと幸いです。

**Comment by cm-dyoshikawa** [comment]
@oreo2990 

本件、アクセスブロックが生じないよう設定を変更しました。
ご都合の良いタイミングでお試しいただけますと幸いです。

もし本問題が続く場合、お手数ですがご報告いただけますと幸いです。

**Comment by oreo2990** [comment]
@cm-dyoshikawa 
ご対応いただきありがとうございます！
修正されていること確認しました。このissueはcloseさせていただきます。
