### ISSUE TITLE
レビュー時にコメントボタンが隠れている場合がある

### ISSUE THREAD

**Issue by na9amura** [zenn-dev/zenn-community#620]
### 事象

記事のレビューをする際、最終行の一部を選択しコメントを入れようとした。その際にボタンが隠れていてコメント用フォームを開くことができなかった。

行全体へのコメントは最終行でも利用可能だったため、そちらでレビューは進めることができました。

### 発生した画面のスクリーンショット

<img width="1102" alt="Pasted_Image_2024_07_25__11_17" src="https://github.com/user-attachments/assets/6eb93003-c7f0-41d9-9ef0-a3250cbbd6d0">

### 環境

- Device: Macbook Air M1, 2020
- OS: OSX 14.2.1 (23C71)
- Browser: Version 126.0.6478.115 (Official Build) (arm64)

**Comment by cm-dyoshikawa** [comment]
@na9amura 

起票いただきありがとうございます。本件についてチームでも再現を確認いたしました。

修正が完了しましたら本Issueで報告いたします 🙇

**Comment by cm-igarashi-ryosuke** [comment]
@na9amura 修正が完了しましたのでクローズいたします。ご報告いただきありがとうございました。
