### ISSUE TITLE
いいね数がマイナスになっている記事を見つけました

### ISSUE THREAD

**Issue by y-hiraoka** [zenn-dev/zenn-community#623]
### 事象

いいね数がマイナスになっている記事を発見しました。

バッド評価はできないと思いますので、不具合かと思い報告いたします。

その記事の`getServerSideProps`の内容を確認したところ、`"likedCount": -15`と書かれていました。

### 発生したページのURL

https://zenn.dev/satoshie/articles/a27c5091c9ac89

### 発生した画面のスクリーンショット

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/c8e62b1e-6a3d-4db8-9774-69d34f21c5e6">

### 再現方法

ページを開く

**Comment by cm-dyoshikawa** [comment]
@y-hiraoka 起票いただきありがとうございます。

事象の発生をチームでも確認いたしました。

原因特定できたため、対応を進めて参ります。
