### ISSUE TITLE
記事本文の「自動保存を復元」した際に、エディタに復元した内容が反映されない

### ISSUE THREAD

**Issue by cm-igarashi-ryosuke** [zenn-dev/zenn-community#626]
### 事象

記事編集ページにて、本文の「自動保存を復元」した際に、エディタに復元した内容が反映されない。
反映されないが保存すると自動保存された内容で更新される。

### 再現方法

こちらのツイートより報告
https://twitter.com/samekard_dev/status/1823818149839692106

**Comment by cm-wada-yusuke** [comment]
修正リリースが適用されました。
「自動保存を復元」した際に、エディタに復元した内容が反映されることを確認。
