### ISSUE TITLE
zenn書籍に文字数制限を付けて欲しい（例：1万文字未満は出版できないとか）

### ISSUE THREAD

**Issue by nshiro** [zenn-dev/zenn-community#627]
### 提案・要望

現在のシステムでは、4千字にも満たない書籍でも出版できているようです。
内容もほぼ日記レベルのようなものもあります。

今後このような書籍が増えていくと、zenn本の品質や信頼性にも関わってきて、
ひいては有料本の売上げにも影響しないか危惧しております。

ご検討いただけると幸いです。

**Comment by cm-dyoshikawa** [comment]
@nshiro 
起票いただきありがとうございます。

ご提案について、文字数が少ない場合も読者にとって有益な記事である場合も少なくないと考えており、なかなか悩ましく考えております。

> Zenn本の品質や信頼性

の一定の担保については仰る通りと思いますので、同様の声を引き続きいただいた場合にサービス側での仕様を検討させていただきたいと思います。

現時点としては、内容として[利用規約](https://zenn.dev/terms)違反と思われるものがあれば、違反報告をしていただくことで運営側で個別に対応を検討させていただきます。

よろしくお願いいたします。

**Comment by nshiro** [comment]
回答ありがとうございます。
現時点での対応の件、承知しました。やはり色々と難しい所がありますね。
日々の運営に感謝します。
