### ISSUE TITLE
検索ページへ遷移すると`皆さまへのお知らせ`が2つ表示される

### ISSUE THREAD

**Issue by Omochice** [zenn-dev/zenn-community#628]
### 事象

トップページから 虫眼鏡アイコンを押し、画面遷移したあと、検索窓右上のリンクが2つとも `皆さまへのお知らせ`になっている。

遷移前は右のlinkが`法人向けメニューのご案内`となっている。

![image](https://github.com/user-attachments/assets/aab36d4a-22cd-4348-817b-33f580b1644b)

期待値は遷移後も `法人向けメニューのご案内`になっているべきだと思われます。

遷移前後でリンク先は変化していない (左: `https://info.zenn.dev/2024-08-22-zenn-business-policy`, 右: `https://zenn.dev/biz-lp` )ため、文言のみの問題の模様。

### 発生したページのURL

https://zenn.dev/search

### 発生した画面のスクリーンショット

![image](https://github.com/user-attachments/assets/db2acc0b-0cb1-43a9-b3f2-443c927279db)

### 再現方法

1. https://zenn.dev/search を表示する
2. 検索窓右上のリンクを確認する

### 環境

```
Vivaldi | 6.8.3381.57 (Stable channel) （arm64）
-- | --
変更履歴 | 1d3c8fde9e8cade5abea61e4f3f68df1fa3bcb56
OS | macOS バージョン14.6.1（ビルド23G93）
JavaScript | V8 12.6.228.30
ユーザーエージェント | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
コマンドライン | /Applications/Vivaldi.app/Contents/MacOS/Vivaldi --flag-switches-begin --flag-switches-end --disable-smooth-scrolling --save-page-as-mhtml
```

**Comment by cm-wada-yusuke** [comment]
@Omochice ご連絡ありがとうございます！！修正・デプロイしました :bow:

**Comment by Omochice** [comment]
確認しました

ありがとうございます :pray:
