### ISSUE TITLE
スクラップで番号付きリストにネストしたリストを加えると、強調される

### ISSUE THREAD

**Issue by katayama8000** [zenn-dev/zenn-community#629]
### 事象

番号付きリストの中にネストして、リストを加えると、強調される
```md
1. aa
2. bb
3. cc
   -  
```
`cc` と `-` が強調される
`-` の後に何か入力すると、事象は解決される

### 発生したページのURL

https://zenn.dev/tattu/scraps/28d9bb382c670c

### 発生した画面のスクリーンショット

![スクリーンショット 2024-08-25 20 17 24](https://github.com/user-attachments/assets/d38d8878-9921-486e-8e75-2af491be17d0)

### 再現方法

上記に記載の通り

### 環境

- MacbookPro
　  - M1チップ
- google chrome

**Comment by cm-wada-yusuke** [comment]
@katayama8000 ありがちな書き方で意図と違う強調が入るのでたしかに少し面食らいますね。ライブラリ含めすぐに修正できそうか見てみます。スクショ含めご連絡ありがとうございます。

**Comment by cm-igarashi-ryosuke** [comment]
確認したところ特定の条件下において、一部のテキストが h2 として解析されていることがわかりました。
条件としては以下のようにテキスト+改行の直後に`-` があるだけで発生するようです。

```
a
-
```

![image](https://github.com/user-attachments/assets/c2ed6a8a-52d8-44e7-98d2-182c4777ac2b)

まずはライブラリの方に報告を上げるのと、時間があれば直せそうかどうか見てみようと思います。

**Comment by cm-igarashi-ryosuke** [comment]
@katayama8000 

CommonMarkにおいて `-` で h2 を表現する記法があり、ご報告いただいた内容はこの記法に該当していました。
https://spec.commonmark.org/0.31.2/#example-83

実際にCommonMarkのPlaygroundでも再現しましたので、こちらのissueはMarkdownの仕様通りとしてクローズさせていただきます 🙇  

![image](https://github.com/user-attachments/assets/64fe6500-7cea-42b8-911c-e6580940d8f6)


私も初見ではバグだと思いました。
ご報告いただき感謝いたします。ありがとうございました。
