### ISSUE TITLE
スクラップ記載中にブラウザバックを押した時にアラートを表示してほしい

### ISSUE THREAD

**Issue by katayama8000** [zenn-dev/zenn-community#633]
### 提案・要望

スクラップ記載中にブラウザバックを押すと編集中でも、編集内容が消えてしまうので、事故が起きないようにブラウザ標準のもので良いので、アラートを表示してほしい。

**Comment by cm-igarashi-ryosuke** [comment]
@katayama8000 先ほどリリースを行い、スクラップ内のコメントを編集中にブラウザバックしようとすると確認アラートを表示するように修正したしました。

ご提案いただきありがとうございました！
