### ISSUE TITLE
/etc/hostsなどの特定の文字列を含めた記事の保存・検索ができない。

### ISSUE THREAD

**Issue by capriblue** [zenn-dev/zenn-community#635]
### 事象

/etc/motd, /etc/hosts, /etc/passwd, /etc/group, /etc/issue, /etc/shadow
などの文字列を含む記事を作成しようとすると、一時保存することができず、記事上では
`Unexpected token '<', "<!DOCTYPE "... is not valid JSON`
というエラーメッセージが表示される。

また、https://zenn.dev/search により、上記の文字列を含めて検索する（ https://zenn.dev/search?q=%252Fetc%252Fhosts ）とblockされたと表示される。

### 発生したページのURL

https://zenn.dev/search?q=%252Fetc%252Fhosts （検索クエリに/etc/hostsを指定)
および各編集ページ

### 発生した画面のスクリーンショット

![image](https://github.com/user-attachments/assets/f7179bdf-5c5f-4549-9f1f-91ed858c0b54)
編集ページでの一時保存（一時保存をクリックしたのちの通信を表示）
![image](https://github.com/user-attachments/assets/fd59d84e-960c-42e8-b24f-cf64cc2a455d)
/etc/hostsの検索結果

### 推定原因

検索クエリで/etc/hostsを含む文字列を検索した際のページによると、cloudflareのファイアウォールにて通信がブロックされているようです。また編集ページの保存が失敗する原因についても、chromeの開発者ツールを使い、httpのレスポンスを見るところ、同様のレスポンスが返ってきているので同等の理由であると考えられます。

一方で、過去の記事には/etc/hostsを含むものがあることから、cloudflareのWAFにおいて意図せぬルールの変更を行われたことによりこの現象が生じていると考えられます。

cloudflareのどのようなサービスが要因になりうるかの推察は難しいですが、御社とは別のcloudflareを利用しているサービスにおいても、同様の結果が得られていることに言及させていただきます。
https://www.producthunt.com/search?q=%2Fetc%2Fhosts (検索クエリに/etc/hostsを指定)

**Comment by cm-dyoshikawa** [comment]
起票いただきありがとうございます。

本件、順次調査いたします。

**Comment by cm-dyoshikawa** [comment]
@capriblue お待たせしました。本件、特定の文字列を含めた記事の保存・検索ができるようにWAFの設定を調節いたしました。

ご確認いただけますと幸いです。

**Comment by capriblue** [comment]
@cm-dyoshikawa 

ご対応いただき、誠にありがとうございます。

**Comment by cm-dyoshikawa** [comment]
こちらこそ起票いただきありがとうございました。

クローズいたします。
何かあればReopenをお願いします 🙏
