### ISSUE TITLE
ライブラリ | 「読んでいる本」タブにある履歴の削除をしようとすると、500エラーが発生する

### ISSUE THREAD

**Issue by shmokmt** [zenn-dev/zenn-community#636]
### 事象

「履歴から削除する」ボタンを押すと、500エラーが発生します。
その後、URLをリロードすると、該当する履歴は表示されないため、削除には成功しているようです。

### 発生したページのURL

https://zenn.dev/dashboard/library?type=reading_book_histories 

### 発生した画面のスクリーンショット

![image](https://github.com/user-attachments/assets/7fbaa12a-8bb6-4300-83ef-a7725446a1b4)

### 再現方法

https://zenn.dev/dashboard/library?type=reading_book_histories  の読んでいる本から「履歴から削除する」をクリックする。
私の環境ではどの本を選択しても再現するようです。

**Comment by cm-wada-yusuke** [comment]
@shmokmt ご連絡ありがとうございます。修正します。

**Comment by cm-igarashi-ryosuke** [comment]
@shmokmt 不具合の修正が完了いたしました。ご報告いただきありがとうございました！
