### ISSUE TITLE
コードブロックのdiff のシンタックスハイライトを使ったテキストのコピーについて

### ISSUE THREAD

**Issue by mikann-260** [zenn-dev/zenn-community#641]
### 事象

バグかわかりませんが、diff のシンタックスハイライトを使ったコードブロックの内容を右上のコピーボタンでコピーすると、+や-も一緒にコピーされてしまう問題があります。
#### 元のテキスト
-name = "mikann-260"
 name = input("あなたの名前は何ですか")
+print(f"Hello, {name}")
#### コピーしたテキスト
-name = "mikann-260"
 name = input("あなたの名前は何ですか")
+print(f"Hello, {name}")
#### コピーされてほしいテキスト
name = "mikann-260"
name = input("あなたの名前は何ですか")
print(f"Hello, {name}")

### 発生したページのURL

diffのシンタックスハイライトを使ったコードブロックがある記事や、本のすべて

### 再現方法

1. diffシンタックスハイライトを使ったコードブロックがある、記事を開く
2. コードブロックのエリアの右上に表示されるコピーボタンを押してコピーする
3. コピーしたテキストの内容を確認する

### 環境

OS : [ Windows 11 Version 23H2 ]
Browser : [Google Chrome ( 64 ビット ) ]

**Comment by cm-dyoshikawa** [comment]
起票いただきありがとうございます。
本件は仕様となります。

GitHubでもコピー時に `+` `-` が含まれるようです。そのためある程度一般的な仕様であるかと考えております。

```diff
-name = "mikann-260"
name = input("あなたの名前は何ですか")
+print(f"Hello, {name}")
```

**Comment by mikann-260** [comment]
仕様なのですね。
ありがとうございます。

**Comment by cm-wada-yusuke** [comment]
解決したためクローズします。
