### ISSUE TITLE
コメントに貼られたリンクをクリックできない

### ISSUE THREAD

**Issue by akku1139** [zenn-dev/zenn-community#648]
### 事象

>  パッケージにソースコードを同梱するだけでも良いのに…。（https://zenn.dev/suin/scraps/9f454023cefb67）

にあるURLをクリックしても移動しません。

![image](https://github.com/user-attachments/assets/c0d6a36d-28b3-4f8a-875e-24350711491b)
aタグにhrefがついていないようです。

同じようにコメントを送っても再現できませんでした。
サーバーサイドキャッシュによって修正されたバグの挙動が残っている可能性は有りますが、断言は出来ません。

### 発生したページのURL

https://zenn.dev/nakasyou/articles/jsr_7m_thoughts#comment-e8400f3bcb336a

**Comment by cm-igarashi-ryosuke** [comment]
@akku1139 ご報告いただきありがとうございます。

こちらのコメントのmarkdownを確認しましたところ、リンク記法 `[]()` の `()` にURLが指定されていないため、hrefがない状態となっておりました。

システムの問題ではありませんのでクローズさせていただきます。
