### ISSUE TITLE
emailでの新規登録の実装について

### ISSUE THREAD

**Issue by EdamAme-x** [zenn-dev/zenn-community#652]
現状recaptchaなどでアカウントの自動生成を防がれていると思いますが、`captcha solver`や`web driver`等の技術で簡単に超えられてしまいます。
また、アカウント作成のip制限がないように思えます。

対策としては、より厳格なIP制限、CF Turnstileの導入(既に回避策が見つかってしまっていますが・・・)、gmailやキャリアメールのドメインに限る。などが挙げられると思います。

この実装がZennへのスパムを増やす結果となりかねないと思っています。
良ければ対策を検討してみてほしいです。

**Comment by cm-dyoshikawa** [comment]
@EdamAme-x ご意見いただきありがとうございます。
本件については仰るような懸念点を軽減する施策について、順次対応を検討いたします。

**Comment by cm-dyoshikawa** [comment]
@EdamAme-x 

本件ご提案いただきありがとうございました。

性質上内容については開示できませんが、対策をさらに強化いたしました。
さらに懸念が上がることがあれば起票もしくはreopenいただけると幸いです。

**Comment by EdamAme-x** [comment]
やっぱり画像認証入れた方が良いですね・・
現状、hcaptchaが一番固いと思うので導入してみてはどうでしょうか
![image](https://github.com/user-attachments/assets/96750f21-5a93-48a8-973c-4569ffa36b96)

**Comment by EdamAme-x** [comment]
re
![image](https://github.com/user-attachments/assets/511a8de1-6ba8-4bd8-84db-5d648759dd20)

**Comment by EdamAme-x** [comment]
reping
