### ISSUE TITLE
GitHubでログイン

### ISSUE THREAD

**Issue by ginpei** [zenn-dev/zenn-community#68]
現在はGoogleのみですが、GitHubアカウントを利用したログインもできるようになってほしいです。（後から増やすのだいぶ面倒そうとは思いますけれど。）

**Comment by rhysd** [comment]
サービスは GitHub を利用するデザインになっているので，アカウントのログインも GitHub でできると嬉しいです．

**Comment by sonarism** [comment]
ログインというかアカウントの作成からできるとありがたいです。

Googleアカウントで使いたくないので、メールアドレスとかでも良いです。

**Comment by tatsuya6502** [comment]
中国本土に住んでおり、Googleのサービスは一切利用できません。GitHubにはアクセスできますので、GitHubアカウントを利用したログインができるようになると助かります。

**Comment by kirisaki** [comment]
Google アカウントは本名に紐づいておりログインに使いたくないという人も多いようです。GitHub であれば本名である必要はないのでそういった人たちの障壁を無くすことにもつながるかと思います。すなわち間口を広げ、ユーザー数を増やすことでコミュニティの活性化に繋がります。「GitHub ログインが使えないから」という理由で Zenn で記事を書いてもらえないのは一ユーザーとしても機会損失です。ぜひ優先度を上げてほしいです。

**Comment by qwexvf** [comment]
その後なにか進展はありますか？？

**Comment by cm-wada-yusuke** [comment]
チームとしてこちらの課題に優先的にあたっています。
https://github.com/zenn-dev/zenn-community/issues/275

こちらの課題が落ち着いた後、認証周りについて検討を再開します。おまたせしており申し訳ありません。

**Comment by geeknees** [comment]
友人にサービスを勧めたところGoogleになるべく情報を渡したくないということからアカウント登録まで至らないことがありました。昨今のSNSのサービス継続性の観点からも、別の選択肢が増えてくると嬉しいです。

**Comment by uttk-dev** [comment]
@geeknees 

ご意見ありがとうございます！
今は他の優先度の高いタスクに注力しており検討するまでには至ってないですが、
そのタスクや他のタスクが落ち着き次第、取り組みたいと思いますので、気長にお待ち頂ければと思います🙇‍♂️

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、現状3rd Partyのログインを増やす見込みはありません。
多くのご要望を頂いておりますがご期待に添えず申し訳ありません。

ただ、Googleアカウント限定という状態は一定のリスクがあると考えていますので、
独自のログイン（ https://github.com/zenn-dev/zenn-community/issues/17 ）は引き続き時期を見て検討したいと考えています。
