### ISSUE TITLE
記事公開時に「🔰この分野の初心者です」ということを示せるスイッチ

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-community#71]
- 学習ノートであるときは学習ノートであることが伝わりやすくしたい
  - ref: https://zenn.dev/uhyo/articles/technical-articles
- 機能を追加するというより、タグで設定するくらいの形が良さそう？
- 問題は学習ノートを書く人がこの機能を認識・活用してくれない可能性があること

**Comment by tannerjohn65** [comment]
現状はTopicで対応します！今後、必要に応じて再検討。
