### ISSUE TITLE
GitHubリポジトリで画像を管理できるように

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-community#72]
Jekyllが参考になるかも？
https://github.com/zenn-dev/zenn-editor/issues/24

**Comment by mikkame** [comment]
FYI:
githubの画像はrawから取得するとして、そちらに負荷をかけないように何かしらのProxyを挟む事で解決するのはいかがでしょうか。

（有名なmd投稿場所として）QiitaでもGitHubでもMD記法で埋め込んだ画像は必ずproxyされます。
Qiitaでは
https://www.imgix.com/
GitHubでは
https://github.com/atmos/camo
が利用されているようです。
負荷をかけない以外にも、サードパーティのトラッキング(画像ベースの)を防止する事ができます。

**Comment by catnose99** [comment]
@mikkame たしかにそうですね。
imgix挟むのが良さそうです。ご指摘ありがとうございます！
