### ISSUE TITLE
記事内の画像をクリックしたら拡大表示する機能を希望

### ISSUE THREAD

**Issue by iedred7584** [zenn-dev/zenn-community#79]

**Comment by catnose99** [comment]
これはたしかに必要そうです。

みなさんの意見を聞きたいのですが、
- たとえばQiitaだと画像をクリックすると画像のページに別タブで飛びます（[画像を含むQiita記事の例](https://qiita.com/dhirabayashi/items/0cbe01f403af7a0223b9)）。求められているは画面遷移することなくポップアップする機能（LightBoxと呼ばれたりするもの）ですか？（[イメージ](http://bandaicandy.hateblo.jp/entry/20200925_digimon)）

- 拡大表示するのって主にPCやタブレットで見てるときですか？
（スマホだと拡大してもほぼ同じサイズに表示されることになるので不要なイメージ。負荷を下げるために読み込み後にウィンドウサイズが一定以上だった場合のみ有効にするのが良さそう）

**Comment by iedred7584** [comment]
@catnose99 私個人としては PC 閲覧時のみ Lightbox の様にポップアップで拡大表示されるものを希望しております。

**Comment by yamanoku** [comment]
私はクリックしたら画像URLを別タブで表示する、みたいなのでも十分に思いました（拡大したり縮小する制御はブラウザ側で委ねる）。

**Comment by cm-wada-yusuke** [comment]
こちら実装済みです
