### ISSUE TITLE
コードブロックの Copy to clipboard

### ISSUE THREAD

**Issue by Reputeless** [zenn-dev/zenn-community#81]
コードブロック内のコードをクリップボードにコピーできるボタンがあると便利です。

**Comment by catnose99** [comment]
検討してみます！

**Comment by takupekopon** [comment]
オプションで枠右上に「Copy to Clipboard」的なショートカットがあるとCLIベースのコンテンツではとても役立ちます！

**Comment by catnose99** [comment]
@Reputeless 

長らくお待たせしてすみません。
さきほどのリリースでクリップボードへのコピー機能が使えるようになりました。
ご要望ありがとうございました。

**Comment by NORI24** [comment]
半角スペースでインデントすることによりコードブロックのように表示した場合は、コピーボタンが表示されません。
\``` で囲んだコードブロックはコピーボタンが表示されます。

半角スペースインデントによるコードブロックの場合もコピーボタンを表示していただけると、
仕様がわかりやすくなって良いと思います。

**Comment by cm-igarashi-ryosuke** [comment]
@NORI24 ご連絡ありがとうございます。再現することを確認しました。対応についてチームで検討いたします。

**Comment by cm-igarashi-ryosuke** [comment]
@NORI24 半角スペースインデントによるコードブロックの場合もコピーボタンが表示されるように修正しました。ご報告ありがとうございました。
