### ISSUE TITLE
ダッシュボードで他の人から来たコメントの一覧が見たい

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [zenn-dev/zenn-community#89]
自分が書いたコメントは公開されているので見れますが，他の人から来たコメントの一覧がダッシュボードで見れると嬉しいです。

過去記事に対してコメントが来たときなど見逃してしまう場合があるもので。

**Comment by catnose99** [comment]
なるほどですね。検討してみます。

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ニーズが限定的であるため実装は見送ることとなりました。
