### ISSUE TITLE
ダッシュボードでPVなどの統計データを見れるように

### ISSUE THREAD

**Issue by 1ntegrale9** [zenn-dev/zenn-community#98]
## 要望と背景

掲題通り、PV数を確認できる方法を提供してほしいです。場所や形態はどのような形でも問題ありません。
アクセス解析という形であればなお良いですが、最小限でも提供が早い方がありがたいです。

理由としては、PV数によって以下を把握したいためです。
- ブラッシュアップすべき記事
- 新規投稿すべき記事/本のカテゴリ
- タイトルや内容、宣伝方法を改善すべき記事

## 補足：現状の仕様

今のところ記事のメタ情報としては
「Like数」「最終更新日」「文字数」「想定読了時間」「カテゴリ」
のみとなっています。

<img width="275" alt="スクリーンショット 2020-09-30 14 43 48" src="https://user-images.githubusercontent.com/11159059/94647513-8da7e600-032b-11eb-9a67-b20042441e71.png">
<img width="857" alt="スクリーンショット 2020-09-30 14 44 11" src="https://user-images.githubusercontent.com/11159059/94647514-8ed91300-032b-11eb-8784-db748fb0e823.png">

## 補足：他サービスのPV数表示仕様

Qiitaの記事閲覧画面です。（投稿者にのみ表示）
ダッシュボード/記事編集画面にはPV数表示はありません。
![スクリーンショット 2020-09-30 14 59 32](https://user-images.githubusercontent.com/11159059/94648702-01e38900-032e-11eb-83f8-6cab3336d3e3.png)

Qrunchのダッシュボード画面です。
記事閲覧/編集画面にはPV数表示はありません。
![スクリーンショット 2020-09-30 14 57 50](https://user-images.githubusercontent.com/11159059/94648359-5fc3a100-032d-11eb-8154-2fee46c1b16a.png)

noteのダッシュボード画面です。
記事閲覧/編集画面にはPV数表示はありません。
<img width="663" alt="スクリーンショット 2020-09-30 15 00 58" src="https://user-images.githubusercontent.com/11159059/94648665-f4c69a00-032d-11eb-9dec-fcee5b576a00.png">

**Comment by catnose99** [comment]
他サービスの例まで載せていただき、ありがとうございます。
開発者向けのサービスなので、Analyticsでの対応が良いだろうと考えています（#4）。
こちらなるべく早く対応しようと思っています。今しばらくお待ちください。

**Comment by catnose99** [comment]
- 以前はAnalyticsのReporting APIを使ってページビュー等の統計情報を取得していたため、ユーザーごとに統計情報を見れるようにすると[Limit](https://developers.google.com/analytics/devguides/collection/analyticsjs/limits-quotas)を超えてしまう可能性が高いという問題がありました。
- 数ヶ月前にBigQueryを導入したことにより、ユーザーごとに細かなデータを取得することが可能になりました。
- 2022年にはzennのダッシュボードに統計ページを追加し、以下のような情報を見れるようにする予定です。
  - 投稿ごとの合計ページビュー / Like
  - 日別や月別のページビューの推移
  - 投稿アクティビティ（GitHubのContributionsの草のような形で投稿量を振り返れるように）

**Comment by maxfie1d** [comment]
any update?

**Comment by cm-wada-yusuke** [comment]
現在、内々で試験運用中です。運用面での懸念が解消できたら多くのユーザー様に開放できるかと思いますので、もうしばらくお待ち下さい。

**Comment by cm-wada-yusuke** [comment]
お待たせしました。こちらオープンβでリリースしました。ぜひお試しください。
※ログインしてご利用ください。

https://zenn.dev/dashboard/stats
